/* English story core: cast, speakers, shared lines, deaths, tips, credits, wall writing. Chapter files
   add their documents, objectives, monologue, radio and recaps; lake.js adds the endings.
   The story bible is docs/STORY.md. */
(function (root) {
  'use strict';
  root.PB.I18N.register('en', 'story', {
    chars: {
      ada: { name: 'Ada', pos: "Ada's", role: 'Ada Lind, 31. Night clerk at Depot 9, the lost property office under Halvard Central, since 1990. You.' },
      wren: { name: 'Wren', pos: "Wren's", role: 'Wren Lind, Ada\'s little sister. Seven. Vanished on the ice of Lake Ostra on 14 January 1979.' },
      otto: { name: 'Otto', pos: "Otto's", role: 'Otto Brandt, night clerk at Depot 9 from 1946 to 1964, when he took the freight elevator down. On channel nine.' },
      ingrid: { name: 'Ingrid', pos: "Ingrid's", role: 'Ingrid Lind, the girls\' grandmother, "Gran". Born in Gammel Ostra. Died in 1996.' },
      clerk: { name: 'The Night Clerk', pos: "the Clerk's", role: 'Keeps the Index at the bottom of the Underneath. Signs her memos "A."' },
    },
    speakers: { ada: 'ADA', otto: 'OTTO', radio: 'RADIO', lyle: 'LYLE HARDY', clerk: 'THE CLERK', wren: 'WREN', voice: '???' },
    items: {},
    obj: {},
    memento: {},
    freed: {},
    shrine: {},
    ghostHelp: {},
    mono: {
      hide: 'Hold your breath.',
      hideLocker: 'Hold your breath. Don\'t move.',
      fearHigh: 'I can\'t breathe...',
      lowBattery: 'The battery is dying.',
      eaterFlicker: 'The lights are going down. It\'s close. I can hear it chewing.',
      watcherSeen: 'Something tall at the far end, standing very still.',
    },
    // [what it says on the screen, what to do differently]
    deaths: {
      eater: ['EATEN', 'The Eater is fast in a straight line and slow in the turns. A lost light in your hand makes it back away for a few seconds.'],
      sorter: ['SORTED', 'Whatever sorts the archive in the dark goes on with its work. Do not get between it and the shelves.'],
      wallpaperMan: ['PAPERED OVER', 'The flat men only come off the wall behind your back. Walk past them facing them.'],
      hummer: ['HUMMED OUT', 'Where the hum swells and the lights flicker, something is listening. Walk slowly and keep away from the loud places.'],
      drowned: ['PULLED UNDER', 'The Drowned wait under the water and hear you in it. Keep out of the water, and never stand still in it.'],
      passenger: ['TAKEN TO A SEAT', 'The passengers wake when a light rests on them. Keep your torch off their faces and do not brush past them.'],
      bellman: ['RUNG', 'On the open deck the Bellman hears you. When the bell starts ringing he is hunting: get under cover and stay low.'],
      pines: ['TAKEN INTO THE TREES', 'The pines only move while you move. Close to them, stand still and let them lose interest.'],
      stag: ['RUN DOWN', 'The stag charges in a straight line. Put a tree or a car between you and it, and it will stun itself.'],
      usher: ['SHOWN TO A SEAT', 'An usher only sees down its red beam. Keep out of the light, and never cross in front of it.'],
      burrower: ['DRAGGED INTO THE EARTH', 'Burrowers feel your steps through the dirt. Crouch on the earth floors; on rails and planks you are safe.'],
      lamplighter: ['LAMP IN THE EYES', 'Lamplighters go to any light. Switch your lamp off and let them walk past.'],
      crawler: ['DROPPED ON', 'Timber crawlers wait in the roof timbers. Look up before you walk under them, and keep low.'],
      frozen: ['FROZEN', 'The frozen guests only move near warmth. Get warm, and get away from the fire before they get up.'],
      cold: ['FROZEN', 'Outside, the cold gets in fast. Go from shelter to shelter and warm up by a fire.'],
      whiteout: ['SWALLOWED BY THE SNOW', 'In the storm you only see its footprints. It hears you: walk, do not run, and keep to shelter.'],
      cook: ['HOOKED', 'The Cook never leaves the kitchen. Wait for him to turn his back at the far end, then go.'],
      silted: ['PULLED INTO THE MUD', 'Stand still on the mud too long and one of them rises beside you. Keep moving.'],
      longone: ['TAKEN INTO THE RIVER', 'Long Ones wait in the wells, the ditches and the river. Crouch when you pass the water.'],
      choir: ['TAKEN INTO THE PEWS', 'While the choir sings it sees nothing. Walk softly behind them; never run, never pass in front.'],
      water: ['DROWNED', 'The water rises faster and faster. Get to high ground, and climb.'],
      conductor: ['PUT OFF THE TRAIN', 'Without a valid ticket the Conductor puts you off. When his lamp comes down the corridor, turn your torch off and get under a bunk.'],
      sleeper: ['PULLED INTO A BUNK', 'Sleepers cannot see. A footstep outside their compartment wakes them: crouch past, and keep still when one is up.'],
      underhand: ['DRAGGED BETWEEN THE CARS', 'Never stop on a gangway. Cross quickly, and have the next door open before you step onto the plates.'],
      mask: ['FACES', 'The masks only move while nobody is watching them. Keep them in front of you and back away.'],
      horse: ['TRAMPLED', 'The horses only run while the organ plays. When the music stops, so do they: that is when you move.'],
      lotte: ['LIFTED', 'Lotte cannot see. She hears, and she never stops laughing: keep away from the laughing and keep quiet.'],
      hush: ['HUSHED', 'Near the Hush every sound fades. When you cannot hear yourself any more, it is very close. Move away, slowly.'],
      underice: ['THROUGH THE ICE', 'Never run on the dark ice over the old river. Walk, and what is under it stays under it.'],
    },
    tips: [
      'Running is loud. Crouch-walking is almost silent.',
      'Every shelf has a lie at the bottom of it. Find the lost thing and put it back where it belongs, and the place lets you go.',
      'Most of them hear better than they see. Turn your torch off when something is close.',
      'You can hide under beds, bunks and desks. If nothing saw you go in, nothing will look.',
      'Hold Shift while hidden to hold your breath. Run out of breath and you gasp.',
      'Hold V to look back over your shoulder while you run.',
      'Read everything. The people who wrote these things are telling you how to get out.',
      'Wren left eight drawings behind, one on most shelves. Some are hidden well.',
      'Otto talks on channel nine when he has something to tell you. He is usually right.',
      'M opens a map of the places you have been.',
    ],
    photoLabels: {},
    credits: [
      ['LEVEL 256', 'a first-person horror story in nine shelves'],
      ['For', 'everyone who was told it was nobody\'s fault'],
      ['Places', 'Halvard, Lake Ostra and the Underneath are invented; so is everyone in them'],
      ['Sound', 'synthesized live: not a single recording'],
      ['Pictures and models', 'procedural: not a single image file'],
      ['Depot 9', 'is open every night. Ask at the counter.'],
    ],
    // Writing scrawled on the walls of the Underneath
    scrawl: {
      yellow: ['WHO CAME BACK FOR IT?', 'IT IS ALWAYS 02:56', 'CLAIM 256', 'YOU CAN\'T SKIP A SHELF', 'LOOK FOR THE LIE', 'NOBODY ASKED', 'FILED UNDER: FORGOTTEN'],
      dark: ['KEEP THE LIGHT ON', 'IT EATS WHAT YOU STOPPED LOOKING FOR', 'ADA?'],
      concrete: ['HOLD FOR: ADA LIND', '256', 'UNCLAIMED'],
    },
  });
})(typeof window !== 'undefined' ? window : globalThis);
