/* Chapter definitions: gameplay data only (layout, lighting, items, creatures, objectives).
   Names, intros and documents live in the language packs (js/text/<lang>/). */
(function (root) {
  'use strict';
  const PB = root.PB || (root.PB = {});

  const supplies = (bat, alm, extra = []) => [
    { type: 'battery', count: bat, place: 'any', group: 'bat', sep: 6 },
    { type: 'almond', count: alm, place: 'any', group: 'alm', sep: 8 },
  ].concat(extra);

  const LEVELS = [
    {
      id: 'prolog',
      layout: 'arcade', seed: 1994, theme: 'arcade', music: 'arcade', fog: [0x08060e, 0.035], grade: { tint: [1.02, 0.97, 1.05], sat: 1.05 },
      startFlashlight: false,
      items: [
        { type: 'flashlight', id: 'flashlight', place: 'spot', spot: 'counter', h: 1.02 },
        { type: 'fuseBox', id: 'mainBreaker', place: 'spot', spot: 'fuseBox', h: 1.5 },
        { type: 'register', id: 'register', place: 'spot', spot: 'counter', reuse: true, h: 1.02, offset: [1.4, 0] },
        { type: 'token', id: 'token', place: 'spot', spot: 'officeDesk' },
        { type: 'specialCabinet', id: 'special', place: 'spot', spot: 'specialCabinet', h: 0 },
        { type: 'freeCabinet', id: 'freeplay', place: 'spot', spot: 'freeCabinet', h: 0 },
        { type: 'note', id: 'n_sticky', data: 'p_sticky', place: 'spot', spot: 'specialCabinet', reuse: true, h: 1.02, offset: [0.55, -0.35] },
        { type: 'note', id: 'n_repair', data: 'p_repair', place: 'spot', spot: 'specialCabinet', reuse: true, h: 1.02, offset: [-0.55, -0.35] },
        { type: 'note', id: 'n_workorder', data: 'p_workorder', place: 'spot', spot: 'hall' },
        { type: 'note', id: 'n_notice', data: 'p_notice', place: 'spot', spot: 'counter', reuse: true, h: 1.02, offset: [-1.6, 0] },
        { type: 'note', id: 'n_hiscore', data: 'p_hiscore', place: 'spot', spot: 'corridor', wall: true, h: 1.6 },
        { type: 'note', id: 'n_ledger', data: 'p_ledger', place: 'spot', spot: 'officeDesk', reuse: true, h: 0.82, offset: [-0.35, 0.18] },
        { type: 'note', id: 'n_frank', data: 'p_frank', place: 'spot', spot: 'officeDesk', reuse: true, h: 0.82, offset: [0.55, 0.12] },
        { type: 'note', id: 'n_birthday', data: 'p_birthday', place: 'spot', spot: 'storage' },
        { type: 'note', id: 'n_photo', data: 'p_photo', place: 'spot', spot: 'officeWall', h: 1.6 },
        { type: 'drawing', id: 'd_lily1', data: 'p_lily1', place: 'spot', spot: 'officeWall', reuse: true, h: 1.25, beside: 0.9 },
        { type: 'note', id: 'n_nora', data: 'p_nora', place: 'spot', spot: 'hall', reuse: true, offset: [0.9, 0.6] },
        { type: 'note', id: 'n_mirror', data: 'p_mirror', place: 'spot', spot: 'wc' },
        { type: 'tape', id: 'tape_p', data: 'p_tape', place: 'spot', spot: 'officeDesk', reuse: true, h: 0.82, offset: [0.2, -0.2] },
        { type: 'battery', count: 2, place: 'spot', spot: 'hall', fallback: 'any' },
      ],
      entities: [],
    },
    {
      id: 'lobby',
      layout: 'backrooms', seed: 1987, theme: 'yellow', music: 'lobby', fog: [0x4a3f1f, 0.016], grade: { tint: [1.04, 1.0, 0.9], sat: 0.95 },
      gen: { w: 50, h: 50, landmarks: [{ tag: 'camp', w: 3, h: 3 }, { tag: 'lone', w: 4, h: 3, openings: 2 }, { tag: 'chairs', w: 4, h: 4, openings: 2 }, { tag: 'stairs', w: 3, h: 4 }, { tag: 'puddle', w: 5, h: 4, openings: 3 }] },
      items: [
        { type: 'powerPellet', id: 'pellet', count: 4, place: 'deadEnd', group: 'pellet', minFrac: 0.35 },
        { type: 'exitPanel', id: 'exitPanel', place: 'spot', spot: 'exitPanel', reuse: true, h: 1.3, beside: 1.05 },
        { type: 'radio', id: 'radio', place: 'spot', spot: 'camp', h: 0.02 },
        { type: 'tape', id: 'tape_lobby', data: 'lobby_tape', place: 'spot', spot: 'camp', reuse: true, offset: [0.9, 0.5] },
        { type: 'note', id: 'n_rules', data: 'lobby_rules', place: 'near', wall: true, h: 1.5 },
        { type: 'note', id: 'n_camp', data: 'lobby_camp', place: 'spot', spot: 'camp', reuse: true, offset: [-0.8, 0.4] },
        { type: 'note', id: 'n_walt1', data: 'lobby_walt1', place: 'mid' },
        { type: 'note', id: 'n_walt2', data: 'lobby_walt2', place: 'far', group: 'notes' },
        { type: 'note', id: 'n_flyer', data: 'lobby_flyer', place: 'spot', spot: 'lone', fallback: 'mid' },
        { type: 'note', id: 'n_chairs', data: 'lobby_chairs', place: 'spot', spot: 'chairs', fallback: 'mid', wall: true, h: 1.6 },
        { type: 'note', id: 'n_puddle', data: 'lobby_puddle', place: 'spot', spot: 'puddle', fallback: 'far' },
        { type: 'note', id: 'n_exitwall', data: 'lobby_exitwall', place: 'spot', spot: 'exitPanel', reuse: true, beside: -1.05, h: 1.5 },
        { type: 'drawing', id: 'd_lily2', data: 'lobby_lily2', place: 'deadEnd', minFrac: 0.6 },
      ].concat(supplies(6, 4)),
      entities: [{ type: 'pacman', dormant: true }],
      objectives: ['lobby_explore', 'lobby_pellets', 'lobby_insert', 'lobby_leave'],
    },
    {
      id: 'mill',
      layout: 'warehouse', seed: 3171987, theme: 'concrete', music: 'warehouse', fog: [0x0d0f12, 0.028], grade: { tint: [0.95, 0.98, 1.05], sat: 0.85 },
      items: [
        { type: 'fuse', id: 'fuse', count: 3, place: 'far', group: 'fuse', minFrac: 0.4 },
        { type: 'fusePanel', id: 'fusePanel', place: 'spot', spot: 'fusePanel', h: 1.4 },
        { type: 'memento', id: 'watch', data: 'billy', place: 'far', group: 'mem', minFrac: 0.5 },
        { type: 'shrine', id: 'shrine_b', data: 'billy', place: 'spot', spot: 'shrine' },
        { type: 'tape', id: 'tape_mill', data: 'mill_tape', place: 'spot', spot: 'camp' },
        { type: 'note', id: 'n_mill_intro', data: 'mill_intro', place: 'near' },
        { type: 'note', id: 'n_layoff', data: 'mill_layoff', place: 'spot', spot: 'office1', fallback: 'mid' },
        { type: 'note', id: 'n_punch', data: 'mill_punch', place: 'mid' },
        { type: 'note', id: 'n_billy1', data: 'mill_billy1', place: 'far', group: 'notes' },
        { type: 'note', id: 'n_ray', data: 'mill_ray', place: 'far', group: 'notes' },
        { type: 'note', id: 'n_manifest', data: 'mill_manifest', place: 'spot', spot: 'office2', fallback: 'far' },
        { type: 'note', id: 'n_walt3', data: 'mill_walt3', place: 'mid' },
        { type: 'note', id: 'n_graffiti', data: 'mill_graffiti', place: 'mid', wall: true, h: 1.8 },
        { type: 'note', id: 'n_mill_shrine', data: 'mill_shrine', place: 'spot', spot: 'shrine', fallback: 'far' },
      ].concat(supplies(5, 3)),
      entities: [{ type: 'ghost', ghost: 'blinky' }, { type: 'pacman', dormant: true }],
      ghost: 'billy',
      objectives: ['mill_fuses', 'mill_panel', 'mill_wait', 'mill_leave'],
    },
    {
      id: 'pipes',
      layout: 'tunnels', seed: 1985, theme: 'tunnel', music: 'pipes', fog: [0x0a0908, 0.05], grade: { tint: [1.04, 0.98, 0.9], sat: 0.8 }, ceil: 2.8,
      gen: { w: 40, h: 40, min: 2, gapEvery: 4, gapMax: 1, stop: 0.2, maxRoom: 12, remove: 0.02, stubs: 110, stubLen: 4, corridors: 2, pillar: 0, theme: 'tunnel', ceil: 2.8,
        exitDoor: { kind: 'metal', nameKey: 'door.pressure', lockKey: 'lock.pressure' },
        light: { kind: 'cage', density: 0.16, darkThreshold: -0.1, flicker: 0.2, broken: 0.25, color: [1, 0.78, 0.5], intensity: 0.8, range: 8 },
        landmarks: [{ tag: 'fort', w: 3, h: 3 }, { tag: 'boiler', w: 4, h: 4, openings: 2 }, { tag: 'camp', w: 3, h: 3 }] },
      items: [
        { type: 'valve', id: 'pvalve', count: 3, place: 'far', group: 'valve', wall: true, h: 1.2, minFrac: 0.3 },
        { type: 'note', id: 'n_pipes_intro', data: 'pipes_intro', place: 'near' },
        { type: 'note', id: 'n_pipes_chalk', data: 'pipes_chalk', place: 'mid', wall: true, h: 1.3 },
        { type: 'note', id: 'n_pipes_map', data: 'pipes_map', place: 'spot', spot: 'fort', fallback: 'mid' },
        { type: 'note', id: 'n_pipes_rules', data: 'pipes_rules', place: 'spot', spot: 'fort', reuse: true, wall: true, h: 1.2, fallback: 'far' },
        { type: 'note', id: 'n_pipes_works', data: 'pipes_works', place: 'spot', spot: 'boiler', fallback: 'far' },
        { type: 'note', id: 'n_pipes_walt', data: 'pipes_walt', place: 'far', group: 'notes' },
        { type: 'note', id: 'n_pipes_photo', data: 'pipes_photo', place: 'spot', spot: 'fort', reuse: true, offset: [0.8, -0.5], fallback: 'mid' },
        { type: 'note', id: 'n_pipes_crawlers', data: 'pipes_crawlers', place: 'mid' },
        { type: 'tape', id: 'tape_pipes', data: 'pipes_tape', place: 'spot', spot: 'camp', fallback: 'mid' },
        { type: 'drawing', id: 'd_lily3', data: 'pipes_lily3', place: 'deadEnd', minFrac: 0.55 },
        { type: 'glowstick', count: 5, place: 'any', group: 'glow', sep: 6 },
      ].concat(supplies(6, 3)),
      entities: [{ type: 'crawler', count: 5 }, { type: 'pacman', dormant: true }],
      objectives: ['pipes_valves', 'pipes_leave'],
    },
    {
      id: 'pool',
      layout: 'pools', seed: 1989, theme: 'pool', music: 'pools', fog: [0x7d9aa2, 0.012], grade: { tint: [0.97, 1.02, 1.05], sat: 0.9 },
      items: [
        { type: 'valve', id: 'valve', count: 4, place: 'far', wall: true, group: 'valve', minFrac: 0.35, h: 1.1 },
        { type: 'drain', id: 'drain', place: 'spot', spot: 'drain' },
        { type: 'memento', id: 'glasses', data: 'ivy', place: 'far', group: 'mem', minFrac: 0.5 },
        { type: 'shrine', id: 'shrine_i', data: 'ivy', place: 'spot', spot: 'shrine' },
        { type: 'tape', id: 'tape_pool', data: 'pool_tape', place: 'spot', spot: 'camp' },
        { type: 'note', id: 'n_pool_intro', data: 'pool_intro', place: 'near' },
        { type: 'note', id: 'n_report', data: 'pool_report', place: 'mid' },
        { type: 'note', id: 'n_theo1', data: 'pool_theo1', place: 'mid', group: 'theo', sep: 8 },
        { type: 'note', id: 'n_theo2', data: 'pool_theo2', place: 'far', group: 'theo', sep: 8 },
        { type: 'note', id: 'n_theo3', data: 'pool_theo3', place: 'far', group: 'theo', sep: 8 },
        { type: 'note', id: 'n_comic', data: 'pool_comic', place: 'far', group: 'notes' },
        { type: 'note', id: 'n_tiles', data: 'pool_tiles', place: 'far', wall: true, h: 1.2, group: 'notes' },
        { type: 'note', id: 'n_walt4', data: 'pool_walt4', place: 'mid' },
        { type: 'note', id: 'n_poolrules', data: 'pool_rules', place: 'mid', wall: true, h: 1.6 },
      ].concat(supplies(3, 3)),
      entities: [{ type: 'ghost', ghost: 'inky' }, { type: 'pacman', dormant: true }],
      ghost: 'ivy',
      objectives: ['pool_valves', 'pool_drain', 'pool_hatch'],
    },
    {
      id: 'office',
      layout: 'office', seed: 1990, theme: 'office', music: 'office', fog: [0x1a1d22, 0.02], grade: { tint: [0.96, 1.0, 1.04], sat: 0.85 },
      code: '1073',
      items: [
        { type: 'codeClue', id: 'clue_memo', data: 'office_clue1', place: 'spot', spot: 'server', fallback: 'far', prop: 'printer' },
        { type: 'codeClue', id: 'clue_pc', data: 'office_clue2', place: 'spot', spot: 'openplan', fallback: 'mid', h: 0.78, prop: 'computer' },
        { type: 'codeClue', id: 'clue_board', data: 'office_clue3', place: 'spot', spot: 'whiteboard', fallback: 'far', wall: true, h: 1.5, prop: 'whiteboard' },
        { type: 'phone', id: 'phone1', data: 'office_clue4', place: 'mid', group: 'phone', clue: true },
        { type: 'keypad', id: 'keypad', place: 'spot', spot: 'keypad', reuse: true, h: 1.35, beside: 0.95 },
        { type: 'keycard', id: 'keycard', place: 'spot', spot: 'keycard', h: 0.8 },
        { type: 'cardReader', id: 'cardReader', place: 'spot', spot: 'cardReader', reuse: true, h: 1.3, beside: 0.95 },
        { type: 'memento', id: 'mixtape', data: 'penny', place: 'far', group: 'mem', minFrac: 0.45 },
        { type: 'shrine', id: 'shrine_p', data: 'penny', place: 'spot', spot: 'shrine' },
        { type: 'tape', id: 'tape_office', data: 'office_penny_tape', place: 'spot', spot: 'kitchen', fallback: 'mid' },
        { type: 'note', id: 'n_office_intro', data: 'office_intro', place: 'spot', spot: 'keypad', reuse: true, h: 1.55, beside: -0.95 },
        { type: 'note', id: 'n_carol', data: 'office_carol', place: 'spot', spot: 'kitchen', reuse: true, offset: [0.8, 0.6], fallback: 'mid' },
        { type: 'note', id: 'n_tracklist', data: 'office_tracklist', place: 'far', group: 'notes' },
        { type: 'note', id: 'n_walt5', data: 'office_walt5', place: 'far', group: 'notes' },
        { type: 'note', id: 'n_eddie_page', data: 'office_eddie_page', place: 'mid' },
        { type: 'note', id: 'n_board', data: 'office_board', place: 'spot', spot: 'meeting', fallback: 'far', wall: true, h: 1.5, prop: 'whiteboard' },
        { type: 'computer', id: 'pc_personnel', data: 'office_personnel', place: 'spot', spot: 'offices', fallback: 'any', h: 0.78 },
        { type: 'drawing', id: 'd_lily4', data: 'office_lily4', place: 'far', group: 'notes', minFrac: 0.5 },
        { type: 'phone', id: 'phone2', data: 'office_phone2', place: 'far', group: 'phone' },
        { type: 'phone', id: 'phone3', data: 'office_phone3', place: 'far', group: 'phone' },
      ].concat(supplies(4, 3)),
      entities: [{ type: 'ghost', ghost: 'pinky' }, { type: 'pacman', dormant: true }],
      ghost: 'penny',
      objectives: ['office_code', 'office_keypad', 'office_card', 'office_stairs'],
    },
    {
      id: 'school',
      layout: 'building', seed: 4161987, theme: 'school', music: 'school', fog: [0x1a1c1a, 0.02], grade: { tint: [1.0, 1.02, 0.98], sat: 0.85 },
      code: '317',
      gen: { w: 38, h: 22, rows: [10], cols: [18], cw: 2, maxDepth: 5, roomDepth: 3, roomW: [3, 4], numbered: 100, corridor: 'school', exitKind: 'metal', exitName: 'door.fireExit', exitLock: 'lock.fireExit',
        light: { kind: 'panel', color: [0.95, 1, 0.95], intensity: 0.85, flicker: 0.1, broken: 0.12 },
        specials: [
          { tag: 'gym', w: 6, minD: 5, depth: 6, count: 1, sign: 'GYM', second: true },
          { tag: 'janitor', w: 2, depth: 2, count: 1, locked: true, doorId: 'janitorDoor', nameKey: 'door.janitor', lockKey: 'lock.janitor', sign: 'CUSTODIAN', keypad: true },
          { tag: 'library', w: 5, minD: 4, depth: 4, count: 1, sign: 'LIBRARY' },
          { tag: 'office', w: 3, count: 1, sign: 'OFFICE' },
          { tag: 'cafeteria', w: 6, minD: 4, depth: 5, count: 1, sign: 'CAFETERIA' },
          { tag: 'restroom', w: 2, count: 1, sign: 'BOYS' },
        ],
        tags: [['classroom', 1]] },
      items: [
        { type: 'codeClue', id: 'clue_board', data: 'school_clue1', place: 'spot', spot: 'chalkboard', fallback: 'mid', wall: true, h: 1.1 },
        { type: 'codeClue', id: 'clue_slip', data: 'school_clue2', place: 'spot', spot: 'officeDeskTop', fallback: 'far' },
        { type: 'codeClue', id: 'clue_year', data: 'school_clue3', place: 'spot', spot: 'libraryTable', fallback: 'far' },
        { type: 'keypad', id: 'keypad', place: 'spot', spot: 'janitorKeypad', h: 1.35 },
        { type: 'key', id: 'janitorKeys', data: 'janitorKeys', place: 'spot', spot: 'janitorShelf', fallback: 'far' },
        { type: 'note', id: 'n_school_intro', data: 'school_intro', place: 'near' },
        { type: 'note', id: 'n_school_pass', data: 'school_passnote', place: 'spot', spot: 'classroomDesk', fallback: 'mid' },
        { type: 'note', id: 'n_school_plaque', data: 'school_plaque', place: 'mid', wall: true, h: 1.5 },
        { type: 'note', id: 'n_school_paper', data: 'school_paper', place: 'spot', spot: 'cafTableTop', fallback: 'mid' },
        { type: 'note', id: 'n_school_samlocker', data: 'school_samlocker', place: 'spot', spot: 'locker217', fallback: 'far' },
        { type: 'note', id: 'n_school_attend', data: 'school_attendance', place: 'spot', spot: 'classroomDesk', fallback: 'far' },
        { type: 'note', id: 'n_school_walt', data: 'school_walt', place: 'spot', spot: 'gym', fallback: 'far' },
        { type: 'tape', id: 'tape_school', data: 'school_tape', place: 'spot', spot: 'officeDeskTop', reuse: true, offset: [0.45, 0.1], fallback: 'mid' },
      ].concat(supplies(5, 3)),
      entities: [{ type: 'monitor' }, { type: 'pacman', dormant: true }],
      objectives: ['school_code', 'school_closet', 'school_keys', 'school_leave'],
    },
    {
      id: 'dark',
      layout: 'backrooms', seed: 1991, theme: 'dark', music: 'dark', fog: [0x020203, 0.06], grade: { tint: [1.0, 0.98, 0.95], sat: 0.8 },
      gen: { w: 46, h: 46, zones: 3, min: 2, gapEvery: 4, remove: 0.06, stubs: 90, corridors: 5, theme: 'dark', exitDoor: { kind: 'elevator', nameKey: 'door.service', lockKey: 'lock.service' },
        light: { density: 0.55, darkThreshold: -0.2, flicker: 0.15, broken: 0.1, color: [1, 0.9, 0.7] },
        landmarks: [{ tag: 'camp', w: 3, h: 3 }, { tag: 'shrine', w: 3, h: 3 }] },
      items: [
        { type: 'generator', id: 'gen', count: 3, place: 'spot', spot: 'generator', depth: 0.45, h: 0 },
        { type: 'fuelCan', id: 'fuel', count: 3, place: 'far', group: 'fuel', minFrac: 0.3 },
        { type: 'memento', id: 'lighter', data: 'clyde', place: 'spot', spot: 'generator', fallback: 'far' },
        { type: 'shrine', id: 'shrine_c', data: 'clyde', place: 'spot', spot: 'shrine' },
        { type: 'tape', id: 'tape_dark', data: 'dark_tape', place: 'spot', spot: 'camp' },
        { type: 'note', id: 'n_dark_intro', data: 'dark_intro', place: 'near' },
        { type: 'note', id: 'n_diary1', data: 'dark_diary1', place: 'mid' },
        { type: 'note', id: 'n_diary2', data: 'dark_diary2', place: 'far', group: 'notes' },
        { type: 'note', id: 'n_grandpa', data: 'dark_grandpa', place: 'spot', spot: 'shrine', fallback: 'far' },
        { type: 'note', id: 'n_grinners', data: 'dark_grinners', place: 'mid' },
        { type: 'note', id: 'n_walt6', data: 'dark_walt6', place: 'far', group: 'notes' },
        { type: 'note', id: 'n_darkwall', data: 'dark_wall', place: 'far', wall: true, h: 1.3, group: 'notes' },
        { type: 'note', id: 'n_porch', data: 'dark_porch', place: 'mid' },
        { type: 'glowstick', count: 7, place: 'any', group: 'glow', sep: 6 },
      ].concat(supplies(7, 3)),
      entities: [{ type: 'ghost', ghost: 'clyde' }, { type: 'grinner', count: 4 }, { type: 'pacman', dormant: true }],
      ghost: 'clyde',
      objectives: ['dark_generators', 'dark_leave'],
    },
    {
      id: 'mall',
      layout: 'building', seed: 12201986, theme: 'mall', music: 'mall', fog: [0x14120f, 0.018], grade: { tint: [1.04, 1.0, 0.96], sat: 1.0 },
      gen: { w: 34, h: 16, ceil: 5.2, storeSigns: true, rows: [6], cw: 3, maxDepth: 8, roomDepth: 5, roomW: [4, 5], glassFronts: true, numbered: false, corridor: 'mall', exitKind: 'glass', exitName: 'door.mallExit', exitLock: 'lock.mallExit',
        light: { kind: 'panel', color: [1, 0.95, 0.85], intensity: 1.15, range: 13, flicker: 0.06, broken: 0.1, roomBroken: 0.35 },
        specials: [
          { tag: 'records', w: 5, count: 1, sign: 'SPINS RECORDS' }, { tag: 'comics', w: 4, count: 1, sign: 'COMIC VAULT' },
          { tag: 'toys', w: 5, count: 1, sign: 'TOY PARADE' }, { tag: 'food', w: 6, count: 1, sign: 'FOOD COURT', noGlass: true },
          { tag: 'photo', w: 3, count: 1, sign: 'PHOTO' }, { tag: 'clothes', w: 5, count: 2, sign: 'FASHION' },
        ],
        tags: [['empty', 1]] },
      items: [
        { type: 'key', id: 'frame1', data: 'frame1', place: 'spot', spot: 'recordsCounter', fallback: 'far' },
        { type: 'key', id: 'frame2', data: 'frame2', place: 'spot', spot: 'comicsCounter', fallback: 'far' },
        { type: 'key', id: 'frame3', data: 'frame3', place: 'spot', spot: 'toysCounter', fallback: 'far' },
        { type: 'key', id: 'frame4', data: 'frame4', place: 'spot', spot: 'cafTableTop', fallback: 'far' },
        { type: 'booth', id: 'booth', place: 'spot', spot: 'photoBooth', h: 0 },
        { type: 'note', id: 'n_mall_intro', data: 'mall_intro', place: 'near' },
        { type: 'note', id: 'n_mall_dir', data: 'mall_directory', place: 'spot', spot: 'atrium', fallback: 'mid' },
        { type: 'note', id: 'n_mall_lists', data: 'mall_lists', place: 'spot', spot: 'toysCounter', reuse: true, offset: [0.5, 0], fallback: 'mid' },
        { type: 'note', id: 'n_mall_rec', data: 'mall_receipt', place: 'spot', spot: 'recordsCounter', reuse: true, offset: [0.5, 0], fallback: 'mid' },
        { type: 'note', id: 'n_mall_guard', data: 'mall_guard', place: 'far', group: 'notes' },
        { type: 'note', id: 'n_mall_kiosk', data: 'mall_kiosk', place: 'spot', spot: 'kioskTop', fallback: 'far' },
        { type: 'note', id: 'n_mall_walt', data: 'mall_walt', place: 'far', group: 'notes' },
        { type: 'tape', id: 'tape_mall', data: 'mall_tape', place: 'spot', spot: 'cafTableTop', fallback: 'mid' },
        { type: 'drawing', id: 'd_lily5', data: 'mall_lily5', place: 'spot', spot: 'emptyStore', fallback: 'far' },
      ].concat(supplies(5, 3)),
      entities: [{ type: 'mannequin', count: 6 }, { type: 'pacman', dormant: true }],
      objectives: ['mall_frames', 'mall_booth', 'mall_leave'],
      extraDocs: ['mall_frame1', 'mall_frame2', 'mall_frame3', 'mall_frame4', 'mall_strip'],
    },
    {
      id: 'motel',
      layout: 'building', seed: 6121993, theme: 'motel', music: 'motel', fog: [0x100b08, 0.03], grade: { tint: [1.06, 0.98, 0.9], sat: 0.9 },
      gen: { w: 32, h: 16, rows: [7], cw: 2, maxDepth: 7, roomDepth: 3, roomW: [2, 3], numbered: 0, corridor: 'motel', exitKind: 'metal', exitName: 'door.fireExit', exitLock: 'lock.fireExitMotel',
        light: { kind: 'hanging', color: [1, 0.8, 0.55], intensity: 0.75, flicker: 0.15, broken: 0.15, roomKind: 'bulb', roomBroken: 0.4, every: 3 },
        specials: [
          { tag: 'lobby', w: 5, count: 1, sign: 'OFFICE', noNumber: true }, { tag: 'laundry', w: 3, count: 1, sign: 'LAUNDRY' },
          { tag: 'ice', w: 2, count: 1, sign: 'ICE' },
          { tag: 'room12', w: 3, count: 1, locked: true, doorId: 'room12Door', nameKey: 'door.room12', lockKey: 'lock.room12', label: '12' },
        ],
        tags: [['motelRoom', 1]] },
      items: [
        { type: 'key', id: 'room12Key', data: 'room12Key', place: 'spot', spot: 'dryerTop', fallback: 'far' },
        { type: 'note', id: 'n_motel_register', data: 'motel_register', place: 'spot', spot: 'frontDesk', fallback: 'near' },
        { type: 'note', id: 'n_motel_intro', data: 'motel_intro', place: 'near' },
        { type: 'note', id: 'n_motel_complaint', data: 'motel_complaint', place: 'spot', spot: 'motelStand', fallback: 'mid' },
        { type: 'note', id: 'n_motel_postcard', data: 'motel_postcard', place: 'spot', spot: 'motelStand', fallback: 'mid' },
        { type: 'note', id: 'n_motel_walt', data: 'motel_walt', place: 'far', group: 'notes' },
        { type: 'note', id: 'n_motel_notebook', data: 'motel_notebook', place: 'spot', spot: 'room12Bed', fallback: 'far' },
        { type: 'note', id: 'n_motel_june', data: 'motel_june', place: 'spot', spot: 'room12', reuse: true, offset: [0.9, 0.4], fallback: 'far' },
        { type: 'note', id: 'n_motel_ultra', data: 'motel_ultrasound', place: 'spot', spot: 'room12StandL', fallback: 'far' },
        { type: 'tape', id: 'tape_motel', data: 'motel_tape', place: 'spot', spot: 'room12StandR', fallback: 'far' },
      ].concat(supplies(5, 3)),
      entities: [{ type: 'neighbor' }, { type: 'pacman', dormant: true }],
      objectives: ['motel_find12', 'motel_key', 'motel_room12', 'motel_leave'],
    },
    {
      id: 'hospital',
      layout: 'building', seed: 10111983, theme: 'hospital', music: 'hospital', fog: [0x121614, 0.022], grade: { tint: [0.96, 1.02, 1.0], sat: 0.8 },
      gen: { w: 36, h: 22, rows: [9], cols: [17], cw: 2, maxDepth: 5, roomDepth: 3, roomW: [3, 4], numbered: 200, corridor: 'hospital', exitKind: 'elevator', exitName: 'door.elevatorH', exitLock: 'lock.elevatorH',
        light: { kind: 'panel', color: [0.92, 1, 0.98], intensity: 0.85, flicker: 0.12, broken: 0.15 },
        specials: [
          { tag: 'room207', w: 3, count: 1, locked: true, doorId: 'room207Door', nameKey: 'door.room207', lockKey: 'lock.room207', label: '207' },
          { tag: 'nurse', w: 4, count: 1, sign: 'NURSES' }, { tag: 'chapel', w: 4, minD: 4, depth: 4, count: 1, sign: 'CHAPEL' }, { tag: 'storage', w: 2, count: 2 },
        ],
        tags: [['patient', 1]] },
      items: [
        { type: 'key', id: 'page1', data: 'page1', place: 'spot', spot: 'patientBed', fallback: 'far' },
        { type: 'key', id: 'page2', data: 'page2', place: 'spot', spot: 'patientBed', fallback: 'far' },
        { type: 'key', id: 'page3', data: 'page3', place: 'spot', spot: 'chapelAltar', fallback: 'far' },
        { type: 'key', id: 'page4', data: 'page4', place: 'spot', spot: 'storageShelf', fallback: 'far' },
        { type: 'key', id: 'page5', data: 'page5', place: 'spot', spot: 'patientBed', fallback: 'far' },
        { type: 'key', id: 'room207Key', data: 'room207Key', place: 'spot', spot: 'nurseTop', fallback: 'mid' },
        { type: 'note', id: 'n_hosp_intro', data: 'hospital_intro', place: 'near' },
        { type: 'note', id: 'n_hosp_nurse', data: 'hospital_nurse', place: 'spot', spot: 'nurseTop', reuse: true, offset: [0.6, 0.05], fallback: 'mid' },
        { type: 'note', id: 'n_hosp_ruth', data: 'hospital_ruth', place: 'spot', spot: 'chapelPew', fallback: 'far' },
        { type: 'note', id: 'n_hosp_visitors', data: 'hospital_visitors', place: 'spot', spot: 'nurseTop', reuse: true, offset: [-0.6, 0.05], fallback: 'mid' },
        { type: 'note', id: 'n_hosp_card', data: 'hospital_card', place: 'spot', spot: 'room207Stand', fallback: 'far' },
        { type: 'note', id: 'n_hosp_chompy', data: 'hospital_chompy', place: 'spot', spot: 'room207Wall', fallback: 'far' },
        { type: 'note', id: 'n_hosp_chart', data: 'hospital_chart', place: 'spot', spot: 'room207Foot', fallback: 'far' },
        { type: 'tape', id: 'tape_hosp', data: 'hospital_tape', place: 'spot', spot: 'patientStand', fallback: 'mid' },
        { type: 'drawing', id: 'd_lily6', data: 'hospital_lily6', place: 'spot', spot: 'room207Side', fallback: 'far' },
      ].concat(supplies(5, 3)),
      entities: [{ type: 'watcher' }, { type: 'pacman', dormant: true }],
      objectives: ['hospital_pages', 'hospital_207', 'hospital_leave'],
      extraDocs: ['hospital_diary1', 'hospital_diary2', 'hospital_diary3', 'hospital_diary4', 'hospital_diary5'],
    },
    {
      id: 'maple',
      layout: 'street', seed: 4171987, theme: 'street', music: 'maple', fog: [0x0a0c12, 0.028], grade: { tint: [0.96, 0.98, 1.06], sat: 0.85 },
      gen: { w: 40, h: 14, houses: 10 },
      items: [
        { type: 'phone', id: 'machine', data: 'maple_machine', place: 'spot', spot: 'samHouseLiving', fallback: 'mid' },
        { type: 'note', id: 'n_maple_intro', data: 'maple_intro', place: 'near' },
        { type: 'note', id: 'n_maple_missing', data: 'maple_missing', place: 'spot', spot: 'poleFlyer', fallback: 'mid' },
        { type: 'note', id: 'n_maple_paper', data: 'maple_paper', place: 'spot', spot: 'samHousePorch', fallback: 'mid' },
        { type: 'note', id: 'n_maple_samroom', data: 'maple_samroom', place: 'spot', spot: 'samHousePillow', fallback: 'far' },
        { type: 'note', id: 'n_maple_clyderoom', data: 'maple_clyderoom', place: 'spot', spot: 'clydeHousePillow', fallback: 'far' },
        { type: 'note', id: 'n_maple_porch', data: 'maple_porch', place: 'spot', spot: 'clydeHouseScreenDoor', fallback: 'mid' },
        { type: 'note', id: 'n_maple_walt', data: 'maple_walt', place: 'far', group: 'notes' },
        { type: 'drawing', id: 'd_lily7', data: 'maple_lily7', place: 'spot', spot: 'samHouseDesk', fallback: 'far' },
      ].concat(supplies(4, 2)),
      entities: [{ type: 'neighbor' }],
      objectives: ['maple_clyde', 'maple_home', 'maple_corner', 'maple_leave'],
    },
    {
      id: 'workshop',
      layout: 'workshop', seed: 3171987, theme: 'workshop', music: 'workshop', fog: [0x0e0c0a, 0.03], grade: { tint: [1.05, 1.0, 0.92], sat: 0.9 },
      dials: [2, 5, 6],
      items: [
        { type: 'key', id: 'waltKey', data: 'waltKey', place: 'spot', spot: 'desk' },
        { type: 'dial', id: 'dial', count: 3, place: 'spot', spot: 'dial' },
        { type: 'note', id: 'n_ws_intro', data: 'workshop_intro', place: 'near' },
        { type: 'note', id: 'n_ws_schem', data: 'workshop_schematic', place: 'spot', spot: 'bench2', fallback: 'mid' },
        { type: 'note', id: 'n_ws_eddie', data: 'workshop_eddiebench', place: 'spot', spot: 'bench3', fallback: 'mid' },
        { type: 'note', id: 'n_ws_keytag', data: 'workshop_keytag', place: 'spot', spot: 'desk', reuse: true, offset: [0.5, 0.1] },
        { type: 'note', id: 'n_ws_receipt', data: 'workshop_receipt', place: 'spot', spot: 'chompyTag', fallback: 'mid' },
        { type: 'note', id: 'n_ws_nora', data: 'workshop_nora', place: 'spot', spot: 'benchW', fallback: 'mid' },
        { type: 'note', id: 'n_ws_ticket', data: 'workshop_ticket', place: 'spot', spot: 'bench1', fallback: 'mid' },
        { type: 'tape', id: 'tape_317', data: 'workshop_317', place: 'spot', spot: 'kernel', fallback: 'far' },
        { type: 'drawing', id: 'd_lily8', data: 'workshop_lily8', place: 'spot', spot: 'wsShelf', fallback: 'far' },
      ].concat(supplies(3, 2)),
      entities: [{ type: 'chompy', spot: 'chompy', dormant: true, heading: -Math.PI / 2 }],
      objectives: ['workshop_key', 'workshop_kernel', 'workshop_dials', 'workshop_leave'],
    },
    {
      id: 'maze',
      layout: 'maze', seed: 1992, theme: 'maze', music: 'maze', fog: [0x000006, 0.02], grade: { tint: [0.95, 0.97, 1.08], sat: 1.15 },
      items: [
        { type: 'powerPellet', id: 'mpellet', count: 4, place: 'spot', spot: 'corner', center: true },
        { type: 'note', id: 'n_neon', data: 'maze_neon', place: 'spot', spot: 'corner', center: true },
        { type: 'note', id: 'n_rules', data: 'maze_rules', place: 'spot', spot: 'corner', center: true },
        { type: 'note', id: 'n_house', data: 'maze_house', place: 'spot', spot: 'corner', center: true },
        { type: 'battery', count: 1, place: 'spot', spot: 'corner', center: true },
        { type: 'portal', id: 'portal', place: 'spot', spot: 'houseInside', center: true },
      ],
      entities: [{ type: 'pacman', arcade: true }, { type: 'ghost', ghost: 'blinky', maze: true }, { type: 'ghost', ghost: 'pinky', maze: true }, { type: 'ghost', ghost: 'inky', maze: true }, { type: 'ghost', ghost: 'clyde', maze: true }, { type: 'watcher' }],
      objectives: ['maze_pellets', 'maze_house'],
    },
    {
      id: 'killscreen',
      layout: 'killscreen', seed: 256, theme: 'glitch', music: 'glitch', fog: [0x04000a, 0.03], grade: { tint: [1.05, 0.95, 1.08], sat: 1.2 },
      items: [
        { type: 'plug', id: 'plug', place: 'spot', spot: 'core', center: true },
        { type: 'powerPellet', id: 'gpellet', count: 2, place: 'spot', spot: 'corner', center: true, fallback: 'any' },
        { type: 'note', id: 'n_glitch1', data: 'ks_glitch1', place: 'mid' },
        { type: 'note', id: 'n_glitch2', data: 'ks_glitch2', place: 'far' },
        { type: 'note', id: 'n_walt8', data: 'ks_walt8', place: 'spot', spot: 'core', fallback: 'far' },
        { type: 'note', id: 'n_eddie_exit', data: 'ks_eddie', place: 'far', group: 'notes' },
      ],
      entities: [{ type: 'pacman', arcade: true, final: true }, { type: 'watcher' }],
      objectives: ['ks_core', 'ks_choice'],
    },
  ];
  LEVELS.forEach((L, i) => { L.index = i; });

  // Ghost type ↔ character
  const GHOSTS = { blinky: 'billy', pinky: 'penny', inky: 'ivy', clyde: 'clyde' };
  const CHAR_COLOR = { billy: '#ff2a2a', penny: '#ff9ad5', ivy: '#39e6ff', clyde: '#ffae3b' };

  PB.Levels = { LEVELS, GHOSTS, CHAR_COLOR, byId: id => LEVELS.find(l => l.id === id) };
})(typeof window !== 'undefined' ? window : globalThis);
