/* 日本語インターフェース。 */
(function (root) {
  'use strict';
  root.PB.I18N.register('ja', 'ui', {
    'game.title': 'LEVEL 256',
    'game.subtitle': 'スターライト・ゲームセンター',
    'game.aria': 'ゲーム画面',
    'noscript': 'このゲームには JavaScript が必要です。',

    'boot.tip': 'ヒント',
    'boot.init': '起動中…',
    'boot.fonts': 'フォントを読み込み中…',
    'boot.sounds': '効果音を録音中…',
    'boot.voices': '声を録音中…',
    'boot.prep': 'ステージを準備中…',
    'boot.noThree': '3D エンジン（three.js）を読み込めませんでした。インターネット接続を確認して、ページを再読み込みしてください。',
    'boot.error': '起動エラー：{msg}',
    'boot.noWebgl': 'グラフィックカードで3D（WebGL 2）を開始できませんでした。グラフィックドライバーを更新してから、ゲームを起動し直してください。',
    'load.textures': 'テクスチャを織っています…（{n}/{m}）',
    'load.walls': '壁を立てています…',
    'load.bake': '光を焼き付けています…',
    'load.fixtures': '蛍光灯を吊るしています…',
    'load.props': '家具を配置しています…',
    'load.decals': '染みと傷…',
    'load.shaders': 'シェーダーをコンパイル中…',
    'load.ready': '準備完了',
    'load.error': '読み込みエラー：{msg}',

    'first.title': 'はじめる前に',
    'first.lang': '言語',
    'first.bright': '左の記号がかろうじて見え、右の記号がはっきり見えるように明るさを調整してください。',
    'first.phones': 'ヘッドホンを付けて、暗い部屋でのプレイをおすすめします。',
    'first.go': '次へ',

    'menu.continue': 'つづきから',
    'menu.new': 'はじめから',
    'menu.levels': 'チャプター',
    'menu.settings': '設定',
    'menu.archive': 'アーカイブ',
    'menu.help': '遊び方',
    'menu.quit': 'ゲームを終了',
    'menu.credit': 'ハーロウ · 1994年11月30日 · 午前2時11分',
    'menu.foot': 'ヘッドホンを付けて、暗闇で。',
    'menu.footDone': 'エンディング：{list} · 死亡 {deaths} 回',

    'confirm.title': 'はじめからプレイしますか？',
    'confirm.body': 'セーブデータは上書きされます。見つけた資料はアーカイブに残ります。',
    'confirm.yes': 'はい、やり直す',
    'confirm.no': 'キャンセル',

    'diff.title': '難易度',
    'diff.easy': 'イージー',
    'diff.easyDesc': '物語を楽しみたい人向け。怪物は遅く、注意力も鈍い。各チャプターで一度だけ、捕まっても振りほどける。',
    'diff.normal': 'ノーマル',
    'diff.normalDesc': '想定どおりの体験。一度捕まると最後のセーブに戻る。',
    'diff.nightmare': 'ナイトメア',
    'diff.nightmareDesc': '怪物はより速く、耳も鋭い。電池の減りが早い。恐怖が早く訪れる。',
    'diff.time': 'プレイ時間の目安：すべての資料を読み、四体の亡霊をすべて解放して約4〜6時間。',

    'levels.title': 'チャプター',
    'levels.locked': '未解放',

    'common.back': '戻る',
    'common.on': 'オン',
    'common.off': 'オフ',

    'settings.title': '設定',
    'settings.reset': '初期設定に戻す',
    'settings.reloadNote': '* の付いた設定は、次にチャプターを読み込んだときに反映されます。',
    'tab.screen': '画面',
    'set.displayMode': '表示モード',
    'set.displayMode.help': 'フルスクリーンではブラウザが隠れます。Esc か F11 で解除、ゲーム中は Alt+Enter で切り替え。',
    'opt.windowed': 'ウィンドウ',
    'opt.fullscreen': 'フルスクリーン',
    'set.resolution': '解像度',
    'set.resolution.help': '描画する画像のサイズ。「ネイティブ」は画面の解像度を使い、それ以外のサイズは下のスケーリング方式でウィンドウに合わせます。',
    'opt.native': 'ネイティブ（画面）',
    'set.scaleMode': 'スケーリング方式',
    'set.scaleMode.help': 'ウィンドウと縦横比が異なる解像度の表示方法。',
    'opt.fit': 'フィット（比率維持、黒帯あり）',
    'opt.stretch': '引き伸ばし',
    'opt.fill': 'フィル（端をトリミング）',
    'set.upscale': '拡大フィルター',
    'set.upscale.help': '「スムーズ」は拡大時にピクセルを混ぜ、「ピクセル」はくっきり四角いまま残します（低解像度でレトロな見た目）。',
    'opt.smooth': 'スムーズ',
    'opt.pixel': 'ピクセル',
    'set.sharpen': 'シャープネス',
    'set.sharpen.help': '最終画像にコントラスト適応型のシャープ処理をかけます。ネイティブ未満の解像度やアンチエイリアス使用時に効果的。',
    'set.fpsLimit': 'フレームレート上限',
    'set.fpsLimit.help': '1秒あたりのフレーム数を制限します。低めの上限はGPUの発熱を抑え、フレーム間隔を安定させます。',
    'opt.unlimited': '無制限',
    'set.vsync': '垂直同期',
    'set.vsync.help': 'オン：フレームがモニターのリフレッシュに合わせて表示され、ティアリングが起きません。オフ：フレームレート上限まで、できるだけ速く描画します。ウェブブラウザではブラウザ自体が常にモニターを待つため、オフはゲーム側の待機をなくすだけです。デスクトップ版では同期を完全にオフにします（再起動後）。',
    'tab.graphics': 'グラフィック',
    'tab.display': '映像',
    'tab.audio': 'サウンド',
    'tab.controls': '操作',
    'tab.gameplay': 'ゲーム',
    'preset.low': '低',
    'preset.medium': '中',
    'preset.high': '高',
    'preset.ultra': '最高',
    'preset.extreme': 'エクストリーム',
    'preset.custom': 'カスタム',
    'opt.off': 'オフ',
    'opt.low': '低',
    'opt.medium': '中',
    'opt.high': '高',
    'opt.ultra': '最高',
    'opt.extreme': 'エクストリーム',
    'opt.shadow1': '低（1024）',
    'opt.shadow2': '高（2048）',
    'opt.shadow3': '最高（4096）',
    'opt.small': '小',
    'opt.large': '大',
    'opt.full': 'フル',
    'opt.reduced': '控えめ',

    'set.preset': '画質プリセット',
    'set.preset.help': '下のグラフィック設定をまとめて変更します。「エクストリーム」はハイエンドGPU向け。「最高+」はさらにその上（8192の影、最も緻密なライトベイク、最も精細なモデル、被写界深度）で、最も強力なPC向けです。',
    'set.renderScale': '解像度スケール',
    'set.renderScale.help': '100%を超えると高い解像度で描画してから縮小します。画像は鮮明になりますが、GPUの負荷は大きく増えます。',
    'set.textureRes': 'テクスチャ解像度',
    'set.shadows': '影',
    'set.antialias': 'アンチエイリアス',
    'set.lightmapRes': 'ライトベイク品質',
    'set.lightmapRes.help': 'あらかじめ計算された柔らかな光と影の精細さ。',
    'set.dynLights': 'ダイナミックライト',
    'set.bloom': 'ブルーム',
    'set.bloomStrength': 'ブルームの強さ',
    'set.volumetric': 'ボリュームライトと塵',
    'set.ao': 'アンビエントオクルージョン（SSAO）',
    'set.ao.help': '部屋の隅や家具の下、タイルの間にできる柔らかな接地影。',
    'set.ssr': 'スクリーンスペース反射',
    'set.ssr.help': '濡れた床、タイル、ガラス、磨かれた金属に映る本物の反射。',
    'set.volumetric.help': 'レイマーチングで計算する光の筋、懐中電灯の光束、漂う塵。エクストリームでは非常に重い。',
    'set.motionBlur': 'モーションブラー',
    'set.lensDirt': 'レンズの汚れ',
    'set.lensDirt.help': '強い光を受けて浮かび上がるレンズの汚れ。',
    'set.particles': 'パーティクル密度',
    'set.viewDist': '描画距離',
    'set.anisotropy': '異方性フィルタリング',
    'set.brightness': '明るさ',
    'set.brightness.help': '一番暗い隅がかろうじて見える程度に合わせてください。',
    'set.contrast': 'コントラスト',
    'set.saturation': '彩度',
    'set.fov': '視野角',
    'set.headBob': '頭の揺れ',
    'set.shake': 'カメラの揺れ',
    'set.grain': 'フィルムグレイン',
    'set.chromatic': '色収差',
    'set.vignette': 'ビネット',
    'set.vhs': 'ビデオカメラ（VHS）風',
    'set.vhs.help': '1994年のビデオカメラのファインダー越しのようにゲームを映します。',
    'set.reduceFlicker': 'ちらつきを抑える',
    'set.reduceFlicker.help': '光に敏感なプレイヤーのために、点滅する照明や画面のフラッシュを和らげます。',
    'set.crosshair': '照準点',
    'set.subtitles': '字幕',
    'set.captions': '効果音字幕',
    'set.captions.help': '重要な音を文字で表示します。例：[遠くで咀嚼する音]',
    'set.subtitleSize': '字幕サイズ',
    'set.master': 'マスター音量',
    'set.music': '音楽',
    'set.sfx': '効果音',
    'set.ambience': '環境音（うなり、水滴、雨）',
    'set.entities': '怪物の音',
    'set.voice': '声と無線',
    'set.hrtf': '3Dオーディオ（HRTF、ヘッドホン推奨）',
    'set.mouseSens': 'マウス感度',
    'set.invertY': '上下の視点操作を反転',
    'set.touchSens': 'タッチ感度',
    'set.toggleCrouch': 'しゃがむ：押し続けずに切り替え',
    'set.toggleSprint': '走る：押し続けずに切り替え',
    'set.lang': '言語',
    'set.difficulty': '難易度',
    'set.difficulty.help': '怪物の速さと聴覚、懐中電灯の電池に影響します。',
    'set.jumpscare': 'ジャンプスケア',
    'set.hints': 'ヒント',

    'archive.title': 'アーカイブ',
    'archive.count': '資料 {n} / {m}',
    'archive.notFound': '未発見',
    'kind.note': 'メモ',
    'kind.letter': '手紙',
    'kind.diary': '日記のページ',
    'kind.tape': 'テープの録音',
    'kind.photo': '写真',
    'kind.screen': 'コンピューターの画面',
    'kind.phone': '留守番電話のメッセージ',
    'kind.printout': 'プリントアウト',
    'kind.wall': '壁の書き込み',
    'kind.notice': '貼り紙',
    'kind.memory': '記憶',
    'kind.drawing': '絵',
    'kind.card': 'カード',
    'kind.report': '報告書',
    'kind.flyer': 'チラシ',
    'kind.doc': '資料',

    'help.title': '遊び方',
    'help.kbm': 'キーボードとマウス',
    'help.walk': '歩く',
    'help.mouse': 'マウス',
    'help.look': '見回す（クリックでカーソルを固定）',
    'help.sprint': '走る（音が大きく、息を消費）',
    'help.crouch': 'しゃがむ（ほぼ無音）',
    'help.interact': '調べる、読む、取る、隠れる',
    'help.flash': '懐中電灯',
    'help.drink': 'Star Pop を飲む',
    'help.throw': 'ケミカルライトを投げる',
    'help.lean': '左右に身を乗り出す（角の先をのぞく）',
    'help.map': 'マップ',
    'help.bag': '持ち物 / 手帳',
    'bag.items': '持ち物',
    'bag.journal': '手帳',
    'bag.close': '閉じる（I / J）',
    'bag.empty': 'ポケットは空っぽだ。',
    'bag.inspectHint': 'ドラッグして回す。',
    'bag.now': 'いま',
    'bag.story': 'これまでの物語',
    'bag.docs': 'ここで見つけたもの',
    'bag.noDocs': 'ここではまだ何も見つけていない。よく探そう。',
    'bag.people': '人物',
    'bag.freed': '安らかに',
    'bag.hunting': 'まだ狩っている',
    'bag.stats': '資料 {a} / {b}   ·   リリーの絵 {c} / {d}',
    'bag.n.flashlight': '懐中電灯',
    'bag.d.flashlight': 'ゲームセンターのバンにあった重い鋼の懐中電灯。電池：{n}%。消える前にまず暗くなる。',
    'bag.n.battery': '予備の電池',
    'bag.d.battery': '懐中電灯用の単一電池。R で交換。電池が切れると自動で入れ替わる。',
    'bag.n.almond': 'Star Pop',
    'bag.d.almond': 'ゲームセンター特製のチェリーソーダの缶。なぜかまだ冷たい。糖分と炭酸で手の震えが止まる。Q で飲む。',
    'bag.n.glow': 'ケミカルライト',
    'bag.d.glow': '折って光らせ、G で投げる。這うものと笑うものは緑の光を越えられない。',
    'bag.d.officeKey': 'レジから出てきたウォルトの事務所の鍵。真鍮はすり減ってつるつるだ。',
    'bag.d.token': '星形の穴があいたスターライトのメダル。7番台専用。',
    'bag.n.fuse': 'ヒューズ',
    'bag.d.fuse': '工場の古い配電盤に使う、重い陶器のヒューズ。',
    'bag.n.fuel': '軽油の缶',
    'bag.d.fuel': '発電機用の軽油。大きな音で揺れる。ゆっくり歩こう。',
    'bag.d.keycard': '磁気ストライプ付きのセキュリティカード。誰かの写真が削り取られている。',
    'bag.d.key': '紙の札が付いた鍵。ここの何かを開ける。',
    'help.pause': 'ポーズ',
    'help.touch': 'タッチ操作',
    'help.touchText': '左下のスティックで移動、画面の右側をドラッグして見回す。右のボタン：調べる、懐中電灯、走る、しゃがむ、マップ。',
    'help.survive': '生き延びるには',
    'help.tip1': '<b>喰らうもの</b>はまっすぐな通路ではこちらより速く、曲がり角では遅い。角を曲がれ。',
    'help.tip2': '蛍光灯がちらつき始めたら、<b>近くにいる</b>。',
    'help.tip3': '<b>ランタン</b>を取れば、数秒のあいだ何もかもがこちらから逃げていく。',
    'help.tip4': '<b>赤</b>は決して止まらない。<b>紫</b>は行く手をふさぐ。<b>青緑</b>は水の音を聞きつけ、あちこちに跳ぶ。<b>琥珀</b>は見つめているあいだ動けない。',
    'help.tip5': '机の下やロッカーに<b>隠れ</b>られる。入るところを見られていなければ、見つかることはない。',
    'help.tip6': '<b>テープレコーダー</b>でセーブできる。目標を達成して安全なときにはオートセーブされる。',
    'help.tip7': 'それぞれの亡霊の形見を<b>その祭壇</b>へ届けよう。エンディングが変わる。',

    'pause.title': 'ポーズ',
    'pause.resume': 'ゲームに戻る',
    'pause.map': 'マップ',
    'pause.journal': '手帳',
    'pause.archive': 'アーカイブ',
    'pause.settings': '設定',
    'pause.help': '遊び方',
    'pause.load': '最後のセーブをロード',
    'pause.menu': 'メインメニュー',

    'note.close': '閉じる',
    'note.closeKey': '閉じる（E）',

    'map.close': '閉じる',
    'map.closeKey': '閉じる（M）',
    'map.objective': '目標',
    'map.tape': 'テープ',
    'map.doc': '資料',
    'map.shrine': '祭壇',
    'map.supply': '物資',
    'map.locked': '施錠された扉',

    'kp.label': 'セキュリティ',
    'kp.clear': '消去',
    'kp.enter': '決定',
    'kp.open': '解錠',
    'kp.error': 'エラー',
    'kp.close': 'キャンセル（Esc）',

    'cab.help': '矢印キーか WASD · Enter でスタート · P でポーズ ·',
    'cab.exit': '筐体から離れる（Esc）',

    'choice.back': '後ずさる',
    'card.skip': 'クリックするか E で次へ',

    'death.retry': '最後のセーブから再開',
    'death.menu': 'メインメニュー',

    'end.menu': 'メインメニュー',
    'end.skip': 'スキップ',
    'end.time': 'プレイ時間',
    'end.deaths': '死亡回数',
    'end.docs': '資料',
    'end.freed': '解放した亡霊',
    'end.drawings': '見つけた絵',

    'hud.objective': '目標',
    'hud.rec': 'REC',
    'hud.stamina': '息',
    'hud.battery': '明かり',
    'hud.power': '電力 {t}',
    'hud.fps': '{n} FPS',

    'touch.pause': 'ポーズ',
    'touch.bag': '持ち物',
    'touch.map': 'マップ',
    'touch.drink': '飲む',
    'touch.throw': '投げる',
    'touch.crouch': 'しゃがむ',
    'touch.sprint': '走る',
    'touch.flash': 'ライト',
    'touch.tap': 'タップ',

    'inv.battery': '電池 ×{n}',
    'inv.almond': 'STAR POP ×{n}',
    'inv.glow': 'ケミカルライト ×{n}',
    'inv.officeKey': '事務所の鍵',
    'inv.token': '金のメダル',
    'inv.fuses': 'ヒューズ ×{n}',
    'inv.fuel': '軽油 ×{n}',
    'inv.keycard': 'セキュリティカード',
    'inv.pellets': 'ランタン ×{n}',

    'n.added': 'アーカイブに追加：{title}',
    'n.saved': 'セーブしました',
    'n.batteryIn': '懐中電灯に新しい電池',
    'n.batterySpare': '予備の電池',
    'n.noSpare': '予備の電池がない。',
    'n.batteryFull': '電池はまだ満タンだ。',
    'hint.reload': 'R：懐中電灯の電池を交換',
    'touch.reload': '電池',
    'help.reload': '懐中電灯の電池を交換',
    'help.lookBack': '走りながら振り返る（長押し）',
    'n.batterySwap': '予備の電池に交換した',
    'n.almond': 'Star Pop（Q で飲む）',
    'n.glow': 'ケミカルライト（G で投げる）',
    'n.found': '入手：{name}',
    'n.drank': 'Star Pop を飲んだ。呼吸が落ち着く。',
    'n.noAlmond': 'Star Pop を持っていない。',
    'n.noGlow': 'ケミカルライトを持っていない。',
    'n.slow': '動作が重くなっています。ポーズ › 設定 › グラフィック で画質を下げられます。',
    'n.lockFail': 'マウスを固定できませんでした。左ボタンを押したままドラッグして見回してください。',
    'n.flashDead': '懐中電灯が切れた。',
    'n.holdBreath': '何かが近くにいる。Shift を押し続けて息を止めろ。',
    'n.heardBreath': '息づかいを聞かれた。',
    'n.noFlash': '懐中電灯を持っていない。',
    'n.noBattery': '電池が切れた。予備を探そう。',
    'n.grace': '危なかった！（イージー：各チャプター一度だけ）',
    'n.freed': '{name}は安らぎを得た',
    'n.ghostBack': '{name}は退いた',
    'n.cabinetHi': 'ハイスコア表にイニシャルが載った：SAM',
    'n.perfect': '星をすべて食べた。パーフェクト。',
    'n.fruit': '家の前にボーナスが現れた',
    'n.diesel': '軽油の缶',
    'n.drawing': 'リリーの絵（{n}/8）',

    'pr.read': '読む：{title}',
    'pr.readWall': '書き込みを読む',
    'pr.screen': '画面を見る',
    'pr.tape': 'テープを再生（セーブ）',
    'pr.battery': '電池を取る',
    'pr.almond': 'Star Pop を取る',
    'pr.glow': 'ケミカルライトを取る',
    'pr.flashlight': '懐中電灯を取る',
    'pr.token': 'メダルを取る',
    'pr.fuse': 'ヒューズを取る',
    'pr.fuel': '軽油の缶を取る',
    'pr.keycard': 'セキュリティカードを取る',
    'pr.take': '取る：{name}',
    'pr.pellet': 'ランタンを取る',
    'pr.phoneRing': '電話に出る',
    'pr.phone': '受話器を取る',
    'pr.cabinetFree': '筐体で遊ぶ（FREE PLAY）',
    'pr.doorLocked': '{name}（施錠）',
    'pr.doorOpen': '扉を開ける',
    'pr.doorClose': '扉を閉める',
    'pr.drawerOpen': '引き出しを開ける',
    'pr.drawerClose': '引き出しを閉める',
    'pr.safeOpen': '金庫を開ける',
    'pr.safeClose': '金庫を閉める',
    'pr.safeLocked': '金庫（番号を入力）',
    'pr.hide': '下に隠れる',
    'pr.hideLocker': 'ロッカーに隠れる',
    'pr.unhide': '出る',
    'pr.shrineLook': '祭壇を見る',
    'pr.shrinePlace': '形見を祭壇に置く',
    'pr.drawing': 'リリーの絵を取る',

    'door.default': '扉',
    'door.office': '事務所の扉',
    'door.storage': '倉庫',
    'door.wc': 'トイレ',
    'door.front': '正面の扉',
    'door.elevator': '貨物用エレベーター',
    'door.security': '警備室',
    'door.stair': '非常階段',
    'door.house': '亡霊の家',
    'door.service': '業務用エレベーター',
    'lock.service': 'エレベーターは死んでいる。三台の発電機をすべて動かす必要がある。',
    'door.exit': '出口',
    'door.room': '{n}号室',
    'door.jammed': '扉',
    'lock.jammed': '動かない。ノブは回るが、向こう側で何かが押さえている。',
    'lock.exit': '出口には鍵がかかっている。まだだ。',
    'door.pressure': '耐圧扉',
    'lock.pressure': '耐圧扉はびくともしない。向こうで蒸気が噴き出している。',
    'door.janitor': '用務員室',
    'lock.janitor': 'ダイヤル錠。三桁。',
    'door.fireExit': '非常口',
    'lock.fireExit': '太い鎖と南京錠。鍵は用務員が持っている。',
    'lock.fireExitMotel': 'バーが押せない。誰かが外から塞いでいる。',
    'door.gym': '体育館',
    'door.mallExit': 'ショッピングモールの扉',
    'lock.mallExit': '夜間は閉鎖。遠くで証明写真ボックスがうなっている。',
    'door.room12': '12号室',
    'lock.room12': '施錠されている。番号札は、毎日誰かが触れているかのように磨かれている。',
    'door.room207': '207号室',
    'lock.room207': '施錠されている。紙の貼り紙：おしずかに。クレヨンの太陽が描かれている。',
    'door.elevatorH': 'エレベーター',
    'lock.elevatorH': 'エレベーターは扉を閉ざして待っている。何かを待っている。',
    'door.samHouse': '自分の家',
    'door.tobyHouse': 'トビーの家',
    'door.neighbor': '玄関',
    'lock.neighbor': '施錠されている。目をそらすとカーテンが動く。',
    'door.alley': '路地への扉',
    'lock.alley': '施錠されている。あの角に立つまでは開かない。',
    'door.kernel': '鋼鉄の扉',
    'lock.kernel': '鋼鉄製で、施錠されている。真鍮の札：KERNEL — W. 以外立入禁止',
    'lock.default': '施錠されている。',
    'lock.office': '施錠されている。扉に真鍮の札：「W. — 支配人」',
    'lock.front': '外から南京錠がかけられている。鍵は引っ越し業者が持っている。',
    'lock.elevator': 'エレベーターに電気が来ていない。呼び出しボタンが反応しない。',
    'lock.security': 'キーパッドが四桁の暗証番号を求めている。',
    'lock.stair': 'カードリーダーのランプが赤い。セキュリティカードが必要だ。',
    'lock.house': '紫色の光の幕。四つのランタンがそれを閉ざしている。',

    'cap.front': '前方',
    'cap.back': '背後',
    'cap.left': '左',
    'cap.right': '右',
    'cap.phone': '[電話が鳴っている]',
    'cap.drag': '[近くで足を引きずる音]',
    'cap.moan': '[うめき声]',
    'cap.farSteps': '[建物のどこか別の場所で足音]',
    'cap.thud': '[遠くで何かが倒れた]',
    'cap.buzz': '[蛍光灯がパチパチ鳴る]',
    'cap.whisper': '[ささやき声]',
    'cap.giggle': '[暗闇でくすくす笑う声]',
    'cap.radio': '[無線の雑音]',
    'cap.thunder': '[雷鳴]',
    'cap.hiss': '[湿ったシューという音が遠ざかる]',
    'cap.skitter': '[レンガの上を何かが這い回る]',
    'cap.whistle': '[笛が甲高く鳴る]',
    'cap.plastic': '[プラスチックがきしむ]',
    'cap.bite': '[すぐ近くで歯が噛み合う音]',
    'cap.biteFar': '[遠くで咀嚼する音]',
    'cap.callName': '[誰かがトビーの声で名前を呼ぶ]',
    'cap.heavySteps': '[重い足音、ゴムのきしみ]',
    'cap.pipe': '[トンネルのどこかでパイプが鳴る]',
    'cap.locker': '[廊下の奥でロッカーが勢いよく閉まる]',
    'cap.knock': '[廊下の奥で三回ノックの音]',
    'cap.beep': '[誰もいない病室でモニターが鳴る]',
    'cap.arc': '[鋼鉄の扉の向こうで電気がはじける]',
    'cap.pop': '[蛍光管が破裂する]',
    'cap.slam': '[背後で扉が叩きつけられる]',
    'cap.run': '[見えないところで誰かが走っている]',
    'cap.callJune': '[廊下の奥から女の声：「エディ？ エディ、あなたなの？」]',
    'cap.car': '[濡れた通りを車が音を立てて通り過ぎる]',
    'cap.door': '[どこかで扉の音]',
    'cap.drip': '[水の滴る音]',
    'cap.hum': '[蛍光灯のうなり]',
    'tab.access': 'アクセシビリティ',
    'tab.perf': 'パフォーマンス',
    'set.perfOverlay': 'パフォーマンス表示',
    'set.perfOverlay.help': 'ゲームの動作状況を表示します。「FPSのみ」、「基本」はフレーム時間、1フレームあたりのCPU時間とGPU時間、それぞれの負荷を追加、「詳細」はさらにフレーム時間グラフ、描画コール、ポリゴン数、メモリ、描画解像度、グラフィックカードを表示します。GPU時間にはGPUタイマークエリに対応したブラウザが必要です（デスクトップ版は常に対応）。',
    'set.perfCorner': '表示位置',
    'set.perfCorner.help': 'パフォーマンス表示を画面のどの隅に置くか。',
    'opt.perfFps': 'FPSのみ',
    'opt.perfBasic': '基本',
    'opt.perfDetailed': '詳細',
    'opt.cornerTR': '右上',
    'opt.cornerTL': '左上',
    'opt.cornerBR': '右下',
    'opt.cornerBL': '左下',
    'preset.ultraplus': '最高+',
    'opt.ultraplus': '最高+',
    'opt.shadow4': '最高+（8192）',
    'set.modelDetail': 'モデルの精細さ',
    'set.modelDetail.help': '怪物や手など、彫刻されたモデルをどれだけ細かく作るか。高いほど近くで滑らかに見え、チャプターの読み込みに時間がかかります。「最高+」は最速のCPU向け。',
    'set.clutter': '小物の量',
    'set.clutter.help': '部屋を埋める小物の数：絵、写真、カレンダー、箱、紙、瓶。多いほど生活感が出て、少ないほど古いPCに優しくなります。',
    'set.dof': '被写界深度',
    'set.dof.help': 'カメラのレンズのように、見ている場所から離れたものをぼかします。ピントは画面中央を追います。高い設定ほどサンプル数が増え、柔らかくきれいなボケになります。',
    'set.textureRes.help': '壁、床、木材、布などの表面の鮮明さ。高いほどビデオメモリを使います。',
    'set.shadows.help': '懐中電灯と屋外の街灯が落とす影。高いほど鮮明です。「最高+」は8192のシャドウマップを使い、大量のビデオメモリが必要です。',
    'set.antialias.help': 'ギザギザの輪郭を滑らかにします。MSAAが最もきれいで、FXAAは軽いものの画面全体が少し柔らかくなります。両方で最も滑らかになります。',
    'set.dynLights.help': '近くのランプのうち、動く物や怪物を同時に照らせる数。',
    'set.bloom.help': '明るい照明や画面のまわりに出る柔らかな光のにじみ。',
    'set.bloomStrength.help': 'そのにじみの強さ。',
    'set.motionBlur.help': '素早く振り向いたときに画面をぼかします。手と手に持った物はくっきりしたままです。',
    'set.particles.help': '空気中の塵、雨、火花、水滴。',
    'set.viewDist.help': 'どれだけ遠くまで描画し、霧がどこまで見せてくれるか。',
    'set.anisotropy.help': '浅い角度から見た床や壁をくっきり保ちます。負荷はほとんどありません。',
    'set.contrast.help': '画面の暗い部分と明るい部分の差。',
    'set.saturation.help': '色の鮮やかさ。低くすると古い写真のようになります。',
    'set.fov.help': '見える範囲の広さ。広いほど多くが見えますが、すべてが遠くに感じられます。',
    'set.headBob.help': '歩くときの視点の揺れの大きさ。酔う場合は下げてください。',
    'set.shake.help': '驚いたとき、ぶつかったとき、走ったときのカメラの揺れ。',
    'set.grain.help': '画面に乗るフィルムの粒子。',
    'set.chromatic.help': '安いレンズのような、画面の端の色ずれ。',
    'set.vignette.help': '画面の四隅に向かって暗くなる効果。',
    'set.crosshair.help': '拾える物を狙いやすくする、画面中央の小さな点。',
    'set.subtitles.help': '話している内容を表示します：無線、テープ、心の声。',
    'set.subtitleSize.help': '字幕と効果音字幕の大きさ。',
    'set.master.help': '全体の音量。',
    'set.music.help': '音楽の音量。',
    'set.sfx.help': '足音、扉、物、そして自分の行動すべての音。',
    'set.ambience.help': '部屋、雨、うなり、建物が立てる音。',
    'set.entities.help': '怪物の足音、息づかい、声。',
    'set.voice.help': '無線、テープ、心の声。',
    'set.hrtf.help': '音を立体的に周囲に配置します。ヘッドホンに最適。スピーカーではオフにしてください。',
    'set.mouseSens.help': 'マウスで視点が回る速さ。',
    'set.invertY.help': 'マウスを上に動かすと下を向きます。',
    'set.touchSens.help': 'タッチスクリーンでドラッグしたときに視点が回る速さ。',
    'set.toggleCrouch.help': 'キーを押し続ける代わりに、一度押すとしゃがみ、もう一度押すと立ちます。',
    'set.toggleSprint.help': 'キーを押し続ける代わりに、一度押すと走り、もう一度押すと歩きます。',
    'set.lang.help': 'メニュー、字幕、ゲーム内のすべての資料の言語。',
    'set.jumpscare.help': '「控えめ」ではすべての恐怖演出を残したまま、最も激しい閃光と音を和らげます。',
    'set.hints.help': '新しいことが起きたときに短いヒントを表示します。',
    'perf.frame': 'フレーム',
    'perf.low1': '1% Low',
    'perf.cpu': 'CPU',
    'perf.cpuUse': 'CPU負荷',
    'perf.gpu': 'GPU',
    'perf.gpuUse': 'GPU負荷',
    'perf.na': 'なし',
    'perf.draws': '描画コール',
    'perf.tris': 'ポリゴン',
    'perf.textures': 'テクスチャ',
    'perf.programs': 'シェーダー',
    'perf.res': '描画',
    'perf.heap': 'JSメモリ',
    'perf.sysCpu': 'システムCPU',
    'perf.appCpu': 'ゲームのCPU',
    'perf.procMem': 'ゲームのメモリ',
    'perf.card': 'グラフィックカード',
    'settings.revert': '元に戻す',
    'settings.keys': '↑↓ 選択 · ←→ 変更 · Q/E タブ · Backspace 元に戻す · Esc 戻る',
    'settings.impact': 'パフォーマンスへの影響',
    'impact.0': 'なし',
    'impact.1': '小',
    'impact.2': '中',
    'impact.3': '大',
    'impact.4': '特大',
    'impact.5': '極大',
    'settings.gpuLoad': '推定GPU負荷',
    'settings.vram': '推定ビデオメモリ',
    'settings.reloadBadge': '次にチャプターを読み込んだときに反映',
    'settings.restartBadge': 'ゲームの再起動後に反映',
    'settings.restartNow': '今すぐ再起動',
  });
})(typeof window !== 'undefined' ? window : globalThis);
