/* 한국어 인터페이스. */
(function (root) {
  'use strict';
  root.PB.I18N.register('ko', 'ui', {
    'game.title': 'LEVEL 256',
    'game.subtitle': '스타라이트 오락실',
    'game.aria': '게임 화면',
    'noscript': '이 게임을 하려면 JavaScript가 필요합니다.',

    'boot.tip': '팁',
    'boot.init': '시작하는 중…',
    'boot.fonts': '글꼴을 불러오는 중…',
    'boot.sounds': '소리를 녹음하는 중…',
    'boot.voices': '목소리를 녹음하는 중…',
    'boot.prep': '스테이지를 준비하는 중…',
    'boot.noThree': '3D 엔진(three.js)을 불러오지 못했습니다. 인터넷 연결을 확인하고 페이지를 새로 고치세요.',
    'boot.error': '시작 오류: {msg}',
    'boot.noWebgl': '그래픽 카드에서 3D(WebGL 2)를 시작하지 못했습니다. 그래픽 드라이버를 업데이트한 뒤 게임을 다시 시작하세요.',
    'load.textures': '텍스처를 짜는 중… ({n}/{m})',
    'load.walls': '벽을 세우는 중…',
    'load.bake': '빛을 굽는 중…',
    'load.fixtures': '형광등을 다는 중…',
    'load.props': '가구를 놓는 중…',
    'load.decals': '얼룩과 긁힌 자국…',
    'load.shaders': '셰이더를 컴파일하는 중…',
    'load.ready': '준비 완료',
    'load.error': '불러오기 오류: {msg}',

    'first.title': '시작하기 전에',
    'first.lang': '언어',
    'first.bright': '왼쪽 기호가 겨우 보이고 오른쪽 기호가 뚜렷하게 보이도록 밝기를 맞추세요.',
    'first.phones': '헤드폰을 끼고 어두운 방에서 플레이하는 것을 권장합니다.',
    'first.go': '계속',

    'menu.continue': '이어하기',
    'menu.new': '새 게임',
    'menu.levels': '챕터',
    'menu.settings': '설정',
    'menu.archive': '기록 보관소',
    'menu.help': '플레이 방법',
    'menu.quit': '게임 종료',
    'menu.credit': '할로 · 1994년 11월 30일 · 오전 2:11',
    'menu.foot': '헤드폰을 끼고, 어둠 속에서.',
    'menu.footDone': '엔딩: {list} · 사망 {deaths}회',

    'confirm.title': '새 게임을 시작할까요?',
    'confirm.body': '저장된 진행 상황을 덮어씁니다. 찾은 문서는 기록 보관소에 남습니다.',
    'confirm.yes': '네, 처음부터',
    'confirm.no': '취소',

    'diff.title': '난이도',
    'diff.easy': '쉬움',
    'diff.easyDesc': '이야기에 집중. 괴물이 더 느리고 덜 예민합니다. 챕터마다 한 번은 붙잡혀도 빠져나옵니다.',
    'diff.normal': '보통',
    'diff.normalDesc': '의도한 그대로. 한 번 붙잡히면 마지막 저장으로 돌아갑니다.',
    'diff.nightmare': '악몽',
    'diff.nightmareDesc': '괴물이 더 빠르고 귀도 더 밝습니다. 배터리가 빨리 닳습니다. 공포가 더 일찍 찾아옵니다.',
    'diff.time': '예상 플레이 시간: 모든 문서를 읽고 네 유령을 모두 풀어 주면 4~6시간.',

    'levels.title': '챕터',
    'levels.locked': '잠김',

    'common.back': '뒤로',
    'common.on': '켬',
    'common.off': '끔',

    'settings.title': '설정',
    'settings.reset': '기본값',
    'settings.reloadNote': '* 표시가 있는 설정은 다음에 챕터를 불러올 때 적용됩니다.',
    'tab.screen': '화면',
    'set.displayMode': '화면 모드',
    'set.displayMode.help': '전체 화면에서는 브라우저가 숨겨집니다. Esc나 F11로 나가고, 게임 중에는 Alt+Enter로 전환합니다.',
    'opt.windowed': '창 모드',
    'opt.fullscreen': '전체 화면',
    'set.resolution': '해상도',
    'set.resolution.help': '렌더링되는 이미지의 크기. 기본은 화면 해상도를 쓰며, 다른 크기는 아래 크기 조정 방식에 따라 창에 맞춥니다.',
    'opt.native': '기본(화면)',
    'set.scaleMode': '크기 조정 방식',
    'set.scaleMode.help': '창과 비율이 다른 해상도를 어떻게 보여 줄지 정합니다.',
    'opt.fit': '맞춤(비율 유지, 검은 여백)',
    'opt.stretch': '늘리기',
    'opt.fill': '채우기(가장자리 자름)',
    'set.upscale': '확대 필터',
    'set.upscale.help': '부드럽게는 확대할 때 픽셀을 섞고, 픽셀은 선명한 네모 그대로 둡니다(저해상도에서 레트로 느낌).',
    'opt.smooth': '부드럽게',
    'opt.pixel': '픽셀',
    'set.sharpen': '선명도',
    'set.sharpen.help': '최종 이미지에 대비 적응형 선명화를 적용합니다. 기본 해상도보다 낮을 때나 안티앨리어싱을 쓸 때 도움이 됩니다.',
    'set.fpsLimit': '프레임 제한',
    'set.fpsLimit.help': '초당 프레임 수를 제한합니다. 제한이 낮을수록 그래픽 카드가 덜 뜨겁고 프레임 간격이 고릅니다.',
    'opt.unlimited': '제한 없음',
    'set.vsync': '수직 동기화',
    'set.vsync.help': '켬: 프레임이 모니터 주사율에 맞춰 나와 화면 찢어짐이 없습니다. 끔: 프레임 제한까지 최대한 빠르게 그립니다. 웹 브라우저에서는 브라우저 자체가 항상 모니터를 기다리므로, 끔은 게임 자체의 대기만 없앱니다. 데스크톱 버전은 동기화를 완전히 끕니다(재시작 후).',
    'tab.graphics': '그래픽',
    'tab.display': '영상',
    'tab.audio': '오디오',
    'tab.controls': '조작',
    'tab.gameplay': '게임',
    'preset.low': '낮음',
    'preset.medium': '중간',
    'preset.high': '높음',
    'preset.ultra': '울트라',
    'preset.extreme': '익스트림',
    'preset.custom': '사용자 지정',
    'opt.off': '끔',
    'opt.low': '낮음',
    'opt.medium': '중간',
    'opt.high': '높음',
    'opt.ultra': '울트라',
    'opt.extreme': '익스트림',
    'opt.shadow1': '낮음 (1024)',
    'opt.shadow2': '높음 (2048)',
    'opt.shadow3': '울트라 (4096)',
    'opt.small': '작게',
    'opt.large': '크게',
    'opt.full': '전체',
    'opt.reduced': '약하게',

    'set.preset': '품질 프리셋',
    'set.preset.help': '아래의 그래픽 설정을 한꺼번에 바꿉니다. 익스트림은 고급 그래픽 카드용이고, 울트라+는 그보다 더 나아가(8192 그림자, 가장 촘촘한 빛 굽기, 가장 정교한 모델, 피사계 심도) 가장 강력한 PC를 위한 설정입니다.',
    'set.renderScale': '해상도 배율',
    'set.renderScale.help': '100%를 넘으면 더 높은 해상도로 렌더링한 뒤 줄입니다. 화면은 더 선명해지지만 그래픽 카드 부담이 크게 늘어납니다.',
    'set.textureRes': '텍스처 해상도',
    'set.shadows': '그림자',
    'set.antialias': '안티앨리어싱',
    'set.lightmapRes': '구운 조명 품질',
    'set.lightmapRes.help': '미리 계산한 부드러운 빛과 그림자의 세밀함.',
    'set.dynLights': '동적 조명',
    'set.bloom': '블룸',
    'set.bloomStrength': '블룸 강도',
    'set.volumetric': '볼류메트릭 조명과 먼지',
    'set.ao': '앰비언트 오클루전(SSAO)',
    'set.ao.help': '구석, 가구 아래, 타일 사이에 생기는 부드러운 접촉 그림자.',
    'set.ssr': '화면 공간 반사',
    'set.ssr.help': '젖은 바닥, 타일, 유리, 윤이 나는 금속에 비치는 진짜 반사.',
    'set.volumetric.help': '레이 마칭으로 계산한 빛줄기, 손전등 불빛, 떠다니는 먼지. 익스트림에서는 매우 무겁습니다.',
    'set.motionBlur': '모션 블러',
    'set.lensDirt': '렌즈 얼룩',
    'set.lensDirt.help': '강한 빛을 받으면 드러나는 카메라 렌즈의 얼룩.',
    'set.particles': '입자 밀도',
    'set.viewDist': '시야 거리',
    'set.anisotropy': '비등방성 필터링',
    'set.brightness': '밝기',
    'set.brightness.help': '가장 어두운 구석이 겨우 보일 정도로 맞추세요.',
    'set.contrast': '대비',
    'set.saturation': '채도',
    'set.fov': '시야각',
    'set.headBob': '머리 흔들림',
    'set.shake': '카메라 흔들림',
    'set.grain': '필름 그레인',
    'set.chromatic': '색수차',
    'set.vignette': '비네팅',
    'set.vhs': '캠코더(VHS) 효과',
    'set.vhs.help': '1994년 캠코더 뷰파인더로 보는 것처럼 화면을 보여 줍니다.',
    'set.reduceFlicker': '깜빡임 줄이기',
    'set.reduceFlicker.help': '빛에 민감한 플레이어를 위해 깜빡이는 조명과 화면 섬광을 누그러뜨립니다.',
    'set.crosshair': '조준점',
    'set.subtitles': '자막',
    'set.captions': '소리 자막',
    'set.captions.help': '중요한 소리를 글로 보여 줍니다. 예: [멀리서 씹는 소리]',
    'set.subtitleSize': '자막 크기',
    'set.master': '전체 음량',
    'set.music': '음악',
    'set.sfx': '효과음',
    'set.ambience': '환경음(웅웅거림, 물방울, 비)',
    'set.entities': '괴물 소리',
    'set.voice': '목소리와 무전',
    'set.hrtf': '3D 오디오(HRTF, 헤드폰 권장)',
    'set.mouseSens': '마우스 감도',
    'set.invertY': '세로 시점 반전',
    'set.touchSens': '터치 감도',
    'set.toggleCrouch': '앉기: 누르고 있지 않고 전환',
    'set.toggleSprint': '달리기: 누르고 있지 않고 전환',
    'set.lang': '언어',
    'set.difficulty': '난이도',
    'set.difficulty.help': '괴물의 속도와 청각, 손전등 배터리에 영향을 줍니다.',
    'set.jumpscare': '점프 스케어',
    'set.hints': '힌트',

    'archive.title': '기록 보관소',
    'archive.count': '문서 {n} / {m}',
    'archive.notFound': '아직 찾지 못함',
    'kind.note': '쪽지',
    'kind.letter': '편지',
    'kind.diary': '일기장',
    'kind.tape': '테이프 녹음',
    'kind.photo': '사진',
    'kind.screen': '컴퓨터 화면',
    'kind.phone': '자동 응답기 메시지',
    'kind.printout': '출력물',
    'kind.wall': '벽의 글씨',
    'kind.notice': '공지',
    'kind.memory': '기억',
    'kind.drawing': '그림',
    'kind.card': '카드',
    'kind.report': '보고서',
    'kind.flyer': '전단지',
    'kind.doc': '문서',

    'help.title': '플레이 방법',
    'help.kbm': '키보드와 마우스',
    'help.walk': '걷기',
    'help.mouse': '마우스',
    'help.look': '둘러보기(클릭하면 커서 고정)',
    'help.sprint': '달리기(시끄럽고 숨을 씀)',
    'help.crouch': '앉기(거의 소리 없음)',
    'help.interact': '상호작용, 읽기, 줍기, 숨기',
    'help.flash': '손전등',
    'help.drink': 'Star Pop 마시기',
    'help.throw': '야광봉 던지기',
    'help.lean': '왼쪽 / 오른쪽으로 몸 기울이기(모퉁이 엿보기)',
    'help.map': '지도',
    'help.bag': '소지품 / 수첩',
    'bag.items': '소지품',
    'bag.journal': '수첩',
    'bag.close': '닫기 (I / J)',
    'bag.empty': '주머니가 텅 비었다.',
    'bag.inspectHint': '드래그해서 돌려 보세요.',
    'bag.now': '지금',
    'bag.story': '지금까지의 이야기',
    'bag.docs': '여기서 찾은 것',
    'bag.noDocs': '여기서는 아직 아무것도 찾지 못했다. 더 자세히 살펴보자.',
    'bag.people': '사람들',
    'bag.freed': '평안함',
    'bag.hunting': '아직 사냥 중',
    'bag.stats': '문서 {a} / {b}   ·   릴리의 그림 {c} / {d}',
    'bag.n.flashlight': '손전등',
    'bag.d.flashlight': '오락실 승합차에서 꺼낸 묵직한 강철 손전등. 배터리: {n}%. 꺼지기 전에 먼저 어두워진다.',
    'bag.n.battery': '예비 배터리',
    'bag.d.battery': '손전등용 대형 배터리. R로 갈아 끼운다. 배터리가 다 되면 자동으로 교체된다.',
    'bag.n.almond': 'Star Pop',
    'bag.d.almond': '오락실에서 직접 만든 체리 탄산음료. 어째서인지 아직도 차갑다. 설탕과 탄산이 떨리는 손을 진정시킨다. Q로 마신다.',
    'bag.n.glow': '야광봉',
    'bag.d.glow': '하나를 꺾어 G로 던진다. 기는 것과 웃는 것은 초록빛을 넘지 않는다.',
    'bag.d.officeKey': '금전 등록기에서 나온 월트의 사무실 열쇠. 놋쇠가 닳아 매끈하다.',
    'bag.d.token': '별 모양 구멍이 뚫린 스타라이트 토큰. 7번 기계 전용.',
    'bag.n.fuse': '퓨즈',
    'bag.d.fuse': '공장의 낡은 배전반에 쓰는 무거운 도자기 퓨즈.',
    'bag.n.fuel': '경유 통',
    'bag.d.fuel': '발전기에 넣을 경유. 출렁거리는 소리가 크다. 천천히 걷자.',
    'bag.d.keycard': '마그네틱 띠가 있는 보안 카드. 누군가의 사진이 긁혀 지워져 있다.',
    'bag.d.key': '종이 꼬리표가 달린 열쇠. 여기 있는 무언가를 연다.',
    'help.pause': '일시 정지',
    'help.touch': '터치',
    'help.touchText': '왼쪽 아래 스틱으로 움직이고, 화면 오른쪽을 드래그해 둘러봅니다. 오른쪽 버튼: 상호작용, 손전등, 달리기, 앉기, 지도.',
    'help.survive': '살아남는 법',
    'help.tip1': '<b>포식자</b>는 곧은 복도에서는 나보다 빠르지만 모퉁이에서는 느리다. 모퉁이를 돌아라.',
    'help.tip2': '형광등이 깜빡이기 시작하면 <b>가까이 있다</b>.',
    'help.tip3': '<b>등불</b>을 집으면 몇 초 동안 모든 것이 나를 피해 달아난다.',
    'help.tip4': '<b>빨강</b>은 절대 멈추지 않는다. <b>보라</b>는 길을 막아선다. <b>청록</b>은 물소리를 듣고 이곳저곳으로 순간 이동한다. <b>호박색</b>은 바라보는 동안 얼어붙는다.',
    'help.tip5': '책상 밑이나 사물함에 <b>숨을</b> 수 있다. 들어가는 모습을 들키지 않으면 찾아내지 못한다.',
    'help.tip6': '<b>테이프 녹음기</b>로 저장한다. 목표를 달성하고 안전할 때는 자동 저장된다.',
    'help.tip7': '유령마다 유품을 <b>그 제단</b>에 가져다주자. 엔딩이 달라진다.',

    'pause.title': '일시 정지',
    'pause.resume': '계속하기',
    'pause.map': '지도',
    'pause.journal': '수첩',
    'pause.archive': '기록 보관소',
    'pause.settings': '설정',
    'pause.help': '플레이 방법',
    'pause.load': '마지막 저장 불러오기',
    'pause.menu': '메인 메뉴',

    'note.close': '닫기',
    'note.closeKey': '닫기 (E)',

    'map.close': '닫기',
    'map.closeKey': '닫기 (M)',
    'map.objective': '목표',
    'map.tape': '테이프',
    'map.doc': '문서',
    'map.shrine': '제단',
    'map.supply': '보급품',
    'map.locked': '잠긴 문',

    'kp.label': '보안',
    'kp.clear': '지움',
    'kp.enter': '확인',
    'kp.open': '열림',
    'kp.error': '오류',
    'kp.close': '취소 (Esc)',

    'cab.help': '방향키 또는 WASD · Enter로 시작 · P로 일시 정지 ·',
    'cab.exit': '기계에서 떨어지기 (Esc)',

    'choice.back': '물러서기',
    'card.skip': '클릭하거나 E를 눌러 계속',

    'death.retry': '마지막 저장부터 계속',
    'death.menu': '메인 메뉴',

    'end.menu': '메인 메뉴',
    'end.skip': '건너뛰기',
    'end.time': '플레이 시간',
    'end.deaths': '사망',
    'end.docs': '문서',
    'end.freed': '풀어 준 유령',
    'end.drawings': '찾은 그림',

    'hud.objective': '목표',
    'hud.rec': 'REC',
    'hud.stamina': '숨',
    'hud.battery': '불빛',
    'hud.power': '전력 {t}',
    'hud.fps': '{n} FPS',

    'touch.pause': '일시 정지',
    'touch.bag': '가방',
    'touch.map': '지도',
    'touch.drink': '마시기',
    'touch.throw': '던지기',
    'touch.crouch': '앉기',
    'touch.sprint': '달리기',
    'touch.flash': '불빛',
    'touch.tap': '누르기',

    'inv.battery': '배터리 ×{n}',
    'inv.almond': 'STAR POP ×{n}',
    'inv.glow': '야광봉 ×{n}',
    'inv.officeKey': '사무실 열쇠',
    'inv.token': '금색 토큰',
    'inv.fuses': '퓨즈 ×{n}',
    'inv.fuel': '경유 ×{n}',
    'inv.keycard': '보안 카드',
    'inv.pellets': '등불 ×{n}',

    'n.added': '기록 보관소에 추가됨: {title}',
    'n.saved': '저장했습니다',
    'n.batteryIn': '손전등에 새 배터리',
    'n.batterySpare': '예비 배터리',
    'n.noSpare': '예비 배터리가 없다.',
    'n.batteryFull': '배터리가 아직 가득하다.',
    'hint.reload': 'R: 손전등 배터리 교체',
    'touch.reload': '배터리',
    'help.reload': '손전등 배터리 교체',
    'help.lookBack': '달리면서 뒤돌아보기(누르고 있기)',
    'n.batterySwap': '예비 배터리로 갈아 끼웠다',
    'n.almond': 'Star Pop (Q로 마시기)',
    'n.glow': '야광봉 (G로 던지기)',
    'n.found': '찾음: {name}',
    'n.drank': 'Star Pop을 마신다. 숨이 가라앉는다.',
    'n.noAlmond': 'Star Pop이 없다.',
    'n.noGlow': '야광봉이 없다.',
    'n.slow': '게임이 느리게 실행되고 있습니다. 일시 정지 › 설정 › 그래픽에서 품질을 낮출 수 있습니다.',
    'n.lockFail': '마우스를 고정하지 못했습니다. 왼쪽 버튼을 누른 채 드래그해 둘러보세요.',
    'n.flashDead': '손전등이 꺼졌다.',
    'n.holdBreath': '무언가 가까이 있다. Shift를 누르고 있으면 숨을 참는다.',
    'n.heardBreath': '숨소리를 들켰다.',
    'n.noFlash': '손전등이 없다.',
    'n.noBattery': '배터리가 다 됐다. 예비를 찾자.',
    'n.grace': '아슬아슬했다! (쉬움: 챕터마다 한 번)',
    'n.freed': '{name}, 평안을 얻다',
    'n.ghostBack': '{name}, 물러나다',
    'n.cabinetHi': '최고 점수표에 이니셜이 올랐다: SAM',
    'n.perfect': '별을 전부 먹었다. 퍼펙트.',
    'n.fruit': '집 앞에 상품이 나타났다',
    'n.diesel': '경유 통',
    'n.drawing': '릴리의 그림 ({n}/8)',

    'pr.read': '읽기: {title}',
    'pr.readWall': '글씨 읽기',
    'pr.screen': '화면 보기',
    'pr.tape': '테이프 재생(저장)',
    'pr.battery': '배터리 줍기',
    'pr.almond': 'Star Pop 줍기',
    'pr.glow': '야광봉 줍기',
    'pr.flashlight': '손전등 줍기',
    'pr.token': '토큰 줍기',
    'pr.fuse': '퓨즈 줍기',
    'pr.fuel': '경유 통 줍기',
    'pr.keycard': '보안 카드 줍기',
    'pr.take': '줍기: {name}',
    'pr.pellet': '등불 줍기',
    'pr.phoneRing': '전화 받기',
    'pr.phone': '수화기 들기',
    'pr.cabinetFree': '기계로 게임하기(FREE PLAY)',
    'pr.doorLocked': '{name}(잠김)',
    'pr.doorOpen': '문 열기',
    'pr.doorClose': '문 닫기',
    'pr.drawerOpen': '서랍 열기',
    'pr.drawerClose': '서랍 닫기',
    'pr.safeOpen': '금고 열기',
    'pr.safeClose': '금고 닫기',
    'pr.safeLocked': '금고(비밀번호 입력)',
    'pr.hide': '밑에 숨기',
    'pr.hideLocker': '사물함에 숨기',
    'pr.unhide': '나오기',
    'pr.shrineLook': '제단 살펴보기',
    'pr.shrinePlace': '유품을 제단에 두기',
    'pr.drawing': '릴리의 그림 줍기',

    'door.default': '문',
    'door.office': '사무실 문',
    'door.storage': '창고',
    'door.wc': '화장실',
    'door.front': '정문',
    'door.elevator': '화물 엘리베이터',
    'door.security': '경비실',
    'door.stair': '비상계단',
    'door.house': '유령의 집',
    'door.service': '직원용 엘리베이터',
    'lock.service': '엘리베이터가 죽어 있다. 발전기 세 대가 모두 돌아가야 한다.',
    'door.exit': '출구',
    'door.room': '{n}호실',
    'door.jammed': '문',
    'lock.jammed': '꽉 끼었다. 손잡이는 돌아가지만 반대편에서 무언가가 붙잡고 있다.',
    'lock.exit': '출구가 잠겨 있다. 아직은 아니다.',
    'door.pressure': '압력문',
    'lock.pressure': '압력문이 꿈쩍도 하지 않는다. 뒤에서 증기가 쉭쉭거린다.',
    'door.janitor': '관리인실',
    'lock.janitor': '번호 자물쇠. 세 자리.',
    'door.fireExit': '비상구',
    'lock.fireExit': '굵은 쇠사슬과 자물쇠. 열쇠는 관리인에게 있다.',
    'lock.fireExitMotel': '손잡이 봉이 밀리지 않는다. 누군가 밖에서 막아 놓았다.',
    'door.gym': '체육관',
    'door.mallExit': '쇼핑몰 문',
    'lock.mallExit': '밤이라 닫혔다. 멀리서 즉석 사진 부스가 웅웅거린다.',
    'door.room12': '12호실',
    'lock.room12': '잠겨 있다. 번호판이 반짝반짝하다. 누군가 매일 만지기라도 하는 것처럼.',
    'door.room207': '207호',
    'lock.room207': '잠겨 있다. 종이 안내문: 조용히 해 주세요. 크레용으로 그린 해가 있다.',
    'door.elevatorH': '엘리베이터',
    'lock.elevatorH': '엘리베이터가 문을 닫은 채 기다린다. 무언가를 기다리고 있다.',
    'door.samHouse': '우리 집',
    'door.tobyHouse': '토비네 집',
    'door.neighbor': '현관문',
    'lock.neighbor': '잠겨 있다. 눈을 돌리면 커튼이 움직인다.',
    'door.alley': '골목으로 난 문',
    'lock.alley': '잠겨 있다. 그 모퉁이에 서 보기 전에는 열리지 않는다.',
    'door.kernel': '강철 문',
    'lock.kernel': '강철로 된 문이 잠겨 있다. 놋쇠 명판: KERNEL — W. 전용',
    'lock.default': '잠겨 있다.',
    'lock.office': '잠겨 있다. 문에 놋쇠 명판: "W. — 지배인"',
    'lock.front': '밖에서 자물쇠로 잠겨 있다. 열쇠는 이삿짐 인부들이 가지고 있다.',
    'lock.elevator': '엘리베이터에 전기가 없다. 호출 버튼이 먹통이다.',
    'lock.security': '키패드가 네 자리 비밀번호를 요구한다.',
    'lock.stair': '카드 리더기에 빨간불이 켜져 있다. 보안 카드가 필요하다.',
    'lock.house': '보랏빛 빛의 장막. 등불 네 개가 그것을 닫아 두고 있다.',

    'cap.front': '앞',
    'cap.back': '뒤',
    'cap.left': '왼쪽',
    'cap.right': '오른쪽',
    'cap.phone': '[전화가 울린다]',
    'cap.drag': '[가까이서 발을 끄는 소리]',
    'cap.moan': '[신음 소리]',
    'cap.farSteps': '[건물 다른 곳에서 발소리]',
    'cap.thud': '[멀리서 무언가 쓰러진다]',
    'cap.buzz': '[형광등이 지직거린다]',
    'cap.whisper': '[속삭임]',
    'cap.giggle': '[어둠 속 킥킥거리는 소리]',
    'cap.radio': '[무전기 잡음]',
    'cap.thunder': '[천둥]',
    'cap.hiss': '[축축한 쉭 소리가 멀어진다]',
    'cap.skitter': '[벽돌 위를 긁으며 기어가는 소리]',
    'cap.whistle': '[호루라기가 날카롭게 울린다]',
    'cap.plastic': '[플라스틱이 삐걱거린다]',
    'cap.bite': '[가까이서 이빨이 맞부딪친다]',
    'cap.biteFar': '[멀리서 씹는 소리]',
    'cap.callName': '[누군가 토비의 목소리로 이름을 부른다]',
    'cap.heavySteps': '[무거운 발소리, 고무가 끽 하는 소리]',
    'cap.pipe': '[터널 어딘가에서 파이프가 울린다]',
    'cap.locker': '[복도 끝에서 사물함이 쾅 닫힌다]',
    'cap.knock': '[복도 어딘가에서 세 번 두드리는 소리]',
    'cap.beep': '[빈 병실에서 모니터가 삑삑거린다]',
    'cap.arc': '[강철 문 뒤에서 전기가 튄다]',
    'cap.pop': '[형광등이 터진다]',
    'cap.slam': '[뒤에서 문이 쾅 닫힌다]',
    'cap.run': '[보이지 않는 곳에서 누군가 달린다]',
    'cap.callJune': '[복도 끝에서 여자 목소리: "에디? 에디, 당신이야?"]',
    'cap.car': '[젖은 길 위로 차가 쉭 지나간다]',
    'cap.door': '[어딘가에서 문소리]',
    'cap.drip': '[물 떨어지는 소리]',
    'cap.hum': '[형광등 웅웅거림]',
    'tab.access': '접근성',
    'tab.perf': '성능',
    'set.perfOverlay': '성능 표시',
    'set.perfOverlay.help': '게임이 어떻게 돌아가는지 보여 줍니다. FPS만, 기본은 프레임 시간과 프레임당 CPU·GPU 시간, 각각의 부하를 더하고, 자세히는 여기에 프레임 시간 그래프, 드로 콜, 삼각형 수, 메모리, 렌더링 해상도, 그래픽 카드를 더합니다. GPU 시간은 GPU 타이머 쿼리를 지원하는 브라우저가 필요합니다(데스크톱 버전은 항상 지원).',
    'set.perfCorner': '표시 위치',
    'set.perfCorner.help': '성능 표시가 화면의 어느 모서리에 놓일지 정합니다.',
    'opt.perfFps': 'FPS만',
    'opt.perfBasic': '기본',
    'opt.perfDetailed': '자세히',
    'opt.cornerTR': '오른쪽 위',
    'opt.cornerTL': '왼쪽 위',
    'opt.cornerBR': '오른쪽 아래',
    'opt.cornerBL': '왼쪽 아래',
    'preset.ultraplus': '울트라+',
    'opt.ultraplus': '울트라+',
    'opt.shadow4': '울트라+ (8192)',
    'set.modelDetail': '모델 정밀도',
    'set.modelDetail.help': '괴물, 손, 그 밖의 조각된 모델을 얼마나 세밀하게 만드는지. 높을수록 가까이서 매끄럽고 챕터를 불러오는 시간이 길어집니다. 울트라+는 가장 빠른 프로세서용입니다.',
    'set.clutter': '소품 양',
    'set.clutter.help': '방을 채우는 작은 물건의 수: 그림, 사진, 달력, 상자, 종이, 병. 많을수록 사람이 살던 곳 같고, 적을수록 오래된 컴퓨터에 가볍습니다.',
    'set.dof': '피사계 심도',
    'set.dof.help': '카메라 렌즈처럼, 바라보는 곳에서 먼 것을 흐리게 합니다. 초점은 화면 중앙을 따라갑니다. 높은 설정일수록 샘플을 더 많이 써서 더 부드럽고 깨끗하게 흐려집니다.',
    'set.textureRes.help': '벽, 바닥, 나무, 천 같은 표면의 선명도. 높을수록 비디오 메모리가 더 필요합니다.',
    'set.shadows.help': '손전등과 바깥 가로등이 드리우는 그림자. 높을수록 선명합니다. 울트라+는 8192 그림자 맵을 써서 비디오 메모리가 많이 필요합니다.',
    'set.antialias.help': '계단 같은 가장자리를 매끄럽게 합니다. MSAA가 가장 깨끗하고, FXAA는 가볍지만 화면 전체가 살짝 부드러워지며, 둘을 함께 쓰면 가장 매끄럽습니다.',
    'set.dynLights.help': '근처 조명 중 움직이는 물체와 괴물을 동시에 비출 수 있는 수.',
    'set.bloom.help': '밝은 조명과 화면 주변에 번지는 부드러운 빛.',
    'set.bloomStrength.help': '그 빛 번짐의 세기.',
    'set.motionBlur.help': '빠르게 돌아볼 때 화면을 흐리게 합니다. 손과 손에 든 물건은 선명하게 유지됩니다.',
    'set.particles.help': '공기 중의 먼지, 비, 불꽃, 물방울.',
    'set.viewDist.help': '얼마나 멀리까지 그리는지, 안개가 얼마나 멀리까지 보여 주는지.',
    'set.anisotropy.help': '비스듬히 보는 바닥과 벽을 선명하게 유지합니다. 부담은 거의 없습니다.',
    'set.contrast.help': '화면의 어두운 부분과 밝은 부분의 차이.',
    'set.saturation.help': '색이 얼마나 진한지. 낮을수록 오래된 사진처럼 보입니다.',
    'set.fov.help': '보이는 폭. 넓을수록 많이 보이지만 모든 것이 멀어 보입니다.',
    'set.headBob.help': '걸을 때 시야가 흔들리는 정도. 멀미가 나면 낮추세요.',
    'set.shake.help': '놀랄 때, 부딪힐 때, 달릴 때의 카메라 흔들림.',
    'set.grain.help': '화면 위의 필름 입자.',
    'set.chromatic.help': '싸구려 렌즈처럼 화면 가장자리에 생기는 색 번짐.',
    'set.vignette.help': '화면 모서리 쪽으로 어두워지는 효과.',
    'set.crosshair.help': '주울 수 있는 물건을 겨누기 쉽게 화면 중앙에 찍는 작은 점.',
    'set.subtitles.help': '말하는 내용을 보여 줍니다: 무전, 테이프, 속마음.',
    'set.subtitleSize.help': '자막과 소리 자막의 크기.',
    'set.master.help': '전체 음량.',
    'set.music.help': '음악 음량.',
    'set.sfx.help': '발소리, 문, 물건, 그리고 내가 하는 모든 일의 소리.',
    'set.ambience.help': '방, 비, 웅웅거림, 건물이 내는 소리.',
    'set.entities.help': '괴물의 발소리, 숨소리, 목소리.',
    'set.voice.help': '무전, 테이프, 속마음.',
    'set.hrtf.help': '소리를 주변에 입체적으로 배치합니다. 헤드폰에 가장 좋고, 스피커라면 끄세요.',
    'set.mouseSens.help': '마우스로 시점이 도는 속도.',
    'set.invertY.help': '마우스를 위로 움직이면 아래를 봅니다.',
    'set.touchSens.help': '터치스크린을 드래그할 때 시점이 도는 속도.',
    'set.toggleCrouch.help': '키를 누르고 있는 대신 한 번 누르면 앉고, 다시 누르면 일어섭니다.',
    'set.toggleSprint.help': '키를 누르고 있는 대신 한 번 누르면 달리고, 다시 누르면 걷습니다.',
    'set.lang.help': '메뉴, 자막, 게임 속 모든 문서의 언어.',
    'set.jumpscare.help': '약하게는 모든 공포 장면을 그대로 두되, 가장 강한 섬광과 소리를 부드럽게 합니다.',
    'set.hints.help': '새로운 일이 생기면 짧은 도움말을 보여 줍니다.',
    'perf.frame': '프레임',
    'perf.low1': '1% 최저',
    'perf.cpu': 'CPU',
    'perf.cpuUse': 'CPU 부하',
    'perf.gpu': 'GPU',
    'perf.gpuUse': 'GPU 부하',
    'perf.na': '없음',
    'perf.draws': '드로 콜',
    'perf.tris': '삼각형',
    'perf.textures': '텍스처',
    'perf.programs': '셰이더',
    'perf.res': '렌더링',
    'perf.heap': 'JS 메모리',
    'perf.sysCpu': '시스템 CPU',
    'perf.appCpu': '게임 CPU',
    'perf.procMem': '게임 메모리',
    'perf.card': '그래픽 카드',
    'settings.revert': '되돌리기',
    'settings.keys': '↑↓ 선택 · ←→ 변경 · Q/E 탭 · Backspace 되돌리기 · Esc 뒤로',
    'settings.impact': '성능 부담',
    'impact.0': '없음',
    'impact.1': '낮음',
    'impact.2': '중간',
    'impact.3': '높음',
    'impact.4': '매우 높음',
    'impact.5': '극심함',
    'settings.gpuLoad': '예상 GPU 부하',
    'settings.vram': '예상 비디오 메모리',
    'settings.reloadBadge': '다음에 챕터를 불러올 때 적용',
    'settings.restartBadge': '게임을 다시 시작하면 적용',
    'settings.restartNow': '지금 다시 시작',
  });
})(typeof window !== 'undefined' ? window : globalThis);
