/* 에이다 린드 이야기를 위한 한국어 인터페이스: 옛 이야기에 속했던 문구를 바꾸고, 아홉 개의 선반에
   필요한 문구(문, 계단, 문서 종류, 자막)를 더한다. ui.js 다음에 불러온다. */
(function (root) {
  'use strict';
  root.PB.I18N.register('ko', 'ui', {
    'game.subtitle': '유실물',
    'menu.credit': '할바르 · 1998년 1월 13일 · 02:56',
    'diff.time': '예상 플레이 시간: 모든 문서를 읽고 그림 여덟 장을 모두 찾는다면 5~7시간.',
    'set.vhs.help': '오래된 가정용 비디오카메라로 찍은 것처럼 화면을 보여 줍니다.',
    'help.drink': '보리엿 먹기',
    'bag.stats': '문서 {a} / {b}   ·   렌의 그림 {c} / {d}',
    'bag.d.flashlight': '제9보관소 창구 밑에 있던 묵직한 고무 손전등. 배터리: {n}%. 꺼지기 전에 어두워진다.',
    'bag.n.almond': '보리엿',
    'bag.d.almond': '창구 밑 깡통에서 꺼낸 꽈배기 보리엿. 힘든 밤을 위해 아껴 둔 것이다. 단맛이 손떨림을 가라앉힌다. Q로 먹는다.',
    'bag.d.officeKey': '닳아서 매끈해진 작은 놋쇠 열쇠.',
    'bag.d.token': '놋쇠 토큰.',
    'help.padText': '왼쪽 스틱: 걷기. 오른쪽 스틱: 둘러보기. A: 상호작용. B: 웅크리기. X: 배터리 교체. Y: 손전등. LB / RB: 몸 기울이기. RT 또는 왼쪽 스틱 누르기: 달리기. LT: 야광봉. 오른쪽 스틱 누르기: 뒤돌아보기. 방향 패드: ↑ 수첩, ↓ 보리엿, → 소지품. View: 지도. Menu: 일시 정지. 메뉴에서는 방향 패드로 이동하고, A로 선택하고, B로 돌아갑니다.',
    'help.tip7': '모든 장소의 밑바닥에는 거짓말이 하나 있다. <b>잃어버린 물건을 제자리에 돌려놓으면</b> 앞으로 가는 길이 열린다.',
    'map.shrine': '수령',
    'end.freed': '찾아간 선반',
    'end.claimed': '찾아간 선반',
    'inv.almond': '보리엿 ×{n}',
    'inv.token': '토큰',
    'n.almond': '보리엿 (Q로 먹기)',
    'n.drank': '보리엿을 먹는다. 숨이 가라앉는다.',
    'n.noAlmond': '보리엿이 없다.',
    'n.drawing': '렌의 그림 ({n}/8)',
    'pr.almond': '보리엿 집기',
    'pr.drawing': '렌의 그림 집기',
    'door.house': '집',
    'touch.drink': '엿',
    'inv.pellets': '잃어버린 등불 ×{n}',
    'pr.pellet': '잃어버린 등불 집기',
    'lock.house': '빛의 장막. 잃어버린 등불 네 개가 그것을 닫아 두고 있다.',
    'help.tip1': '<b>보기 전에 들어라.</b> 괴물마다 저만의 규칙이 있다. 어떤 것은 소리를 듣고, 어떤 것은 빛만 보고, 어떤 것은 아무도 보지 않을 때만 움직인다. 문서가 어느 쪽인지 알려 준다.',
    'help.tip2': '불빛이 더듬거리기 시작하거나 세상에서 소리가 빠져나가면, <b>무언가 가까이 있다</b>.',
    'help.tip3': '지하 세계에서 <b>잃어버린 등불</b>을 집으면 먹는 자가 몇 초 동안 당신에게서 물러난다.',
    'help.tip4': '선반마다 <b>저만의 괴물</b>이 있다. 승차권을 검사하는 차장, 오르간이 연주될 때만 달리는 말, 당신이 움직일 때만 움직이는 소나무. 각각의 규칙을 익혀라.',
    'help.tip5': '침대, 간이침대, 책상 밑과 사물함에 <b>숨을</b> 수 있다. 들어가는 것을 아무도 보지 않았다면 아무도 찾지 않는다.',
    'help.tip6': '목표를 달성할 때마다, 안전할 때 게임이 <b>자동으로 저장</b>된다.',
    'set.subtitles.help': '사람들이 하는 말을 보여 줍니다: 9번 채널, 테이프, 생각.',
    'set.voice.help': '9번 채널, 테이프, 생각.',
    // 아홉 선반의 문과 통로
    'pr.unlock': '잠금 해제',
    'pr.stairs': '계단으로 가기',
    'pr.stairsDown': '계단 내려가기',
    'pr.stairsUp': '계단 올라가기',
    'pr.ladderDown': '사다리 내려가기',
    'pr.ladderUp': '사다리 올라가기',
    'door.otto': '오토 브란트의 사무실',
    'lock.otto': '1964년부터 잠겨 있다. 열쇠는 기록 보관소 어딘가에 있을 것이다.',
    'door.concourse': '중앙 홀',
    'lock.concourse': '반대편에서 잠겨 있다.',
    'door.bridge': '선교',
    'lock.bridge': '잠겨 있다. 열쇠는 선장이 갖고 있다.',
    'door.cage': '승강 케이지',
    'lock.cage': '케이지 문. 전기 없이는 아무것도 움직이지 않는다.',
    'door.fire': '방화문',
    'lock.fire': '꽉 끼여 열리지 않는다. 이쪽에서.',
    'door.signe': '스투에가타 4번지',
    'lock.signe': '잠겨 있다. 안에서 램프가 타고 있다.',
    'door.ghost': '유령 열차',
    // 문서의 종류
    'kind.telegram': '전보',
    'kind.transcript': '녹취록',
    'kind.clipping': '신문',
    // 소리 자막
    'hint.flash': 'F로 손전등을 켜고 끈다.',
    'cap.chute': '[소포가 투입구로 떨어진다]',
    'cap.tube': '[기송관이 쿵 울린다]',
    'cap.bellFar': '[안개 속에서 종소리]',
    'cap.doorShut': '[어딘가에서 문이 닫힌다]',
    'cap.stepsFar': '[멀리서 발소리]',
    'cap.organ': '[손풍금이 저절로 연주되기 시작한다]',
    'cap.organStop': '[오르간 소리가 잦아들다 멈춘다]',
    'cap.choir': '[성가대의 노랫소리]',
    'cap.knocks': '[강철을 두드리는 소리 일곱 번]',
    'cap.ice': '[멀리서 얼음이 갈라진다]',
    'cap.brake': '[브레이크가 비명을 지른다]',
    'cap.laugh': '[웃음소리]',
    'cap.toll': '[종이 울린다]',
    'cap.breath': '[바로 뒤에서 숨소리]',
    'cap.train': '[질주하는 기차]',
    'cap.pa': '[차임벨, 안내 방송이 지직거린다]',
  });
})(typeof window !== 'undefined' ? window : globalThis);
