/* English story core: cast, shared lines, deaths, tips, endings, credits. Chapter files add the rest. */
(function (root) {
  'use strict';
  root.PB.I18N.register('en', 'story', {
    chars: {
      sam: { name: 'Sam', pos: "Sam's", role: 'Machine mover, 20. Was 13 in 1987, the fifth regular. You.' },
      walt: { name: 'Walt', pos: "Walt's", role: 'Owner of the Starlight Arcade. Former Air Force radar technician. Missing since March 1992.' },
      lily: { name: 'Lily', pos: "Lily's", role: "Walt's daughter. Died in October 1983, age nine." },
      billy: { name: 'Billy', pos: "Billy's", role: '16 in 1987. Loud, fearless, #1 on the high score table.' },
      penny: { name: 'Penny', pos: "Penny's", role: '15 in 1987. The planner. Wanted to be a radio DJ.' },
      ivy: { name: 'Ivy', pos: "Ivy's", role: '15 in 1987. Quiet, drew comics, never sure of herself.' },
      clyde: { name: 'Clyde', pos: "Clyde's", role: "13 in 1987. Sam's best friend. Afraid of the dark." },
      eddie: { name: 'Eddie', pos: "Eddie's", role: "Walt's assistant 1984–1988. Went in after them in June 1993." },
      nora: { name: 'Nora', pos: "Nora's", role: "Walt's sister." },
      frank: { name: 'Frank', pos: "Frank's", role: 'Harlow police detective, 1987.' },
      june: { name: 'June', pos: "June's", role: "Eddie's wife." },
      theo: { name: 'Theo', pos: "Theo's", role: "Ivy's little brother." },
      maggie: { name: 'Maggie', pos: "Maggie's", role: "Clyde's mother." },
      ruth: { name: 'Ruth', pos: "Ruth's", role: "Walt's wife until 1985." },
    },
    speakers: { sam: 'SAM', eddie: 'EDDIE', walt: 'WALT', billy: 'BILLY', penny: 'PENNY', ivy: 'IVY', clyde: 'CLYDE', lily: 'LILY', radio: 'RADIO', voice: '???' },
    items: {},
    recap: {
      prolog: 'The Starlight Arcade, the night before the auction. I came back for one last look at cabinet #7, and it looked back. Level 255. Then the floor was gone.',
      lobby: 'Yellow rooms that never end. The Eater hunts by sound. Eddie on a walkie-talkie from 1993. Four power pellets opened the way down.',
      mill: 'Billy\'s father\'s mill. Billy chased me the way he chased everyone. I gave him back his watch and he stopped, and remembered.',
      pipes: 'The storm tunnels. Our fort. Rule four: nobody goes home alone. I bled the steam and the crawlers let me pass.',
      pool: 'The pool where Theo got hurt. Ivy spent ten years waiting to be sure. I gave her glasses back and she could see again.',
      office: 'Penny\'s mother\'s office. One-oh-seven-three, her radio station. Side B of her tape is still blank.',
      school: 'April 16, 1987. The last day all five of us were together. The note I never gave Clyde was still taped to locker 217.',
      dark: 'The dark. Three generators and one lighter. Clyde was always the one who was scared of the dark. Not anymore.',
      mall: 'The best Saturday of 1986: five kids in one photo booth. The mannequins only moved when I looked away.',
      motel: 'Eddie\'s memory, not mine. Room 12. ONE IN, ONE OUT. He wanted me to hold the door. He has a daughter he has never held.',
      hospital: 'St. Agnes, October 1983. Walt\'s daughter Lily, nine years old, 3,190 points. He built all of this so nobody would ever be gone.',
      maple: 'My street, the night I told Clyde to disappear. I was going to go back. I fell asleep.',
      workshop: 'Walt\'s basement. Eddie left the back door open for a midnight movie; Walt gave Billy a key. Two, five, six: the counter reads 256.',
      maze: 'Level 255, the game itself. Four colored lights follow me now instead of hunting me.',
      killscreen: 'Level 256. The broken side. A plug, a door, and a choice.',
    },
    memento: {
      billy: { name: "Billy's watch", line: 'A wristwatch with a cracked face. The hands are frozen at 3:17. On the back: "For the mill, 25 years."' },
      penny: { name: "Penny's mixtape", line: 'A pink walkman with a tape inside. Handwritten label: "SIDE B: FOR AFTER". Side B is blank.' },
      ivy: { name: "Ivy's glasses", line: 'Thick glasses with one lens cracked. They are fogged, as if someone just breathed on them.' },
      clyde: { name: "Clyde's lighter", line: 'An old brass lighter. Engraved: "To Clyde, so you never sit in the dark. —Grandpa".' },
    },
    freed: {
      billy: ['BILLY: "3:17. My watch stopped. I never did."', 'BILLY: "I dragged them all back here. Me and that key. Go. I won\'t chase you anymore."'],
      penny: ['PENNY: "Side B. We never got to record it."', 'PENNY: "I always ran ahead of everyone. This time I\'ll walk next to you."'],
      ivy: ['IVY: "My glasses! Everything is... sharp."', 'IVY: "I\'m done waiting to be sure. I\'m coming with you."'],
      clyde: ['CLYDE: "Grandpa\'s lighter..." (The flame catches. For the first time you see his face: a kid.)', 'CLYDE: "...Don\'t look at me yet, Sam. Just walk."'],
    },
    shrine: {
      quiet: 'The shrine is quiet. The candle keeps burning.',
      missing: 'A small shrine. A photo of {name} in a frame. Something is missing here.',
    },
    mono: {
      watcherSeen: 'Far away, something tall and black is standing. Its head is tilted to one side. It is counting.',
      hide: 'Hold your breath.',
      fearHigh: "I can't breathe...",
      lowBattery: 'The battery is dying.',
      freed: "{name} isn't chasing me anymore. The light softened.",
      eaterFlicker: 'The lights are flickering. It is close.',
    },
    ghostHelp: {
      billy: 'BILLY: "Run! I\'ve got him!"',
      clydeWatch: 'CLYDE: "Don\'t look at me... please don\'t look..."',
    },
    deaths: {
      pacman: ['EATEN', 'The Eater found you. Use the corners: it is faster in straight corridors and slow in the turns.'],
      blinky: ['CAUGHT', 'Billy never stops. Break his line of sight and take a corner.'],
      pinky: ['AMBUSHED', 'Penny cuts you off in the direction you are looking. Try walking while looking back.'],
      inky: ['LOST', 'Ivy comes closer when you splash through water. Walk along the edges.'],
      clyde: ['FROZEN', 'Clyde cannot move while you look at him. Keep your light on him.'],
      grinner: ['IT SMILED', 'Grinners flee from light. Keep the flashlight on them or throw a glow stick.'],
      watcher: ['COUNTED', 'The Counter comes closer while you are not looking. Do not turn your back on it for long.'],
      crawler: ['DRAGGED DOWN', 'Crawlers hate light. Keep your flashlight on them or drop a glow stick behind you.'],
      monitor: ['NO HALL PASS', 'The Hall Monitor only sees what its flashlight touches. Get into a locker before the beam finds you.'],
      mannequin: ['POSED', 'Mannequins move only while nobody is looking. Walk backwards if you have to.'],
      neighbor: ['LET IN', 'The Neighbor comes closer while your back is turned. Your flashlight makes him step back.'],
      chompy: ['BIG HUG', 'Chompy is slow but never stops. Shine the light in its eyes and it hides its face.'],
    },
    tips: [
      'The Eater is faster than you in a straight corridor but slows down in the turns. Take corners.',
      'Running makes noise. Crouch-walking is almost silent.',
      'If the lights start to flicker, the Eater is close.',
      'When you swallow a power pellet, everything runs from you for eight seconds.',
      'Tape players save the game and play back a memory.',
      'You can hide under desks and in lockers. If they did not see you go in, they will not find you.',
      'Bring the ghosts\' belongings to their shrines and they stop hunting you. It matters for the ending.',
      'Almond water calms your fear and gets your breath back.',
      'M opens a map of the places you have explored.',
      'The flashlight battery drains fast in the dark. Throw glow sticks with G: they light the way, and the clatter pulls hunters away from you.',
      'Keep looking at the orange one. But not for too long.',
      'Lily left eight drawings behind. Some are hidden well.',
      'Eddie knows a lot about this place. Not everything he says is the whole truth.',
      'You can raise the resolution scale up to 200% in the graphics settings.',
      'Lockers hide you completely. Hall monitors never check them. When something comes close, hold Shift to hold your breath.',
      'Mannequins cannot move while you look at them. Neither can you, forever.',
      'The Neighbor uses voices you know. Do not answer.',
      'Walt tore five pages out of his diary. They matter more than they seem.',
      'Crawlers eat forgotten things. Keep the light on and you will not be forgotten.',
    ],
    endings: {
      exit: {
        title: 'EXIT', subtitle: 'Bad ending — Alone',
        lines: [
          'The door closes behind you. Cold air. The smell of rain.',
          'When you open your eyes you are on the wet floor of the arcade. It is morning. The shutters are half open.',
          'Cabinet #7 is still running. On the screen, four ghosts wait in the middle of the maze.',
          'The movers load it into the truck at noon. The driver will later say he heard something in the back. Waka, waka.',
          'The truck never reaches the auction.',
          'You told yourself you would never leave them again. You left them again.',
        ],
      },
      deal: {
        title: 'THE DEAL', subtitle: 'Dark ending — One in, one out',
        lines: [
          'You hold the door. Eddie looks at you for a long second. "I\'ll tell them. I\'ll tell all of them about you."',
          'He steps through. The door closes on its own, softly, like a tape ending.',
          'Somewhere in Harlow, a man walks into a kitchen at dawn, soaking wet, and a one-year-old girl stares at him.',
          'You are hungry.',
          'The maze is quiet. The pellets glow. You know exactly where every one of them is.',
          'On a high score table in an empty arcade, a new row lights up: 7 SAM.',
        ],
      },
      plug: {
        title: 'GAME OVER', subtitle: 'Good ending — Everyone goes home',
        lines: [
          'Four colored lights close over your hands. Red, pink, blue, orange. You pull together.',
          'The plug comes out. The sound stops. For the first time, the hum is silent.',
          'In the dark, very close, a tired but human voice: "I\'m full, Sam. Finally."',
          'You wake up on the arcade floor. Dawn is coming through the window.',
          'Four kids are sitting on the carpet in their 1987 jackets, blinking. Clyde looks at you. "Sam? ...You got old."',
          'Outside it has stopped raining. On Maple Street, a porch light that has been on for seven years finally goes out.',
          'Eddie walks home through the empty streets. He does not run. He wants to remember the way.',
          'Cabinet #7 is dark. One line stays burned into the screen: GAME OVER — 5 PLAYERS.',
        ],
      },
      lil: {
        title: 'LIL', subtitle: 'True ending — The names on the table',
        lines: [
          'You lay eight drawings on the core. Crayon on paper: the arcade, a yellow costume, a hospital window, a daddy.',
          'The Eater stops. It is quiet for a long time. Then, in a voice you remember from 1985: "...Lily drew those."',
          'Walt stands where the Eater was. He is thin and gray and himself. "Put your hands down, Sam. This one\'s mine to pull."',
          'He pulls the plug. The maze folds like paper.',
          'The last thing you see is a small girl in a hospital gown taking his hand, and the two of them walking into the dark between the dots.',
          'Dawn. Four kids on the arcade carpet. Eddie on the curb outside, laughing and crying into a pay phone. "June? June, it\'s me."',
          'A week later Nora opens the arcade one last time and finds the high score table rewritten in a hand she knows. 1 LIL. 2 BLY. 3 PNY. 4 IVY. 5 CLY. 6 SAM. 7 WLT.',
          'Clyde\'s porch light goes out. On Maple Street, two kids who are not kids anymore sit on the curb and talk until noon.',
        ],
      },
    },
    credits: [
      ['PACMAN: THE BACK ROOMS', ''],
      ['A horror escape game', ''],
      ['Dedicated to', 'everyone who put their last token into the Starlight Arcade'],
      ['The classic maze', 'with respect to the 1980 arcade original'],
      ['Sound', 'synthesized live in your browser'],
      ['Textures', 'all procedural, not a single image file'],
      ['To the players', 'never put a token in a Pacman cabinet after midnight'],
    ],
  });
})(typeof window !== 'undefined' ? window : globalThis);
