/* English story core: cast, shared lines, deaths, tips, endings, credits. Chapter files add the rest.
   The story bible is docs/STORY.md. */
(function (root) {
  'use strict';
  root.PB.I18N.register('en', 'story', {
    chars: {
      sam: { name: 'Sam', pos: "Sam's", role: 'Night driver for Tri-County Movers, 20. Was 13 in 1987, the fifth regular. You.' },
      walt: { name: 'Walt', pos: "Walt's", role: 'Owner of the Starlight Arcade. Air Force radar technician, then TV repairman. Missing since March 1992.' },
      lily: { name: 'Lily', pos: "Lily's", role: "Walt's daughter. Died in October 1983, age nine. Scored 3,190." },
      danny: { name: 'Danny', pos: "Danny's", role: '16 in 1987. Loud, fearless, first on the score sheet. Had Walt\'s spare key.' },
      rosie: { name: 'Rosie', pos: "Rosie's", role: '15 in 1987. The planner. Wanted her own radio show.' },
      nell: { name: 'Nell', pos: "Nell's", role: '15 in 1987. Quiet, drew comics, thick glasses. Never forgave herself for one afternoon at the pool.' },
      toby: { name: 'Toby', pos: "Toby's", role: "13 in 1987. Sam's best friend. Afraid of the dark." },
      eddie: { name: 'Eddie', pos: "Eddie's", role: "Walt's assistant 1984–1988. Went in after them in June 1993. Has a daughter he has never held." },
      nora: { name: 'Nora', pos: "Nora's", role: "Walt's younger sister." },
      frank: { name: 'Frank Dobbs', pos: "Dobbs's", role: 'Harlow police detective, 1987.' },
      june: { name: 'June', pos: "June's", role: "Eddie's wife. Night clerk at the Blue Moon Motor Inn." },
      theo: { name: 'Theo', pos: "Theo's", role: "Nell's little brother." },
      maggie: { name: 'Maggie', pos: "Maggie's", role: "Toby's mother." },
      ruth: { name: 'Ruth', pos: "Ruth's", role: "Walt's wife until 1985." },
      ray: { name: 'Ray', pos: "Ray's", role: "Danny's father." },
      carol: { name: 'Carol', pos: "Carol's", role: "Rosie's mother." },
      ann: { name: 'Ann', pos: "Ann's", role: "Sam's mother." },
    },
    speakers: { sam: 'SAM', eddie: 'EDDIE', walt: 'WALT', danny: 'DANNY', rosie: 'ROSIE', nell: 'NELL', toby: 'TOBY', lily: 'LILY', june: 'JUNE', radio: 'RADIO', voice: '???' },
    items: {},
    obj: {
      ghost: 'Bring {pos} belonging to the shrine (optional)',
    },
    recap: {
      prolog: 'The Starlight Arcade, the night before the auction. Cabinet #7 was running with no plug in the wall, and it knew my name. PLAYER 1: SAM — CONTINUE?',
      lobby: 'Yellow rooms that never end: the game waiting for a player. Something round and pale eats in the dark there. Eddie is alive, on a walkie-talkie, inside since 1993.',
      mill: 'Danny\'s father\'s warehouse. Danny chased me screaming "You let go!" I gave him back his dad\'s watch and he stopped, and remembered his name.',
      pipes: 'The storm tunnels. Our fort. Rule four: nobody goes home alone. I wrote that rule.',
      pool: 'The pool where Theo nearly drowned while Nell finished a drawing. She has been waiting years to be forgiven. Theo forgave her in his very first letter.',
      office: 'Rosie\'s mother\'s office, one-oh-seven-three. On her tape, at 12:40 AM, somebody knocks at the back door of the arcade. Rosie: "Look who came crawling back."',
      school: 'April 16, 1987. The pact: all five hands on the stick, nobody lets go. Five initials at the bottom. The last one is mine.',
      dark: 'The dark, three generators and a brass lighter. Toby\'s last page says Sam came back. I did not remember coming back.',
      mall: 'The best Saturday of 1986: five kids in one photo booth, and one of them is me, laughing. The mannequins only moved when I looked away.',
      motel: 'Eddie\'s memory, not mine. Room 12, and his notebook: ONE IN, ONE OUT. He needs someone to stay in his place. He wanted it to be me.',
      hospital: 'St. Agnes, October 1983. Lily asked her father for a game that never ends, so nobody ever has to go. Walt built it.',
      maple: 'My street. My mother\'s voice on the answering machine at 2:50 in the morning, asking where I was. I didn\'t go home at 9:40.',
      workshop: 'Walt\'s basement and the 3:17 tape. Five hands on the stick, and one of them let go. Mine.',
      maze: 'Level 255, the house itself. The Haunts that remember walk beside me as colored lights.',
      killscreen: 'Level 256. The broken side. A plug that needs five hands, and a door that lets one out.',
    },
    memento: {
      danny: { name: "Danny's watch", line: 'A steel wristwatch with a cracked face, stopped at 3:17. Engraved on the back: "RAY KOWALSKI — 25 YEARS — HARLOW MILL".' },
      rosie: { name: "Rosie's mixtape", line: 'A violet tape player with a tape inside. The label says SIDE B: FOR AFTER. Side B is blank.' },
      nell: { name: "Nell's glasses", line: 'Heavy glasses, one lens cracked. They fog up in your hand, as if someone just breathed on them.' },
      toby: { name: "Toby's lighter", line: 'An old brass lighter. Engraved: "TOBY — SO YOU NEVER SIT IN THE DARK. GRANDPA".' },
    },
    freed: {
      danny: ['DANNY: "3:17. My watch stopped. I never did."', 'DANNY: "...You came back. Took you long enough, Keller. Go. I\'ll keep the big one busy."'],
      rosie: ['ROSIE: "Side B. We were going to record it after. After we won."', 'ROSIE: "I always ran ahead of everyone. I\'ll walk next to you now."'],
      nell: ['NELL: "My glasses. Everything is so... sharp."', 'NELL: "I\'m done waiting to be sure. I\'m coming with you."'],
      toby: ['TOBY: "Grandpa\'s lighter..." (The flame catches. For the first time you see his face: a kid, thirteen, freckles.)', 'TOBY: "...Don\'t look at me yet, Sam. Just walk. I\'m right behind you."'],
    },
    shrine: {
      quiet: 'The shrine is quiet. The candle keeps burning.',
      missing: 'A small shrine. A photo of {name} in a frame, and an empty place where something belongs.',
    },
    mono: {
      watcherSeen: 'Far away, something tall and black is standing. Its head is tilted to one side. It is counting.',
      hide: 'Hold your breath.',
      hideLocker: 'Hold your breath. Don\'t move.',
      fearHigh: "I can't breathe...",
      lowBattery: 'The battery is dying.',
      freed: "{name} isn't chasing me anymore.",
      eaterFlicker: 'The lights are dimming. It is close. I can hear it chewing.',
    },
    ghostHelp: {
      danny: 'DANNY: "Run! I\'ve got him!"',
      amberWatch: 'TOBY: "Don\'t look at me... please don\'t look..."',
    },
    deaths: {
      eater: ['EATEN', 'The Eater is faster than you in a straight line and slow in the turns. Take corners, and listen for the chewing.'],
      red: ['CAUGHT', 'Danny never stops and never gives up a chase. Break his line of sight and put a corner between you.'],
      violet: ['CUT OFF', 'Rosie goes where you are going, not where you are. Change direction when she disappears.'],
      teal: ['PULLED UNDER', 'Nell hears water. Keep out of the puddles and walk along the edges.'],
      amber: ['FROZEN', 'Toby cannot move while you look at him. Keep your eyes, or your light, on him.'],
      grinner: ['IT SMILED', 'Grinners melt in light. Keep the flashlight on them or drop a glow stick.'],
      watcher: ['COUNTED', 'The Counter only moves while you are not looking. Do not turn your back on it for long.'],
      crawler: ['DRAGGED DOWN', 'Crawlers recoil from light, then circle round. Keep your back to a wall, and do not pin one in the beam for too long.'],
      monitor: ['NO HALL PASS', 'The Hall Monitor only sees what its flashlight touches. Get into a locker before the beam finds you.'],
      mannequin: ['POSED', 'Mannequins move only while nobody is looking. Walk backwards if you have to.'],
      neighbor: ['LET IN', 'The Neighbor comes closer while your back is turned. Your flashlight makes him step back. Never answer the voice.'],
      chompy: ['BIG HUG', 'Chompy is slow but never stops. Shine the light in its eyes and it hides its face.'],
    },
    tips: [
      'The Eater is faster than you in a straight corridor but slow in the turns. Take corners.',
      'Running is loud. Crouch-walking is almost silent, and crouching opens doors quietly.',
      'If the lights start to dim and flicker, the Eater is close.',
      'A lantern makes everything run from you for a few seconds.',
      'Tape recorders save your game, and play back a memory.',
      'You can hide under desks, beds and counters, and in lockers. If nothing saw you go in, nothing will look.',
      'Bring each Haunt\'s belonging to their shrine and they stop hunting you. The ending depends on it.',
      'A Star Pop calms your nerves and gives you your breath back.',
      'M opens a map of the places you have explored.',
      'The flashlight eats batteries. Glow sticks (G) light a corner, and their clatter draws hunters away from you.',
      'Keep looking at the amber one. But not for too long.',
      'Lily left eight drawings behind. Some are hidden well.',
      'Eddie knows this place better than anyone. That is not the same as telling you everything.',
      'Lockers hide you completely. When something comes close, hold Shift to hold your breath.',
      'Mannequins cannot move while you look at them.',
      'The Neighbor uses voices you know. Do not answer.',
      'Walt tore five pages out of his diary. They matter more than they seem.',
      'A drawer left a finger\'s width open has something in it. So does a safe with its door off the latch.',
      'Hold V (or the middle mouse button) to look back over your shoulder while you run.',
      'The longer it is quiet, the closer they come. The game does not like to wait.',
    ],
    endings: {
      exit: {
        title: 'EXIT', subtitle: 'Bad ending — Again',
        lines: [
          'You take the door. Behind you Eddie is shouting your name, and then the door is shut and the shouting is on the other side of it.',
          'Cold air. Rain. You open your eyes on the wet carpet of the arcade. It is morning. The shutters are half open.',
          'Cabinet #7 is still running. On the attract screen five Haunts drift through the house now. The fifth one is wearing a work jacket.',
          'The movers load it at noon. The driver will say later that he heard someone knocking from inside the cabinet, all the way down Route 9.',
          'The truck never reaches the auction.',
          'You told yourself you would never leave them again. It was easier the second time. That is the worst part.',
        ],
      },
      deal: {
        title: 'THE DEAL', subtitle: 'Dark ending — One in, one out',
        lines: [
          'You hold the door. Eddie looks at you for a long second. "I\'ll tell them. I\'ll tell all of them who you were."',
          'He steps through. The door closes softly, like the end of a tape.',
          'Somewhere in Harlow, at dawn, a man walks into a kitchen soaking wet, and a one-year-old girl stares at him from her high chair.',
          'The house is quiet. Far away, something round starts chewing again.',
          'You are not the Player. You are not a Haunt. You are the one who stayed. The stars glow. You know where every one of them is.',
          'On the score sheet in an empty arcade, in handwriting nobody can explain, a new line: SAM — STILL PLAYING.',
        ],
      },
      plug: {
        title: 'GAME OVER', subtitle: 'Good ending — Nobody lets go',
        lines: [
          'Four colored lights close over your hands. Red, violet, teal, amber. Five hands, like the pact said.',
          'You pull. The plug comes out. For the first time since 1987 the hum stops.',
          'In the dark, very close, a tired, human voice: "I\'m full, Sam. Finally."',
          'You wake on the arcade carpet. Dawn is coming through the glass.',
          'Four kids in 1987 jackets are sitting on the floor, blinking. Toby looks at you for a long time. "Sam? ...You got old." Then he hugs you so hard it hurts.',
          'On Maple Street a porch light that has been on for seven years goes out.',
          'Eddie walks home through the empty streets. He does not run. He wants to remember the way.',
          'Cabinet #7 is dark. One line stays burned into the glass: GAME OVER — 5 PLAYERS.',
        ],
      },
      lil: {
        title: 'LIL', subtitle: 'True ending — The names on the sheet',
        lines: [
          'You lay eight drawings on the core. Crayon on paper: the arcade, an orange Chompy with horns, a hospital window, a daddy.',
          'The Eater stops chewing. It is quiet for a long time. Then, in a voice you remember from 1985: "...Lily drew those."',
          'Walt stands where the Eater was, thin and gray and himself. "Put your hands down, kid. This one\'s mine to pull. It was always mine."',
          'Four colored lights close over his hands. He pulls. The house folds up like paper.',
          'The last thing you see is a small girl in a hospital gown taking his hand, and the two of them walking into the dark between the stars.',
          'Dawn. Four kids on the arcade carpet. Eddie at the pay phone outside, laughing and crying at the same time. "June? June, it\'s me."',
          'A week later Nora opens the arcade one last time and finds the score sheet rewritten in a hand she knows. 1 LIL. 2 DAN. 3 ROS. 4 NEL. 5 TOB. 6 SAM. 7 WALT.',
          'Toby\'s porch light goes out. On Maple Street two people who are not kids anymore sit on the curb and talk until noon. Sam tells him everything. He already knew.',
        ],
      },
    },
    // Writing scrawled on the walls, per kind of place
    scrawl: {
      yellow: ['WHO WENT HOME?', 'IT IS ALWAYS 3:17', 'DON\'T LET GO', 'FIVE HANDS', 'I HEAR IT CHEWING', 'COUNT THE DOORS'],
      dark: ['KEEP THE LIGHT ON', 'SAM?', 'IT SMILES WHEN YOU BLINK', 'I\'M NOT SCARED'],
      office: ['WHERE DID EVERYONE GO', '107.3', 'SIDE B'],
      hospital: ['QUIET PLEASE', 'SHE DREW ON EVERYTHING', '207'],
      motel: ['ONE IN ONE OUT', 'DON\'T ANSWER', '3:17'],
      school: ['NOBODY LETS GO', 'D R N T S', 'SAM WAS HERE'],
      concrete: ['YOU LET GO', 'DAN #1', '3:17'],
      pool: ['ONE SECOND', 'I WAS WATCHING'],
      mall: ['FRIENDS FOREVER', 'EVEN IF'],
      tunnel: ['NOBODY GOES HOME ALONE', 'D+T+S'],
      workshop: ['DON\'T PULL THE PLUG', '2 5 6'],
    },
    // Captions written on the white border of photographs
    photoLabels: { fort: 'THE FORT. OPENING DAY.', chompy: 'LIL & CHOMPY' },
    credits: [
      ['LEVEL 256', 'The Starlight Arcade'],
      ['A first-person horror game', ''],
      ['Dedicated to', 'everyone who ever let go of something, and came back for it'],
      ['Hungry House', 'a fictional 1981 arcade game, made for this story'],
      ['Sound', 'synthesized live, not a single recording'],
      ['Textures and models', 'procedural, not a single image file'],
      ['To the players', 'never put a token in cabinet #7 after midnight'],
    ],
  });
})(typeof window !== 'undefined' ? window : globalThis);
