/* English interface text. */
(function (root) {
  'use strict';
  root.PB.I18N.register('en', 'ui', {
    'game.title': 'PACMAN',
    'game.subtitle': 'THE BACK ROOMS',
    'game.aria': 'Game view',
    'noscript': 'This game needs JavaScript.',

    'boot.init': 'Starting…',
    'boot.fonts': 'Loading fonts…',
    'boot.prep': 'Preparing level…',
    'boot.noThree': 'The 3D engine (three.js) failed to load. Check your internet connection and reload the page.',
    'boot.error': 'Startup error: {msg}',
    'load.textures': 'Weaving textures… ({n}/{m})',
    'load.walls': 'Raising walls…',
    'load.bake': 'Baking light…',
    'load.fixtures': 'Hanging the fluorescents…',
    'load.props': 'Placing furniture…',
    'load.decals': 'Stains and scuffs…',
    'load.shaders': 'Compiling shaders…',
    'load.ready': 'Ready',
    'load.error': 'Loading error: {msg}',

    'first.title': 'Before you start',
    'first.lang': 'Language',
    'first.bright': 'Adjust brightness until the left symbol is barely visible and the right one is clearly visible.',
    'first.phones': 'Best with headphones, in a dark room.',
    'first.go': 'Continue',

    'menu.continue': 'Continue',
    'menu.new': 'New game',
    'menu.levels': 'Chapters',
    'menu.settings': 'Settings',
    'menu.archive': 'Archive',
    'menu.help': 'How to play',
    'menu.credit': 'Harlow · November 30, 1994 · 2:11 AM',
    'menu.foot': 'Play with headphones, in the dark.',
    'menu.footDone': 'Endings: {list} · deaths {deaths}',

    'confirm.title': 'New game?',
    'confirm.body': 'Your saved progress will be overwritten. Documents you found stay in the archive.',
    'confirm.yes': 'Yes, start over',
    'confirm.no': 'Cancel',

    'diff.title': 'Difficulty',
    'diff.easy': 'Easy',
    'diff.easyDesc': 'Focus on the story. Creatures are slower and less alert. Once per chapter you slip out of a catch.',
    'diff.normal': 'Normal',
    'diff.normalDesc': 'As designed. One catch sends you back to your last save.',
    'diff.nightmare': 'Nightmare',
    'diff.nightmareDesc': 'Faster creatures with sharper ears. Batteries drain quickly. Fear sets in sooner.',
    'diff.time': 'Estimated play time: 4–6 hours for someone who reads every document and frees all four ghosts.',

    'levels.title': 'Chapters',
    'levels.locked': 'Locked',

    'common.back': 'Back',
    'common.on': 'On',
    'common.off': 'Off',

    'settings.title': 'Settings',
    'settings.reset': 'Defaults',
    'settings.reloadNote': 'Settings marked * apply the next time a chapter loads.',
    'tab.graphics': 'Graphics',
    'tab.display': 'Display',
    'tab.audio': 'Audio',
    'tab.controls': 'Controls',
    'tab.gameplay': 'Gameplay',
    'preset.low': 'Low',
    'preset.medium': 'Medium',
    'preset.high': 'High',
    'preset.ultra': 'Ultra',
    'preset.extreme': 'Extreme',
    'preset.custom': 'Custom',
    'opt.off': 'Off',
    'opt.low': 'Low',
    'opt.medium': 'Medium',
    'opt.high': 'High',
    'opt.ultra': 'Ultra',
    'opt.extreme': 'Extreme',
    'opt.shadow1': 'Low (1024)',
    'opt.shadow2': 'High (2048)',
    'opt.shadow3': 'Ultra (4096)',
    'opt.small': 'Small',
    'opt.large': 'Large',
    'opt.full': 'Full',
    'opt.reduced': 'Reduced',

    'set.preset': 'Quality preset',
    'set.preset.help': 'Changes all the graphics settings below at once. Extreme is made for high-end graphics cards.',
    'set.renderScale': 'Resolution scale',
    'set.renderScale.help': 'Above 100% renders at a higher resolution and scales down: sharper image, much heavier GPU load.',
    'set.textureRes': 'Texture resolution',
    'set.shadows': 'Shadows',
    'set.antialias': 'Anti-aliasing',
    'set.lightmapRes': 'Baked lighting quality',
    'set.lightmapRes.help': 'Detail of the soft baked light and shadows.',
    'set.dynLights': 'Dynamic lights',
    'set.bloom': 'Bloom',
    'set.bloomStrength': 'Bloom strength',
    'set.volumetric': 'Volumetric light and dust',
    'set.ao': 'Ambient occlusion (SSAO)',
    'set.ao.help': 'Soft contact shadows in corners, under furniture and between tiles.',
    'set.ssr': 'Screen-space reflections',
    'set.ssr.help': 'Real reflections on wet floors, tiles, glass and polished metal.',
    'set.volumetric.help': 'Ray-marched light shafts, flashlight beam and drifting dust. Very heavy on Extreme.',
    'set.motionBlur': 'Motion blur',
    'set.lensDirt': 'Lens dirt',
    'set.lensDirt.help': 'Smudges on the camera lens that catch bright light.',
    'set.particles': 'Particle density',
    'set.viewDist': 'View distance',
    'set.anisotropy': 'Anisotropic filtering',
    'set.showFps': 'FPS counter',
    'set.brightness': 'Brightness',
    'set.brightness.help': 'Set it so the darkest corners are barely visible.',
    'set.contrast': 'Contrast',
    'set.saturation': 'Color saturation',
    'set.fov': 'Field of view',
    'set.headBob': 'Head bob',
    'set.shake': 'Camera shake',
    'set.grain': 'Film grain',
    'set.chromatic': 'Chromatic aberration',
    'set.vignette': 'Vignette',
    'set.vhs': 'Camcorder (VHS) look',
    'set.vhs.help': 'Shows the game as if through the viewfinder of a 1994 camcorder.',
    'set.reduceFlicker': 'Reduce flicker',
    'set.reduceFlicker.help': 'Softens flickering lights and screen flashes for light-sensitive players.',
    'set.crosshair': 'Crosshair dot',
    'set.subtitles': 'Subtitles',
    'set.captions': 'Sound captions',
    'set.captions.help': 'Shows important sounds as text, like [distant chewing].',
    'set.subtitleSize': 'Subtitle size',
    'set.master': 'Master volume',
    'set.music': 'Music',
    'set.sfx': 'Effects',
    'set.ambience': 'Ambience (hum, drips, rain)',
    'set.entities': 'Creature sounds',
    'set.voice': 'Voices and radio',
    'set.hrtf': '3D audio (HRTF, headphones recommended)',
    'set.mouseSens': 'Mouse sensitivity',
    'set.invertY': 'Invert vertical look',
    'set.touchSens': 'Touch look sensitivity',
    'set.toggleCrouch': 'Crouch: toggle instead of hold',
    'set.toggleSprint': 'Sprint: toggle instead of hold',
    'set.lang': 'Language',
    'set.difficulty': 'Difficulty',
    'set.difficulty.help': 'Affects creature speed, hearing and flashlight battery.',
    'set.jumpscare': 'Jump scares',
    'set.hints': 'Hints',

    'archive.title': 'Archive',
    'archive.count': '{n} / {m} documents',
    'archive.notFound': 'Not found yet',
    'kind.note': 'Note',
    'kind.letter': 'Letter',
    'kind.diary': 'Journal page',
    'kind.tape': 'Tape recording',
    'kind.photo': 'Photograph',
    'kind.screen': 'Computer screen',
    'kind.phone': 'Phone message',
    'kind.printout': 'Printout',
    'kind.wall': 'Writing on the wall',
    'kind.notice': 'Notice',
    'kind.memory': 'Memory',
    'kind.drawing': 'Drawing',
    'kind.card': 'Card',
    'kind.report': 'Report',
    'kind.flyer': 'Flyer',
    'kind.doc': 'Document',

    'help.title': 'How to play',
    'help.kbm': 'Keyboard and mouse',
    'help.walk': 'Walk',
    'help.mouse': 'Mouse',
    'help.look': 'Look around (click to lock)',
    'help.sprint': 'Run (loud, uses breath)',
    'help.crouch': 'Crouch (almost silent)',
    'help.interact': 'Interact, read, take, hide',
    'help.flash': 'Flashlight',
    'help.drink': 'Drink almond water',
    'help.throw': 'Throw a glow stick',
    'help.map': 'Map',
    'help.pause': 'Pause',
    'help.touch': 'Touch',
    'help.touchText': 'Movement stick at the bottom left, drag on the right side of the screen to look. The buttons on the right: interact, flashlight, run, crouch, map.',
    'help.survive': 'Staying alive',
    'help.tip1': '<b>The Eater</b> is faster than you in a straight corridor and slow in the turns. Take corners.',
    'help.tip2': 'When the fluorescents start to flicker, <b>it is close</b>.',
    'help.tip3': 'Swallow a <b>power pellet</b> and everything runs from you for a few seconds.',
    'help.tip4': '<b>Red</b> never stops. <b>Pink</b> cuts you off. <b>Blue</b> is unpredictable. <b>Orange</b> freezes while you look at it.',
    'help.tip5': 'You can <b>hide</b> under desks and in lockers. If they did not see you go in, they will not find you.',
    'help.tip6': '<b>Tape players</b> save the game. Autosaves happen at objectives, when you are safe.',
    'help.tip7': 'Bring each ghost\'s belonging to <b>their shrine</b>. The ending depends on it.',

    'pause.title': 'Paused',
    'pause.resume': 'Resume',
    'pause.map': 'Map',
    'pause.archive': 'Archive',
    'pause.settings': 'Settings',
    'pause.help': 'How to play',
    'pause.load': 'Load last save',
    'pause.menu': 'Main menu',

    'note.close': 'Close',
    'note.closeKey': 'Close (E)',

    'map.close': 'Close',
    'map.closeKey': 'Close (M)',
    'map.objective': 'Objective',
    'map.tape': 'Tape',
    'map.doc': 'Document',
    'map.shrine': 'Shrine',
    'map.supply': 'Supplies',
    'map.locked': 'Locked door',

    'kp.label': 'SECURITY',
    'kp.clear': 'DEL',
    'kp.enter': 'ENTER',
    'kp.open': 'OPEN',
    'kp.error': 'ERROR',
    'kp.close': 'Cancel (Esc)',

    'cab.help': 'Arrow keys or WASD · Enter to start · P to pause ·',
    'cab.exit': 'Leave the cabinet (Esc)',

    'choice.back': 'Step back',
    'card.skip': 'Click or press E to continue',

    'death.retry': 'Continue from last save',
    'death.menu': 'Main menu',

    'end.menu': 'Main menu',
    'end.skip': 'Skip',
    'end.time': 'play time',
    'end.deaths': 'deaths',
    'end.docs': 'documents',
    'end.freed': 'ghosts freed',
    'end.drawings': 'drawings found',

    'hud.objective': 'OBJECTIVE',
    'hud.rec': 'REC',
    'hud.stamina': 'BREATH',
    'hud.battery': 'LIGHT',
    'hud.power': 'POWER {t}',
    'hud.fps': '{n} FPS',

    'touch.pause': 'Pause',
    'touch.map': 'MAP',
    'touch.drink': 'DRINK',
    'touch.throw': 'THROW',
    'touch.crouch': 'CROUCH',
    'touch.sprint': 'RUN',
    'touch.flash': 'LIGHT',
    'touch.tap': 'TAP',

    'inv.battery': 'BATTERY ×{n}',
    'inv.almond': 'ALMOND WATER ×{n}',
    'inv.glow': 'GLOW STICK ×{n}',
    'inv.officeKey': 'OFFICE KEY',
    'inv.token': 'GOLD TOKEN',
    'inv.fuses': 'FUSE ×{n}',
    'inv.fuel': 'DIESEL ×{n}',
    'inv.keycard': 'SECURITY CARD',
    'inv.pellets': 'POWER PELLET ×{n}',

    'n.added': 'Added to archive: {title}',
    'n.saved': 'Game saved',
    'n.batteryIn': 'New battery in the flashlight',
    'n.batterySpare': 'Spare battery',
    'n.batterySwap': 'You swapped in a spare battery',
    'n.almond': 'Almond water (Q to drink)',
    'n.glow': 'Glow stick (G to throw)',
    'n.found': 'Found: {name}',
    'n.drank': 'You drink the almond water. Your breathing steadies.',
    'n.noAlmond': 'You have no almond water.',
    'n.noGlow': 'You have no glow sticks.',
    'n.slow': 'The game is running slowly. Pause › Settings › Graphics lets you lower the quality.',
    'n.lockFail': 'Mouse lock failed. Hold the left button and drag to look around.',
    'n.flashDead': 'Your flashlight died.',
    'n.grace': 'That was close! (Easy: once per chapter)',
    'n.freed': '{name} is free',
    'n.ghostBack': '{name} backed off',
    'n.cabinetHi': 'Your initials made the high score table: SAM',
    'n.perfect': 'You ate every pellet. Perfect game.',
    'n.fruit': 'A fruit appeared in front of the house',
    'n.diesel': 'Diesel can',
    'n.drawing': "Lily's drawing ({n}/8)",

    'pr.read': 'Read: {title}',
    'pr.readWall': 'Read the writing',
    'pr.screen': 'Look at the screen',
    'pr.tape': 'Play the tape (saves the game)',
    'pr.battery': 'Take the battery',
    'pr.almond': 'Take the almond water',
    'pr.glow': 'Take the glow stick',
    'pr.flashlight': 'Take the flashlight',
    'pr.token': 'Take the token',
    'pr.fuse': 'Take the fuse',
    'pr.fuel': 'Take the diesel can',
    'pr.keycard': 'Take the security card',
    'pr.take': 'Take: {name}',
    'pr.pellet': 'Swallow the power pellet',
    'pr.phoneRing': 'Answer the phone',
    'pr.phone': 'Pick up the receiver',
    'pr.cabinetFree': 'Play the cabinet (FREE PLAY)',
    'pr.doorLocked': '{name} (locked)',
    'pr.doorOpen': 'Open the door',
    'pr.doorClose': 'Close the door',
    'pr.hide': 'Hide under the desk',
    'pr.unhide': 'Come out',
    'pr.shrineLook': 'Look at the shrine',
    'pr.shrinePlace': 'Leave the belonging at the shrine',
    'pr.drawing': "Take Lily's drawing",

    'door.default': 'Door',
    'door.office': 'Office door',
    'door.storage': 'Storage room',
    'door.wc': 'Restroom',
    'door.front': 'Front door',
    'door.elevator': 'Freight elevator',
    'door.security': 'Security room',
    'door.stair': 'Fire stairs',
    'door.house': 'Ghost house',
    'door.service': 'Service elevator',
    'lock.service': 'The elevator is dead. All three generators need to be running.',
    'door.exit': 'EXIT',
    'lock.default': 'Locked.',
    'lock.office': 'Locked. A brass plate on the door: "W. — MANAGER".',
    'lock.front': 'Padlocked from the outside. The movers have the key.',
    'lock.elevator': 'The elevator has no power. The call button is dead.',
    'lock.security': 'The keypad wants a four-digit code.',
    'lock.stair': 'The card reader light is red. It needs a security card.',
    'lock.house': 'A pink energy curtain. Four power pellets hold it shut.',

    'cap.front': 'ahead',
    'cap.back': 'behind',
    'cap.left': 'left',
    'cap.right': 'right',
    'cap.waka': '[chewing nearby: waka, waka]',
    'cap.wakaFar': '[distant chewing]',
    'cap.phone': '[a phone is ringing]',
    'cap.drag': '[footsteps dragging nearby]',
    'cap.moan': '[a moan]',
    'cap.thud': '[something fell, far away]',
    'cap.buzz': '[a fluorescent tube crackles]',
    'cap.whisper': '[whispering]',
    'cap.giggle': '[giggling in the dark]',
    'cap.radio': '[radio static]',
    'cap.thunder': '[thunder]',
    'cap.door': '[a door somewhere]',
    'cap.drip': '[dripping]',
    'cap.hum': '[fluorescent hum]',
  });
})(typeof window !== 'undefined' ? window : globalThis);
