/* English interface text for the story of Ada Lind: replaces what belonged to the old story, adds
   what the nine shelves need (doors, stairs, document kinds, captions). Loaded after ui.js. */
(function (root) {
  'use strict';
  root.PB.I18N.register('en', 'ui', {
    'game.subtitle': 'LOST PROPERTY',
    'menu.credit': 'Halvard · 13 January 1998 · 02:56',
    'diff.time': 'Estimated play time: 5–7 hours for someone who reads every document and finds all eight drawings.',
    'set.vhs.help': 'Shows the game as if through an old home-video camera.',
    'help.drink': 'Eat a barley sugar',
    'bag.stats': 'Documents {a} / {b}   ·   Wren\'s drawings {c} / {d}',
    'bag.d.flashlight': 'A heavy rubber torch from under the Depot 9 counter. Battery: {n}%. It dims before it dies.',
    'bag.n.almond': 'Barley sugar',
    'bag.d.almond': 'A twist of barley sugar from the tin under the counter, kept for bad nights. The sugar steadies your hands. Eat with Q.',
    'bag.d.officeKey': 'A small brass key, worn smooth.',
    'bag.d.token': 'A brass token.',
    'help.padText': 'Left stick: walk. Right stick: look. A: interact. B: crouch. X: change batteries. Y: torch. LB / RB: lean. RT or left stick click: run. LT: glow stick. Right stick click: look back. D-pad: ↑ journal, ↓ barley sugar, → items. View: map. Menu: pause. In menus the D-pad moves, A chooses and B goes back.',
    'help.tip7': 'Every place has a lie at the bottom of it. <b>Put the lost thing back where it belongs</b> and the way on opens.',
    'map.shrine': 'Claim',
    'end.freed': 'Shelves claimed',
    'end.claimed': 'Shelves claimed',
    'inv.almond': 'BARLEY SUGAR ×{n}',
    'inv.token': 'TOKEN',
    'n.almond': 'Barley sugar (Q to eat)',
    'n.drank': 'You eat the barley sugar. Your breathing steadies.',
    'n.noAlmond': 'You have no barley sugar.',
    'n.drawing': 'Wren\'s drawing ({n}/8)',
    'pr.almond': 'Take the barley sugar',
    'pr.drawing': 'Take Wren\'s drawing',
    'door.house': 'The house',
    'touch.drink': 'SUGAR',
    'inv.pellets': 'LOST LIGHTS ×{n}',
    'pr.pellet': 'Take the lost light',
    'lock.house': 'A curtain of light. Four lost lights hold it shut.',
    'help.tip1': '<b>Listen before you look.</b> Every creature keeps its own rule: some hear, some only see light, some only move while nobody is watching. The documents tell you which.',
    'help.tip2': 'When the lights start to stutter, or the sound goes out of the world, <b>something is close</b>.',
    'help.tip3': 'In the Underneath, take a <b>lost light</b> and the Eater keeps away from you for a few seconds.',
    'help.tip4': 'Every shelf has <b>its own creatures</b>: a conductor who checks tickets, horses that run only while the organ plays, pines that move only while you move. Learn each one\'s rule.',
    'help.tip5': 'You can <b>hide</b> under beds, bunks and desks, and in lockers. If nothing saw you go in, nothing will look.',
    'help.tip6': 'The game <b>saves itself</b> at every objective, when you are safe.',
    'set.subtitles.help': 'Shows what people say: channel nine, tapes, thoughts.',
    'set.voice.help': 'Channel nine, tapes and thoughts.',
    // doors and ways through on the nine shelves
    'pr.unlock': 'Unlock',
    'pr.stairs': 'Take the stairs',
    'pr.stairsDown': 'Go down the stairs',
    'pr.stairsUp': 'Go up the stairs',
    'pr.ladderDown': 'Climb down the ladder',
    'pr.ladderUp': 'Climb up the ladder',
    'door.otto': 'Otto Brandt\'s office',
    'lock.otto': 'Locked since 1964. The key must be somewhere in the archive.',
    'door.concourse': 'The concourse',
    'lock.concourse': 'Locked from the other side.',
    'door.bridge': 'The bridge',
    'lock.bridge': 'Locked. The captain has the key.',
    'door.cage': 'The cage',
    'lock.cage': 'The cage gate. Nothing moves without power.',
    'door.fire': 'The fire door',
    'lock.fire': 'Wedged shut. From this side.',
    'door.signe': 'Stuegata 4',
    'lock.signe': 'Locked. There is a lamp burning inside.',
    'door.ghost': 'The ghost train',
    // kinds of document
    'kind.telegram': 'Telegram',
    'kind.transcript': 'Transcript',
    'kind.clipping': 'Newspaper',
    // captions for sounds
    'hint.flash': 'F switches the torch on and off.',
    'cap.chute': '[a parcel drops down the chute]',
    'cap.tube': '[the pneumatic tube thumps]',
    'cap.bellFar': '[a bell, out in the fog]',
    'cap.doorShut': '[a door shuts somewhere]',
    'cap.stepsFar': '[footsteps, far off]',
    'cap.organ': '[a band organ starts playing by itself]',
    'cap.organStop': '[the organ winds down and stops]',
    'cap.choir': '[a choir, singing]',
    'cap.knocks': '[seven knocks, on steel]',
    'cap.ice': '[the ice cracks, far out]',
    'cap.brake': '[brakes screaming]',
    'cap.laugh': '[laughing]',
    'cap.toll': '[a bell tolls]',
    'cap.breath': '[breathing, right behind you]',
    'cap.train': '[the train, at speed]',
    'cap.pa': '[a chime; the PA crackles]',
  });
})(typeof window !== 'undefined' ? window : globalThis);
