/* Núcleo da história em português do Brasil: personagens, falantes, falas comuns, mortes, dicas, créditos, pichações.
   Os arquivos de capítulo acrescentam documentos, objetivos, pensamentos, rádio e resumos; lake.js acrescenta os finais.
   A bíblia da história é docs/STORY.md. */
(function (root) {
  'use strict';
  root.PB.I18N.register('pt-BR', 'story', {
    chars: {
      ada: { name: 'Ada', pos: 'de Ada', role: 'Ada Lind, 31 anos. Funcionária do turno da noite no Depósito 9, o setor de achados e perdidos sob a estação central de Halvard, desde 1990. Você.' },
      wren: { name: 'Wren', pos: 'de Wren', role: 'Wren Lind, a irmãzinha de Ada. Sete anos. Desapareceu no gelo do lago Ostra em 14 de janeiro de 1979.' },
      otto: { name: 'Otto', pos: 'de Otto', role: 'Otto Brandt, funcionário noturno do Depósito 9 de 1946 a 1964, quando desceu no elevador de carga. No canal nove.' },
      ingrid: { name: 'Ingrid', pos: 'de Ingrid', role: 'Ingrid Lind, a avó das meninas. Nascida em Gammel Ostra. Morreu em 1996.' },
      clerk: { name: 'A Funcionária da Noite', pos: 'da Funcionária da Noite', role: 'Cuida do Índice no fundo do Embaixo. Assina seus bilhetes como “A.”' },
    },
    speakers: { ada: 'ADA', otto: 'OTTO', radio: 'RÁDIO', lyle: 'LYLE HARDY', clerk: 'A FUNCIONÁRIA', wren: 'WREN', voice: '???' },
    items: {},
    obj: {},
    memento: {},
    freed: {},
    shrine: {},
    ghostHelp: {},
    mono: {
      hide: 'Prenda a respiração.',
      hideLocker: 'Prenda a respiração. Não se mexa.',
      fearHigh: 'Não consigo respirar...',
      lowBattery: 'A pilha está morrendo.',
      eaterFlicker: 'As luzes estão baixando. Está perto. Dá para ouvir ele mastigando.',
      watcherSeen: 'Uma coisa alta lá no fundo, completamente parada.',
    },
    // [o que aparece na tela, o que fazer diferente]
    deaths: {
      eater: ['DEVORADA', 'O Devorador é rápido em linha reta e lento nas curvas. Uma luz perdida recém-pega na mão faz ele recuar por alguns segundos.'],
      sorter: ['TRIADA', 'O que organiza o arquivo no escuro continua o seu trabalho. Não fique entre ele e as prateleiras.'],
      wallpaperMan: ['EMPAPELADA', 'Os homens achatados só saem da parede pelas suas costas. Passe por eles olhando para eles.'],
      hummer: ['ZUMBIDA', 'Onde o zumbido cresce e as luzes piscam, alguma coisa escuta. Ande devagar e fique longe dos lugares barulhentos.'],
      drowned: ['PUXADA PARA O FUNDO', 'Os Afogados esperam debaixo d’água e ouvem você dentro dela. Fique fora da água, e nunca fique parada nela.'],
      passenger: ['LEVADA AO ASSENTO', 'Os passageiros acordam quando uma luz fica sobre eles. Mantenha a lanterna longe do rosto deles e não esbarre neles.'],
      bellman: ['BADALADA', 'No convés aberto, o Sineiro ouve você. Quando o sino começa a tocar, ele está caçando: procure abrigo e fique abaixada.'],
      pines: ['LEVADA PARA AS ÁRVORES', 'Os pinheiros só se mexem enquanto você se mexe. Perto deles, fique parada e deixe que percam o interesse.'],
      stag: ['ATROPELADA', 'O cervo investe em linha reta. Ponha uma árvore ou um carro entre vocês e ele se atordoa sozinho.'],
      usher: ['LEVADA À POLTRONA', 'Um lanterninha só enxerga dentro do seu facho vermelho. Fique fora da luz e nunca passe na frente dele.'],
      burrower: ['ARRASTADA PARA A TERRA', 'Os escavadores sentem seus passos pela terra. No chão de terra, agache; em trilhos e tábuas você está segura.'],
      lamplighter: ['LAMPIÃO NOS OLHOS', 'Os portadores de lampião vão atrás de qualquer luz. Apague a sua e deixe que passem.'],
      crawler: ['PEGA POR CIMA', 'Os rastejadores do madeiramento esperam nas vigas do teto. Olhe para cima antes de passar por baixo e fique abaixada.'],
      frozen: ['CONGELADA', 'Os hóspedes congelados só se mexem perto do calor. Esquente-se e saia de perto do fogo antes que eles se levantem.'],
      cold: ['CONGELADA', 'Lá fora o frio entra rápido. Vá de abrigo em abrigo e esquente-se perto de uma fogueira.'],
      whiteout: ['ENGOLIDA PELA NEVE', 'Na tempestade você só vê as pegadas dele. Ele ouve você: ande, não corra, e fique perto dos abrigos.'],
      cook: ['FISGADA', 'O Cozinheiro nunca sai da cozinha. Espere ele virar as costas lá no fundo e então passe.'],
      silted: ['PUXADA PARA A LAMA', 'Fique parada tempo demais na lama e um deles se ergue ao seu lado. Continue andando.'],
      longone: ['LEVADA PARA O RIO', 'Os Compridos esperam nos poços, nas valas e no rio. Agache ao passar perto da água.'],
      choir: ['SENTADA NOS BANCOS', 'Enquanto o coro canta, não vê nada. Ande de mansinho atrás deles; nunca corra, nunca passe na frente.'],
      water: ['AFOGADA', 'A água sobe cada vez mais rápido. Vá para um lugar alto e escale.'],
      conductor: ['TIRADA DO TREM', 'Sem passagem válida, o Condutor tira você do trem. Quando a lanterna dele vier pelo corredor, apague a sua e se enfie debaixo de um beliche.'],
      sleeper: ['PUXADA PARA UM BELICHE', 'Os dorminhocos não enxergam. Um passo na frente da cabine deles os acorda: passe agachada e fique imóvel quando um deles estiver de pé.'],
      underhand: ['ARRASTADA ENTRE OS VAGÕES', 'Nunca pare numa passagem entre vagões. Atravesse rápido e abra a próxima porta antes de pisar nas chapas.'],
      mask: ['ROSTOS', 'As máscaras só se mexem quando ninguém está olhando. Mantenha-as à sua frente e vá recuando.'],
      horse: ['PISOTEADA', 'Os cavalos só correm enquanto o realejo toca. Quando a música para, eles também param: é aí que você se mexe.'],
      lotte: ['ERGUIDA', 'Lotte não enxerga. Ela ouve, e nunca para de rir: fique longe da risada e faça silêncio.'],
      hush: ['SILENCIADA', 'Perto do Silêncio, todo som some. Quando você não consegue mais ouvir a si mesma, ele está muito perto. Afaste-se, devagar.'],
      underice: ['ATRAVÉS DO GELO', 'Nunca corra sobre o gelo escuro em cima do rio antigo. Ande, e o que está embaixo fica embaixo.'],
    },
    tips: [
      'Correr faz barulho. Andar agachada é quase silencioso.',
      'No fundo de cada prateleira há uma mentira. Encontre a coisa perdida e devolva ao lugar dela, e o lugar deixa você ir.',
      'A maioria ouve melhor do que enxerga. Apague a lanterna quando algo estiver perto.',
      'Você pode se esconder debaixo de camas, beliches e mesas. Se nada viu você entrar, nada vai procurar.',
      'Escondida, segure Shift para prender a respiração. Se o fôlego acabar, você arfa.',
      'Segure V para olhar por cima do ombro enquanto corre.',
      'Leia tudo. Quem escreveu essas coisas está dizendo a você como sair.',
      'Wren deixou oito desenhos, um em quase todas as prateleiras. Alguns estão bem escondidos.',
      'Otto fala no canal nove quando tem algo a dizer. Normalmente ele tem razão.',
      'M abre um mapa dos lugares por onde você passou.',
    ],
    photoLabels: {},
    credits: [
      ['LEVEL 256', 'uma história de terror em primeira pessoa, em nove prateleiras'],
      ['Para', 'todos a quem disseram que não foi culpa de ninguém'],
      ['Lugares', 'Halvard, o lago Ostra e o Embaixo são inventados; assim como todos que estão neles'],
      ['Som', 'sintetizado ao vivo: nenhuma gravação'],
      ['Imagens e modelos', 'procedurais: nenhum arquivo de imagem'],
      ['O Depósito 9', 'abre todas as noites. Pergunte no balcão.'],
    ],
    // Pichações nas paredes do Embaixo
    scrawl: {
      yellow: ['QUEM VOLTOU PARA BUSCAR?', 'SÃO SEMPRE 02:56', 'RETIRADA 256', 'NÃO DÁ PARA PULAR UMA PRATELEIRA', 'PROCURE A MENTIRA', 'NINGUÉM PERGUNTOU', 'ARQUIVADO EM: ESQUECIDO'],
      dark: ['DEIXE A LUZ ACESA', 'COME O QUE VOCÊ PAROU DE PROCURAR', 'ADA?'],
      concrete: ['GUARDAR PARA: ADA LIND', '256', 'NÃO RETIRADO'],
    },
  });
})(typeof window !== 'undefined' ? window : globalThis);
