/* Núcleo da história em português do Brasil: personagens, falas comuns, mortes, dicas, finais, créditos. */
(function (root) {
  'use strict';
  root.PB.I18N.register('pt-BR', 'story', {
    chars: {
      sam: { name: 'Sam', pos: 'de Sam', role: 'Dirige à noite para a Tri-County Movers, 20 anos. Tinha 13 em 1987 e completava a turma de cinco. Você.' },
      walt: { name: 'Walt', pos: 'do Walt', role: 'Dono do fliperama Starlight. Técnico de radar na Força Aérea, depois consertador de televisão. Desaparecido desde março de 1992.' },
      lily: { name: 'Lily', pos: 'da Lily', role: 'A filha do Walt. Morreu em outubro de 1983, aos nove anos. Pontuação: 3.190.' },
      danny: { name: 'Danny', pos: 'do Danny', role: '16 anos em 1987. Barulhento, destemido, sempre o primeiro na tabela de recordes. Tinha a chave reserva do Walt.' },
      rosie: { name: 'Rosie', pos: 'da Rosie', role: '15 anos em 1987. A que planejava tudo. Queria ter o próprio programa de rádio.' },
      nell: { name: 'Nell', pos: 'da Nell', role: '15 anos em 1987. Quieta, desenhava quadrinhos, óculos grossos. Nunca se perdoou por uma tarde na piscina.' },
      toby: { name: 'Toby', pos: 'do Toby', role: '13 anos em 1987. O melhor amigo de Sam. Tinha medo do escuro.' },
      eddie: { name: 'Eddie', pos: 'do Eddie', role: 'Assistente do Walt de 1984 a 1988. Entrou atrás deles em junho de 1993. Tem uma filha que nunca pegou no colo.' },
      nora: { name: 'Nora', pos: 'da Nora', role: 'A irmã mais nova do Walt.' },
      frank: { name: 'Frank Dobbs', pos: 'do Dobbs', role: 'Detetive da polícia de Harlow, 1987.' },
      june: { name: 'June', pos: 'da June', role: 'A esposa do Eddie. Recepcionista da noite no Blue Moon Motor Inn.' },
      theo: { name: 'Theo', pos: 'do Theo', role: 'O irmão mais novo da Nell.' },
      maggie: { name: 'Maggie', pos: 'da Maggie', role: 'A mãe do Toby.' },
      ruth: { name: 'Ruth', pos: 'da Ruth', role: 'A esposa do Walt até 1985.' },
      ray: { name: 'Ray', pos: 'do Ray', role: 'O pai do Danny.' },
      carol: { name: 'Carol', pos: 'da Carol', role: 'A mãe da Rosie.' },
      ann: { name: 'Ann', pos: 'da Ann', role: 'A mãe de Sam.' },
    },
    speakers: { sam: 'SAM', eddie: 'EDDIE', walt: 'WALT', danny: 'DANNY', rosie: 'ROSIE', nell: 'NELL', toby: 'TOBY', lily: 'LILY', june: 'JUNE', radio: 'RÁDIO', voice: '???' },
    items: {},
    obj: {
      ghost: 'Leve o objeto {pos} até o altar (opcional)',
    },
    recap: {
      prolog: 'O fliperama Starlight, na noite antes do leilão. A máquina nº 7 estava ligada sem estar na tomada, e sabia o meu nome. PLAYER 1: SAM — CONTINUE?',
      lobby: 'Salas amarelas sem fim: o jogo esperando um jogador. Algo redondo e pálido come ali no escuro. O Eddie está vivo, no walkie-talkie, lá dentro desde 1993.',
      mill: 'O depósito do pai do Danny. O Danny veio atrás de mim gritando: “Você soltou!”. Devolvi o relógio do pai dele, e ele parou, e lembrou o próprio nome.',
      pipes: 'As galerias pluviais. Nosso forte. Regra número quatro: ninguém volta para casa sem companhia. Fui eu que escrevi essa regra.',
      pool: 'A piscina onde o Theo quase se afogou enquanto a Nell terminava um desenho. Faz anos que ela espera ser perdoada. O Theo a perdoou logo na primeira carta.',
      office: 'O escritório da mãe da Rosie, cento e sete ponto três. Na fita dela, à 0h40, alguém bate na porta dos fundos do fliperama. Rosie: “Olha só quem voltou rastejando.”',
      school: '16 de abril de 1987. O pacto: as cinco mãos no controle, ninguém solta. Cinco iniciais embaixo. A última é a minha.',
      dark: 'O escuro, três geradores e um isqueiro de latão. A última página do Toby diz que Sam voltou. Eu não me lembrava de ter voltado.',
      mall: 'O melhor sábado de 1986: cinco crianças numa cabine de fotos, e uma delas sou eu, rindo. Os manequins só se mexiam quando eu desviava o olhar.',
      motel: 'A lembrança do Eddie, não a minha. O quarto 12 e o caderno dele: UM ENTRA, UM SAI. Ele precisa de alguém que fique no lugar dele. Ele queria que fosse eu.',
      hospital: 'St. Agnes, outubro de 1983. A Lily pediu ao pai um jogo que nunca acabasse, para que ninguém precisasse ir embora. O Walt construiu.',
      maple: 'Minha rua. A voz da minha mãe na secretária eletrônica às 2h50 da manhã, perguntando onde eu estou. Eu não fui para casa às 21h40.',
      workshop: 'O porão do Walt e a fita das 3h17. Cinco mãos no controle, e uma soltou. A minha.',
      maze: 'O nível 255, a própria casa. As Assombrações que se lembram andam ao meu lado como luzes coloridas.',
      killscreen: 'O nível 256. O lado quebrado. Uma tomada que precisa de cinco mãos, e uma porta que deixa um sair.',
    },
    memento: {
      danny: { name: 'O relógio do Danny', line: 'Um relógio de aço com o vidro trincado, parado às 3h17. Gravado atrás: “RAY KOWALSKI — 25 ANOS — HARLOW MILL”.' },
      rosie: { name: 'A fita da Rosie', line: 'Um walkman violeta com uma fita dentro. A etiqueta diz LADO B: PARA DEPOIS. O lado B está vazio.' },
      nell: { name: 'Os óculos da Nell', line: 'Óculos pesados, uma lente trincada. Embaçam na sua mão, como se alguém tivesse acabado de bafejar neles.' },
      toby: { name: 'O isqueiro do Toby', line: 'Um velho isqueiro de latão. Gravado: “TOBY — PARA VOCÊ NUNCA FICAR NO ESCURO. VOVÔ”.' },
    },
    freed: {
      danny: ['DANNY: “3h17. Meu relógio parou. Eu não.”', 'DANNY: “…Você voltou. Demorou, hein, Keller. Vai. Eu distraio o grandão.”'],
      rosie: ['ROSIE: “O lado B. A gente ia gravar depois. Depois de ganhar.”', 'ROSIE: “Eu sempre corri na frente de todo mundo. Agora vou andar do seu lado.”'],
      nell: ['NELL: “Meus óculos. Está tudo tão… nítido.”', 'NELL: “Chega de esperar ter certeza. Eu vou com você.”'],
      toby: ['TOBY: “O isqueiro do vovô…” (A chama acende. Pela primeira vez você vê o rosto dele: um garoto de treze anos, sardento.)', 'TOBY: “…Não olha pra mim ainda, Sam. Só anda. Estou logo atrás de você.”'],
    },
    shrine: {
      quiet: 'O altar está em silêncio. A vela continua acesa.',
      missing: 'Um pequeno altar. Uma foto de {name} num porta-retratos, e um espaço vazio onde falta alguma coisa.',
    },
    mono: {
      watcherSeen: 'Lá longe, uma coisa alta e preta está de pé. A cabeça tombada para o lado. Está contando.',
      hide: 'Prende a respiração.',
      hideLocker: 'Prende a respiração. Não se mexe.',
      fearHigh: 'Não consigo respirar…',
      lowBattery: 'A pilha está morrendo.',
      freed: '{name} não está mais me perseguindo.',
      eaterFlicker: 'As luzes estão enfraquecendo. Está perto. Dá pra ouvir mastigando.',
    },
    ghostHelp: {
      danny: 'DANNY: “Corre! Deixa ele comigo!”',
      amberWatch: 'TOBY: “Não olha pra mim… por favor, não olha…”',
    },
    deaths: {
      eater: ['BANQUETE', 'O Devorador é mais rápido que você em linha reta e lento nas curvas. Faça as curvas e preste atenção na mastigação.'],
      red: ['CAPTURA', 'O Danny nunca para e nunca desiste de uma perseguição. Quebre a linha de visão dele e ponha uma esquina entre vocês.'],
      violet: ['SEM SAÍDA', 'A Rosie vai para onde você está indo, não para onde você está. Mude de direção quando ela sumir.'],
      teal: ['DEBAIXO D’ÁGUA', 'A Nell ouve a água. Fique fora das poças e ande pelas beiradas.'],
      amber: ['IMÓVEL', 'O Toby não consegue se mexer enquanto você olha para ele. Mantenha os olhos, ou a luz, nele.'],
      grinner: ['SORRIU', 'Os Sorridentes derretem na luz. Mantenha a lanterna neles ou solte um bastão luminoso.'],
      watcher: ['CONTA FEITA', 'O Contador só se mexe quando você não está olhando. Não dê as costas para ele por muito tempo.'],
      crawler: ['PARA O FUNDO', 'Os Rastejantes recuam diante da luz e depois dão a volta. Fique de costas para a parede e não prenda um no facho por tempo demais.'],
      monitor: ['SEM AUTORIZAÇÃO', 'O Bedel só vê o que a lanterna dele toca. Entre num armário antes que o facho encontre você.'],
      mannequin: ['POSE', 'Os manequins só se mexem quando ninguém está olhando. Ande de costas se precisar.'],
      neighbor: ['PORTA ABERTA', 'O Vizinho se aproxima quando você vira as costas. Sua lanterna faz ele recuar. Nunca responda à voz.'],
      chompy: ['ABRAÇO APERTADO', 'O Chompy é lento, mas nunca para. Aponte a luz nos olhos dele e ele esconde o rosto.'],
    },
    tips: [
      'O Devorador é mais rápido que você num corredor reto, mas lento nas curvas. Faça as curvas.',
      'Correr faz barulho. Andar agachado é quase silencioso, e agachado você abre portas sem barulho.',
      'Se as luzes começarem a enfraquecer e piscar, o Devorador está perto.',
      'Um lampião faz tudo fugir de você por alguns segundos.',
      'Os gravadores salvam o jogo e tocam uma lembrança.',
      'Dá para se esconder embaixo de mesas, camas e balcões, e dentro de armários. Se nada vir você entrar, nada vai procurar.',
      'Leve o objeto de cada Assombração até o altar dela e ela para de caçar você. O final depende disso.',
      'Um Star Pop acalma os nervos e devolve o fôlego.',
      'M abre um mapa dos lugares que você explorou.',
      'A lanterna come pilhas. Os bastões luminosos (G) iluminam um canto, e o barulho deles atrai os caçadores para longe de você.',
      'Continue olhando para o âmbar. Mas não por tempo demais.',
      'A Lily deixou oito desenhos. Alguns estão bem escondidos.',
      'O Eddie conhece este lugar melhor que ninguém. Isso não quer dizer que ele conte tudo.',
      'Os armários escondem você por completo. Se algo chegar perto, segure Shift para prender a respiração.',
      'Os manequins não conseguem se mexer enquanto você olha para eles.',
      'O Vizinho usa vozes que você conhece. Não responda.',
      'O Walt arrancou cinco páginas do diário. Elas importam mais do que parece.',
      'Uma gaveta aberta um dedo tem alguma coisa dentro. Um cofre com a porta destravada também.',
      'Segure V (ou o botão do meio do mouse) para olhar por cima do ombro enquanto corre.',
      'Quanto mais tempo fica em silêncio, mais perto eles chegam. O jogo não gosta de esperar.',
    ],
    endings: {
      exit: {
        title: 'SAÍDA', subtitle: 'Final ruim — De novo',
        lines: [
          'Você atravessa a porta. Atrás de você, o Eddie grita o seu nome, e então a porta se fecha e os gritos ficam do outro lado.',
          'Ar frio. Chuva. Você abre os olhos no carpete molhado do fliperama. É de manhã. As portas de aço estão meio abertas.',
          'A máquina nº 7 continua ligada. Na tela de demonstração, agora cinco Assombrações flutuam pela casa. A quinta usa uma jaqueta de trabalho.',
          'O pessoal da mudança a carrega ao meio-dia. O motorista vai contar depois que ouviu alguém batendo de dentro da máquina a Rota 9 inteira.',
          'O caminhão nunca chega ao leilão.',
          'Você tinha jurado nunca mais abandoná-los. Da segunda vez foi mais fácil. Essa é a pior parte.',
        ],
      },
      deal: {
        title: 'O ACORDO', subtitle: 'Final sombrio — Um entra, um sai',
        lines: [
          'Você segura a porta. O Eddie olha para você por um segundo comprido. “Eu vou contar pra eles. Vou contar pra todo mundo quem você era.”',
          'Ele atravessa. A porta se fecha devagar, como o fim de uma fita.',
          'Em algum lugar de Harlow, ao amanhecer, um homem encharcado entra numa cozinha, e uma menina de um ano o encara da cadeirinha.',
          'A casa está em silêncio. Lá longe, algo redondo volta a mastigar.',
          'Você não é o Jogador. Você não é uma Assombração. Você é a pessoa que ficou. As estrelas brilham. Você sabe onde cada uma está.',
          'Na tabela de recordes de um fliperama vazio, com uma letra que ninguém sabe explicar, aparece uma linha nova: SAM — AINDA JOGANDO.',
        ],
      },
      plug: {
        title: 'GAME OVER', subtitle: 'Final bom — Ninguém solta',
        lines: [
          'Quatro luzes coloridas se fecham sobre as suas mãos. Vermelho, violeta, turquesa, âmbar. Cinco mãos, como dizia o pacto.',
          'Você puxa. A tomada sai. Pela primeira vez desde 1987, o zumbido para.',
          'No escuro, bem perto, uma voz humana e cansada: “Estou satisfeito, Sam. Finalmente.”',
          'Você acorda no carpete do fliperama. O amanhecer entra pelo vidro.',
          'Quatro crianças com jaquetas de 1987 estão sentadas no chão, piscando. O Toby olha para você por muito tempo. “Sam? …Você envelheceu.” Então ele abraça você tão forte que dói.',
          'Na Maple Street, apaga-se a luz de uma varanda que estava acesa havia sete anos.',
          'O Eddie volta para casa pelas ruas vazias. Não corre. Quer lembrar o caminho.',
          'A máquina nº 7 está apagada. Uma linha fica gravada no vidro: GAME OVER — 5 PLAYERS.',
        ],
      },
      lil: {
        title: 'LIL', subtitle: 'Final verdadeiro — Os nomes na tabela',
        lines: [
          'Você coloca oito desenhos sobre o núcleo. Giz de cera no papel: o fliperama, um Chompy laranja com chifres, a janela de um hospital, um papai.',
          'O Devorador para de mastigar. Fica em silêncio por muito tempo. Depois, com uma voz que você lembra de 1985: “…Foi a Lily que desenhou.”',
          'O Walt está onde estava o Devorador, magro, grisalho e ele mesmo. “Abaixa as mãos. Essa tomada quem puxa sou eu. Sempre fui eu.”',
          'Quatro luzes coloridas se fecham sobre as mãos dele. Ele puxa. A casa se dobra como papel.',
          'A última coisa que você vê é uma menininha de camisola de hospital segurando a mão dele, e os dois caminhando para o escuro entre as estrelas.',
          'Amanhecer. Quatro crianças no carpete do fliperama. O Eddie no orelhão lá fora, rindo e chorando ao mesmo tempo. “June? June, sou eu.”',
          'Uma semana depois, a Nora abre o fliperama pela última vez e encontra a tabela de recordes reescrita numa letra que ela conhece. 1 LIL. 2 DAN. 3 ROS. 4 NEL. 5 TOB. 6 SAM. 7 WALT.',
          'A luz da varanda do Toby se apaga. Na Maple Street, duas pessoas que já não são crianças se sentam no meio-fio e conversam até o meio-dia. Sam conta tudo para ele. Ele já sabia.',
        ],
      },
    },
    scrawl: {
      yellow: ['QUEM FOI PRA CASA?', 'SÃO SEMPRE 3:17', 'NÃO SOLTA', 'CINCO MÃOS', 'EU OUÇO ELE MASTIGANDO', 'CONTA AS PORTAS'],
      dark: ['DEIXA A LUZ ACESA', 'SAM?', 'ELE SORRI QUANDO VOCÊ PISCA', 'NÃO TENHO MEDO'],
      office: ['PRA ONDE FOI TODO MUNDO', '107.3', 'LADO B'],
      hospital: ['SILÊNCIO POR FAVOR', 'ELA DESENHAVA EM TUDO', '207'],
      motel: ['UM ENTRA UM SAI', 'NÃO RESPONDE', '3:17'],
      school: ['NINGUÉM SOLTA', 'D R N T S', 'SAM ESTEVE AQUI'],
      concrete: ['VOCÊ SOLTOU', 'DAN #1', '3:17'],
      pool: ['UM SEGUNDO', 'EU ESTAVA OLHANDO'],
      mall: ['AMIGOS PARA SEMPRE', 'MESMO QUE'],
      tunnel: ['NINGUÉM VOLTA PRA CASA SEM COMPANHIA', 'D+T+S'],
      workshop: ['NÃO TIRA DA TOMADA', '2 5 6'],
    },
    photoLabels: { fort: 'O FORTE. DIA DA INAUGURAÇÃO.', chompy: 'LIL & CHOMPY' },
    credits: [
      ['LEVEL 256', 'O fliperama Starlight'],
      ['Um jogo de terror em primeira pessoa', ''],
      ['Dedicado a', 'todo mundo que um dia soltou alguma coisa, e voltou para buscá-la'],
      ['Hungry House', 'um fliperama fictício de 1981, criado para esta história'],
      ['Som', 'sintetizado ao vivo, nenhuma gravação'],
      ['Texturas e modelos', 'procedurais, nenhum arquivo de imagem'],
      ['Aos jogadores', 'nunca coloquem uma ficha na máquina nº 7 depois da meia-noite'],
    ],
  });
})(typeof window !== 'undefined' ? window : globalThis);
