/* Interface em português do Brasil. */
(function (root) {
  'use strict';
  root.PB.I18N.register('pt-BR', 'ui', {
    'game.title': 'LEVEL 256',
    'game.subtitle': 'O FLIPERAMA STARLIGHT',
    'game.aria': 'Visão do jogo',
    'noscript': 'Este jogo precisa de JavaScript.',

    'boot.tip': 'DICA',
    'boot.init': 'Iniciando…',
    'boot.fonts': 'Carregando fontes…',
    'boot.sounds': 'Gravando sons…',
    'boot.voices': 'Gravando vozes…',
    'boot.prep': 'Preparando a fase…',
    'boot.noThree': 'Não foi possível carregar o motor 3D (three.js). Verifique sua conexão com a internet e recarregue a página.',
    'boot.error': 'Erro ao iniciar: {msg}',
    'boot.noWebgl': 'A placa de vídeo não conseguiu iniciar o 3D (WebGL 2). Atualize o driver de vídeo e abra o jogo de novo.',
    'load.textures': 'Tecendo texturas… ({n}/{m})',
    'load.walls': 'Erguendo paredes…',
    'load.bake': 'Assando a luz…',
    'load.fixtures': 'Pendurando as lâmpadas fluorescentes…',
    'load.props': 'Posicionando os móveis…',
    'load.decals': 'Manchas e arranhões…',
    'load.shaders': 'Compilando shaders…',
    'load.ready': 'Pronto',
    'load.error': 'Erro ao carregar: {msg}',

    'first.title': 'Antes de começar',
    'first.lang': 'Idioma',
    'first.bright': 'Ajuste o brilho até o símbolo da esquerda ficar quase invisível e o da direita bem visível.',
    'first.phones': 'Melhor com fones de ouvido, num quarto escuro.',
    'first.go': 'Continuar',

    'menu.continue': 'Continuar',
    'menu.new': 'Novo jogo',
    'menu.levels': 'Capítulos',
    'menu.settings': 'Configurações',
    'menu.archive': 'Arquivo',
    'menu.help': 'Como jogar',
    'menu.quit': 'Sair do jogo',
    'menu.credit': 'Harlow · 30 de novembro de 1994 · 2h11',
    'menu.foot': 'Jogue com fones de ouvido, no escuro.',
    'menu.footDone': 'Finais: {list} · mortes {deaths}',

    'confirm.title': 'Novo jogo?',
    'confirm.body': 'Seu progresso salvo será substituído. Os documentos encontrados continuam no arquivo.',
    'confirm.yes': 'Sim, recomeçar',
    'confirm.no': 'Cancelar',

    'diff.title': 'Dificuldade',
    'diff.easy': 'Fácil',
    'diff.easyDesc': 'Para curtir a história. As criaturas são mais lentas e menos atentas. Uma vez por capítulo você escapa de uma pegada.',
    'diff.normal': 'Normal',
    'diff.normalDesc': 'Como foi pensado. Uma pegada leva você de volta ao último salvamento.',
    'diff.nightmare': 'Pesadelo',
    'diff.nightmareDesc': 'Criaturas mais rápidas e de ouvido mais apurado. As pilhas acabam rápido. O medo chega antes.',
    'diff.time': 'Tempo estimado: de 4 a 6 horas para quem lê cada documento e liberta as quatro Assombrações.',

    'levels.title': 'Capítulos',
    'levels.locked': 'Bloqueado',

    'common.back': 'Voltar',
    'common.on': 'Sim',
    'common.off': 'Não',

    'settings.title': 'Configurações',
    'settings.reset': 'Padrão',
    'settings.reloadNote': 'As configurações marcadas com * valem a partir do próximo capítulo carregado.',
    'tab.screen': 'Tela',
    'set.displayMode': 'Modo de exibição',
    'set.displayMode.help': 'A tela cheia esconde o navegador. Esc ou F11 sai dela; Alt+Enter alterna durante o jogo.',
    'opt.windowed': 'Janela',
    'opt.fullscreen': 'Tela cheia',
    'set.resolution': 'Resolução',
    'set.resolution.help': 'O tamanho da imagem renderizada. Nativa usa sua tela; qualquer outro tamanho é ajustado à janela pelo modo de escala abaixo.',
    'opt.native': 'Nativa (tela)',
    'set.scaleMode': 'Modo de escala',
    'set.scaleMode.help': 'Como mostrar uma resolução com proporção diferente da janela.',
    'opt.fit': 'Ajustar (proporção, faixas pretas)',
    'opt.stretch': 'Esticar',
    'opt.fill': 'Preencher (cortar bordas)',
    'set.upscale': 'Filtro de escala',
    'set.upscale.help': 'Suave mistura os pixels ao ampliar; Pixel mantém os pixels nítidos e quadrados (visual retrô em baixa resolução).',
    'opt.smooth': 'Suave',
    'opt.pixel': 'Pixel',
    'set.sharpen': 'Nitidez',
    'set.sharpen.help': 'Nitidez adaptativa ao contraste na imagem final. Ajuda abaixo da resolução nativa e com o antisserrilhamento.',
    'set.fpsLimit': 'Limite de quadros',
    'set.fpsLimit.help': 'Limita os quadros por segundo. Limites menores mantêm a placa de vídeo fria e o ritmo dos quadros estável.',
    'opt.unlimited': 'Sem limite',
    'set.vsync': 'Sincronização vertical',
    'set.vsync.help': 'Ligada: os quadros acompanham a taxa de atualização do monitor, sem cortes. Desligada: o jogo desenha o mais rápido que puder, até o limite de quadros. Num navegador, o próprio navegador sempre espera o monitor, então Desligada só remove a espera do jogo; a versão para desktop desliga a sincronização por completo (depois de reiniciar).',
    'tab.graphics': 'Gráficos',
    'tab.display': 'Imagem',
    'tab.audio': 'Áudio',
    'tab.controls': 'Controles',
    'tab.gameplay': 'Jogo',
    'preset.low': 'Baixa',
    'preset.medium': 'Média',
    'preset.high': 'Alta',
    'preset.ultra': 'Ultra',
    'preset.extreme': 'Extrema',
    'preset.custom': 'Personalizada',
    'opt.off': 'Desligado',
    'opt.low': 'Baixo',
    'opt.medium': 'Médio',
    'opt.high': 'Alto',
    'opt.ultra': 'Ultra',
    'opt.extreme': 'Extremo',
    'opt.shadow1': 'Baixas (1024)',
    'opt.shadow2': 'Altas (2048)',
    'opt.shadow3': 'Ultra (4096)',
    'opt.small': 'Pequeno',
    'opt.large': 'Grande',
    'opt.full': 'Completo',
    'opt.reduced': 'Reduzido',

    'set.preset': 'Predefinição de qualidade',
    'set.preset.help': 'Muda de uma vez todas as configurações gráficas abaixo. Extrema é feita para placas de vídeo topo de linha; Ultra+ vai além (sombras 8192, a iluminação pré-calculada mais densa, os modelos mais finos, profundidade de campo) e é para os PCs mais fortes.',
    'set.renderScale': 'Escala de resolução',
    'set.renderScale.help': 'Acima de 100% o jogo renderiza em resolução maior e reduz: imagem mais nítida, carga bem maior na placa de vídeo.',
    'set.textureRes': 'Resolução das texturas',
    'set.shadows': 'Sombras',
    'set.antialias': 'Antisserrilhamento',
    'set.lightmapRes': 'Qualidade da iluminação pré-calculada',
    'set.lightmapRes.help': 'Detalhe da luz suave pré-calculada e das suas sombras.',
    'set.dynLights': 'Luzes dinâmicas',
    'set.bloom': 'Brilho (bloom)',
    'set.bloomStrength': 'Intensidade do brilho',
    'set.volumetric': 'Luz volumétrica e poeira',
    'set.ao': 'Oclusão de ambiente (SSAO)',
    'set.ao.help': 'Sombras de contato suaves nos cantos, embaixo dos móveis e entre os azulejos.',
    'set.ssr': 'Reflexos em espaço de tela',
    'set.ssr.help': 'Reflexos de verdade em pisos molhados, azulejos, vidro e metal polido.',
    'set.volumetric.help': 'Feixes de luz, o facho da lanterna e poeira no ar calculados por ray marching. Muito pesado no Extremo.',
    'set.motionBlur': 'Desfoque de movimento',
    'set.lensDirt': 'Sujeira na lente',
    'set.lensDirt.help': 'Manchas na lente da câmera que pegam a luz forte.',
    'set.particles': 'Densidade de partículas',
    'set.viewDist': 'Distância de visão',
    'set.anisotropy': 'Filtragem anisotrópica',
    'set.brightness': 'Brilho da tela',
    'set.brightness.help': 'Ajuste para que os cantos mais escuros fiquem quase invisíveis.',
    'set.contrast': 'Contraste',
    'set.saturation': 'Saturação das cores',
    'set.fov': 'Campo de visão',
    'set.headBob': 'Balanço da cabeça',
    'set.shake': 'Tremor da câmera',
    'set.grain': 'Granulação de filme',
    'set.chromatic': 'Aberração cromática',
    'set.vignette': 'Vinheta',
    'set.vhs': 'Visual de filmadora (VHS)',
    'set.vhs.help': 'Mostra o jogo como pelo visor de uma filmadora de 1994.',
    'set.reduceFlicker': 'Reduzir cintilação',
    'set.reduceFlicker.help': 'Suaviza luzes piscando e clarões na tela para quem é sensível à luz.',
    'set.crosshair': 'Ponto de mira',
    'set.subtitles': 'Legendas',
    'set.captions': 'Legendas de sons',
    'set.captions.help': 'Mostra sons importantes como texto, como [mastigação ao longe].',
    'set.subtitleSize': 'Tamanho das legendas',
    'set.master': 'Volume geral',
    'set.music': 'Música',
    'set.sfx': 'Efeitos',
    'set.ambience': 'Ambiente (zumbido, goteira, chuva)',
    'set.entities': 'Sons das criaturas',
    'set.voice': 'Vozes e rádio',
    'set.hrtf': 'Áudio 3D (HRTF, recomenda-se fone de ouvido)',
    'set.mouseSens': 'Sensibilidade do mouse',
    'set.invertY': 'Inverter eixo vertical',
    'set.touchSens': 'Sensibilidade do toque',
    'set.toggleCrouch': 'Agachar: apertar em vez de segurar',
    'set.toggleSprint': 'Correr: apertar em vez de segurar',
    'set.lang': 'Idioma',
    'set.difficulty': 'Dificuldade',
    'set.difficulty.help': 'Afeta a velocidade e a audição das criaturas e a pilha da lanterna.',
    'set.jumpscare': 'Sustos',
    'set.hints': 'Dicas',

    'archive.title': 'Arquivo',
    'archive.count': '{n} / {m} documentos',
    'archive.notFound': 'Ainda não encontrado',
    'kind.note': 'Bilhete',
    'kind.letter': 'Carta',
    'kind.diary': 'Página de diário',
    'kind.tape': 'Gravação em fita',
    'kind.photo': 'Fotografia',
    'kind.screen': 'Tela de computador',
    'kind.phone': 'Recado na secretária eletrônica',
    'kind.printout': 'Impressão',
    'kind.wall': 'Escrito na parede',
    'kind.notice': 'Aviso',
    'kind.memory': 'Lembrança',
    'kind.drawing': 'Desenho',
    'kind.card': 'Cartão',
    'kind.report': 'Relatório',
    'kind.flyer': 'Panfleto',
    'kind.doc': 'Documento',

    'help.title': 'Como jogar',
    'help.kbm': 'Teclado e mouse',
    'help.walk': 'Andar',
    'help.mouse': 'Mouse',
    'help.look': 'Olhar em volta (clique para prender o cursor)',
    'help.sprint': 'Correr (barulhento, gasta fôlego)',
    'help.crouch': 'Agachar (quase silencioso)',
    'help.interact': 'Interagir, ler, pegar, esconder-se',
    'help.flash': 'Lanterna',
    'help.drink': 'Tomar um Star Pop',
    'help.throw': 'Jogar um bastão luminoso',
    'help.lean': 'Inclinar para a esquerda / direita (espiar nas esquinas)',
    'help.map': 'Mapa',
    'help.bag': 'Itens / diário',
    'bag.items': 'ITENS',
    'bag.journal': 'DIÁRIO',
    'bag.close': 'Fechar (I / J)',
    'bag.empty': 'Seus bolsos estão vazios.',
    'bag.inspectHint': 'Arraste para virar.',
    'bag.now': 'AGORA',
    'bag.story': 'A HISTÓRIA ATÉ AQUI',
    'bag.docs': 'ENCONTRADO AQUI',
    'bag.noDocs': 'Nada encontrado aqui ainda. Olhe com mais atenção.',
    'bag.people': 'PESSOAS',
    'bag.freed': 'em paz',
    'bag.hunting': 'ainda caçando',
    'bag.stats': 'Documentos {a} / {b}   ·   Desenhos da Lily {c} / {d}',
    'bag.n.flashlight': 'Lanterna',
    'bag.d.flashlight': 'Uma lanterna pesada de aço, da van do fliperama. Pilha: {n}%. Ela enfraquece antes de apagar.',
    'bag.n.battery': 'Pilhas reserva',
    'bag.d.battery': 'Pilhas grandes para a lanterna. R troca as pilhas; uma lanterna apagada recebe as novas sozinha.',
    'bag.n.almond': 'Star Pop',
    'bag.d.almond': 'Uma lata do refrigerante de cereja do próprio fliperama, ainda gelada, não se sabe como. Açúcar e gás acalmam as mãos. Beba com Q.',
    'bag.n.glow': 'Bastões luminosos',
    'bag.d.glow': 'Dobre um e jogue com G. Rastejantes e Sorridentes não atravessam a luz verde.',
    'bag.d.officeKey': 'A chave do escritório do Walt, tirada da caixa registradora. O latão está liso de tanto uso.',
    'bag.d.token': 'Uma ficha do Starlight com uma estrela vazada. Só para a máquina nº 7.',
    'bag.n.fuse': 'Fusíveis',
    'bag.d.fuse': 'Fusíveis pesados de cerâmica para o velho quadro da fábrica.',
    'bag.n.fuel': 'Galões de diesel',
    'bag.d.fuel': 'Diesel para os geradores. Chacoalha alto. Ande devagar.',
    'bag.d.keycard': 'Um cartão de segurança com tarja magnética. A foto de alguém foi raspada.',
    'bag.d.key': 'Uma chave com uma etiqueta de papel. Abre alguma coisa aqui.',
    'help.pause': 'Pausa',
    'help.touch': 'Toque',
    'help.touchText': 'Analógico de movimento no canto inferior esquerdo; arraste no lado direito da tela para olhar. Os botões à direita: interagir, lanterna, correr, agachar, mapa.',
    'help.survive': 'Continuar vivo',
    'help.tip1': '<b>O Devorador</b> é mais rápido que você em corredores retos e lento nas curvas. Faça as curvas.',
    'help.tip2': 'Quando as lâmpadas fluorescentes começam a piscar, <b>ele está perto</b>.',
    'help.tip3': 'Pegue um <b>lampião</b> e tudo foge de você por alguns segundos.',
    'help.tip4': '<b>O vermelho</b> nunca para. <b>O violeta</b> fecha o seu caminho. <b>O turquesa</b> ouve a água e salta de um lugar para outro. <b>O âmbar</b> congela enquanto você olha para ele.',
    'help.tip5': 'Você pode se <b>esconder</b> embaixo das mesas e nos armários. Se ninguém vir você entrar, ninguém vai achar você.',
    'help.tip6': 'Os <b>gravadores</b> salvam o jogo. O salvamento automático acontece nos objetivos, quando você está em segurança.',
    'help.tip7': 'Leve o objeto de cada Assombração <b>ao seu altar</b>. O final depende disso.',

    'pause.title': 'Pausa',
    'pause.resume': 'Continuar',
    'pause.map': 'Mapa',
    'pause.journal': 'Diário',
    'pause.archive': 'Arquivo',
    'pause.settings': 'Configurações',
    'pause.help': 'Como jogar',
    'pause.load': 'Carregar último salvamento',
    'pause.menu': 'Menu principal',

    'note.close': 'Fechar',
    'note.closeKey': 'Fechar (E)',

    'map.close': 'Fechar',
    'map.closeKey': 'Fechar (M)',
    'map.objective': 'Objetivo',
    'map.tape': 'Fita',
    'map.doc': 'Documento',
    'map.shrine': 'Altar',
    'map.supply': 'Suprimentos',
    'map.locked': 'Porta trancada',

    'kp.label': 'SEGURANÇA',
    'kp.clear': 'APAGAR',
    'kp.enter': 'OK',
    'kp.open': 'ABERTO',
    'kp.error': 'ERRO',
    'kp.close': 'Cancelar (Esc)',

    'cab.help': 'Setas ou WASD · Enter para começar · P para pausar ·',
    'cab.exit': 'Sair da máquina (Esc)',

    'choice.back': 'Dar um passo para trás',
    'card.skip': 'Clique ou aperte E para continuar',

    'death.retry': 'Continuar do último salvamento',
    'death.menu': 'Menu principal',

    'end.menu': 'Menu principal',
    'end.skip': 'Pular',
    'end.time': 'tempo de jogo',
    'end.deaths': 'mortes',
    'end.docs': 'documentos',
    'end.freed': 'Assombrações libertadas',
    'end.drawings': 'desenhos encontrados',

    'hud.objective': 'OBJETIVO',
    'hud.rec': 'REC',
    'hud.stamina': 'FÔLEGO',
    'hud.battery': 'LUZ',
    'hud.power': 'ENERGIA {t}',
    'hud.fps': '{n} FPS',

    'touch.pause': 'Pausa',
    'touch.bag': 'BOLSA',
    'touch.map': 'MAPA',
    'touch.drink': 'BEBER',
    'touch.throw': 'JOGAR',
    'touch.crouch': 'AGACHAR',
    'touch.sprint': 'CORRER',
    'touch.flash': 'LUZ',
    'touch.tap': 'TOCAR',

    'inv.battery': 'PILHA ×{n}',
    'inv.almond': 'STAR POP ×{n}',
    'inv.glow': 'BASTÃO LUMINOSO ×{n}',
    'inv.officeKey': 'CHAVE DO ESCRITÓRIO',
    'inv.token': 'FICHA DOURADA',
    'inv.fuses': 'FUSÍVEL ×{n}',
    'inv.fuel': 'DIESEL ×{n}',
    'inv.keycard': 'CARTÃO DE SEGURANÇA',
    'inv.pellets': 'LAMPIÃO ×{n}',

    'n.added': 'Adicionado ao arquivo: {title}',
    'n.saved': 'Jogo salvo',
    'n.batteryIn': 'Pilha nova na lanterna',
    'n.batterySpare': 'Pilha reserva',
    'n.noSpare': 'Nenhuma pilha reserva.',
    'n.batteryFull': 'A pilha ainda está cheia.',
    'hint.reload': 'R: trocar as pilhas da lanterna',
    'touch.reload': 'PILHAS',
    'help.reload': 'Trocar as pilhas da lanterna',
    'help.lookBack': 'Olhar para trás enquanto corre (segurar)',
    'n.batterySwap': 'Você colocou uma pilha reserva',
    'n.almond': 'Star Pop (Q para beber)',
    'n.glow': 'Bastão luminoso (G para jogar)',
    'n.found': 'Encontrado: {name}',
    'n.drank': 'Você toma o Star Pop. A respiração se acalma.',
    'n.noAlmond': 'Você não tem Star Pop.',
    'n.noGlow': 'Você não tem bastões luminosos.',
    'n.slow': 'O jogo está lento. Em Pausa › Configurações › Gráficos dá para baixar a qualidade.',
    'n.lockFail': 'Não foi possível prender o mouse. Segure o botão esquerdo e arraste para olhar em volta.',
    'n.flashDead': 'Sua lanterna apagou.',
    'n.holdBreath': 'Tem alguma coisa perto. Segure Shift para prender a respiração.',
    'n.heardBreath': 'Ele ouviu a sua respiração.',
    'n.noFlash': 'Você não tem lanterna.',
    'n.noBattery': 'A pilha acabou. Encontre outra.',
    'n.grace': 'Foi por pouco! (Fácil: uma vez por capítulo)',
    'n.freed': '{name} está em paz',
    'n.ghostBack': '{name} recuou',
    'n.cabinetHi': 'Suas iniciais entraram na tabela de recordes: SAM',
    'n.perfect': 'Você comeu todas as estrelas. Jogo perfeito.',
    'n.fruit': 'Apareceu um prêmio na frente da casa',
    'n.diesel': 'Galão de diesel',
    'n.drawing': 'Desenho da Lily ({n}/8)',

    'pr.read': 'Ler: {title}',
    'pr.readWall': 'Ler o que está escrito',
    'pr.screen': 'Olhar a tela',
    'pr.tape': 'Tocar a fita (salva o jogo)',
    'pr.battery': 'Pegar a pilha',
    'pr.almond': 'Pegar o Star Pop',
    'pr.glow': 'Pegar o bastão luminoso',
    'pr.flashlight': 'Pegar a lanterna',
    'pr.token': 'Pegar a ficha',
    'pr.fuse': 'Pegar o fusível',
    'pr.fuel': 'Pegar o galão de diesel',
    'pr.keycard': 'Pegar o cartão de segurança',
    'pr.take': 'Pegar: {name}',
    'pr.pellet': 'Pegar o lampião',
    'pr.phoneRing': 'Atender o telefone',
    'pr.phone': 'Tirar o fone do gancho',
    'pr.cabinetFree': 'Jogar na máquina (FREE PLAY)',
    'pr.doorLocked': '{name} (trancada)',
    'pr.doorOpen': 'Abrir a porta',
    'pr.doorClose': 'Fechar a porta',
    'pr.drawerOpen': 'Abrir a gaveta',
    'pr.drawerClose': 'Fechar a gaveta',
    'pr.safeOpen': 'Abrir o cofre',
    'pr.safeClose': 'Fechar o cofre',
    'pr.safeLocked': 'Cofre (digite a combinação)',
    'pr.hide': 'Esconder-se embaixo',
    'pr.hideLocker': 'Esconder-se no armário',
    'pr.unhide': 'Sair',
    'pr.shrineLook': 'Olhar o altar',
    'pr.shrinePlace': 'Deixar o objeto no altar',
    'pr.drawing': 'Pegar o desenho da Lily',

    'door.default': 'Porta',
    'door.office': 'Porta do escritório',
    'door.storage': 'Depósito',
    'door.wc': 'Banheiro',
    'door.front': 'Porta da frente',
    'door.elevator': 'Elevador de carga',
    'door.security': 'Sala de segurança',
    'door.stair': 'Escada de incêndio',
    'door.house': 'A casa das Assombrações',
    'door.service': 'Elevador de serviço',
    'lock.service': 'O elevador está morto. Os três geradores precisam estar ligados.',
    'door.exit': 'SAÍDA',
    'door.room': 'Quarto {n}',
    'door.jammed': 'Porta',
    'lock.jammed': 'Emperrada. A maçaneta gira, mas alguma coisa segura a porta do outro lado.',
    'lock.exit': 'A SAÍDA está trancada. Ainda não.',
    'door.pressure': 'Porta estanque',
    'lock.pressure': 'A porta estanque não se mexe. Atrás dela o vapor chia.',
    'door.janitor': 'Zelador',
    'lock.janitor': 'Um cadeado de segredo. Três dígitos.',
    'door.fireExit': 'Saída de emergência',
    'lock.fireExit': 'Uma corrente grossa e um cadeado. O zelador tem as chaves.',
    'lock.fireExitMotel': 'A barra não cede. Alguém travou a porta por fora.',
    'door.gym': 'Ginásio',
    'door.mallExit': 'Portas do shopping',
    'lock.mallExit': 'Fechado para a noite. Ao longe, a cabine de fotos zumbe.',
    'door.room12': 'Quarto 12',
    'lock.room12': 'Trancada. A plaquinha do número está polida, como se alguém a tocasse todo dia.',
    'door.room207': 'Quarto 207',
    'lock.room207': 'Trancada. Um aviso de papel: SILÊNCIO, POR FAVOR. Tem um sol desenhado a giz de cera.',
    'door.elevatorH': 'Elevador',
    'lock.elevatorH': 'O elevador espera de portas fechadas. Está esperando alguma coisa.',
    'door.samHouse': 'Sua casa',
    'door.tobyHouse': 'A casa do Toby',
    'door.neighbor': 'Porta da frente',
    'lock.neighbor': 'Trancada. As cortinas se mexem quando você desvia o olhar.',
    'door.alley': 'Porta do beco',
    'lock.alley': 'Trancada. Não antes de uma parada na esquina.',
    'door.kernel': 'Porta de aço',
    'lock.kernel': 'Aço, e trancada. Uma placa de latão: KERNEL — SÓ W.',
    'lock.default': 'Trancada.',
    'lock.office': 'Trancada. Uma placa de latão na porta: “W. — GERENTE”.',
    'lock.front': 'Trancada com cadeado por fora. O pessoal da mudança tem a chave.',
    'lock.elevator': 'O elevador está sem energia. O botão de chamada está morto.',
    'lock.security': 'O teclado pede um código de quatro dígitos.',
    'lock.stair': 'A luz do leitor de cartão está vermelha. Precisa de um cartão de segurança.',
    'lock.house': 'Uma cortina de luz violeta. Quatro lampiões a mantêm fechada.',

    'cap.front': 'à frente',
    'cap.back': 'atrás',
    'cap.left': 'à esquerda',
    'cap.right': 'à direita',
    'cap.phone': '[um telefone toca]',
    'cap.drag': '[passos arrastados por perto]',
    'cap.moan': '[um gemido]',
    'cap.farSteps': '[passos em outra parte do prédio]',
    'cap.thud': '[alguma coisa cai, longe]',
    'cap.buzz': '[uma lâmpada fluorescente estala]',
    'cap.whisper': '[sussurros]',
    'cap.giggle': '[risadinhas no escuro]',
    'cap.radio': '[chiado de rádio]',
    'cap.thunder': '[trovão]',
    'cap.hiss': '[um chiado molhado, se afastando]',
    'cap.skitter': '[algo corre sobre os tijolos]',
    'cap.whistle': '[um apito estridente]',
    'cap.plastic': '[plástico rangendo]',
    'cap.bite': '[dentes se fechando por perto]',
    'cap.biteFar': '[mastigação ao longe]',
    'cap.callName': '[alguém chama seu nome com a voz do Toby]',
    'cap.heavySteps': '[passos pesados, um guincho de borracha]',
    'cap.pipe': '[um cano ressoa em algum lugar dos túneis]',
    'cap.locker': '[um armário bate no fim do corredor]',
    'cap.knock': '[três batidas, em algum lugar do corredor]',
    'cap.beep': '[um monitor apita num quarto vazio]',
    'cap.arc': '[eletricidade estala atrás da porta de aço]',
    'cap.pop': '[uma lâmpada estoura]',
    'cap.slam': '[uma porta bate atrás de você]',
    'cap.run': '[alguém correndo, fora de vista]',
    'cap.callJune': '[uma voz de mulher no fim do corredor: “Eddie? Eddie, é você?”]',
    'cap.car': '[um carro passa chiando na rua molhada]',
    'cap.door': '[uma porta, em algum lugar]',
    'cap.drip': '[goteira]',
    'cap.hum': '[zumbido das fluorescentes]',
    'tab.access': 'Acessibilidade',
    'tab.perf': 'Desempenho',
    'set.perfOverlay': 'Indicador de desempenho',
    'set.perfOverlay.help': 'Mostra como o jogo está rodando. Só FPS; Básico acrescenta o tempo por quadro, os tempos de CPU e GPU por quadro e o quanto cada uma está ocupada; Detalhado acrescenta um gráfico de tempos, chamadas de desenho, triângulos, memória, resolução de renderização e sua placa de vídeo. O tempo de GPU precisa de um navegador que permita consultas de tempo da GPU (a versão para desktop sempre permite).',
    'set.perfCorner': 'Posição do indicador',
    'set.perfCorner.help': 'Em qual canto da tela fica o indicador de desempenho.',
    'opt.perfFps': 'Só FPS',
    'opt.perfBasic': 'Básico',
    'opt.perfDetailed': 'Detalhado',
    'opt.cornerTR': 'Canto superior direito',
    'opt.cornerTL': 'Canto superior esquerdo',
    'opt.cornerBR': 'Canto inferior direito',
    'opt.cornerBL': 'Canto inferior esquerdo',
    'preset.ultraplus': 'Ultra+',
    'opt.ultraplus': 'Ultra+',
    'opt.shadow4': 'Ultra+ (8192)',
    'set.modelDetail': 'Detalhe dos modelos',
    'set.modelDetail.help': 'O capricho com que são construídos as criaturas, as mãos e outros modelos esculpidos. Mais alto fica mais liso de perto e demora mais para carregar um capítulo. Ultra+ é para os processadores mais rápidos.',
    'set.clutter': 'Objetos de detalhe',
    'set.clutter.help': 'Quantas coisinhas enchem os cômodos: quadros, fotos, calendários, caixas, papéis, garrafas. Mais deixa cada cômodo com cara de habitado; menos alivia computadores antigos.',
    'set.dof': 'Profundidade de campo',
    'set.dof.help': 'Desfoca o que está longe do ponto para onde você olha, como a lente de uma câmera. O foco acompanha o centro da tela. Níveis mais altos usam mais amostras para um desfoque mais suave e limpo.',
    'set.textureRes.help': 'Nitidez das superfícies: paredes, pisos, madeira, tecido. Mais alta precisa de mais memória de vídeo.',
    'set.shadows.help': 'Sombras da sua lanterna e dos postes lá fora. Mais alto é mais nítido. Ultra+ usa um mapa de sombras 8192 e precisa de muita memória de vídeo.',
    'set.antialias.help': 'Suaviza bordas serrilhadas. O MSAA é o mais limpo; o FXAA é leve e amacia um pouco a imagem toda; os dois juntos dão o resultado mais suave.',
    'set.dynLights.help': 'Quantas lâmpadas perto de você podem iluminar ao mesmo tempo objetos em movimento e criaturas.',
    'set.bloom.help': 'O brilho suave em volta de luzes fortes e telas.',
    'set.bloomStrength.help': 'A força desse brilho.',
    'set.motionBlur.help': 'Desfoca a imagem quando você vira rápido. Suas mãos e o que você segura continuam nítidos.',
    'set.particles.help': 'Poeira no ar, chuva, faíscas e gotas.',
    'set.viewDist.help': 'Até onde as coisas são desenhadas e até onde a neblina deixa ver.',
    'set.anisotropy.help': 'Mantém pisos e paredes nítidos vistos de lado. Custa muito pouco.',
    'set.contrast.help': 'A diferença entre as partes escuras e claras da imagem.',
    'set.saturation.help': 'A força das cores. Mais baixa lembra uma foto antiga.',
    'set.fov.help': 'A largura da sua visão. Mais larga mostra mais, mas deixa tudo mais distante.',
    'set.headBob.help': 'O quanto a visão balança com os passos. Diminua se der enjoo.',
    'set.shake.help': 'Tremor da câmera em sustos, impactos e corridas.',
    'set.grain.help': 'Granulação de filme sobre a imagem.',
    'set.chromatic.help': 'Franjas coloridas nas bordas da imagem, como numa lente barata.',
    'set.vignette.help': 'Escurecimento em direção aos cantos da tela.',
    'set.crosshair.help': 'Um pontinho no meio da tela para mirar nas coisas que dá para pegar.',
    'set.subtitles.help': 'Mostra o que é dito: walkie-talkie, fitas, pensamentos.',
    'set.subtitleSize.help': 'Tamanho das legendas e das legendas de sons.',
    'set.master.help': 'Volume geral.',
    'set.music.help': 'Volume da trilha.',
    'set.sfx.help': 'Passos, portas, objetos e tudo o que você faz.',
    'set.ambience.help': 'Os cômodos, a chuva, o zumbido e os ruídos do prédio.',
    'set.entities.help': 'As criaturas: seus passos, sua respiração e suas vozes.',
    'set.voice.help': 'Walkie-talkie, fitas e pensamentos.',
    'set.hrtf.help': 'Coloca os sons ao seu redor em três dimensões. Melhor com fones de ouvido; desligue para caixas de som.',
    'set.mouseSens.help': 'A velocidade com que a visão gira com o mouse.',
    'set.invertY.help': 'Mover o mouse para cima faz olhar para baixo.',
    'set.touchSens.help': 'A velocidade com que a visão gira quando você arrasta numa tela de toque.',
    'set.toggleCrouch.help': 'Aperte uma vez para agachar e outra para levantar, em vez de segurar a tecla.',
    'set.toggleSprint.help': 'Aperte uma vez para correr e outra para andar, em vez de segurar a tecla.',
    'set.lang.help': 'O idioma dos menus, das legendas e de todos os documentos do jogo.',
    'set.jumpscare.help': 'Reduzido mantém todos os sustos, mas suaviza os clarões e sons mais fortes.',
    'set.hints.help': 'Dicas curtas quando acontece algo novo.',
    'perf.frame': 'Quadro',
    'perf.low1': '1% mínimo',
    'perf.cpu': 'CPU',
    'perf.cpuUse': 'Uso da CPU',
    'perf.gpu': 'GPU',
    'perf.gpuUse': 'Uso da GPU',
    'perf.na': 'n/d',
    'perf.draws': 'Chamadas de desenho',
    'perf.tris': 'Triângulos',
    'perf.textures': 'Texturas',
    'perf.programs': 'Shaders',
    'perf.res': 'Renderização',
    'perf.heap': 'Memória JS',
    'perf.sysCpu': 'CPU do sistema',
    'perf.appCpu': 'CPU do jogo',
    'perf.procMem': 'Memória do jogo',
    'perf.card': 'Placa de vídeo',
    'settings.revert': 'Desfazer',
    'settings.keys': '↑↓ escolher · ←→ mudar · Q/E abas · Backspace desfazer · Esc voltar',
    'settings.impact': 'Custo de desempenho',
    'impact.0': 'Nenhum',
    'impact.1': 'Baixo',
    'impact.2': 'Médio',
    'impact.3': 'Alto',
    'impact.4': 'Muito alto',
    'impact.5': 'Extremo',
    'settings.gpuLoad': 'Uso estimado da GPU',
    'settings.vram': 'Memória de vídeo estimada',
    'settings.reloadBadge': 'Vale a partir do próximo capítulo carregado',
    'settings.restartBadge': 'Vale depois que o jogo reiniciar',
    'settings.restartNow': 'Reiniciar agora',
  });
})(typeof window !== 'undefined' ? window : globalThis);
