/* Interface em português do Brasil para a história de Ada Lind: substitui o que pertencia à história antiga e
   acrescenta o que as nove prateleiras precisam (portas, escadas, tipos de documento, legendas). Carregado após ui.js. */
(function (root) {
  'use strict';
  root.PB.I18N.register('pt-BR', 'ui', {
    'game.subtitle': 'ACHADOS E PERDIDOS',
    'menu.credit': 'Halvard · 13 de janeiro de 1998 · 02:56',
    'diff.time': 'Tempo de jogo estimado: 5 a 7 horas para quem lê todos os documentos e encontra os oito desenhos.',
    'set.vhs.help': 'Mostra o jogo como se fosse visto por uma velha câmera de vídeo caseira.',
    'help.drink': 'Chupar uma bala de cevada',
    'bag.stats': 'Documentos {a} / {b}   ·   Desenhos de Wren {c} / {d}',
    'bag.d.flashlight': 'Uma lanterna pesada, emborrachada, de debaixo do balcão do Depósito 9. Pilha: {n}%. Ela enfraquece antes de apagar.',
    'bag.n.almond': 'Bala de cevada',
    'bag.d.almond': 'Uma bala de cevada torcida, da lata debaixo do balcão, guardada para noites ruins. O açúcar acalma as mãos. Chupe com Q.',
    'bag.d.officeKey': 'Uma chavezinha de latão, gasta pelo uso.',
    'bag.d.token': 'Uma ficha de latão.',
    'help.padText': 'Analógico esquerdo: andar. Analógico direito: olhar. A: interagir. B: agachar. X: trocar as pilhas. Y: lanterna. LB / RB: inclinar. RT ou clique do analógico esquerdo: correr. LT: bastão luminoso. Clique do analógico direito: olhar para trás. Direcional: ↑ diário, ↓ bala de cevada, → itens. Exibir: mapa. Menu: pausa. Nos menus o direcional move, A escolhe e B volta.',
    'help.tip7': 'No fundo de cada lugar há uma mentira. <b>Devolva a coisa perdida ao lugar dela</b> e o caminho se abre.',
    'map.shrine': 'Retirada',
    'end.freed': 'Prateleiras retiradas',
    'end.claimed': 'Prateleiras retiradas',
    'inv.almond': 'BALA DE CEVADA ×{n}',
    'inv.token': 'FICHA',
    'n.almond': 'Bala de cevada (Q para chupar)',
    'n.drank': 'Você chupa a bala de cevada. A respiração se acalma.',
    'n.noAlmond': 'Você não tem bala de cevada.',
    'n.drawing': 'Desenho de Wren ({n}/8)',
    'pr.almond': 'Pegar a bala de cevada',
    'pr.drawing': 'Pegar o desenho de Wren',
    'door.house': 'A casa',
    'touch.drink': 'AÇÚCAR',
    'inv.pellets': 'LUZES PERDIDAS ×{n}',
    'pr.pellet': 'Pegar a luz perdida',
    'lock.house': 'Uma cortina de luz. Quatro luzes perdidas a mantêm fechada.',
    'help.tip1': '<b>Escute antes de olhar.</b> Cada criatura tem a sua regra: umas ouvem, outras só enxergam a luz, outras só se mexem quando ninguém está olhando. Os documentos dizem qual é qual.',
    'help.tip2': 'Quando as luzes começam a gaguejar, ou o som se retira do mundo, <b>alguma coisa está perto</b>.',
    'help.tip3': 'No Embaixo, pegue uma <b>luz perdida</b> e o Devorador fica longe de você por alguns segundos.',
    'help.tip4': 'Cada prateleira tem <b>as suas próprias criaturas</b>: um condutor que confere passagens, cavalos que só correm enquanto o realejo toca, pinheiros que só se mexem enquanto você se mexe. Aprenda a regra de cada uma.',
    'help.tip5': 'Você pode se <b>esconder</b> debaixo de camas, beliches e mesas, e dentro de armários. Se nada viu você entrar, nada vai procurar.',
    'help.tip6': 'O jogo <b>salva sozinho</b> a cada objetivo, quando você está em segurança.',
    'set.subtitles.help': 'Mostra o que é dito: canal nove, fitas, pensamentos.',
    'set.voice.help': 'Canal nove, fitas e pensamentos.',
    // portas e passagens das nove prateleiras
    'pr.unlock': 'Destrancar',
    'pr.stairs': 'Usar a escada',
    'pr.stairsDown': 'Descer a escada',
    'pr.stairsUp': 'Subir a escada',
    'pr.ladderDown': 'Descer pela escada de mão',
    'pr.ladderUp': 'Subir pela escada de mão',
    'door.otto': 'A sala de Otto Brandt',
    'lock.otto': 'Trancada desde 1964. A chave deve estar em algum lugar do arquivo.',
    'door.concourse': 'O saguão',
    'lock.concourse': 'Trancado do outro lado.',
    'door.bridge': 'A ponte de comando',
    'lock.bridge': 'Trancada. A chave está com o capitão.',
    'door.cage': 'A gaiola',
    'lock.cage': 'O portão da gaiola. Sem energia, nada se mexe.',
    'door.fire': 'A porta corta-fogo',
    'lock.fire': 'Calçada com uma cunha. Deste lado.',
    'door.signe': 'Stuegata 4',
    'lock.signe': 'Trancada. Há um lampião aceso lá dentro.',
    'door.ghost': 'O trem fantasma',
    // tipos de documento
    'kind.telegram': 'Telegrama',
    'kind.transcript': 'Transcrição',
    'kind.clipping': 'Jornal',
    // legendas de sons
    'hint.flash': 'F liga e desliga a lanterna.',
    'cap.chute': '[um pacote cai pela calha]',
    'cap.tube': '[o tubo pneumático bate]',
    'cap.bellFar': '[um sino, lá fora na neblina]',
    'cap.doorShut': '[uma porta se fecha em algum lugar]',
    'cap.stepsFar': '[passos, ao longe]',
    'cap.organ': '[um realejo de parque começa a tocar sozinho]',
    'cap.organStop': '[o realejo desacelera e para]',
    'cap.choir': '[um coro, cantando]',
    'cap.knocks': '[sete batidas, em aço]',
    'cap.ice': '[o gelo estala, ao longe]',
    'cap.brake': '[freios guinchando]',
    'cap.laugh': '[risadas]',
    'cap.toll': '[um sino dobra]',
    'cap.breath': '[uma respiração, logo atrás de você]',
    'cap.train': '[o trem, a toda velocidade]',
    'cap.pa': '[um gongo; o alto-falante chia]',
  });
})(typeof window !== 'undefined' ? window : globalThis);
