/* Türkçe hikâye çekirdeği: karakterler, konuşanlar, ortak replikler, ölümler, ipuçları, jenerik, duvar yazıları.
   Bölüm dosyaları belgeleri, görevleri, iç sesi, telsizi ve özetleri ekler; lake.js sonları ekler.
   Hikâye kılavuzu docs/STORY.md’dir. */
(function (root) {
  'use strict';
  root.PB.I18N.register('tr', 'story', {
    chars: {
      ada: { name: 'Ada', pos: 'Ada’nın', role: 'Ada Lind, 31. 1990’dan beri Halvard Merkez Garı’nın altındaki kayıp eşya bürosu Depo 9’da gece memuru. Sen.' },
      wren: { name: 'Wren', pos: 'Wren’in', role: 'Wren Lind, Ada’nın küçük kız kardeşi. Yedi yaşında. 14 Ocak 1979’da Ostra Gölü’nün buzunda kayboldu.' },
      otto: { name: 'Otto', pos: 'Otto’nun', role: 'Otto Brandt, 1946’dan 1964’e kadar Depo 9’un gece memuru; 1964’te yük asansörüyle aşağı indi. Dokuzuncu kanalda.' },
      ingrid: { name: 'Ingrid', pos: 'Ingrid’in', role: 'Ingrid Lind, kızların anneannesi. Gammel Ostra’da doğdu. 1996’da öldü.' },
      clerk: { name: 'Gece Memuru', pos: 'Gece Memuru’nun', role: 'Aşağısı’nın en dibinde Dizin’i tutuyor. Notlarını “A.” diye imzalıyor.' },
    },
    speakers: { ada: 'ADA', otto: 'OTTO', radio: 'TELSİZ', lyle: 'LYLE HARDY', clerk: 'MEMUR', wren: 'WREN', voice: '???' },
    items: {},
    obj: {},
    memento: {},
    freed: {},
    shrine: {},
    ghostHelp: {},
    mono: {
      hide: 'Nefesini tut.',
      hideLocker: 'Nefesini tut. Kıpırdama.',
      fearHigh: 'Nefes alamıyorum...',
      lowBattery: 'Pil bitiyor.',
      eaterFlicker: 'Işıklar sönüyor. Yakında. Çiğnediğini duyabiliyorum.',
      watcherSeen: 'En uçta uzun bir şey var, kıpırdamadan duruyor.',
    },
    // [ekranda yazan, bir dahaki sefere ne yapmalı]
    deaths: {
      eater: ['YENDİN', 'Yiyici düz koridorda hızlı, dönemeçlerde yavaştır. Elindeki yeni bir kayıp ışık onu birkaç saniyeliğine geri çekilmeye zorlar.'],
      sorter: ['AYIKLANDIN', 'Karanlıkta arşivi ayıklayan şey işine devam eder. Onunla rafların arasına girme.'],
      wallpaperMan: ['DUVARA KAĞITLANDIN', 'Yassı adamlar duvardan yalnızca sen arkanı dönünce çıkar. Yanlarından onlara yüzün dönük geç.'],
      hummer: ['UĞULTUYA GÖMÜLDÜN', 'Uğultunun koyulaştığı, ışıkların titrediği yerde bir şey dinliyor. Yavaş yürü, gürültülü yerlerden uzak dur.'],
      drowned: ['DİBE ÇEKİLDİN', 'Boğulmuşlar suyun altında bekler ve seni suyun içinde duyar. Sudan uzak dur, suyun içinde asla durma.'],
      passenger: ['YERİNE OTURTULDUN', 'Yolcular yüzlerinde ışık durunca uyanır. Fenerini yüzlerinden uzak tut, sürtünerek yanlarından geçme.'],
      bellman: ['ÇANA YAKALANDIN', 'Açık güvertede Çancı seni duyar. Çan çalmaya başladıysa avlanıyordur: bir şeyin altına gir ve eğil.'],
      pines: ['AĞAÇLARIN ARASINA ALINDIN', 'Çamlar yalnızca sen hareket ederken hareket eder. Yakınlarındaysan kıpırdama, ilgilerini kaybetsinler.'],
      stag: ['EZİLDİN', 'Geyik düz bir çizgide hücum eder. Arana bir ağaç ya da araba koy, kendi kendini sersemletir.'],
      usher: ['YERİNE GÖTÜRÜLDÜN', 'Yer gösterici yalnızca kırmızı ışığının içini görür. Işığın dışında kal, asla önünden geçme.'],
      burrower: ['TOPRAĞA ÇEKİLDİN', 'Kazıcılar adımlarını topraktan hisseder. Toprak zeminde çömel; rayların ve kalasların üstünde güvendesin.'],
      lamplighter: ['GÖZÜNE LAMBA TUTULDU', 'Lambacılar her ışığa gider. Lambanı söndür, yanından geçip gitsinler.'],
      crawler: ['ÜSTÜNE ATLADI', 'Kereste sürüngenleri tavan kirişlerinde bekler. Altlarından geçmeden önce yukarı bak ve eğil.'],
      frozen: ['DONDUN', 'Donmuş misafirler yalnızca sıcaklığın yakınında kıpırdar. Isın, sonra onlar kalkmadan ateşten uzaklaş.'],
      cold: ['DONDUN', 'Dışarıda soğuk hızla işler. Sığınaktan sığınağa git, bir ateşin başında ısın.'],
      whiteout: ['KARA GÖMÜLDÜN', 'Fırtınada yalnızca ayak izlerini görürsün. O seni duyar: koşma, yürü, sığınağın yakınında kal.'],
      cook: ['KANCAYA TAKILDIN', 'Aşçı mutfaktan hiç çıkmaz. Uzak uçta sırtını dönmesini bekle, sonra geç.'],
      silted: ['ÇAMURA ÇEKİLDİN', 'Çamurda fazla uzun durursan içlerinden biri yanında yükselir. Hareket etmeye devam et.'],
      longone: ['NEHRE ÇEKİLDİN', 'Uzunlar kuyularda, hendeklerde ve nehirde bekler. Suyun yanından geçerken çömel.'],
      choir: ['SIRALARA ALINDIN', 'Koro şarkı söylerken hiçbir şey görmez. Arkalarından usulca yürü; asla koşma, asla önlerinden geçme.'],
      water: ['BOĞULDUN', 'Su gittikçe daha hızlı yükseliyor. Yüksek bir yere çık ve tırman.'],
      conductor: ['TRENDEN İNDİRİLDİN', 'Geçerli bileti olmayanı Kondüktör trenden indirir. Lambası koridorda göründüğünde fenerini kapat ve bir ranzanın altına gir.'],
      sleeper: ['RANZAYA ÇEKİLDİN', 'Uyuyanlar göremez. Kompartımanlarının önündeki bir adım onları uyandırır: çömelerek geç, biri kalktıysa kıpırdama.'],
      underhand: ['VAGONLARIN ARASINA ÇEKİLDİN', 'Körükte asla durma. Hızla geç ve plakalara basmadan önce sıradaki kapıyı açmış ol.'],
      mask: ['YÜZLER', 'Maskeler yalnızca kimse onlara bakmazken kıpırdar. Onları önünde tut ve geri geri uzaklaş.'],
      horse: ['ÇİĞNENDİN', 'Atlar yalnızca org çalarken koşar. Müzik durunca onlar da durur: sen o zaman hareket et.'],
      lotte: ['KALDIRILDIN', 'Lotte göremez. Duyar ve gülmeyi hiç bırakmaz: kahkahadan uzak dur ve sessiz ol.'],
      hush: ['SUSTURULDUN', 'Sus’un yanında her ses söner. Kendi sesini duyamaz olduysan çok yakındadır. Uzaklaş, yavaşça.'],
      underice: ['BUZUN ALTINA', 'Eski nehrin üstündeki koyu buzda asla koşma. Yürü; altındaki altında kalır.'],
    },
    tips: [
      'Koşmak gürültülüdür. Çömelerek yürümek neredeyse sessizdir.',
      'Her rafın dibinde bir yalan vardır. Kayıp şeyi bul ve ait olduğu yere geri koy; o yer seni bırakır.',
      'Çoğu, gördüğünden iyi duyar. Bir şey yakındayken fenerini kapat.',
      'Yatakların, ranzaların ve masaların altına saklanabilirsin. İçeri girdiğini bir şey görmediyse hiçbir şey bakmaz.',
      'Saklanırken nefesini tutmak için Shift’e basılı tut. Nefesin biterse soluk soluğa kalırsın.',
      'Koşarken omzunun üstünden geriye bakmak için V’ye basılı tut.',
      'Her şeyi oku. Bunları yazan insanlar sana nasıl çıkacağını anlatıyor.',
      'Wren geride sekiz resim bıraktı, çoğu rafta bir tane. Bazıları iyi saklanmış.',
      'Otto söyleyecek bir şeyi olunca dokuzuncu kanaldan konuşur. Genelde haklıdır.',
      'M, gittiğin yerlerin haritasını açar.',
    ],
    photoLabels: {},
    credits: [
      ['LEVEL 256', 'dokuz raflık, birinci şahıs bir korku hikâyesi'],
      ['Şunlara', 'kimsenin suçu olmadığı söylenen herkese'],
      ['Yerler', 'Halvard, Ostra Gölü ve Aşağısı uydurmadır; içlerindeki herkes de öyle'],
      ['Ses', 'canlı sentezlendi: tek bir kayıt yok'],
      ['Resimler ve modeller', 'yordamsal: tek bir resim dosyası yok'],
      ['Depo 9', 'her gece açık. Gişeye sorun.'],
    ],
    // Aşağısı’nın duvarlarına karalanmış yazılar
    scrawl: {
      yellow: ['ONU KİM GERİ ALMAYA GELDİ?', 'SAAT HEP 02:56', 'TALEP 256', 'RAF ATLANMAZ', 'YALANI ARA', 'KİMSE SORMADI', 'DOSYA: UNUTULANLAR'],
      dark: ['IŞIĞI AÇIK TUT', 'ARAMAYI BIRAKTIĞIN ŞEYİ YER', 'ADA?'],
      concrete: ['ADA LIND ADINA SAKLANIYOR', '256', 'SAHİBİ ÇIKMADI'],
    },
  });
})(typeof window !== 'undefined' ? window : globalThis);
