/* Nucleo della storia in italiano: personaggi, battute comuni, morti, consigli, finali, titoli di coda. */
(function (root) {
  'use strict';
  root.PB.I18N.register('it', 'story', {
    chars: {
      sam: { name: 'Sam', pos: 'di Sam', role: 'Guida di notte per la Tri-County Movers, 20 anni. Nel 1987 ne aveva 13: il quinto membro della banda. Tu.' },
      walt: { name: 'Walt', pos: 'di Walt', role: 'Proprietario della sala giochi Starlight. Tecnico radar nell’aeronautica, poi riparatore di televisori. Scomparso dal marzo 1992.' },
      lily: { name: 'Lily', pos: 'di Lily', role: 'La figlia di Walt. Morta nell’ottobre 1983, a nove anni. Punteggio: 3.190.' },
      danny: { name: 'Danny', pos: 'di Danny', role: '16 anni nel 1987. Chiassoso, senza paura, sempre primo in classifica. Aveva la chiave di scorta di Walt.' },
      rosie: { name: 'Rosie', pos: 'di Rosie', role: '15 anni nel 1987. Quella che organizzava tutto. Voleva un programma radio tutto suo.' },
      nell: { name: 'Nell', pos: 'di Nell', role: '15 anni nel 1987. Silenziosa, disegnava fumetti, occhiali spessi. Non si è mai perdonata un pomeriggio in piscina.' },
      toby: { name: 'Toby', pos: 'di Toby', role: '13 anni nel 1987. Il migliore amico di Sam. Aveva paura del buio.' },
      eddie: { name: 'Eddie', pos: 'di Eddie', role: 'Assistente di Walt dal 1984 al 1988. È entrato a cercarli nel giugno 1993. Ha una figlia che non ha mai tenuto in braccio.' },
      nora: { name: 'Nora', pos: 'di Nora', role: 'La sorella minore di Walt.' },
      frank: { name: 'Frank Dobbs', pos: 'di Dobbs', role: 'Ispettore della polizia di Harlow, 1987.' },
      june: { name: 'June', pos: 'di June', role: 'La moglie di Eddie. Portiera di notte al Blue Moon Motor Inn.' },
      theo: { name: 'Theo', pos: 'di Theo', role: 'Il fratellino di Nell.' },
      maggie: { name: 'Maggie', pos: 'di Maggie', role: 'La madre di Toby.' },
      ruth: { name: 'Ruth', pos: 'di Ruth', role: 'La moglie di Walt fino al 1985.' },
      ray: { name: 'Ray', pos: 'di Ray', role: 'Il padre di Danny.' },
      carol: { name: 'Carol', pos: 'di Carol', role: 'La madre di Rosie.' },
      ann: { name: 'Ann', pos: 'di Ann', role: 'La madre di Sam.' },
    },
    speakers: { sam: 'SAM', eddie: 'EDDIE', walt: 'WALT', danny: 'DANNY', rosie: 'ROSIE', nell: 'NELL', toby: 'TOBY', lily: 'LILY', june: 'JUNE', radio: 'RADIO', voice: '???' },
    items: {},
    obj: {
      ghost: 'Porta l’oggetto {pos} al suo altarino (facoltativo)',
    },
    recap: {
      prolog: 'La sala giochi Starlight, la notte prima dell’asta. Il cabinato n. 7 era acceso senza spina nel muro, e conosceva il mio nome. PLAYER 1: SAM — CONTINUE?',
      lobby: 'Stanze gialle che non finiscono mai: il gioco che aspetta un giocatore. Qualcosa di tondo e pallido mangia là, nel buio. Eddie è vivo, al walkie-talkie, lì dentro dal 1993.',
      mill: 'Il magazzino del padre di Danny. Danny si è lanciato al mio inseguimento urlando: «Hai mollato!». Gli ho restituito l’orologio di suo padre, e lui si è fermato, e si è ricordato il suo nome.',
      pipes: 'I canali di scolo. Il nostro forte. Regola numero quattro: nessuno torna a casa da solo. Quella regola l’ho scritta io.',
      pool: 'La piscina dove Theo per poco non è annegato mentre Nell finiva un disegno. Lei aspetta da anni di essere perdonata. Theo l’ha perdonata già nella sua primissima lettera.',
      office: 'L’ufficio della madre di Rosie, centosette-punto-tre. Sul suo nastro, alle 0:40, qualcuno bussa alla porta sul retro della sala giochi. Rosie: «Guarda un po’ chi torna strisciando».',
      school: '16 aprile 1987. Il patto: tutte e cinque le mani sulla leva, nessuno molla. Cinque iniziali in fondo. L’ultima è la mia.',
      dark: 'Il buio, tre generatori e un accendino d’ottone. L’ultima pagina di Toby dice che Sam ha fatto ritorno. Io quel ritorno non lo ricordavo.',
      mall: 'Il sabato più bello del 1986: cinque ragazzini in una cabina per fototessere, e uno di loro sono io, che ride. I manichini si muovevano solo quando distoglievo lo sguardo.',
      motel: 'Il ricordo di Eddie, non il mio. La stanza 12 e il suo taccuino: UNO DENTRO, UNO FUORI. Gli serve qualcuno che resti al posto suo. Voleva che fossi io.',
      hospital: 'St. Agnes, ottobre 1983. Lily chiese a suo padre un gioco che non finisse mai, così nessuno avrebbe dovuto andarsene. Walt lo costruì.',
      maple: 'La mia strada. La voce di mia madre sulla segreteria alle 2:50 del mattino, che chiede dove sono. Alle 21:40 a casa non ci ho messo piede.',
      workshop: 'Lo scantinato di Walt e il nastro delle 3:17. Cinque mani sulla leva, e una ha mollato. La mia.',
      maze: 'Il livello 255, la casa stessa. Gli Spettri che ricordano camminano accanto a me come luci colorate.',
      killscreen: 'Il livello 256. Il lato rotto. Una spina che richiede cinque mani, e una porta che ne lascia uscire uno.',
    },
    memento: {
      danny: { name: 'L’orologio di Danny', line: 'Un orologio d’acciaio col vetro incrinato, fermo alle 3:17. Inciso sul retro: «RAY KOWALSKI — 25 ANNI — HARLOW MILL».' },
      rosie: { name: 'La cassetta di Rosie', line: 'Un walkman viola con una cassetta dentro. L’etichetta dice LATO B: PER DOPO. Il lato B è vuoto.' },
      nell: { name: 'Gli occhiali di Nell', line: 'Occhiali pesanti, una lente incrinata. Si appannano nella tua mano, come se qualcuno ci avesse appena alitato sopra.' },
      toby: { name: 'L’accendino di Toby', line: 'Un vecchio accendino d’ottone. Inciso: «TOBY — COSÌ NON RESTI MAI AL BUIO. IL NONNO».' },
    },
    freed: {
      danny: ['DANNY: «Le 3:17. Il mio orologio si è fermato. Io no».', 'DANNY: «…Eccoti qui. Ce ne hai messo di tempo, Keller. Vai. Il grosso lo tengo impegnato io».'],
      rosie: ['ROSIE: «Il lato B. Volevamo registrarlo dopo. Dopo aver vinto».', 'ROSIE: «Ho sempre corso davanti a tutti. Adesso cammino accanto a te».'],
      nell: ['NELL: «I miei occhiali. È tutto così… nitido».', 'NELL: «Non aspetto più di essere sicura. Vengo con te».'],
      toby: ['TOBY: «L’accendino del nonno…» (La fiamma attecchisce. Per la prima volta vedi la sua faccia: un ragazzino di tredici anni, con le lentiggini.)', 'TOBY: «…Non guardarmi ancora, Sam. Cammina e basta. Sono proprio dietro di te».'],
    },
    shrine: {
      quiet: 'L’altarino è silenzioso. La candela continua a bruciare.',
      missing: 'Un piccolo altarino. Una foto di {name} in una cornice, e uno spazio vuoto dove dovrebbe esserci qualcosa.',
    },
    mono: {
      watcherSeen: 'Lontano, c’è qualcosa di alto e nero, in piedi. Ha la testa piegata di lato. Sta contando.',
      hide: 'Trattieni il respiro.',
      hideLocker: 'Trattieni il respiro. Non muoverti.',
      fearHigh: 'Non riesco a respirare…',
      lowBattery: 'La pila sta morendo.',
      freed: '{name} non mi dà più la caccia.',
      eaterFlicker: 'Le luci si abbassano. È vicino. Lo sento masticare.',
    },
    ghostHelp: {
      danny: 'DANNY: «Scappa! Lo tengo io!»',
      amberWatch: 'TOBY: «Non guardarmi… ti prego, non guardarmi…»',
    },
    deaths: {
      eater: ['UN BANCHETTO', 'Il Divoratore è più veloce di te in rettilineo e lento nelle curve. Prendi gli angoli e ascolta il rumore della masticazione.'],
      red: ['PRESA', 'Danny non si ferma mai e non rinuncia mai a un inseguimento. Spezza la sua linea di vista e metti un angolo tra voi.'],
      violet: ['STRADA SBARRATA', 'Rosie va dove stai andando, non dove sei. Cambia direzione quando sparisce.'],
      teal: ['SOTT’ACQUA', 'Nell sente l’acqua. Stai fuori dalle pozzanghere e cammina lungo i bordi.'],
      amber: ['IMMOBILE', 'Toby non può muoversi mentre lo guardi. Tienigli addosso gli occhi, o la luce.'],
      grinner: ['HA SORRISO', 'I Ghignanti si sciolgono alla luce. Tieni la torcia puntata su di loro o lascia cadere uno stick luminoso.'],
      watcher: ['IL CONTO', 'Il Contatore si muove solo quando non lo guardi. Non voltargli le spalle a lungo.'],
      crawler: ['GIÙ IN FONDO', 'Gli Striscianti indietreggiano davanti alla luce e poi ti girano intorno. Tieni le spalle al muro e non tenerne uno troppo a lungo nel fascio.'],
      monitor: ['SENZA PERMESSO', 'Il Sorvegliante vede solo ciò che tocca la sua torcia. Entra in un armadietto prima che il fascio ti trovi.'],
      mannequin: ['IN POSA', 'I manichini si muovono solo quando nessuno guarda. Cammina all’indietro, se serve.'],
      neighbor: ['PORTA APERTA', 'Il Vicino si avvicina quando gli dai le spalle. La torcia lo fa indietreggiare. Non rispondere mai alla voce.'],
      chompy: ['GRANDE ABBRACCIO', 'Chompy è lento ma non si ferma mai. Puntagli la luce negli occhi e si coprirà la faccia.'],
    },
    tips: [
      'Il Divoratore è più veloce di te in un corridoio dritto, ma lento nelle curve. Prendi gli angoli.',
      'Correre fa rumore. Camminare accovacciati è quasi silenzioso, e accovacciati si aprono le porte senza far rumore.',
      'Se le luci si abbassano e tremolano, il Divoratore è vicino.',
      'Una lanterna fa fuggire tutto per qualche secondo.',
      'I registratori salvano la partita e riproducono un ricordo.',
      'Puoi nasconderti sotto scrivanie, letti e banconi, e negli armadietti. Se niente ti vede entrare, niente verrà a cercarti.',
      'Porta a ogni Spettro il suo oggetto sull’altarino e smetterà di darti la caccia. Il finale dipende da questo.',
      'Uno Star Pop calma i nervi e ti restituisce il fiato.',
      'M apre la mappa dei posti che hai esplorato.',
      'La torcia divora le pile. Gli stick luminosi (G) illuminano un angolo, e il loro tintinnio allontana i cacciatori da te.',
      'Continua a guardare quello color ambra. Ma non troppo a lungo.',
      'Lily ha lasciato otto disegni. Alcuni sono nascosti bene.',
      'Eddie conosce questo posto meglio di chiunque altro. Non vuol dire che ti dica tutto.',
      'Gli armadietti ti nascondono del tutto. Se qualcosa si avvicina, tieni premuto Maiusc per trattenere il respiro.',
      'I manichini non possono muoversi mentre li guardi.',
      'Il Vicino usa voci che conosci. Non rispondere.',
      'Walt ha strappato cinque pagine dal suo diario. Contano più di quanto sembri.',
      'Un cassetto aperto di un dito ha qualcosa dentro. Anche una cassaforte con lo sportello non chiuso.',
      'Tieni premuto V (o il tasto centrale del mouse) per guardarti alle spalle mentre corri.',
      'Più dura il silenzio, più si avvicinano. Al gioco non piace aspettare.',
    ],
    endings: {
      exit: {
        title: 'USCITA', subtitle: 'Finale cattivo — Di nuovo',
        lines: [
          'Prendi la porta. Dietro di te Eddie grida il tuo nome, poi la porta si chiude e le grida restano dall’altra parte.',
          'Aria fredda. Pioggia. Apri gli occhi sulla moquette bagnata della sala giochi. È mattina. Le serrande sono mezze alzate.',
          'Il cabinato n. 7 è ancora acceso. Nella schermata dimostrativa ora cinque Spettri fluttuano per la casa. Il quinto indossa una giacca da lavoro.',
          'I traslocatori lo caricano a mezzogiorno. L’autista racconterà poi di aver sentito qualcuno bussare dall’interno del cabinato per tutta la Route 9.',
          'Il camion non arriva mai all’asta.',
          'Avevi promesso di non abbandonarli mai più. La seconda volta è stato più facile. È questa la cosa peggiore.',
        ],
      },
      deal: {
        title: 'IL PATTO', subtitle: 'Finale oscuro — Uno dentro, uno fuori',
        lines: [
          'Tieni la porta. Eddie ti guarda per un lungo secondo. «Glielo dirò. Dirò a tutti chi eri».',
          'Passa. La porta si chiude piano, come la fine di un nastro.',
          'Da qualche parte a Harlow, all’alba, un uomo fradicio entra in una cucina, e una bambina di un anno lo fissa dal suo seggiolone.',
          'La casa è silenziosa. Lontano, qualcosa di tondo ricomincia a masticare.',
          'Non sei il Giocatore. Non sei uno Spettro. Sei la persona che è rimasta. Le stelle brillano. Sai dove si trova ognuna di loro.',
          'Sulla classifica di una sala giochi vuota, con una grafia che nessuno sa spiegare, compare una riga nuova: SAM — ANCORA IN GIOCO.',
        ],
      },
      plug: {
        title: 'GAME OVER', subtitle: 'Finale buono — Nessuno molla',
        lines: [
          'Quattro luci colorate si chiudono sulle tue mani. Rosso, viola, turchese, ambra. Cinque mani, come diceva il patto.',
          'Tiri. La spina esce. Per la prima volta dal 1987, il ronzio si ferma.',
          'Nel buio, vicinissima, una voce umana e stanca: «Sono sazio, Sam. Finalmente».',
          'Ti svegli sulla moquette della sala giochi. L’alba entra dal vetro.',
          'Quattro ragazzini con i giubbotti del 1987 sono seduti per terra e sbattono le palpebre. Toby ti guarda a lungo. «Sam? …Hai qualche anno in più». Poi ti abbraccia così forte da far male.',
          'In Maple Street si spegne la luce di un portico accesa da sette anni.',
          'Eddie torna a casa a piedi per le strade vuote. Non corre. Vuole ricordarsi la strada.',
          'Il cabinato n. 7 è spento. Una riga resta impressa nel vetro: GAME OVER — 5 PLAYERS.',
        ],
      },
      lil: {
        title: 'LIL', subtitle: 'Finale vero — I nomi in classifica',
        lines: [
          'Posi otto disegni sul nucleo. Pastelli a cera su carta: la sala giochi, un Chompy arancione con le corna, una finestra d’ospedale, un papà.',
          'Il Divoratore smette di masticare. Il silenzio dura a lungo. Poi, con una voce che ricordi dal 1985: «…Quelli li ha disegnati Lily».',
          'Walt è lì dove c’era il Divoratore, magro e grigio, di nuovo sé stesso. «Giù le mani. Questa spina la tiro io. È sempre toccato a me».',
          'Quattro luci colorate si chiudono sulle sue mani. Tira. La casa si ripiega come carta.',
          'L’ultima cosa che vedi è una bambina con la camicia da ospedale che gli prende la mano, e loro due che se ne vanno nel buio tra le stelle.',
          'Alba. Quattro ragazzini sulla moquette della sala giochi. Eddie alla cabina telefonica fuori, che ride e piange insieme. «June? June, sono io».',
          'Una settimana dopo, Nora apre la sala giochi per l’ultima volta e trova la classifica riscritta con una grafia che conosce. 1 LIL. 2 DAN. 3 ROS. 4 NEL. 5 TOB. 6 SAM. 7 WALT.',
          'La luce del portico di Toby si spegne. In Maple Street, due persone che non sono più ragazzini siedono sul marciapiede e parlano fino a mezzogiorno. Sam gli racconta tutto. Lui lo sapeva già.',
        ],
      },
    },
    scrawl: {
      yellow: ['CHI È TORNATO A CASA?', 'SONO SEMPRE LE 3:17', 'NON MOLLARE', 'CINQUE MANI', 'LO SENTO MASTICARE', 'CONTA LE PORTE'],
      dark: ['TIENI LA LUCE ACCESA', 'SAM?', 'SORRIDE QUANDO SBATTI LE PALPEBRE', 'NON HO PAURA'],
      office: ['DOVE SONO FINITI TUTTI', '107.3', 'LATO B'],
      hospital: ['SILENZIO PER FAVORE', 'DISEGNAVA DAPPERTUTTO', '207'],
      motel: ['UNO DENTRO UNO FUORI', 'NON RISPONDERE', '3:17'],
      school: ['NESSUNO MOLLA', 'D R N T S', 'SAM ERA QUI'],
      concrete: ['HAI MOLLATO', 'DAN #1', '3:17'],
      pool: ['UN SECONDO', 'STAVO GUARDANDO'],
      mall: ['AMICI PER SEMPRE', 'ANCHE SE'],
      tunnel: ['NESSUNO TORNA A CASA DA SOLO', 'D+T+S'],
      workshop: ['NON STACCARE LA SPINA', '2 5 6'],
    },
    photoLabels: { fort: 'IL FORTE. GIORNO DELL’INAUGURAZIONE.', chompy: 'LIL & CHOMPY' },
    credits: [
      ['LEVEL 256', 'La sala giochi Starlight'],
      ['Un gioco horror in prima persona', ''],
      ['Dedicato a', 'chiunque abbia lasciato andare qualcosa, e sia tornato a prenderlo'],
      ['Hungry House', 'un videogioco arcade immaginario del 1981, creato per questa storia'],
      ['Suono', 'sintetizzato dal vivo, nemmeno una registrazione'],
      ['Texture e modelli', 'procedurali, nemmeno un file immagine'],
      ['Ai giocatori', 'non mettete mai un gettone nel cabinato n. 7 dopo mezzanotte'],
    ],
  });
})(typeof window !== 'undefined' ? window : globalThis);
