/* Nucleo della storia in italiano: personaggi, voci, battute comuni, morti, consigli, titoli di coda, scritte.
   I file dei capitoli aggiungono documenti, obiettivi, pensieri, radio e riassunti; lake.js aggiunge i finali.
   La bibbia della storia è docs/STORY.md. */
(function (root) {
  'use strict';
  root.PB.I18N.register('it', 'story', {
    chars: {
      ada: { name: 'Ada', pos: 'di Ada', role: 'Ada Lind, 31 anni. Impiegata del turno di notte al Deposito 9, l’ufficio oggetti smarriti sotto la stazione centrale di Halvard, dal 1990. Tu.' },
      wren: { name: 'Wren', pos: 'di Wren', role: 'Wren Lind, la sorellina di Ada. Sette anni. Scomparsa sul ghiaccio del lago Ostra il 14 gennaio 1979.' },
      otto: { name: 'Otto', pos: 'di Otto', role: 'Otto Brandt, impiegato notturno del Deposito 9 dal 1946 al 1964, quando scese con il montacarichi. Sul canale nove.' },
      ingrid: { name: 'Ingrid', pos: 'di Ingrid', role: 'Ingrid Lind, la nonna delle bambine. Nata a Gammel Ostra. Morta nel 1996.' },
      clerk: { name: 'L’Impiegata Notturna', pos: 'dell’Impiegata Notturna', role: 'Tiene l’Indice in fondo al Sotto. Firma i suoi appunti «A.»' },
    },
    speakers: { ada: 'ADA', otto: 'OTTO', radio: 'RADIO', lyle: 'LYLE HARDY', clerk: 'L’IMPIEGATA', wren: 'WREN', voice: '???' },
    items: {},
    obj: {},
    memento: {},
    freed: {},
    shrine: {},
    ghostHelp: {},
    mono: {
      hide: 'Trattieni il respiro.',
      hideLocker: 'Trattieni il respiro. Non muoverti.',
      fearHigh: 'Non riesco a respirare...',
      lowBattery: 'La pila sta morendo.',
      eaterFlicker: 'Le luci si abbassano. È vicino. Lo sento masticare.',
      watcherSeen: 'Qualcosa di alto in fondo, perfettamente immobile.',
    },
    // [cosa dice lo schermo, cosa fare diversamente]
    deaths: {
      eater: ['DIVORATA', 'Il Divoratore è veloce in rettilineo e lento nelle curve. Una luce perduta appena raccolta lo fa indietreggiare per qualche secondo.'],
      sorter: ['SMISTATA', 'Ciò che smista l’archivio al buio continua il suo lavoro. Non metterti fra lui e gli scaffali.'],
      wallpaperMan: ['TAPPEZZATA', 'Gli uomini piatti si staccano dal muro solo alle tue spalle. Passagli accanto guardandoli.'],
      hummer: ['RONZATA', 'Dove il ronzio cresce e le luci tremolano, qualcosa ascolta. Cammina piano e stai lontana dai posti rumorosi.'],
      drowned: ['TRASCINATA SUL FONDO', 'Gli Annegati aspettano sott’acqua e ti sentono quando ci sei dentro. Stai fuori dall’acqua, e non restarci mai ferma.'],
      passenger: ['RIACCOMPAGNATA AL POSTO', 'I passeggeri si svegliano quando una luce si posa su di loro. Tieni la torcia lontana dai loro volti e non sfiorarli.'],
      bellman: ['RINTOCCATA', 'Sul ponte scoperto il Campanaro ti sente. Quando la campana comincia a suonare sta cacciando: mettiti al riparo e stai bassa.'],
      pines: ['PORTATA TRA GLI ALBERI', 'I pini si muovono solo mentre ti muovi tu. Vicino a loro resta immobile e lascia che perdano interesse.'],
      stag: ['TRAVOLTA', 'Il cervo carica in linea retta. Metti un albero o un’auto fra voi due e si stordirà da solo.'],
      usher: ['ACCOMPAGNATA AL POSTO', 'Una maschera vede solo nel suo fascio rosso. Stai fuori dalla luce e non passarle mai davanti.'],
      burrower: ['TRASCINATA SOTTOTERRA', 'Gli scavatori sentono i tuoi passi attraverso la terra. Sui pavimenti di terra abbassati; su rotaie e assi sei al sicuro.'],
      lamplighter: ['LAMPADA NEGLI OCCHI', 'I portalampade vanno verso ogni luce. Spegni la tua e lasciali passare.'],
      crawler: ['CADUTO ADDOSSO', 'Gli striscianti delle travi aspettano nell’armatura del soffitto. Guarda in alto prima di passarci sotto, e stai bassa.'],
      frozen: ['CONGELATA', 'Gli ospiti congelati si muovono solo vicino al calore. Scaldati, poi allontanati dal fuoco prima che si alzino.'],
      cold: ['CONGELATA', 'Fuori il freddo entra in fretta. Vai da riparo a riparo e scaldati vicino a un fuoco.'],
      whiteout: ['INGHIOTTITA DALLA NEVE', 'Nella tormenta vedi solo le sue impronte. Ti sente: cammina, non correre, e resta vicina ai ripari.'],
      cook: ['AGGANCIATA', 'Il Cuoco non lascia mai la cucina. Aspetta che ti volti le spalle in fondo, poi passa.'],
      silted: ['TRASCINATA NEL FANGO', 'Resta ferma troppo a lungo sul fango e uno di loro si alza accanto a te. Continua a muoverti.'],
      longone: ['PORTATA NEL FIUME', 'I Lunghi aspettano nei pozzi, nei fossi e nel fiume. Abbassati quando passi vicino all’acqua.'],
      choir: ['FATTA SEDERE TRA I BANCHI', 'Finché il coro canta non vede nulla. Cammina piano dietro di loro; non correre mai, non passargli mai davanti.'],
      water: ['ANNEGATA', 'L’acqua sale sempre più in fretta. Raggiungi un punto alto e arrampicati.'],
      conductor: ['FATTA SCENDERE DAL TRENO', 'Senza un biglietto valido il Capotreno ti fa scendere. Quando la sua lanterna arriva lungo il corridoio, spegni la torcia e infilati sotto una cuccetta.'],
      sleeper: ['TRASCINATA IN UNA CUCCETTA', 'I dormienti non vedono. Un passo davanti al loro scompartimento li sveglia: passa accucciata, e resta immobile quando uno è in piedi.'],
      underhand: ['TRASCINATA TRA LE CARROZZE', 'Non fermarti mai su un intercomunicante. Attraversa in fretta, e apri la porta successiva prima di mettere piede sulle piastre.'],
      mask: ['VOLTI', 'Le maschere si muovono solo quando nessuno le guarda. Tienile davanti a te e indietreggia.'],
      horse: ['CALPESTATA', 'I cavalli corrono solo mentre l’organo suona. Quando la musica si ferma, si fermano anche loro: è allora che ti muovi tu.'],
      lotte: ['SOLLEVATA', 'Lotte non vede. Sente, e non smette mai di ridere: stai lontana dalla risata e non fare rumore.'],
      hush: ['ZITTITA', 'Vicino al Silenzio ogni suono svanisce. Quando non senti più te stessa, è vicinissimo. Allontanati, piano.'],
      underice: ['SOTTO IL GHIACCIO', 'Non correre mai sul ghiaccio scuro sopra il vecchio fiume. Cammina, e ciò che sta sotto resta sotto.'],
    },
    tips: [
      'Correre fa rumore. Camminare accucciata è quasi silenzioso.',
      'In fondo a ogni scaffale c’è una bugia. Trova la cosa perduta e rimettila dove deve stare, e il posto ti lascia andare.',
      'Quasi tutti sentono meglio di quanto vedano. Spegni la torcia quando qualcosa è vicino.',
      'Puoi nasconderti sotto letti, cuccette e scrivanie. Se niente ti ha vista entrare, niente verrà a guardare.',
      'Da nascosta, tieni premuto Maiusc per trattenere il respiro. Se finisci il fiato, ansimi.',
      'Tieni premuto V per guardarti alle spalle mentre corri.',
      'Leggi tutto. Chi ha scritto queste cose ti sta dicendo come uscire.',
      'Wren ha lasciato otto disegni, uno su quasi ogni scaffale. Alcuni sono nascosti bene.',
      'Otto parla sul canale nove quando ha qualcosa da dirti. Di solito ha ragione.',
      'M apre una mappa dei posti in cui sei stata.',
    ],
    photoLabels: {},
    credits: [
      ['LEVEL 256', 'una storia dell’orrore in prima persona, in nove scaffali'],
      ['Per', 'tutti quelli a cui è stato detto che non era colpa di nessuno'],
      ['Luoghi', 'Halvard, il lago Ostra e il Sotto sono inventati; così come tutti quelli che ci stanno dentro'],
      ['Suono', 'sintetizzato dal vivo: nemmeno una registrazione'],
      ['Immagini e modelli', 'procedurali: nemmeno un file immagine'],
      ['Il Deposito 9', 'è aperto tutte le notti. Chieda allo sportello.'],
    ],
    // Scritte scarabocchiate sui muri del Sotto
    scrawl: {
      yellow: ['CHI È TORNATO A PRENDERLO?', 'SONO SEMPRE LE 02:56', 'RICHIESTA 256', 'NON SI SALTA UNO SCAFFALE', 'CERCA LA BUGIA', 'NESSUNO HA CHIESTO', 'ARCHIVIATO SOTTO: DIMENTICATO'],
      dark: ['TIENI LA LUCE ACCESA', 'MANGIA CIÒ CHE HAI SMESSO DI CERCARE', 'ADA?'],
      concrete: ['DA TENERE PER: ADA LIND', '256', 'NON RITIRATO'],
    },
  });
})(typeof window !== 'undefined' ? window : globalThis);
