/* Interfaccia in italiano. */
(function (root) {
  'use strict';
  root.PB.I18N.register('it', 'ui', {
    'game.title': 'LEVEL 256',
    'game.subtitle': 'LA SALA GIOCHI STARLIGHT',
    'game.aria': 'Vista di gioco',
    'noscript': 'Questo gioco richiede JavaScript.',

    'boot.tip': 'CONSIGLIO',
    'boot.init': 'Avvio…',
    'boot.fonts': 'Caricamento dei caratteri…',
    'boot.sounds': 'Registrazione dei suoni…',
    'boot.voices': 'Registrazione delle voci…',
    'boot.prep': 'Preparazione del livello…',
    'boot.noThree': 'Impossibile caricare il motore 3D (three.js). Controlla la connessione a Internet e ricarica la pagina.',
    'boot.error': 'Errore all’avvio: {msg}',
    'boot.noWebgl': 'La scheda video non è riuscita ad avviare il 3D (WebGL 2). Aggiorna il driver grafico e riavvia il gioco.',
    'load.textures': 'Tessitura delle texture… ({n}/{m})',
    'load.walls': 'Innalzamento dei muri…',
    'load.bake': 'Cottura della luce…',
    'load.fixtures': 'Montaggio dei neon…',
    'load.props': 'Sistemazione dei mobili…',
    'load.decals': 'Macchie e graffi…',
    'load.shaders': 'Compilazione degli shader…',
    'load.ready': 'Pronto',
    'load.error': 'Errore di caricamento: {msg}',

    'first.title': 'Prima di iniziare',
    'first.lang': 'Lingua',
    'first.bright': 'Regola la luminosità finché il simbolo a sinistra si vede appena e quello a destra si vede chiaramente.',
    'first.phones': 'Meglio con le cuffie, in una stanza buia.',
    'first.go': 'Continua',

    'menu.continue': 'Continua',
    'menu.new': 'Nuova partita',
    'menu.levels': 'Capitoli',
    'menu.settings': 'Impostazioni',
    'menu.archive': 'Archivio',
    'menu.help': 'Come si gioca',
    'menu.quit': 'Esci dal gioco',
    'menu.credit': 'Harlow · 30 novembre 1994 · 2:11',
    'menu.foot': 'Gioca con le cuffie, al buio.',
    'menu.footDone': 'Finali: {list} · morti {deaths}',

    'confirm.title': 'Nuova partita?',
    'confirm.body': 'I tuoi progressi salvati verranno sovrascritti. I documenti trovati restano nell’archivio.',
    'confirm.yes': 'Sì, ricomincia',
    'confirm.no': 'Annulla',

    'diff.title': 'Difficoltà',
    'diff.easy': 'Facile',
    'diff.easyDesc': 'Per goderti la storia. Le creature sono più lente e meno attente. Una volta per capitolo sfuggi a una presa.',
    'diff.normal': 'Normale',
    'diff.normalDesc': 'Come è stato pensato. Una sola presa ti riporta all’ultimo salvataggio.',
    'diff.nightmare': 'Incubo',
    'diff.nightmareDesc': 'Creature più veloci e con l’udito più fine. Le pile si scaricano in fretta. La paura arriva prima.',
    'diff.time': 'Durata stimata: 4–6 ore per chi legge ogni documento e libera tutti e quattro gli Spettri.',

    'levels.title': 'Capitoli',
    'levels.locked': 'Bloccato',

    'common.back': 'Indietro',
    'common.on': 'Sì',
    'common.off': 'No',

    'settings.title': 'Impostazioni',
    'settings.reset': 'Predefinite',
    'settings.reloadNote': 'Le impostazioni con * si applicano al prossimo caricamento di un capitolo.',
    'tab.screen': 'Schermo',
    'set.displayMode': 'Modalità schermo',
    'set.displayMode.help': 'Lo schermo intero nasconde il browser. Esc o F11 per uscire; Alt+Invio lo alterna durante il gioco.',
    'opt.windowed': 'Finestra',
    'opt.fullscreen': 'Schermo intero',
    'set.resolution': 'Risoluzione',
    'set.resolution.help': 'La dimensione dell’immagine renderizzata. Nativa usa il tuo schermo; ogni altra dimensione viene adattata alla finestra secondo la modalità di scala qui sotto.',
    'opt.native': 'Nativa (schermo)',
    'set.scaleMode': 'Modalità di scala',
    'set.scaleMode.help': 'Come mostrare una risoluzione con proporzioni diverse dalla finestra.',
    'opt.fit': 'Adatta (proporzioni, bande nere)',
    'opt.stretch': 'Allunga',
    'opt.fill': 'Riempi (bordi tagliati)',
    'set.upscale': 'Filtro di scala',
    'set.upscale.help': 'Morbido fonde i pixel durante l’ingrandimento; Pixel li mantiene netti e quadrati (aspetto retrò a bassa risoluzione).',
    'opt.smooth': 'Morbido',
    'opt.pixel': 'Pixel',
    'set.sharpen': 'Nitidezza',
    'set.sharpen.help': 'Nitidezza adattiva al contrasto sull’immagine finale. Aiuta sotto la risoluzione nativa e con l’antialiasing.',
    'set.fpsLimit': 'Limite di fotogrammi',
    'set.fpsLimit.help': 'Limita i fotogrammi al secondo. Un limite più basso tiene fresca la scheda video e regolare il ritmo delle immagini.',
    'opt.unlimited': 'Illimitato',
    'set.vsync': 'Sincronizzazione verticale',
    'set.vsync.help': 'Attiva: i fotogrammi seguono la frequenza del monitor, senza tearing. Disattiva: il gioco disegna più in fretta che può, fino al limite di fotogrammi. In un browser, il browser stesso aspetta sempre il monitor, quindi Disattiva toglie solo l’attesa del gioco; la versione desktop disattiva del tutto la sincronizzazione (dopo il riavvio).',
    'tab.graphics': 'Grafica',
    'tab.display': 'Immagine',
    'tab.audio': 'Audio',
    'tab.controls': 'Comandi',
    'tab.gameplay': 'Gioco',
    'preset.low': 'Bassa',
    'preset.medium': 'Media',
    'preset.high': 'Alta',
    'preset.ultra': 'Ultra',
    'preset.extreme': 'Estrema',
    'preset.custom': 'Personalizzata',
    'opt.off': 'Disattivato',
    'opt.low': 'Basso',
    'opt.medium': 'Medio',
    'opt.high': 'Alto',
    'opt.ultra': 'Ultra',
    'opt.extreme': 'Estremo',
    'opt.shadow1': 'Basse (1024)',
    'opt.shadow2': 'Alte (2048)',
    'opt.shadow3': 'Ultra (4096)',
    'opt.small': 'Piccoli',
    'opt.large': 'Grandi',
    'opt.full': 'Completo',
    'opt.reduced': 'Ridotto',

    'set.preset': 'Preimpostazione qualità',
    'set.preset.help': 'Cambia in un colpo tutte le impostazioni grafiche qui sotto. Estrema è pensata per schede video di fascia alta; Ultra+ va oltre (ombre 8192, l’illuminazione precalcolata più densa, i modelli più fini, profondità di campo) ed è per i PC più potenti.',
    'set.renderScale': 'Scala di risoluzione',
    'set.renderScale.help': 'Sopra il 100% si renderizza a risoluzione più alta e poi si riduce: immagine più nitida, carico molto maggiore per la scheda video.',
    'set.textureRes': 'Risoluzione texture',
    'set.shadows': 'Ombre',
    'set.antialias': 'Antialiasing',
    'set.lightmapRes': 'Qualità dell’illuminazione precalcolata',
    'set.lightmapRes.help': 'Dettaglio della luce morbida precalcolata e delle sue ombre.',
    'set.dynLights': 'Luci dinamiche',
    'set.bloom': 'Bagliore (bloom)',
    'set.bloomStrength': 'Intensità del bagliore',
    'set.volumetric': 'Luce volumetrica e polvere',
    'set.ao': 'Occlusione ambientale (SSAO)',
    'set.ao.help': 'Morbide ombre di contatto negli angoli, sotto i mobili e tra le piastrelle.',
    'set.ssr': 'Riflessi in spazio schermo',
    'set.ssr.help': 'Riflessi veri su pavimenti bagnati, piastrelle, vetro e metallo lucido.',
    'set.volumetric.help': 'Fasci di luce, il cono della torcia e polvere sospesa calcolati con il ray marching. Molto pesante su Estremo.',
    'set.motionBlur': 'Sfocatura di movimento',
    'set.lensDirt': 'Sporco sull’obiettivo',
    'set.lensDirt.help': 'Aloni sull’obiettivo che catturano la luce forte.',
    'set.particles': 'Densità delle particelle',
    'set.viewDist': 'Distanza visiva',
    'set.anisotropy': 'Filtro anisotropico',
    'set.brightness': 'Luminosità',
    'set.brightness.help': 'Regolala in modo che gli angoli più bui si vedano appena.',
    'set.contrast': 'Contrasto',
    'set.saturation': 'Saturazione dei colori',
    'set.fov': 'Campo visivo',
    'set.headBob': 'Oscillazione della testa',
    'set.shake': 'Tremolio della visuale',
    'set.grain': 'Grana della pellicola',
    'set.chromatic': 'Aberrazione cromatica',
    'set.vignette': 'Vignettatura',
    'set.vhs': 'Effetto videocamera (VHS)',
    'set.vhs.help': 'Mostra il gioco come attraverso il mirino di una videocamera del 1994.',
    'set.reduceFlicker': 'Riduci lo sfarfallio',
    'set.reduceFlicker.help': 'Attenua le luci tremolanti e i lampi sullo schermo per chi è sensibile alla luce.',
    'set.crosshair': 'Punto di mira',
    'set.subtitles': 'Sottotitoli',
    'set.captions': 'Sottotitoli dei suoni',
    'set.captions.help': 'Mostra i suoni importanti come testo, per esempio [masticare in lontananza].',
    'set.subtitleSize': 'Dimensione dei sottotitoli',
    'set.master': 'Volume generale',
    'set.music': 'Musica',
    'set.sfx': 'Effetti',
    'set.ambience': 'Ambiente (ronzio, gocce, pioggia)',
    'set.entities': 'Suoni delle creature',
    'set.voice': 'Voci e radio',
    'set.hrtf': 'Audio 3D (HRTF, consigliate le cuffie)',
    'set.mouseSens': 'Sensibilità del mouse',
    'set.invertY': 'Inverti l’asse verticale',
    'set.touchSens': 'Sensibilità touch',
    'set.padSens': 'Sensibilità del controller',
    'set.toggleCrouch': 'Accovacciarsi: premi invece di tenere premuto',
    'set.toggleSprint': 'Correre: premi invece di tenere premuto',
    'set.lang': 'Lingua',
    'set.difficulty': 'Difficoltà',
    'set.difficulty.help': 'Influisce sulla velocità e sull’udito delle creature e sulle pile della torcia.',
    'set.jumpscare': 'Jumpscare',
    'set.hints': 'Suggerimenti',

    'archive.title': 'Archivio',
    'archive.count': '{n} / {m} documenti',
    'archive.notFound': 'Non ancora trovato',
    'kind.note': 'Biglietto',
    'kind.letter': 'Lettera',
    'kind.diary': 'Pagina di diario',
    'kind.tape': 'Registrazione',
    'kind.photo': 'Fotografia',
    'kind.screen': 'Schermo del computer',
    'kind.phone': 'Messaggio in segreteria',
    'kind.printout': 'Tabulato',
    'kind.wall': 'Scritta sul muro',
    'kind.notice': 'Avviso',
    'kind.memory': 'Ricordo',
    'kind.drawing': 'Disegno',
    'kind.card': 'Biglietto d’auguri',
    'kind.report': 'Rapporto',
    'kind.flyer': 'Volantino',
    'kind.doc': 'Documento',

    'help.title': 'Come si gioca',
    'help.kbm': 'Tastiera e mouse',
    'help.walk': 'Camminare',
    'help.mouse': 'Mouse',
    'help.look': 'Guardarsi intorno (clic per catturare il puntatore)',
    'help.sprint': 'Correre (rumoroso, consuma fiato)',
    'help.crouch': 'Accovacciarsi (quasi silenzioso)',
    'help.interact': 'Interagire, leggere, prendere, nascondersi',
    'help.flash': 'Torcia',
    'help.drink': 'Bere uno Star Pop',
    'help.throw': 'Lanciare uno stick luminoso',
    'help.lean': 'Sporgersi a sinistra / destra (sbirciare dietro gli angoli)',
    'help.map': 'Mappa',
    'help.bag': 'Oggetti / diario',
    'bag.items': 'OGGETTI',
    'bag.journal': 'DIARIO',
    'bag.close': 'Chiudi (I / J)',
    'bag.empty': 'Hai le tasche vuote.',
    'bag.inspectHint': 'Trascina per girarlo.',
    'bag.now': 'IN QUESTO MOMENTO',
    'bag.story': 'LA STORIA FIN QUI',
    'bag.docs': 'TROVATO QUI',
    'bag.noDocs': 'Qui non hai ancora trovato niente. Guarda meglio.',
    'bag.people': 'PERSONE',
    'bag.freed': 'in pace',
    'bag.hunting': 'caccia ancora',
    'bag.stats': 'Documenti {a} / {b}   ·   Disegni di Lily {c} / {d}',
    'bag.n.flashlight': 'Torcia',
    'bag.d.flashlight': 'Una pesante torcia d’acciaio presa dal furgone della sala giochi. Pila: {n}%. Si affievolisce prima di spegnersi.',
    'bag.n.battery': 'Pile di ricambio',
    'bag.d.battery': 'Torce grandi per la torcia. R le inserisce; una torcia scarica le riceve da sola.',
    'bag.n.almond': 'Star Pop',
    'bag.d.almond': 'Una lattina della bibita alla ciliegia della sala giochi, chissà come ancora fredda. Zucchero e bollicine calmano le mani. Si beve con Q.',
    'bag.n.glow': 'Stick luminosi',
    'bag.d.glow': 'Piegane uno e lancialo con G. Striscianti e Ghignanti non attraversano la luce verde.',
    'bag.d.officeKey': 'La chiave dell’ufficio di Walt, presa dal registratore di cassa. L’ottone è consumato e liscio.',
    'bag.d.token': 'Un gettone Starlight con una stella traforata. Solo per il cabinato n. 7.',
    'bag.n.fuse': 'Fusibili',
    'bag.d.fuse': 'Pesanti fusibili di ceramica per il vecchio quadro della fabbrica.',
    'bag.n.fuel': 'Taniche di gasolio',
    'bag.d.fuel': 'Gasolio per i generatori. Sciaguatta rumorosamente. Cammina piano.',
    'bag.d.keycard': 'Una tessera di sicurezza con banda magnetica. La foto di qualcuno è stata grattata via.',
    'bag.d.key': 'Una chiave con un cartellino di carta. Apre qualcosa qui.',
    'help.pause': 'Pausa',
    'help.touch': 'Touch',
    'help.pad': 'Controller',
    'help.touchText': 'Levetta di movimento in basso a sinistra; trascina sul lato destro dello schermo per guardarti intorno. I pulsanti a destra: interagisci, torcia, corri, accovacciati, mappa.',
    'help.padText': 'Stick sinistro: camminare. Stick destro: guardarsi intorno. A: interagire. B: accovacciarsi. X: cambiare le batterie. Y: torcia. LB / RB: sporgersi. RT o premere lo stick sinistro: correre. LT: stick luminoso. Premere lo stick destro: guardarsi alle spalle. Croce direzionale: ↑ diario, ↓ Star Pop, → oggetti. View: mappa. Menu: pausa. Nei menu la croce sposta, A sceglie e B torna indietro.',
    'help.survive': 'Restare vivi',
    'help.tip1': '<b>Il Divoratore</b> è più veloce di te nei corridoi dritti e lento nelle curve. Prendi gli angoli.',
    'help.tip2': 'Quando i neon cominciano a tremolare, <b>è vicino</b>.',
    'help.tip3': 'Prendi una <b>lanterna</b> e per qualche secondo tutto fugge da te.',
    'help.tip4': '<b>Il rosso</b> non si ferma mai. <b>Il viola</b> ti taglia la strada. <b>Il turchese</b> sente l’acqua e salta da un punto all’altro. <b>L’ambra</b> si blocca finché lo guardi.',
    'help.tip5': 'Puoi <b>nasconderti</b> sotto le scrivanie e negli armadietti. Se nessuno ti vede entrare, nessuno ti troverà.',
    'help.tip6': 'I <b>registratori</b> salvano la partita. Il salvataggio automatico avviene agli obiettivi, quando sei al sicuro.',
    'help.tip7': 'Porta a ogni Spettro il suo oggetto <b>al suo altarino</b>. Il finale dipende da questo.',

    'pause.title': 'Pausa',
    'pause.resume': 'Riprendi',
    'pause.map': 'Mappa',
    'pause.journal': 'Diario',
    'pause.archive': 'Archivio',
    'pause.settings': 'Impostazioni',
    'pause.help': 'Come si gioca',
    'pause.load': 'Carica l’ultimo salvataggio',
    'pause.menu': 'Menu principale',

    'note.close': 'Chiudi',
    'note.closeKey': 'Chiudi (E)',

    'map.close': 'Chiudi',
    'map.closeKey': 'Chiudi (M)',
    'map.objective': 'Obiettivo',
    'map.tape': 'Cassetta',
    'map.doc': 'Documento',
    'map.shrine': 'Altarino',
    'map.supply': 'Scorte',
    'map.locked': 'Porta chiusa',

    'kp.label': 'SICUREZZA',
    'kp.clear': 'CANC',
    'kp.enter': 'OK',
    'kp.open': 'APERTO',
    'kp.error': 'ERRORE',
    'kp.close': 'Annulla (Esc)',

    'cab.help': 'Frecce o WASD · Invio per iniziare · P per la pausa ·',
    'cab.exit': 'Lascia il cabinato (Esc)',

    'choice.back': 'Fai un passo indietro',
    'card.skip': 'Fai clic o premi E per continuare',

    'death.retry': 'Continua dall’ultimo salvataggio',
    'death.menu': 'Menu principale',

    'end.menu': 'Menu principale',
    'end.skip': 'Salta',
    'end.time': 'tempo di gioco',
    'end.deaths': 'morti',
    'end.docs': 'documenti',
    'end.freed': 'Spettri liberati',
    'end.drawings': 'disegni trovati',

    'hud.objective': 'OBIETTIVO',
    'hud.rec': 'REC',
    'hud.stamina': 'FIATO',
    'hud.battery': 'LUCE',
    'hud.power': 'CORRENTE {t}',
    'hud.fps': '{n} FPS',

    'touch.pause': 'Pausa',
    'touch.bag': 'BORSA',
    'touch.map': 'MAPPA',
    'touch.drink': 'BEVI',
    'touch.throw': 'LANCIA',
    'touch.crouch': 'GIÙ',
    'touch.sprint': 'CORRI',
    'touch.flash': 'LUCE',
    'touch.tap': 'TOCCA',

    'inv.battery': 'PILA ×{n}',
    'inv.almond': 'STAR POP ×{n}',
    'inv.glow': 'STICK LUMINOSO ×{n}',
    'inv.officeKey': 'CHIAVE DELL’UFFICIO',
    'inv.token': 'GETTONE D’ORO',
    'inv.fuses': 'FUSIBILE ×{n}',
    'inv.fuel': 'GASOLIO ×{n}',
    'inv.keycard': 'TESSERA DI SICUREZZA',
    'inv.pellets': 'LANTERNA ×{n}',

    'n.added': 'Aggiunto all’archivio: {title}',
    'n.saved': 'Partita salvata',
    'n.batteryIn': 'Pila nuova nella torcia',
    'n.batterySpare': 'Pila di ricambio',
    'n.noSpare': 'Nessuna pila di ricambio.',
    'n.batteryFull': 'La pila è ancora carica.',
    'hint.reload': 'R: cambia le pile della torcia',
    'touch.reload': 'PILE',
    'help.reload': 'Cambiare le pile della torcia',
    'help.lookBack': 'Guardarsi alle spalle mentre si corre (tenere premuto)',
    'n.batterySwap': 'Hai inserito una pila di ricambio',
    'n.almond': 'Star Pop (Q per bere)',
    'n.glow': 'Stick luminoso (G per lanciare)',
    'n.found': 'Trovato: {name}',
    'n.drank': 'Bevi lo Star Pop. Il respiro si calma.',
    'n.noAlmond': 'Non hai Star Pop.',
    'n.noGlow': 'Non hai stick luminosi.',
    'n.slow': 'Il gioco va lento. In Pausa › Impostazioni › Grafica puoi abbassare la qualità.',
    'n.lockFail': 'Impossibile catturare il mouse. Tieni premuto il tasto sinistro e trascina per guardarti intorno.',
    'n.flashDead': 'La torcia si è spenta.',
    'n.holdBreath': 'Qualcosa è vicino. Tieni premuto Maiusc per trattenere il respiro.',
    'n.heardBreath': 'Ti ha sentito respirare.',
    'n.noFlash': 'Non hai una torcia.',
    'n.noBattery': 'La pila è scarica. Trovane un’altra.',
    'n.grace': 'C’è mancato poco! (Facile: una volta per capitolo)',
    'n.freed': '{name} ora riposa in pace',
    'n.ghostBack': '{name} ha fatto un passo indietro',
    'n.cabinetHi': 'Le tue iniziali sono entrate in classifica: SAM',
    'n.perfect': 'Hai mangiato tutte le stelle. Partita perfetta.',
    'n.fruit': 'Davanti alla casa è comparso un premio',
    'n.diesel': 'Tanica di gasolio',
    'n.drawing': 'Disegno di Lily ({n}/8)',

    'pr.read': 'Leggi: {title}',
    'pr.readWall': 'Leggi la scritta',
    'pr.screen': 'Guarda lo schermo',
    'pr.tape': 'Ascolta la cassetta (salva la partita)',
    'pr.battery': 'Prendi la pila',
    'pr.almond': 'Prendi lo Star Pop',
    'pr.glow': 'Prendi lo stick luminoso',
    'pr.flashlight': 'Prendi la torcia',
    'pr.token': 'Prendi il gettone',
    'pr.fuse': 'Prendi il fusibile',
    'pr.fuel': 'Prendi la tanica di gasolio',
    'pr.keycard': 'Prendi la tessera di sicurezza',
    'pr.take': 'Prendi: {name}',
    'pr.pellet': 'Prendi la lanterna',
    'pr.phoneRing': 'Rispondi al telefono',
    'pr.phone': 'Alza la cornetta',
    'pr.cabinetFree': 'Gioca al cabinato (FREE PLAY)',
    'pr.doorLocked': '{name} (chiusa a chiave)',
    'pr.doorOpen': 'Apri la porta',
    'pr.doorClose': 'Chiudi la porta',
    'pr.drawerOpen': 'Apri il cassetto',
    'pr.drawerClose': 'Chiudi il cassetto',
    'pr.safeOpen': 'Apri la cassaforte',
    'pr.safeClose': 'Chiudi la cassaforte',
    'pr.safeLocked': 'Cassaforte (inserisci la combinazione)',
    'pr.hide': 'Nasconditi sotto',
    'pr.hideLocker': 'Nasconditi nell’armadietto',
    'pr.unhide': 'Esci',
    'pr.shrineLook': 'Guarda l’altarino',
    'pr.shrinePlace': 'Lascia l’oggetto sull’altarino',
    'pr.drawing': 'Prendi il disegno di Lily',

    'door.default': 'Porta',
    'door.office': 'Porta dell’ufficio',
    'door.storage': 'Magazzino',
    'door.wc': 'Bagno',
    'door.front': 'Porta d’ingresso',
    'door.elevator': 'Montacarichi',
    'door.security': 'Sala sicurezza',
    'door.stair': 'Scala antincendio',
    'door.house': 'La casa degli Spettri',
    'door.service': 'Ascensore di servizio',
    'lock.service': 'L’ascensore è morto. Tutti e tre i generatori devono essere accesi.',
    'door.exit': 'USCITA',
    'door.room': 'Stanza {n}',
    'door.jammed': 'Porta',
    'lock.jammed': 'Bloccata. La maniglia gira, ma qualcosa la trattiene dall’altra parte.',
    'lock.exit': 'L’USCITA è chiusa. Non ancora.',
    'door.pressure': 'Porta stagna',
    'lock.pressure': 'La porta stagna non si muove. Dietro sibila il vapore.',
    'door.janitor': 'Bidello',
    'lock.janitor': 'Un lucchetto a combinazione. Tre cifre.',
    'door.fireExit': 'Uscita di sicurezza',
    'lock.fireExit': 'Una catena pesante e un lucchetto. Le chiavi le ha il bidello.',
    'lock.fireExitMotel': 'Il maniglione non cede. Qualcuno l’ha bloccato da fuori.',
    'door.gym': 'Palestra',
    'door.mallExit': 'Porte del centro commerciale',
    'lock.mallExit': 'Chiuso per la notte. In lontananza ronza la cabina delle fototessere.',
    'door.room12': 'Stanza 12',
    'lock.room12': 'Chiusa a chiave. La targhetta è lucida, come se qualcuno la toccasse ogni giorno.',
    'door.room207': 'Stanza 207',
    'lock.room207': 'Chiusa a chiave. Un cartello di carta: SILENZIO PER FAVORE. C’è un sole disegnato a pastello.',
    'door.elevatorH': 'Ascensore',
    'lock.elevatorH': 'L’ascensore aspetta con le porte chiuse. Aspetta qualcosa.',
    'door.samHouse': 'Casa tua',
    'door.tobyHouse': 'La casa di Toby',
    'door.neighbor': 'Porta d’ingresso',
    'lock.neighbor': 'Chiusa a chiave. Le tende si muovono quando distogli lo sguardo.',
    'door.alley': 'Porta sul vicolo',
    'lock.alley': 'Chiusa a chiave. Non prima di una sosta all’angolo.',
    'door.kernel': 'Porta d’acciaio',
    'lock.kernel': 'Acciaio, e chiusa a chiave. Una targa d’ottone: KERNEL — SOLO W.',
    'lock.default': 'Chiusa a chiave.',
    'lock.office': 'Chiusa a chiave. Una targa d’ottone sulla porta: «W. — DIRETTORE».',
    'lock.front': 'Chiusa con un lucchetto dall’esterno. La chiave ce l’hanno i traslocatori.',
    'lock.elevator': 'Il montacarichi non ha corrente. Il pulsante di chiamata è morto.',
    'lock.security': 'La tastiera chiede un codice di quattro cifre.',
    'lock.stair': 'La spia del lettore di tessere è rossa. Serve una tessera di sicurezza.',
    'lock.house': 'Una tenda di luce viola. Quattro lanterne la tengono chiusa.',

    'cap.front': 'davanti',
    'cap.back': 'dietro',
    'cap.left': 'a sinistra',
    'cap.right': 'a destra',
    'cap.phone': '[squilla un telefono]',
    'cap.drag': '[passi strascicati lì vicino]',
    'cap.moan': '[un gemito]',
    'cap.farSteps': '[passi da qualche altra parte nell’edificio]',
    'cap.thud': '[qualcosa cade, lontano]',
    'cap.buzz': '[un neon sfrigola]',
    'cap.whisper': '[bisbigli]',
    'cap.giggle': '[risatine nel buio]',
    'cap.radio': '[scariche della radio]',
    'cap.thunder': '[tuono]',
    'cap.hiss': '[un sibilo bagnato che si allontana]',
    'cap.skitter': '[zampettio sui mattoni]',
    'cap.whistle': '[un fischietto strilla]',
    'cap.plastic': '[plastica che scricchiola]',
    'cap.bite': '[denti che si chiudono lì vicino]',
    'cap.biteFar': '[masticare in lontananza]',
    'cap.callName': '[qualcuno ti chiama per nome con la voce di Toby]',
    'cap.heavySteps': '[passi pesanti, uno squittio di gomma]',
    'cap.pipe': '[un tubo risuona da qualche parte nei cunicoli]',
    'cap.locker': '[un armadietto sbatte in fondo al corridoio]',
    'cap.knock': '[tre colpi, da qualche parte in fondo al corridoio]',
    'cap.beep': '[un monitor bipa in una stanza vuota]',
    'cap.arc': '[l’elettricità schiocca dietro la porta d’acciaio]',
    'cap.pop': '[un tubo di luce scoppia]',
    'cap.slam': '[una porta sbatte alle tue spalle]',
    'cap.run': '[qualcuno corre, fuori vista]',
    'cap.callJune': '[una voce di donna in fondo al corridoio: «Eddie? Eddie, sei tu?»]',
    'cap.car': '[un’auto passa sibilando sulla strada bagnata]',
    'cap.door': '[una porta, da qualche parte]',
    'cap.drip': '[gocciolio]',
    'cap.hum': '[ronzio dei neon]',
    'tab.access': 'Accessibilità',
    'tab.perf': 'Prestazioni',
    'set.perfOverlay': 'Indicatore delle prestazioni',
    'set.perfOverlay.help': 'Mostra come gira il gioco. Solo FPS; Base aggiunge il tempo per fotogramma, i tempi di CPU e GPU per fotogramma e quanto è impegnata ciascuna; Dettagliato aggiunge un grafico dei tempi, le chiamate di disegno, i triangoli, la memoria, la risoluzione di rendering e la tua scheda video. Il tempo della GPU richiede un browser che consenta le query di temporizzazione della GPU (la versione desktop lo fa sempre).',
    'set.perfCorner': 'Posizione dell’indicatore',
    'set.perfCorner.help': 'In quale angolo dello schermo compare l’indicatore delle prestazioni.',
    'opt.perfFps': 'Solo FPS',
    'opt.perfBasic': 'Base',
    'opt.perfDetailed': 'Dettagliato',
    'opt.cornerTR': 'In alto a destra',
    'opt.cornerTL': 'In alto a sinistra',
    'opt.cornerBR': 'In basso a destra',
    'opt.cornerBL': 'In basso a sinistra',
    'preset.ultraplus': 'Ultra+',
    'opt.ultraplus': 'Ultra+',
    'opt.shadow4': 'Ultra+ (8192)',
    'set.modelDetail': 'Dettaglio dei modelli',
    'set.modelDetail.help': 'Quanto finemente sono costruiti le creature, le mani e gli altri modelli scolpiti. Più alto è più liscio da vicino e rende più lungo il caricamento di un capitolo. Ultra+ è per i processori più veloci.',
    'set.clutter': 'Oggetti di dettaglio',
    'set.clutter.help': 'Quante piccole cose riempiono le stanze: quadri, fotografie, calendari, scatole, fogli, bottiglie. Di più rende ogni stanza vissuta; di meno alleggerisce i computer più vecchi.',
    'set.dof': 'Profondità di campo',
    'set.dof.help': 'Sfoca ciò che è lontano dal punto che guardi, come l’obiettivo di una macchina fotografica. La messa a fuoco segue il centro dello schermo. I livelli alti usano più campioni per una sfocatura più morbida e pulita.',
    'set.textureRes.help': 'Nitidezza delle superfici: muri, pavimenti, legno, stoffa. Più alta richiede più memoria video.',
    'set.shadows.help': 'Le ombre della tua torcia e dei lampioni fuori. Più alte sono più nitide. Ultra+ usa una mappa delle ombre da 8192 e richiede molta memoria video.',
    'set.antialias.help': 'Smussa i bordi seghettati. L’MSAA è il più pulito; l’FXAA è leggero e ammorbidisce un po’ tutta l’immagine; insieme danno il risultato più liscio.',
    'set.dynLights.help': 'Quante lampade vicine possono illuminare insieme gli oggetti in movimento e le creature.',
    'set.bloom.help': 'Il morbido alone attorno alle luci forti e agli schermi.',
    'set.bloomStrength.help': 'Quanto è forte quell’alone.',
    'set.motionBlur.help': 'Sfoca l’immagine quando ti giri in fretta. Le mani e ciò che tieni restano nitidi.',
    'set.particles.help': 'Polvere nell’aria, pioggia, scintille e gocce.',
    'set.viewDist.help': 'Fin dove vengono disegnate le cose e fin dove la nebbia ti lascia vedere.',
    'set.anisotropy.help': 'Mantiene nitidi pavimenti e muri visti di sbieco. Costa pochissimo.',
    'set.contrast.help': 'La differenza tra le parti scure e chiare dell’immagine.',
    'set.saturation.help': 'Quanto sono intensi i colori. Più bassa ricorda una vecchia fotografia.',
    'set.fov.help': 'Quanto è ampia la tua visuale. Più ampia mostra di più ma fa sembrare tutto più lontano.',
    'set.headBob.help': 'Quanto oscilla la visuale con i passi. Abbassala se ti dà la nausea.',
    'set.shake.help': 'Tremolio della visuale per spaventi, urti e corsa.',
    'set.grain.help': 'Grana della pellicola sull’immagine.',
    'set.chromatic.help': 'Frange colorate ai bordi dell’immagine, come con un obiettivo economico.',
    'set.vignette.help': 'Scurimento verso gli angoli dello schermo.',
    'set.crosshair.help': 'Un puntino al centro dello schermo per mirare alle cose da prendere.',
    'set.subtitles.help': 'Mostra ciò che viene detto: il walkie-talkie, le cassette, i pensieri.',
    'set.subtitleSize.help': 'Dimensione dei sottotitoli e dei sottotitoli dei suoni.',
    'set.master.help': 'Volume complessivo.',
    'set.music.help': 'Volume della colonna sonora.',
    'set.sfx.help': 'Passi, porte, oggetti e tutto ciò che fai.',
    'set.ambience.help': 'Le stanze, la pioggia, il ronzio e i rumori dell’edificio.',
    'set.entities.help': 'Le creature: i loro passi, il loro respiro e le loro voci.',
    'set.voice.help': 'Walkie-talkie, cassette e pensieri.',
    'set.hrtf.help': 'Colloca i suoni intorno a te in tre dimensioni. Meglio con le cuffie; disattivalo con gli altoparlanti.',
    'set.mouseSens.help': 'Quanto velocemente gira la visuale con il mouse.',
    'set.invertY.help': 'Muovere il mouse in su fa guardare in giù.',
    'set.touchSens.help': 'Quanto velocemente gira la visuale quando trascini su un touchscreen.',
    'set.padSens.help': 'Quanto velocemente gira la visuale con lo stick destro di un controller.',
    'set.toggleCrouch.help': 'Premi una volta per accovacciarti e un’altra per alzarti, invece di tenere premuto il tasto.',
    'set.toggleSprint.help': 'Premi una volta per correre e un’altra per camminare, invece di tenere premuto il tasto.',
    'set.lang.help': 'La lingua dei menu, dei sottotitoli e di ogni documento del gioco.',
    'set.jumpscare.help': 'Ridotto mantiene ogni spavento, ma rende più gentili i lampi e i suoni più forti.',
    'set.hints.help': 'Brevi consigli quando succede qualcosa di nuovo.',
    'perf.frame': 'Fotogramma',
    'perf.low1': '1% minimo',
    'perf.cpu': 'CPU',
    'perf.cpuUse': 'Carico CPU',
    'perf.gpu': 'GPU',
    'perf.gpuUse': 'Carico GPU',
    'perf.na': 'n.d.',
    'perf.draws': 'Chiamate di disegno',
    'perf.tris': 'Triangoli',
    'perf.textures': 'Texture',
    'perf.programs': 'Shader',
    'perf.res': 'Rendering',
    'perf.heap': 'Memoria JS',
    'perf.sysCpu': 'CPU di sistema',
    'perf.appCpu': 'CPU del gioco',
    'perf.procMem': 'Memoria del gioco',
    'perf.card': 'Scheda video',
    'settings.revert': 'Ripristina',
    'settings.keys': '↑↓ scegli · ←→ modifica · Q/E schede · Backspace ripristina · Esc indietro',
    'settings.impact': 'Costo in prestazioni',
    'impact.0': 'Nessuno',
    'impact.1': 'Basso',
    'impact.2': 'Medio',
    'impact.3': 'Alto',
    'impact.4': 'Molto alto',
    'impact.5': 'Estremo',
    'settings.gpuLoad': 'Carico GPU stimato',
    'settings.vram': 'Memoria video stimata',
    'settings.reloadBadge': 'Si applica al prossimo caricamento di un capitolo',
    'settings.restartBadge': 'Si applica al riavvio del gioco',
    'settings.restartNow': 'Riavvia ora',
  });
})(typeof window !== 'undefined' ? window : globalThis);
