/* Interfaccia italiana per la storia di Ada Lind: sostituisce ciò che apparteneva alla vecchia storia e aggiunge
   ciò che serve ai nove scaffali (porte, scale, tipi di documento, sottotitoli). Caricato dopo ui.js. */
(function (root) {
  'use strict';
  root.PB.I18N.register('it', 'ui', {
    'game.subtitle': 'OGGETTI SMARRITI',
    'menu.credit': 'Halvard · 13 gennaio 1998 · 02:56',
    'diff.time': 'Durata stimata: 5–7 ore per chi legge ogni documento e trova tutti e otto i disegni.',
    'set.vhs.help': 'Mostra il gioco come attraverso una vecchia videocamera di famiglia.',
    'help.drink': 'Succhiare una caramella d’orzo',
    'bag.stats': 'Documenti {a} / {b}   ·   Disegni di Wren {c} / {d}',
    'bag.d.flashlight': 'Una pesante torcia gommata presa da sotto lo sportello del Deposito 9. Pila: {n}%. Si affievolisce prima di spegnersi.',
    'bag.n.almond': 'Caramella d’orzo',
    'bag.d.almond': 'Una caramella d’orzo attorcigliata dalla latta sotto lo sportello, tenuta per le notti brutte. Lo zucchero calma le mani. Succhiala con Q.',
    'bag.d.officeKey': 'Una piccola chiave d’ottone, lisciata dall’uso.',
    'bag.d.token': 'Un gettone d’ottone.',
    'help.padText': 'Levetta sinistra: cammina. Levetta destra: guarda. A: interagisci. B: accucciati. X: cambia pile. Y: torcia. LB / RB: sporgiti. RT o clic della levetta sinistra: corri. LT: bastoncino luminoso. Clic della levetta destra: guarda indietro. Croce: ↑ diario, ↓ caramella d’orzo, → oggetti. Visualizza: mappa. Menu: pausa. Nei menu la croce si sposta, A sceglie e B torna indietro.',
    'help.tip7': 'In fondo a ogni posto c’è una bugia. <b>Rimetti la cosa perduta dove deve stare</b> e la strada si apre.',
    'map.shrine': 'Richiesta',
    'end.freed': 'Scaffali reclamati',
    'end.claimed': 'Scaffali reclamati',
    'inv.almond': 'CARAMELLA D’ORZO ×{n}',
    'inv.token': 'GETTONE',
    'n.almond': 'Caramella d’orzo (Q per succhiarla)',
    'n.drank': 'Succhi la caramella d’orzo. Il respiro si calma.',
    'n.noAlmond': 'Non hai caramelle d’orzo.',
    'n.drawing': 'Disegno di Wren ({n}/8)',
    'pr.almond': 'Prendi la caramella d’orzo',
    'pr.drawing': 'Prendi il disegno di Wren',
    'door.house': 'La casa',
    'touch.drink': 'ZUCCHERO',
    'inv.pellets': 'LUCI PERDUTE ×{n}',
    'pr.pellet': 'Prendi la luce perduta',
    'lock.house': 'Una tenda di luce. Quattro luci perdute la tengono chiusa.',
    'help.tip1': '<b>Ascolta prima di guardare.</b> Ogni creatura ha la sua regola: alcune sentono, alcune vedono solo la luce, alcune si muovono solo quando nessuno le guarda. I documenti ti dicono quali.',
    'help.tip2': 'Quando le luci cominciano a balbettare, o il suono si ritira dal mondo, <b>qualcosa è vicino</b>.',
    'help.tip3': 'Nel Sotto, prendi una <b>luce perduta</b> e il Divoratore ti sta lontano per qualche secondo.',
    'help.tip4': 'Ogni scaffale ha <b>le sue creature</b>: un capotreno che controlla i biglietti, cavalli che corrono solo mentre l’organo suona, pini che si muovono solo mentre ti muovi tu. Impara la regola di ciascuna.',
    'help.tip5': 'Puoi <b>nasconderti</b> sotto letti, cuccette e scrivanie, e negli armadietti. Se niente ti ha vista entrare, niente verrà a guardare.',
    'help.tip6': 'Il gioco <b>salva da solo</b> a ogni obiettivo, quando sei al sicuro.',
    'set.subtitles.help': 'Mostra ciò che viene detto: canale nove, cassette, pensieri.',
    'set.voice.help': 'Canale nove, cassette e pensieri.',
    // porte e passaggi dei nove scaffali
    'pr.unlock': 'Apri con la chiave',
    'pr.stairs': 'Prendi le scale',
    'pr.stairsDown': 'Scendi le scale',
    'pr.stairsUp': 'Sali le scale',
    'pr.ladderDown': 'Scendi la scala a pioli',
    'pr.ladderUp': 'Sali la scala a pioli',
    'door.otto': 'L’ufficio di Otto Brandt',
    'lock.otto': 'Chiuso a chiave dal 1964. La chiave dev’essere da qualche parte nell’archivio.',
    'door.concourse': 'L’atrio',
    'lock.concourse': 'Chiuso dall’altra parte.',
    'door.bridge': 'La plancia',
    'lock.bridge': 'Chiusa a chiave. La chiave ce l’ha il capitano.',
    'door.cage': 'La gabbia',
    'lock.cage': 'Il cancello della gabbia. Senza corrente non si muove niente.',
    'door.fire': 'La porta tagliafuoco',
    'lock.fire': 'Bloccata con un cuneo. Da questa parte.',
    'door.signe': 'Stuegata 4',
    'lock.signe': 'Chiusa a chiave. Dentro arde una lampada.',
    'door.ghost': 'Il treno fantasma',
    // tipi di documento
    'kind.telegram': 'Telegramma',
    'kind.transcript': 'Trascrizione',
    'kind.clipping': 'Giornale',
    // sottotitoli dei suoni
    'hint.flash': 'F accende e spegne la torcia.',
    'cap.chute': '[un pacco cade giù per lo scivolo]',
    'cap.tube': '[la posta pneumatica sbatte]',
    'cap.bellFar': '[una campana, lontano nella nebbia]',
    'cap.doorShut': '[una porta si chiude da qualche parte]',
    'cap.stepsFar': '[passi, lontani]',
    'cap.organ': '[un organo da fiera comincia a suonare da solo]',
    'cap.organStop': '[l’organo rallenta e tace]',
    'cap.choir': '[un coro, che canta]',
    'cap.knocks': '[sette colpi, sull’acciaio]',
    'cap.ice': '[il ghiaccio scricchiola, lontano]',
    'cap.brake': '[freni che stridono]',
    'cap.laugh': '[risate]',
    'cap.toll': '[una campana suona a morto]',
    'cap.breath': '[un respiro, proprio dietro di te]',
    'cap.train': '[il treno, a tutta velocità]',
    'cap.pa': '[un gong; l’altoparlante gracchia]',
  });
})(typeof window !== 'undefined' ? window : globalThis);
