/* Núcleo de la historia en español: personajes, hablantes, frases comunes, muertes, consejos, créditos, pintadas.
   Los archivos de capítulo añaden documentos, objetivos, pensamientos, radio y resúmenes; lake.js añade los finales.
   La biblia de la historia es docs/STORY.md. */
(function (root) {
  'use strict';
  root.PB.I18N.register('es', 'story', {
    chars: {
      ada: { name: 'Ada', pos: 'de Ada', role: 'Ada Lind, 31 años. Empleada nocturna del Depósito 9, la oficina de objetos perdidos bajo la estación central de Halvard, desde 1990. Tú.' },
      wren: { name: 'Wren', pos: 'de Wren', role: 'Wren Lind, la hermana pequeña de Ada. Siete años. Desapareció en el hielo del lago Ostra el 14 de enero de 1979.' },
      otto: { name: 'Otto', pos: 'de Otto', role: 'Otto Brandt, empleado nocturno del Depósito 9 de 1946 a 1964, cuando bajó en el montacargas. En el canal nueve.' },
      ingrid: { name: 'Ingrid', pos: 'de Ingrid', role: 'Ingrid Lind, la abuela de las niñas, «la abuela». Nacida en Gammel Ostra. Murió en 1996.' },
      clerk: { name: 'La Empleada Nocturna', pos: 'de la Empleada Nocturna', role: 'Lleva el Índice en el fondo del Debajo. Firma sus notas «A.»' },
    },
    speakers: { ada: 'ADA', otto: 'OTTO', radio: 'RADIO', lyle: 'LYLE HARDY', clerk: 'LA EMPLEADA', wren: 'WREN', voice: '???' },
    items: {},
    obj: {},
    memento: {},
    freed: {},
    shrine: {},
    ghostHelp: {},
    mono: {
      hide: 'Contén la respiración.',
      hideLocker: 'Contén la respiración. No te muevas.',
      fearHigh: 'No puedo respirar...',
      lowBattery: 'La pila se está muriendo.',
      eaterFlicker: 'Las luces se apagan. Está cerca. Lo oigo masticar.',
      watcherSeen: 'Algo alto al fondo, completamente quieto.',
    },
    // [lo que dice la pantalla, qué hacer distinto]
    deaths: {
      eater: ['DEVORADA', 'El Devorador es rápido en línea recta y lento en las curvas. Una luz perdida recién cogida en la mano lo hace retroceder unos segundos.'],
      sorter: ['CLASIFICADA', 'Lo que ordena el archivo a oscuras sigue con su trabajo. No te pongas entre eso y las estanterías.'],
      wallpaperMan: ['EMPAPELADA', 'Los hombres planos solo salen de la pared a tu espalda. Pasa junto a ellos mirándolos.'],
      hummer: ['ZUMBADA', 'Donde el zumbido crece y las luces parpadean, algo escucha. Camina despacio y aléjate de los sitios ruidosos.'],
      drowned: ['ARRASTRADA AL FONDO', 'Los Ahogados esperan bajo el agua y te oyen dentro de ella. No te metas en el agua, y nunca te quedes quieta en ella.'],
      passenger: ['LLEVADA A SU ASIENTO', 'Los pasajeros despiertan cuando una luz se posa sobre ellos. Aparta la linterna de sus caras y no los roces.'],
      bellman: ['TAÑIDA', 'En la cubierta abierta, el Campanero te oye. Cuando la campana empieza a sonar, está cazando: ponte a cubierto y agáchate.'],
      pines: ['LLEVADA ENTRE LOS ÁRBOLES', 'Los pinos solo se mueven mientras tú te mueves. Cerca de ellos, quédate quieta y deja que pierdan el interés.'],
      stag: ['ARROLLADA', 'El ciervo embiste en línea recta. Pon un árbol o un coche entre los dos y se aturdirá solo.'],
      usher: ['ACOMPAÑADA A SU BUTACA', 'Un acomodador solo ve por su haz rojo. Quédate fuera de la luz y nunca cruces por delante.'],
      burrower: ['ARRASTRADA BAJO TIERRA', 'Los excavadores notan tus pasos a través de la tierra. En los suelos de tierra agáchate; sobre raíles y tablones estás a salvo.'],
      lamplighter: ['LÁMPARA EN LOS OJOS', 'Los portalámparas van hacia cualquier luz. Apaga la tuya y deja que pasen de largo.'],
      crawler: ['CAÍDA DESDE ARRIBA', 'Los reptadores de las vigas esperan en el entibado del techo. Mira arriba antes de pasar por debajo y mantente agachada.'],
      frozen: ['CONGELADA', 'Los huéspedes congelados solo se mueven cerca del calor. Caliéntate y aléjate del fuego antes de que se levanten.'],
      cold: ['CONGELADA', 'Fuera, el frío entra rápido. Ve de refugio en refugio y caliéntate junto a un fuego.'],
      whiteout: ['TRAGADA POR LA NIEVE', 'En la tormenta solo ves sus huellas. Te oye: camina, no corras, y no te alejes del refugio.'],
      cook: ['ENGANCHADA', 'El Cocinero nunca sale de la cocina. Espera a que te dé la espalda al fondo y entonces pasa.'],
      silted: ['ARRASTRADA AL BARRO', 'Si te quedas quieta en el barro demasiado tiempo, uno de ellos se alza a tu lado. Sigue moviéndote.'],
      longone: ['LLEVADA AL RÍO', 'Los Largos esperan en los pozos, las zanjas y el río. Agáchate al pasar junto al agua.'],
      choir: ['SENTADA EN LOS BANCOS', 'Mientras el coro canta no ve nada. Camina en silencio detrás de ellos; nunca corras, nunca pases por delante.'],
      water: ['AHOGADA', 'El agua sube cada vez más deprisa. Busca un lugar alto y trepa.'],
      conductor: ['BAJADA DEL TREN', 'Sin billete válido, el Revisor te baja del tren. Cuando su farol baje por el pasillo, apaga la linterna y métete bajo una litera.'],
      sleeper: ['ARRASTRADA A UNA LITERA', 'Los durmientes no ven. Un paso delante de su compartimento los despierta: pasa agachada y quédate quieta cuando uno esté levantado.'],
      underhand: ['ARRASTRADA ENTRE LOS VAGONES', 'Nunca te pares en un fuelle. Cruza deprisa y abre la puerta siguiente antes de pisar las chapas.'],
      mask: ['CARAS', 'Las máscaras solo se mueven cuando nadie las mira. Tenlas delante y retrocede.'],
      horse: ['PISOTEADA', 'Los caballos solo corren mientras suena el órgano. Cuando la música para, ellos también: entonces te mueves tú.'],
      lotte: ['LEVANTADA', 'Lotte no ve. Oye, y nunca deja de reír: aléjate de la risa y no hagas ruido.'],
      hush: ['SILENCIADA', 'Cerca del Silencio, todo sonido se apaga. Cuando ya no te oyes a ti misma, está muy cerca. Aléjate, despacio.'],
      underice: ['BAJO EL HIELO', 'Nunca corras sobre el hielo oscuro encima del viejo río. Camina, y lo que hay debajo se queda debajo.'],
    },
    tips: [
      'Correr hace ruido. Andar agachada es casi silencioso.',
      'En el fondo de cada estantería hay una mentira. Encuentra la cosa perdida y devuélvela a su sitio, y el lugar te deja ir.',
      'La mayoría oye mejor de lo que ve. Apaga la linterna cuando algo esté cerca.',
      'Puedes esconderte bajo camas, literas y escritorios. Si nada te vio entrar, nada vendrá a mirar.',
      'Mantén Mayús mientras estás escondida para contener la respiración. Si te quedas sin aire, jadearás.',
      'Mantén V para mirar por encima del hombro mientras corres.',
      'Léelo todo. Quienes escribieron esas cosas te están diciendo cómo salir.',
      'Wren dejó ocho dibujos, uno en casi cada estantería. Algunos están bien escondidos.',
      'Otto habla por el canal nueve cuando tiene algo que decirte. Suele tener razón.',
      'M abre un mapa de los lugares por los que has pasado.',
    ],
    photoLabels: {},
    credits: [
      ['LEVEL 256', 'una historia de terror en primera persona, en nueve estanterías'],
      ['Para', 'todos aquellos a quienes les dijeron que no fue culpa de nadie'],
      ['Lugares', 'Halvard, el lago Ostra y el Debajo son inventados; también todos los que aparecen en ellos'],
      ['Sonido', 'sintetizado en directo: ni una sola grabación'],
      ['Imágenes y modelos', 'procedurales: ni un solo archivo de imagen'],
      ['El Depósito 9', 'abre todas las noches. Pregunte en el mostrador.'],
    ],
    // Pintadas en las paredes del Debajo
    scrawl: {
      yellow: ['¿QUIÉN VOLVIÓ A BUSCARLO?', 'SIEMPRE SON LAS 02:56', 'RECLAMACIÓN 256', 'NO PUEDES SALTARTE UNA ESTANTERÍA', 'BUSCA LA MENTIRA', 'NADIE PREGUNTÓ', 'ARCHIVADO EN: OLVIDADO'],
      dark: ['DEJA LA LUZ ENCENDIDA', 'SE COME LO QUE DEJASTE DE BUSCAR', '¿ADA?'],
      concrete: ['RESERVADO PARA: ADA LIND', '256', 'SIN RECLAMAR'],
    },
  });
})(typeof window !== 'undefined' ? window : globalThis);
