/* Núcleo de la historia en español: personajes, frases comunes, muertes, consejos, finales, créditos. */
(function (root) {
  'use strict';
  root.PB.I18N.register('es', 'story', {
    chars: {
      sam: { name: 'Sam', pos: 'de Sam', role: 'Conduce de noche para Tri-County Movers, 20 años. Tenía 13 en 1987 y era el quinto miembro de la pandilla. Tú.' },
      walt: { name: 'Walt', pos: 'de Walt', role: 'Dueño del salón recreativo Starlight. Técnico de radar en la Fuerza Aérea, luego reparador de televisores. Desaparecido desde marzo de 1992.' },
      lily: { name: 'Lily', pos: 'de Lily', role: 'La hija de Walt. Murió en octubre de 1983, con nueve años. Puntuación: 3.190.' },
      danny: { name: 'Danny', pos: 'de Danny', role: '16 años en 1987. Ruidoso, sin miedo, siempre primero en la tabla de récords. Tenía la llave de repuesto de Walt.' },
      rosie: { name: 'Rosie', pos: 'de Rosie', role: '15 años en 1987. La que lo planeaba todo. Quería tener su propio programa de radio.' },
      nell: { name: 'Nell', pos: 'de Nell', role: '15 años en 1987. Callada, dibujaba cómics, gafas gruesas. Nunca se perdonó una tarde en la piscina.' },
      toby: { name: 'Toby', pos: 'de Toby', role: '13 años en 1987. El mejor amigo de Sam. Le daba miedo la oscuridad.' },
      eddie: { name: 'Eddie', pos: 'de Eddie', role: 'Ayudante de Walt de 1984 a 1988. Entró a buscarlos en junio de 1993. Tiene una hija a la que nunca ha tenido en brazos.' },
      nora: { name: 'Nora', pos: 'de Nora', role: 'La hermana pequeña de Walt.' },
      frank: { name: 'Frank Dobbs', pos: 'de Dobbs', role: 'Inspector de la policía de Harlow, 1987.' },
      june: { name: 'June', pos: 'de June', role: 'La mujer de Eddie. Recepcionista de noche en el Blue Moon Motor Inn.' },
      theo: { name: 'Theo', pos: 'de Theo', role: 'El hermano pequeño de Nell.' },
      maggie: { name: 'Maggie', pos: 'de Maggie', role: 'La madre de Toby.' },
      ruth: { name: 'Ruth', pos: 'de Ruth', role: 'La mujer de Walt hasta 1985.' },
      ray: { name: 'Ray', pos: 'de Ray', role: 'El padre de Danny.' },
      carol: { name: 'Carol', pos: 'de Carol', role: 'La madre de Rosie.' },
      ann: { name: 'Ann', pos: 'de Ann', role: 'La madre de Sam.' },
    },
    speakers: { sam: 'SAM', eddie: 'EDDIE', walt: 'WALT', danny: 'DANNY', rosie: 'ROSIE', nell: 'NELL', toby: 'TOBY', lily: 'LILY', june: 'JUNE', radio: 'RADIO', voice: '???' },
    items: {},
    obj: {
      ghost: 'Lleva el objeto {pos} a su altar (opcional)',
    },
    recap: {
      prolog: 'El salón recreativo Starlight, la noche antes de la subasta. La máquina n.º 7 funcionaba sin estar enchufada, y sabía mi nombre. PLAYER 1: SAM — CONTINUE?',
      lobby: 'Salas amarillas que no terminan nunca: el juego esperando a un jugador. Algo redondo y pálido come allí en la oscuridad. Eddie está vivo, al otro lado del walkie-talkie, dentro desde 1993.',
      mill: 'El almacén del padre de Danny. Danny me persiguió gritando «¡Te soltaste!». Le devolví el reloj de su padre, se detuvo y recordó su nombre.',
      pipes: 'Los túneles de desagüe. Nuestro fuerte. Regla número cuatro: nadie vuelve a casa sin compañía. Esa regla la escribí yo.',
      pool: 'La piscina donde Theo casi se ahoga mientras Nell terminaba un dibujo. Lleva años esperando que la perdonen. Theo la perdonó en su primerísima carta.',
      office: 'La oficina de la madre de Rosie, ciento siete punto tres. En su cinta, a las 0:40, alguien llama a la puerta trasera del salón. Rosie: «Mira quién vuelve arrastrándose».',
      school: '16 de abril de 1987. El pacto: las cinco manos en el mando, nadie se suelta. Cinco iniciales abajo. La última es la mía.',
      dark: 'La oscuridad, tres generadores y un mechero de latón. La última página de Toby dice que Sam volvió. Yo no recordaba haber vuelto.',
      mall: 'El mejor sábado de 1986: cinco críos en un fotomatón, y uno de ellos soy yo, riéndome. Los maniquíes solo se movían cuando yo apartaba la vista.',
      motel: 'El recuerdo de Eddie, no el mío. La habitación 12 y su libreta: UNO ENTRA, UNO SALE. Necesita a alguien que se quede en su lugar. Quería que fuera yo.',
      hospital: 'St. Agnes, octubre de 1983. Lily le pidió a su padre un juego que no se acabara nunca, para que nadie tuviera que irse. Walt lo construyó.',
      maple: 'Mi calle. La voz de mi madre en el contestador a las 2:50 de la madrugada, preguntando dónde estoy. No volví a casa a las 21:40.',
      workshop: 'El sótano de Walt y la cinta de las 3:17. Cinco manos en el mando, y una se soltó. La mía.',
      maze: 'El nivel 255, la casa en sí. Los Espectros que recuerdan caminan a mi lado como luces de colores.',
      killscreen: 'El nivel 256. El lado roto. Un enchufe que necesita cinco manos, y una puerta que deja salir a uno.',
    },
    memento: {
      danny: { name: 'El reloj de Danny', line: 'Un reloj de acero con el cristal rajado, parado a las 3:17. Grabado en el dorso: «RAY KOWALSKI — 25 AÑOS — HARLOW MILL».' },
      rosie: { name: 'La cinta de Rosie', line: 'Un walkman violeta con una cinta dentro. La etiqueta dice CARA B: PARA DESPUÉS. La cara B está vacía.' },
      nell: { name: 'Las gafas de Nell', line: 'Unas gafas pesadas, con un cristal rajado. Se empañan en tu mano, como si alguien acabara de echarles el aliento.' },
      toby: { name: 'El mechero de Toby', line: 'Un viejo mechero de latón. Grabado: «TOBY — PARA QUE NUNCA ESTÉS A OSCURAS. EL ABUELO».' },
    },
    freed: {
      danny: ['DANNY: «Las 3:17. Mi reloj se paró. Yo no».', 'DANNY: «…Has vuelto. Ya era hora, Keller. Vete. Yo entretengo al grandullón».'],
      rosie: ['ROSIE: «La cara B. Íbamos a grabarla después. Después de ganar».', 'ROSIE: «Siempre corría por delante de todos. Ahora caminaré a tu lado».'],
      nell: ['NELL: «Mis gafas. Todo está tan… nítido».', 'NELL: «Ya no espero a estar segura. Voy contigo».'],
      toby: ['TOBY: «El mechero del abuelo…» (La llama prende. Por primera vez le ves la cara: un chaval de trece años, con pecas).', 'TOBY: «…No me mires todavía, Sam. Tú camina. Voy justo detrás de ti».'],
    },
    shrine: {
      quiet: 'El altar está en silencio. La vela sigue ardiendo.',
      missing: 'Un pequeño altar. Una foto enmarcada de {name} y un hueco vacío donde debería haber algo.',
    },
    mono: {
      watcherSeen: 'A lo lejos hay algo alto y negro, de pie. Tiene la cabeza ladeada. Está contando.',
      hide: 'Contén la respiración.',
      hideLocker: 'Contén la respiración. No te muevas.',
      fearHigh: 'No puedo respirar…',
      lowBattery: 'La pila se está muriendo.',
      freed: '{name} ya no me persigue.',
      eaterFlicker: 'Las luces bajan. Está cerca. Lo oigo masticar.',
    },
    ghostHelp: {
      danny: 'DANNY: «¡Corre! ¡Lo tengo!»',
      amberWatch: 'TOBY: «No me mires… por favor, no me mires…»',
    },
    deaths: {
      eater: ['FESTÍN', 'El Devorador es más rápido que tú en línea recta y lento en las curvas. Toma las esquinas y atiende al ruido de masticar.'],
      red: ['CAPTURA', 'Danny nunca se detiene y nunca abandona una persecución. Rompe su línea de visión y pon una esquina de por medio.'],
      violet: ['SIN SALIDA', 'Rosie va hacia donde tú vas, no hacia donde estás. Cambia de dirección cuando desaparezca.'],
      teal: ['BAJO EL AGUA', 'Nell oye el agua. No pises los charcos y camina por los bordes.'],
      amber: ['INMÓVIL', 'Toby no puede moverse mientras lo miras. No le quites los ojos, ni la luz, de encima.'],
      grinner: ['SONRIÓ', 'Los Sonrientes se derriten con la luz. Mantén la linterna sobre ellos o suelta una barra luminosa.'],
      watcher: ['LA CUENTA', 'El Contador solo se mueve cuando no lo miras. No le des la espalda mucho tiempo.'],
      crawler: ['AL FONDO', 'Los Reptantes retroceden ante la luz y luego te rodean. Mantén la espalda contra la pared y no retengas a uno demasiado tiempo en el haz.'],
      monitor: ['SIN PASE', 'El Celador solo ve lo que toca su linterna. Métete en una taquilla antes de que el haz te encuentre.'],
      mannequin: ['LA POSE', 'Los maniquíes solo se mueven cuando nadie mira. Camina hacia atrás si hace falta.'],
      neighbor: ['PUERTA ABIERTA', 'El Vecino se acerca cuando le das la espalda. Tu linterna lo hace retroceder. Nunca contestes a la voz.'],
      chompy: ['GRAN ABRAZO', 'Chompy es lento, pero nunca se detiene. Enfócale los ojos con la luz y se tapará la cara.'],
    },
    tips: [
      'El Devorador es más rápido que tú en un pasillo recto, pero lento en las curvas. Toma las esquinas.',
      'Correr hace ruido. Caminar agachado es casi silencioso, y agachado abres las puertas sin hacer ruido.',
      'Si las luces bajan y parpadean, el Devorador está cerca.',
      'Un farolillo hace que todo huya de ti durante unos segundos.',
      'Las grabadoras guardan la partida y reproducen un recuerdo.',
      'Puedes esconderte bajo escritorios, camas y mostradores, y en taquillas. Si nada te ve entrar, nada te buscará.',
      'Lleva a cada Espectro su objeto a su altar y dejará de cazarte. El final depende de ello.',
      'Un Star Pop calma los nervios y te devuelve el aliento.',
      'M abre un mapa de los lugares que has explorado.',
      'La linterna se come las pilas. Las barras luminosas (G) iluminan un rincón, y su tintineo aleja a los cazadores.',
      'Sigue mirando al de color ámbar. Pero no demasiado tiempo.',
      'Lily dejó ocho dibujos. Algunos están muy bien escondidos.',
      'Eddie conoce este sitio mejor que nadie. Eso no significa que te lo cuente todo.',
      'Las taquillas te ocultan por completo. Si algo se acerca, mantén Mayús para contener la respiración.',
      'Los maniquíes no pueden moverse mientras los miras.',
      'El Vecino usa voces que conoces. No contestes.',
      'Walt arrancó cinco páginas de su diario. Importan más de lo que parece.',
      'Un cajón abierto un dedo tiene algo dentro. Y una caja fuerte con la puerta sin encajar, también.',
      'Mantén V (o el botón central del ratón) para mirar por encima del hombro mientras corres.',
      'Cuanto más dura el silencio, más se acercan. Al juego no le gusta esperar.',
    ],
    endings: {
      exit: {
        title: 'SALIDA', subtitle: 'Final malo — Otra vez',
        lines: [
          'Cruzas la puerta. Detrás, Eddie grita tu nombre, y luego la puerta se cierra y los gritos se quedan al otro lado.',
          'Aire frío. Lluvia. Abres los ojos sobre la moqueta mojada del salón. Es de día. Las persianas están a medio subir.',
          'La máquina n.º 7 sigue encendida. En la pantalla de demostración, ahora flotan cinco Espectros por la casa. El quinto lleva una chaqueta de trabajo.',
          'Los de la mudanza la cargan a mediodía. El conductor contará después que oyó a alguien golpear desde dentro de la máquina durante toda la Ruta 9.',
          'El camión nunca llega a la subasta.',
          'Te habías jurado no volver a abandonarlos nunca. La segunda vez fue más fácil. Eso es lo peor.',
        ],
      },
      deal: {
        title: 'EL TRATO', subtitle: 'Final oscuro — Uno entra, uno sale',
        lines: [
          'Sujetas la puerta. Eddie te mira durante un largo segundo. «Se lo contaré. Les contaré a todos quién eras».',
          'Cruza. La puerta se cierra despacio, como el final de una cinta.',
          'En algún lugar de Harlow, al amanecer, un hombre empapado entra en una cocina, y una niña de un año lo mira fijamente desde su trona.',
          'La casa está en silencio. A lo lejos, algo redondo vuelve a masticar.',
          'No eres el Jugador. No eres un Espectro. Eres la persona que se quedó. Las estrellas brillan. Sabes dónde está cada una.',
          'En la tabla de récords de un salón vacío, con una letra que nadie sabe explicar, aparece una línea nueva: SAM — SIGUE JUGANDO.',
        ],
      },
      plug: {
        title: 'GAME OVER', subtitle: 'Final bueno — Nadie se suelta',
        lines: [
          'Cuatro luces de colores se cierran sobre tus manos. Rojo, violeta, turquesa, ámbar. Cinco manos, como decía el pacto.',
          'Tiras. El enchufe sale. Por primera vez desde 1987, el zumbido se detiene.',
          'En la oscuridad, muy cerca, una voz humana y cansada: «Ya estoy lleno, Sam. Por fin».',
          'Te despiertas sobre la moqueta del salón. El amanecer entra por el cristal.',
          'Cuatro críos con chaquetas de 1987 están sentados en el suelo, parpadeando. Toby te mira durante mucho rato. «¿Sam? …Te has hecho mayor». Luego te abraza tan fuerte que duele.',
          'En Maple Street se apaga la luz de un porche que llevaba siete años encendida.',
          'Eddie vuelve a casa por las calles vacías. No corre. Quiere recordar el camino.',
          'La máquina n.º 7 está apagada. Una línea queda grabada en el cristal: GAME OVER — 5 PLAYERS.',
        ],
      },
      lil: {
        title: 'LIL', subtitle: 'Final verdadero — Los nombres de la tabla',
        lines: [
          'Colocas ocho dibujos sobre el núcleo. Cera sobre papel: el salón, un Chompy naranja con cuernos, la ventana de un hospital, un papá.',
          'El Devorador deja de masticar. Hay silencio durante mucho rato. Luego, con una voz que recuerdas de 1985: «…Esos los dibujó Lily».',
          'Walt está donde estaba el Devorador, flaco y gris y siendo él mismo. «Baja las manos. De este enchufe tiro yo. Siempre me tocó a mí».',
          'Cuatro luces de colores se cierran sobre sus manos. Tira. La casa se pliega como el papel.',
          'Lo último que ves es a una niña pequeña con camisón de hospital que le da la mano, y a los dos caminando hacia la oscuridad entre las estrellas.',
          'Amanecer. Cuatro críos sobre la moqueta del salón. Eddie en la cabina de fuera, riendo y llorando a la vez. «¿June? June, soy yo».',
          'Una semana después, Nora abre el salón por última vez y encuentra la tabla de récords reescrita con una letra que conoce. 1 LIL. 2 DAN. 3 ROS. 4 NEL. 5 TOB. 6 SAM. 7 WALT.',
          'La luz del porche de Toby se apaga. En Maple Street, dos personas que ya no son niños se sientan en el bordillo y hablan hasta el mediodía. Sam se lo cuenta todo. Él ya lo sabía.',
        ],
      },
    },
    scrawl: {
      yellow: ['¿QUIÉN SE FUE A CASA?', 'SIEMPRE SON LAS 3:17', 'NO TE SUELTES', 'CINCO MANOS', 'LO OIGO MASTICAR', 'CUENTA LAS PUERTAS'],
      dark: ['NO APAGUES LA LUZ', '¿SAM?', 'SONRÍE CUANDO PARPADEAS', 'NO TENGO MIEDO'],
      office: ['DÓNDE SE FUERON TODOS', '107.3', 'CARA B'],
      hospital: ['SILENCIO POR FAVOR', 'DIBUJABA EN TODO', '207'],
      motel: ['UNO ENTRA UNO SALE', 'NO CONTESTES', '3:17'],
      school: ['NADIE SE SUELTA', 'D R N T S', 'SAM ESTUVO AQUÍ'],
      concrete: ['TE SOLTASTE', 'DAN #1', '3:17'],
      pool: ['UN SEGUNDO', 'YO ESTABA MIRANDO'],
      mall: ['AMIGOS PARA SIEMPRE', 'AUNQUE'],
      tunnel: ['NADIE VUELVE A CASA SIN COMPAÑÍA', 'D+T+S'],
      workshop: ['NO LO DESENCHUFES', '2 5 6'],
    },
    photoLabels: { fort: 'EL FUERTE. DÍA DE LA INAUGURACIÓN.', chompy: 'LIL & CHOMPY' },
    credits: [
      ['LEVEL 256', 'El salón recreativo Starlight'],
      ['Un juego de terror en primera persona', ''],
      ['Dedicado a', 'todos los que alguna vez soltaron algo y volvieron a por ello'],
      ['Hungry House', 'un juego arcade ficticio de 1981, creado para esta historia'],
      ['Sonido', 'sintetizado en directo, ni una sola grabación'],
      ['Texturas y modelos', 'procedurales, ni un solo archivo de imagen'],
      ['A los jugadores', 'nunca metáis una ficha en la máquina n.º 7 después de medianoche'],
    ],
  });
})(typeof window !== 'undefined' ? window : globalThis);
