/* Interfaz en español. */
(function (root) {
  'use strict';
  root.PB.I18N.register('es', 'ui', {
    'game.title': 'LEVEL 256',
    'game.subtitle': 'EL SALÓN RECREATIVO STARLIGHT',
    'game.aria': 'Vista del juego',
    'noscript': 'Este juego necesita JavaScript.',

    'boot.tip': 'CONSEJO',
    'boot.init': 'Iniciando…',
    'boot.fonts': 'Cargando fuentes…',
    'boot.sounds': 'Grabando sonidos…',
    'boot.voices': 'Grabando voces…',
    'boot.prep': 'Preparando el nivel…',
    'boot.noThree': 'No se pudo cargar el motor 3D (three.js). Comprueba tu conexión a Internet y recarga la página.',
    'boot.error': 'Error al iniciar: {msg}',
    'boot.noWebgl': 'La tarjeta gráfica no pudo iniciar el 3D (WebGL 2). Actualiza el controlador gráfico y vuelve a abrir el juego.',
    'load.textures': 'Tejiendo texturas… ({n}/{m})',
    'load.walls': 'Levantando paredes…',
    'load.bake': 'Horneando la luz…',
    'load.fixtures': 'Colgando los fluorescentes…',
    'load.props': 'Colocando los muebles…',
    'load.decals': 'Manchas y arañazos…',
    'load.shaders': 'Compilando shaders…',
    'load.ready': 'Listo',
    'load.error': 'Error de carga: {msg}',

    'first.title': 'Antes de empezar',
    'first.lang': 'Idioma',
    'first.bright': 'Ajusta el brillo hasta que el símbolo de la izquierda apenas se vea y el de la derecha se vea con claridad.',
    'first.phones': 'Mejor con auriculares, en una habitación a oscuras.',
    'first.go': 'Continuar',

    'menu.continue': 'Continuar',
    'menu.new': 'Nueva partida',
    'menu.levels': 'Capítulos',
    'menu.settings': 'Ajustes',
    'menu.archive': 'Archivo',
    'menu.help': 'Cómo jugar',
    'menu.quit': 'Salir del juego',
    'menu.credit': 'Harlow · 30 de noviembre de 1994 · 2:11',
    'menu.foot': 'Juega con auriculares, a oscuras.',
    'menu.footDone': 'Finales: {list} · muertes {deaths}',

    'confirm.title': '¿Nueva partida?',
    'confirm.body': 'Se sobrescribirá tu progreso guardado. Los documentos encontrados se quedan en el archivo.',
    'confirm.yes': 'Sí, empezar de nuevo',
    'confirm.no': 'Cancelar',

    'diff.title': 'Dificultad',
    'diff.easy': 'Fácil',
    'diff.easyDesc': 'Para disfrutar de la historia. Las criaturas son más lentas y menos atentas. Una vez por capítulo te zafas de un agarre.',
    'diff.normal': 'Normal',
    'diff.normalDesc': 'Tal como se diseñó. Un solo agarre te devuelve a tu último guardado.',
    'diff.nightmare': 'Pesadilla',
    'diff.nightmareDesc': 'Criaturas más rápidas y con mejor oído. Las pilas se agotan pronto. El miedo llega antes.',
    'diff.time': 'Duración estimada: de 4 a 6 horas si lees cada documento y liberas a los cuatro Espectros.',

    'levels.title': 'Capítulos',
    'levels.locked': 'Bloqueado',

    'common.back': 'Volver',
    'common.on': 'Sí',
    'common.off': 'No',

    'settings.title': 'Ajustes',
    'settings.reset': 'Predeterminado',
    'settings.reloadNote': 'Los ajustes marcados con * se aplican la próxima vez que se cargue un capítulo.',
    'tab.screen': 'Pantalla',
    'set.displayMode': 'Modo de pantalla',
    'set.displayMode.help': 'La pantalla completa oculta el navegador. Esc o F11 para salir; Alt+Intro la alterna durante el juego.',
    'opt.windowed': 'Ventana',
    'opt.fullscreen': 'Pantalla completa',
    'set.resolution': 'Resolución',
    'set.resolution.help': 'El tamaño de la imagen renderizada. Nativa usa tu pantalla; cualquier otro tamaño se adapta a la ventana según el modo de escalado de abajo.',
    'opt.native': 'Nativa (pantalla)',
    'set.scaleMode': 'Modo de escalado',
    'set.scaleMode.help': 'Cómo se muestra una resolución con proporciones distintas a las de la ventana.',
    'opt.fit': 'Ajustar (proporción, franjas negras)',
    'opt.stretch': 'Estirar',
    'opt.fill': 'Rellenar (recortar bordes)',
    'set.upscale': 'Filtro de escalado',
    'set.upscale.help': 'Suave mezcla los píxeles al escalar; Píxel los mantiene nítidos y cuadrados (aspecto retro a baja resolución).',
    'opt.smooth': 'Suave',
    'opt.pixel': 'Píxel',
    'set.sharpen': 'Nitidez',
    'set.sharpen.help': 'Enfoque adaptativo al contraste de la imagen final. Ayuda por debajo de la resolución nativa y con el antialiasing.',
    'set.fpsLimit': 'Límite de fotogramas',
    'set.fpsLimit.help': 'Limita los fotogramas por segundo. Un límite bajo mantiene fresca la tarjeta gráfica y el ritmo de imagen estable.',
    'opt.unlimited': 'Sin límite',
    'set.vsync': 'Sincronización vertical',
    'set.vsync.help': 'Activada: los fotogramas siguen la frecuencia del monitor, sin cortes. Desactivada: el juego dibuja tan rápido como puede, hasta el límite de fotogramas. En un navegador, el propio navegador siempre espera al monitor, así que Desactivada solo quita la espera del juego; la versión de escritorio desactiva la sincronización por completo (tras reiniciar).',
    'tab.graphics': 'Gráficos',
    'tab.display': 'Imagen',
    'tab.audio': 'Audio',
    'tab.controls': 'Controles',
    'tab.gameplay': 'Juego',
    'preset.low': 'Bajo',
    'preset.medium': 'Medio',
    'preset.high': 'Alto',
    'preset.ultra': 'Ultra',
    'preset.extreme': 'Extremo',
    'preset.custom': 'Personalizado',
    'opt.off': 'Desactivado',
    'opt.low': 'Bajo',
    'opt.medium': 'Medio',
    'opt.high': 'Alto',
    'opt.ultra': 'Ultra',
    'opt.extreme': 'Extremo',
    'opt.shadow1': 'Bajo (1024)',
    'opt.shadow2': 'Alto (2048)',
    'opt.shadow3': 'Ultra (4096)',
    'opt.small': 'Pequeño',
    'opt.large': 'Grande',
    'opt.full': 'Completo',
    'opt.reduced': 'Reducido',

    'set.preset': 'Preajuste de calidad',
    'set.preset.help': 'Cambia de una vez todos los ajustes gráficos de abajo. Extremo está pensado para tarjetas gráficas de gama alta; Ultra+ va más allá (sombras de 8192, la iluminación precalculada más densa, los modelos más finos, profundidad de campo) y es para los PC más potentes.',
    'set.renderScale': 'Escala de resolución',
    'set.renderScale.help': 'Por encima del 100 % se renderiza a mayor resolución y se reduce: imagen más nítida, carga mucho mayor para la tarjeta gráfica.',
    'set.textureRes': 'Resolución de texturas',
    'set.shadows': 'Sombras',
    'set.antialias': 'Antialiasing',
    'set.lightmapRes': 'Calidad de la iluminación precalculada',
    'set.lightmapRes.help': 'Detalle de la luz suave precalculada y de sus sombras.',
    'set.dynLights': 'Luces dinámicas',
    'set.bloom': 'Resplandor (bloom)',
    'set.bloomStrength': 'Intensidad del resplandor',
    'set.volumetric': 'Luz volumétrica y polvo',
    'set.ao': 'Oclusión ambiental (SSAO)',
    'set.ao.help': 'Sombras de contacto suaves en rincones, bajo los muebles y entre baldosas.',
    'set.ssr': 'Reflejos en espacio de pantalla',
    'set.ssr.help': 'Reflejos reales en suelos mojados, azulejos, cristal y metal pulido.',
    'set.volumetric.help': 'Haces de luz, el cono de la linterna y polvo flotante calculados por trazado de rayos. Muy exigente en Extremo.',
    'set.motionBlur': 'Desenfoque de movimiento',
    'set.lensDirt': 'Suciedad en la lente',
    'set.lensDirt.help': 'Manchas en la lente de la cámara que atrapan la luz intensa.',
    'set.particles': 'Densidad de partículas',
    'set.viewDist': 'Distancia de visión',
    'set.anisotropy': 'Filtrado anisotrópico',
    'set.brightness': 'Brillo',
    'set.brightness.help': 'Ajústalo para que los rincones más oscuros apenas se vean.',
    'set.contrast': 'Contraste',
    'set.saturation': 'Saturación del color',
    'set.fov': 'Campo de visión',
    'set.headBob': 'Balanceo de la cabeza',
    'set.shake': 'Temblor de cámara',
    'set.grain': 'Grano de película',
    'set.chromatic': 'Aberración cromática',
    'set.vignette': 'Viñeta',
    'set.vhs': 'Aspecto de videocámara (VHS)',
    'set.vhs.help': 'Muestra el juego como a través del visor de una videocámara de 1994.',
    'set.reduceFlicker': 'Reducir parpadeos',
    'set.reduceFlicker.help': 'Suaviza las luces que parpadean y los destellos de pantalla para jugadores sensibles a la luz.',
    'set.crosshair': 'Punto de mira',
    'set.subtitles': 'Subtítulos',
    'set.captions': 'Subtítulos de sonidos',
    'set.captions.help': 'Muestra los sonidos importantes como texto, por ejemplo [masticar a lo lejos].',
    'set.subtitleSize': 'Tamaño de los subtítulos',
    'set.master': 'Volumen general',
    'set.music': 'Música',
    'set.sfx': 'Efectos',
    'set.ambience': 'Ambiente (zumbido, goteo, lluvia)',
    'set.entities': 'Sonidos de criaturas',
    'set.voice': 'Voces y radio',
    'set.hrtf': 'Audio 3D (HRTF, se recomiendan auriculares)',
    'set.mouseSens': 'Sensibilidad del ratón',
    'set.invertY': 'Invertir eje vertical',
    'set.touchSens': 'Sensibilidad táctil',
    'set.padSens': 'Sensibilidad del mando',
    'set.toggleCrouch': 'Agacharse: pulsar en vez de mantener',
    'set.toggleSprint': 'Correr: pulsar en vez de mantener',
    'set.lang': 'Idioma',
    'set.difficulty': 'Dificultad',
    'set.difficulty.help': 'Afecta a la velocidad y al oído de las criaturas y a la pila de la linterna.',
    'set.jumpscare': 'Sustos repentinos',
    'set.hints': 'Pistas',

    'archive.title': 'Archivo',
    'archive.count': '{n} / {m} documentos',
    'archive.notFound': 'Aún no encontrado',
    'kind.note': 'Nota',
    'kind.letter': 'Carta',
    'kind.diary': 'Página de diario',
    'kind.tape': 'Grabación',
    'kind.photo': 'Fotografía',
    'kind.screen': 'Pantalla de ordenador',
    'kind.phone': 'Mensaje telefónico',
    'kind.printout': 'Listado impreso',
    'kind.wall': 'Escrito en la pared',
    'kind.notice': 'Aviso',
    'kind.memory': 'Recuerdo',
    'kind.drawing': 'Dibujo',
    'kind.card': 'Tarjeta',
    'kind.report': 'Informe',
    'kind.flyer': 'Folleto',
    'kind.doc': 'Documento',

    'help.title': 'Cómo jugar',
    'help.kbm': 'Teclado y ratón',
    'help.walk': 'Caminar',
    'help.mouse': 'Ratón',
    'help.look': 'Mirar alrededor (haz clic para fijar el cursor)',
    'help.sprint': 'Correr (ruidoso, gasta aliento)',
    'help.crouch': 'Agacharse (casi silencioso)',
    'help.interact': 'Interactuar, leer, coger, esconderse',
    'help.flash': 'Linterna',
    'help.drink': 'Beber un Star Pop',
    'help.throw': 'Lanzar una barra luminosa',
    'help.lean': 'Asomarse a izquierda / derecha (mirar tras las esquinas)',
    'help.map': 'Mapa',
    'help.bag': 'Objetos / diario',
    'bag.items': 'OBJETOS',
    'bag.journal': 'DIARIO',
    'bag.close': 'Cerrar (I / J)',
    'bag.empty': 'Tienes los bolsillos vacíos.',
    'bag.inspectHint': 'Arrastra para darle la vuelta.',
    'bag.now': 'AHORA MISMO',
    'bag.story': 'LA HISTORIA HASTA AHORA',
    'bag.docs': 'ENCONTRADO AQUÍ',
    'bag.noDocs': 'Aún no has encontrado nada aquí. Mira con más atención.',
    'bag.people': 'PERSONAS',
    'bag.freed': 'en paz',
    'bag.hunting': 'aún caza',
    'bag.stats': 'Documentos {a} / {b}   ·   Dibujos de Lily {c} / {d}',
    'bag.n.flashlight': 'Linterna',
    'bag.d.flashlight': 'Una pesada linterna de acero de la furgoneta del salón. Pila: {n} %. Se debilita antes de apagarse.',
    'bag.n.battery': 'Pilas de repuesto',
    'bag.d.battery': 'Pilas grandes para la linterna. R las cambia; una linterna agotada las recibe automáticamente.',
    'bag.n.almond': 'Star Pop',
    'bag.d.almond': 'Una lata del refresco de cereza del propio salón, todavía fría, quién sabe cómo. El azúcar y las burbujas te calman las manos. Bébelo con Q.',
    'bag.n.glow': 'Barras luminosas',
    'bag.d.glow': 'Dobla una y lánzala con G. Ni Reptantes ni Sonrientes cruzan la luz verde.',
    'bag.d.officeKey': 'La llave del despacho de Walt, sacada de la caja registradora. El latón está gastado de tanto uso.',
    'bag.d.token': 'Una ficha del Starlight con una estrella perforada. Solo para la máquina n.º 7.',
    'bag.n.fuse': 'Fusibles',
    'bag.d.fuse': 'Pesados fusibles de cerámica para el viejo cuadro de la fábrica.',
    'bag.n.fuel': 'Bidones de gasóleo',
    'bag.d.fuel': 'Gasóleo para los generadores. Chapotea mucho. Camina despacio.',
    'bag.d.keycard': 'Una tarjeta de seguridad con banda magnética. Alguien ha rascado la foto.',
    'bag.d.key': 'Una llave con una etiqueta de papel. Abre algo de aquí.',
    'help.pause': 'Pausa',
    'help.touch': 'Táctil',
    'help.pad': 'Mando',
    'help.touchText': 'Joystick de movimiento abajo a la izquierda; arrastra en la parte derecha de la pantalla para mirar. Los botones de la derecha: interactuar, linterna, correr, agacharse, mapa.',
    'help.padText': 'Stick izquierdo: andar. Stick derecho: mirar. A: interactuar. B: agacharse. X: cambiar las pilas. Y: linterna. LB / RB: asomarse. RT o pulsar el stick izquierdo: correr. LT: barra luminosa. Pulsar el stick derecho: mirar atrás. Cruceta: ↑ diario, ↓ Star Pop, → objetos. View: mapa. Menu: pausa. En los menús, la cruceta mueve, A elige y B vuelve atrás.',
    'help.survive': 'Seguir con vida',
    'help.tip1': '<b>El Devorador</b> es más rápido que tú en los pasillos rectos y lento en las curvas. Toma las esquinas.',
    'help.tip2': 'Cuando los fluorescentes empiezan a parpadear, <b>está cerca</b>.',
    'help.tip3': 'Coge un <b>farolillo</b> y todo huirá de ti durante unos segundos.',
    'help.tip4': '<b>El rojo</b> nunca se detiene. <b>El violeta</b> te corta el paso. <b>El turquesa</b> oye el agua y salta de un sitio a otro. <b>El ámbar</b> se queda quieto mientras lo miras.',
    'help.tip5': 'Puedes <b>esconderte</b> bajo los escritorios y en las taquillas. Si no te vieron entrar, no te encontrarán.',
    'help.tip6': 'Las <b>grabadoras</b> guardan la partida. El guardado automático ocurre en los objetivos, cuando estás a salvo.',
    'help.tip7': 'Lleva a cada Espectro su objeto <b>a su altar</b>. El final depende de ello.',

    'pause.title': 'Pausa',
    'pause.resume': 'Reanudar',
    'pause.map': 'Mapa',
    'pause.journal': 'Diario',
    'pause.archive': 'Archivo',
    'pause.settings': 'Ajustes',
    'pause.help': 'Cómo jugar',
    'pause.load': 'Cargar último guardado',
    'pause.menu': 'Menú principal',

    'note.close': 'Cerrar',
    'note.closeKey': 'Cerrar (E)',

    'map.close': 'Cerrar',
    'map.closeKey': 'Cerrar (M)',
    'map.objective': 'Objetivo',
    'map.tape': 'Cinta',
    'map.doc': 'Documento',
    'map.shrine': 'Altar',
    'map.supply': 'Suministros',
    'map.locked': 'Puerta cerrada',

    'kp.label': 'SEGURIDAD',
    'kp.clear': 'BORRAR',
    'kp.enter': 'OK',
    'kp.open': 'ABIERTO',
    'kp.error': 'ERROR',
    'kp.close': 'Cancelar (Esc)',

    'cab.help': 'Flechas o WASD · Intro para empezar · P para pausar ·',
    'cab.exit': 'Dejar la máquina (Esc)',

    'choice.back': 'Retroceder',
    'card.skip': 'Haz clic o pulsa E para continuar',

    'death.retry': 'Continuar desde el último guardado',
    'death.menu': 'Menú principal',

    'end.menu': 'Menú principal',
    'end.skip': 'Saltar',
    'end.time': 'tiempo de juego',
    'end.deaths': 'muertes',
    'end.docs': 'documentos',
    'end.freed': 'Espectros liberados',
    'end.drawings': 'dibujos encontrados',

    'hud.objective': 'OBJETIVO',
    'hud.rec': 'REC',
    'hud.stamina': 'ALIENTO',
    'hud.battery': 'LUZ',
    'hud.power': 'CORRIENTE {t}',
    'hud.fps': '{n} FPS',

    'touch.pause': 'Pausa',
    'touch.bag': 'BOLSA',
    'touch.map': 'MAPA',
    'touch.drink': 'BEBER',
    'touch.throw': 'LANZAR',
    'touch.crouch': 'AGACHAR',
    'touch.sprint': 'CORRER',
    'touch.flash': 'LUZ',
    'touch.tap': 'TOCAR',

    'inv.battery': 'PILA ×{n}',
    'inv.almond': 'STAR POP ×{n}',
    'inv.glow': 'BARRA LUMINOSA ×{n}',
    'inv.officeKey': 'LLAVE DEL DESPACHO',
    'inv.token': 'FICHA DE ORO',
    'inv.fuses': 'FUSIBLE ×{n}',
    'inv.fuel': 'GASÓLEO ×{n}',
    'inv.keycard': 'TARJETA DE SEGURIDAD',
    'inv.pellets': 'FAROLILLO ×{n}',

    'n.added': 'Añadido al archivo: {title}',
    'n.saved': 'Partida guardada',
    'n.batteryIn': 'Pila nueva en la linterna',
    'n.batterySpare': 'Pila de repuesto',
    'n.noSpare': 'No hay pilas de repuesto.',
    'n.batteryFull': 'La pila todavía está llena.',
    'hint.reload': 'R: cambiar las pilas de la linterna',
    'touch.reload': 'PILAS',
    'help.reload': 'Cambiar las pilas de la linterna',
    'help.lookBack': 'Mirar atrás mientras corres (mantener)',
    'n.batterySwap': 'Has puesto una pila de repuesto',
    'n.almond': 'Star Pop (Q para beber)',
    'n.glow': 'Barra luminosa (G para lanzar)',
    'n.found': 'Encontrado: {name}',
    'n.drank': 'Te bebes el Star Pop. Tu respiración se calma.',
    'n.noAlmond': 'No tienes ningún Star Pop.',
    'n.noGlow': 'No tienes barras luminosas.',
    'n.slow': 'El juego va lento. En Pausa › Ajustes › Gráficos puedes bajar la calidad.',
    'n.lockFail': 'No se pudo fijar el ratón. Mantén pulsado el botón izquierdo y arrastra para mirar.',
    'n.flashDead': 'Tu linterna se ha apagado.',
    'n.holdBreath': 'Algo está cerca. Mantén Mayús para contener la respiración.',
    'n.heardBreath': 'Te ha oído respirar.',
    'n.noFlash': 'No tienes linterna.',
    'n.noBattery': 'La pila está agotada. Busca otra.',
    'n.grace': '¡Por los pelos! (Fácil: una vez por capítulo)',
    'n.freed': '{name} es libre',
    'n.ghostBack': '{name} se ha retirado',
    'n.cabinetHi': 'Tus iniciales entraron en la tabla de récords: SAM',
    'n.perfect': 'Te has comido todas las estrellas. Partida perfecta.',
    'n.fruit': 'Ha aparecido un premio delante de la casa',
    'n.diesel': 'Bidón de gasóleo',
    'n.drawing': 'Dibujo de Lily ({n}/8)',

    'pr.read': 'Leer: {title}',
    'pr.readWall': 'Leer lo escrito',
    'pr.screen': 'Mirar la pantalla',
    'pr.tape': 'Reproducir la cinta (guarda la partida)',
    'pr.battery': 'Coger la pila',
    'pr.almond': 'Coger el Star Pop',
    'pr.glow': 'Coger la barra luminosa',
    'pr.flashlight': 'Coger la linterna',
    'pr.token': 'Coger la ficha',
    'pr.fuse': 'Coger el fusible',
    'pr.fuel': 'Coger el bidón de gasóleo',
    'pr.keycard': 'Coger la tarjeta de seguridad',
    'pr.take': 'Coger: {name}',
    'pr.pellet': 'Coger el farolillo',
    'pr.phoneRing': 'Contestar al teléfono',
    'pr.phone': 'Descolgar el auricular',
    'pr.cabinetFree': 'Jugar a la máquina (FREE PLAY)',
    'pr.doorLocked': '{name} (cerrada)',
    'pr.doorOpen': 'Abrir la puerta',
    'pr.doorClose': 'Cerrar la puerta',
    'pr.drawerOpen': 'Abrir el cajón',
    'pr.drawerClose': 'Cerrar el cajón',
    'pr.safeOpen': 'Abrir la caja fuerte',
    'pr.safeClose': 'Cerrar la caja fuerte',
    'pr.safeLocked': 'Caja fuerte (introduce la combinación)',
    'pr.hide': 'Esconderse debajo',
    'pr.hideLocker': 'Esconderse en la taquilla',
    'pr.unhide': 'Salir',
    'pr.shrineLook': 'Mirar el altar',
    'pr.shrinePlace': 'Dejar el objeto en el altar',
    'pr.drawing': 'Coger el dibujo de Lily',

    'door.default': 'Puerta',
    'door.office': 'Puerta del despacho',
    'door.storage': 'Almacén',
    'door.wc': 'Aseo',
    'door.front': 'Puerta principal',
    'door.elevator': 'Montacargas',
    'door.security': 'Sala de seguridad',
    'door.stair': 'Escalera de incendios',
    'door.house': 'La casa de los Espectros',
    'door.service': 'Ascensor de servicio',
    'lock.service': 'El ascensor está muerto. Los tres generadores tienen que estar en marcha.',
    'door.exit': 'SALIDA',
    'door.room': 'Habitación {n}',
    'door.jammed': 'Puerta',
    'lock.jammed': 'Atascada. El picaporte gira, pero algo la sujeta desde el otro lado.',
    'lock.exit': 'La SALIDA está cerrada. Todavía no.',
    'door.pressure': 'Puerta estanca',
    'lock.pressure': 'La puerta estanca no se mueve. Detrás silba el vapor.',
    'door.janitor': 'Conserje',
    'lock.janitor': 'Un candado de combinación. Tres cifras.',
    'door.fireExit': 'Salida de emergencia',
    'lock.fireExit': 'Una cadena gruesa y un candado. El conserje tiene las llaves.',
    'lock.fireExitMotel': 'La barra no cede. Alguien la ha bloqueado desde fuera.',
    'door.gym': 'Gimnasio',
    'door.mallExit': 'Puertas del centro comercial',
    'lock.mallExit': 'Cerrado por la noche. A lo lejos zumba el fotomatón.',
    'door.room12': 'Habitación 12',
    'lock.room12': 'Cerrada. El número está pulido, como si alguien lo tocara todos los días.',
    'door.room207': 'Habitación 207',
    'lock.room207': 'Cerrada. Un cartel de papel: SILENCIO, POR FAVOR. Tiene un sol dibujado con cera.',
    'door.elevatorH': 'Ascensor',
    'lock.elevatorH': 'El ascensor espera con las puertas cerradas. Espera algo.',
    'door.samHouse': 'Tu casa',
    'door.tobyHouse': 'La casa de Toby',
    'door.neighbor': 'Puerta principal',
    'lock.neighbor': 'Cerrada. Las cortinas se mueven cuando apartas la vista.',
    'door.alley': 'Puerta del callejón',
    'lock.alley': 'Cerrada. No hasta que te hayas parado en la esquina.',
    'door.kernel': 'Puerta de acero',
    'lock.kernel': 'Acero, y cerrada. Una placa de latón: KERNEL — SOLO W.',
    'lock.default': 'Cerrada.',
    'lock.office': 'Cerrada. Una placa de latón en la puerta: «W. — GERENTE».',
    'lock.front': 'Con candado por fuera. Los de la mudanza tienen la llave.',
    'lock.elevator': 'El montacargas no tiene corriente. El botón de llamada está muerto.',
    'lock.security': 'El teclado pide un código de cuatro cifras.',
    'lock.stair': 'La luz del lector de tarjetas está en rojo. Hace falta una tarjeta de seguridad.',
    'lock.house': 'Una cortina de luz violeta. Cuatro farolillos la mantienen cerrada.',

    'cap.front': 'delante',
    'cap.back': 'detrás',
    'cap.left': 'a la izquierda',
    'cap.right': 'a la derecha',
    'cap.phone': '[suena un teléfono]',
    'cap.drag': '[pasos que se arrastran cerca]',
    'cap.moan': '[un gemido]',
    'cap.farSteps': '[pasos en otra parte del edificio]',
    'cap.thud': '[algo se cae, lejos]',
    'cap.buzz': '[chisporrotea un fluorescente]',
    'cap.whisper': '[susurros]',
    'cap.giggle': '[risitas en la oscuridad]',
    'cap.radio': '[estática de radio]',
    'cap.thunder': '[trueno]',
    'cap.hiss': '[un siseo húmedo que se aleja]',
    'cap.skitter': '[correteo sobre el ladrillo]',
    'cap.whistle': '[chilla un silbato]',
    'cap.plastic': '[cruje el plástico]',
    'cap.bite': '[unos dientes se cierran cerca]',
    'cap.biteFar': '[masticar a lo lejos]',
    'cap.callName': '[alguien dice tu nombre con la voz de Toby]',
    'cap.heavySteps': '[pasos pesados, un chirrido de goma]',
    'cap.pipe': '[resuena una tubería en algún punto de los túneles]',
    'cap.locker': '[una taquilla se cierra de golpe al fondo del pasillo]',
    'cap.knock': '[tres golpes, en algún punto del pasillo]',
    'cap.beep': '[un monitor pita en una habitación vacía]',
    'cap.arc': '[chasquea la electricidad tras la puerta de acero]',
    'cap.pop': '[revienta un tubo de luz]',
    'cap.slam': '[una puerta se cierra de golpe a tu espalda]',
    'cap.run': '[alguien corre, fuera de la vista]',
    'cap.callJune': '[una voz de mujer al fondo del pasillo: «¿Eddie? Eddie, ¿eres tú?»]',
    'cap.car': '[un coche pasa siseando por la calle mojada]',
    'cap.door': '[una puerta, en alguna parte]',
    'cap.drip': '[goteo]',
    'cap.hum': '[zumbido de fluorescentes]',
    'tab.access': 'Accesibilidad',
    'tab.perf': 'Rendimiento',
    'set.perfOverlay': 'Indicador de rendimiento',
    'set.perfOverlay.help': 'Muestra cómo va el juego. Solo FPS; Básico añade el tiempo por fotograma, el tiempo de CPU y de GPU por fotograma y cuánto trabaja cada una; Detallado añade una gráfica de tiempos, llamadas de dibujo, triángulos, memoria, resolución de render y tu tarjeta gráfica. El tiempo de GPU necesita un navegador que permita consultas de tiempo de GPU (la versión de escritorio siempre lo permite).',
    'set.perfCorner': 'Posición del indicador',
    'set.perfCorner.help': 'En qué esquina de la pantalla aparece el indicador de rendimiento.',
    'opt.perfFps': 'Solo FPS',
    'opt.perfBasic': 'Básico',
    'opt.perfDetailed': 'Detallado',
    'opt.cornerTR': 'Arriba a la derecha',
    'opt.cornerTL': 'Arriba a la izquierda',
    'opt.cornerBR': 'Abajo a la derecha',
    'opt.cornerBL': 'Abajo a la izquierda',
    'preset.ultraplus': 'Ultra+',
    'opt.ultraplus': 'Ultra+',
    'opt.shadow4': 'Ultra+ (8192)',
    'set.modelDetail': 'Detalle de los modelos',
    'set.modelDetail.help': 'Con cuánta finura se construyen las criaturas, las manos y otros modelos esculpidos. Más alto se ve más suave de cerca y tarda más en cargar un capítulo. Ultra+ es para los procesadores más rápidos.',
    'set.clutter': 'Objetos de detalle',
    'set.clutter.help': 'Cuántas cosas pequeñas llenan las habitaciones: cuadros, fotos, calendarios, cajas, papeles, botellas. Más hace que cada habitación parezca habitada; menos alivia a los equipos antiguos.',
    'set.dof': 'Profundidad de campo',
    'set.dof.help': 'Desenfoca lo que está lejos de donde miras, como el objetivo de una cámara. El enfoque sigue el centro de la pantalla. Los niveles altos toman más muestras para un desenfoque más suave y limpio.',
    'set.textureRes.help': 'Nitidez de las superficies: paredes, suelos, madera, tela. Más alto necesita más memoria de vídeo.',
    'set.shadows.help': 'Sombras de tu linterna y de las farolas de fuera. Más alto es más nítido. Ultra+ usa un mapa de sombras de 8192 y necesita mucha memoria de vídeo.',
    'set.antialias.help': 'Suaviza los bordes dentados. MSAA es el más limpio; FXAA es ligero y suaviza un poco toda la imagen; los dos juntos dan el resultado más suave.',
    'set.dynLights.help': 'Cuántas lámparas cercanas pueden iluminar a la vez los objetos en movimiento y las criaturas.',
    'set.bloom.help': 'El brillo suave alrededor de las luces intensas y las pantallas.',
    'set.bloomStrength.help': 'La intensidad de ese brillo.',
    'set.motionBlur.help': 'Desenfoca la imagen cuando giras rápido. Tus manos y lo que sostienes siguen nítidos.',
    'set.particles.help': 'Polvo en el aire, lluvia, chispas y gotas.',
    'set.viewDist.help': 'Hasta dónde se dibujan las cosas y hasta dónde deja ver la niebla.',
    'set.anisotropy.help': 'Mantiene nítidos suelos y paredes vistos en ángulo muy cerrado. Cuesta muy poco.',
    'set.contrast.help': 'Diferencia entre las partes oscuras y claras de la imagen.',
    'set.saturation.help': 'La fuerza de los colores. Más bajo se parece a una foto antigua.',
    'set.fov.help': 'La amplitud de tu visión. Más amplio muestra más, pero todo parece más lejano.',
    'set.headBob.help': 'Cuánto se balancea la vista con tus pasos. Bájalo si te marea.',
    'set.shake.help': 'Temblor de cámara con los sustos, los golpes y al correr.',
    'set.grain.help': 'Grano de película sobre la imagen.',
    'set.chromatic.help': 'Bordes de color en los extremos de la imagen, como con una lente barata.',
    'set.vignette.help': 'Oscurecimiento hacia las esquinas de la pantalla.',
    'set.crosshair.help': 'Un pequeño punto en el centro de la pantalla para apuntar a lo que quieres coger.',
    'set.subtitles.help': 'Muestra lo que se dice: el walkie-talkie, las cintas, los pensamientos.',
    'set.subtitleSize.help': 'Tamaño de los subtítulos y de los subtítulos de sonidos.',
    'set.master.help': 'Volumen general.',
    'set.music.help': 'Volumen de la música.',
    'set.sfx.help': 'Pasos, puertas, objetos y todo lo que haces.',
    'set.ambience.help': 'Las salas, la lluvia, el zumbido y los ruidos del edificio.',
    'set.entities.help': 'Las criaturas: sus pasos, su respiración y sus voces.',
    'set.voice.help': 'Walkie-talkie, cintas y pensamientos.',
    'set.hrtf.help': 'Sitúa los sonidos a tu alrededor en tres dimensiones. Mejor con auriculares; desactívalo con altavoces.',
    'set.mouseSens.help': 'Lo rápido que gira la vista con el ratón.',
    'set.invertY.help': 'Mover el ratón hacia arriba mira hacia abajo.',
    'set.touchSens.help': 'Lo rápido que gira la vista al arrastrar en una pantalla táctil.',
    'set.padSens.help': 'Lo rápido que gira la vista con el stick derecho de un mando.',
    'set.toggleCrouch.help': 'Pulsa una vez para agacharte y otra para levantarte, en lugar de mantener la tecla.',
    'set.toggleSprint.help': 'Pulsa una vez para correr y otra para caminar, en lugar de mantener la tecla.',
    'set.lang.help': 'Idioma de los menús, los subtítulos y todos los documentos del juego.',
    'set.jumpscare.help': 'Reducido mantiene cada susto, pero suaviza los destellos y sonidos más fuertes.',
    'set.hints.help': 'Consejos breves cuando ocurre algo nuevo.',
    'perf.frame': 'Fotograma',
    'perf.low1': '1 % mínimo',
    'perf.cpu': 'CPU',
    'perf.cpuUse': 'Carga de CPU',
    'perf.gpu': 'GPU',
    'perf.gpuUse': 'Carga de GPU',
    'perf.na': 'n/d',
    'perf.draws': 'Llamadas de dibujo',
    'perf.tris': 'Triángulos',
    'perf.textures': 'Texturas',
    'perf.programs': 'Shaders',
    'perf.res': 'Render',
    'perf.heap': 'Memoria JS',
    'perf.sysCpu': 'CPU del sistema',
    'perf.appCpu': 'CPU del juego',
    'perf.procMem': 'Memoria del juego',
    'perf.card': 'Tarjeta gráfica',
    'settings.revert': 'Deshacer',
    'settings.keys': '↑↓ elegir · ←→ cambiar · Q/E pestañas · Retroceso deshacer · Esc volver',
    'settings.impact': 'Coste de rendimiento',
    'impact.0': 'Ninguno',
    'impact.1': 'Bajo',
    'impact.2': 'Medio',
    'impact.3': 'Alto',
    'impact.4': 'Muy alto',
    'impact.5': 'Extremo',
    'settings.gpuLoad': 'Carga de GPU estimada',
    'settings.vram': 'Memoria de vídeo estimada',
    'settings.reloadBadge': 'Se aplica la próxima vez que se cargue un capítulo',
    'settings.restartBadge': 'Se aplica al reiniciar el juego',
    'settings.restartNow': 'Reiniciar ahora',
  });
})(typeof window !== 'undefined' ? window : globalThis);
