/* Interfaz en español para la historia de Ada Lind: sustituye lo que pertenecía a la historia antigua y añade
   lo que necesitan las nueve estanterías (puertas, escaleras, tipos de documento, subtítulos). Se carga tras ui.js. */
(function (root) {
  'use strict';
  root.PB.I18N.register('es', 'ui', {
    'game.subtitle': 'OBJETOS PERDIDOS',
    'menu.credit': 'Halvard · 13 de enero de 1998 · 02:56',
    'diff.time': 'Duración estimada: 5–7 horas para quien lea cada documento y encuentre los ocho dibujos.',
    'set.vhs.help': 'Muestra el juego como a través de una vieja videocámara doméstica.',
    'help.drink': 'Chupar un caramelo de cebada',
    'bag.stats': 'Documentos {a} / {b}   ·   Dibujos de Wren {c} / {d}',
    'bag.d.flashlight': 'Una pesada linterna de goma de debajo del mostrador del Depósito 9. Pila: {n} %. Se debilita antes de apagarse.',
    'bag.n.almond': 'Caramelo de cebada',
    'bag.d.almond': 'Un caramelo de cebada retorcido de la lata bajo el mostrador, guardado para las malas noches. El azúcar calma las manos. Chúpalo con Q.',
    'bag.d.officeKey': 'Una pequeña llave de latón, gastada de tanto uso.',
    'bag.d.token': 'Una ficha de latón.',
    'help.padText': 'Stick izquierdo: andar. Stick derecho: mirar. A: interactuar. B: agacharse. X: cambiar pilas. Y: linterna. LB / RB: asomarse. RT o pulsar el stick izquierdo: correr. LT: barra luminosa. Pulsar el stick derecho: mirar atrás. Cruceta: ↑ diario, ↓ caramelo, → objetos. Vista: mapa. Menú: pausa. En los menús la cruceta mueve, A elige y B vuelve.',
    'help.tip7': 'En el fondo de cada lugar hay una mentira. <b>Devuelve la cosa perdida a su sitio</b> y el camino se abre.',
    'map.shrine': 'Reclamación',
    'end.freed': 'Estanterías reclamadas',
    'end.claimed': 'Estanterías reclamadas',
    'inv.almond': 'CARAMELO ×{n}',
    'inv.token': 'FICHA',
    'n.almond': 'Caramelo de cebada (Q para chuparlo)',
    'n.drank': 'Te comes el caramelo de cebada. Tu respiración se calma.',
    'n.noAlmond': 'No te quedan caramelos de cebada.',
    'n.drawing': 'Dibujo de Wren ({n}/8)',
    'pr.almond': 'Coger el caramelo de cebada',
    'pr.drawing': 'Coger el dibujo de Wren',
    'door.house': 'La casa',
    'touch.drink': 'AZÚCAR',
    'inv.pellets': 'LUCES PERDIDAS ×{n}',
    'pr.pellet': 'Coger la luz perdida',
    'lock.house': 'Una cortina de luz. Cuatro luces perdidas la mantienen cerrada.',
    'help.tip1': '<b>Escucha antes de mirar.</b> Cada criatura tiene su propia regla: unas oyen, otras solo ven la luz, otras solo se mueven cuando nadie las mira. Los documentos te dicen cuál es cuál.',
    'help.tip2': 'Cuando las luces empiezan a tartamudear o el sonido se retira del mundo, <b>algo está cerca</b>.',
    'help.tip3': 'En el Debajo, coge una <b>luz perdida</b> y el Devorador se mantiene alejado unos segundos.',
    'help.tip4': 'Cada estantería tiene <b>sus propias criaturas</b>: un revisor que pide billetes, caballos que solo corren mientras suena el órgano, pinos que solo se mueven cuando tú te mueves. Aprende la regla de cada una.',
    'help.tip5': 'Puedes <b>esconderte</b> bajo camas, literas y escritorios, y en taquillas. Si nada te vio entrar, nada vendrá a mirar.',
    'help.tip6': 'El juego <b>guarda solo</b> en cada objetivo, cuando estás a salvo.',
    'set.subtitles.help': 'Muestra lo que se dice: canal nueve, cintas, pensamientos.',
    'set.voice.help': 'Canal nueve, cintas y pensamientos.',
    // puertas y pasos de las nueve estanterías
    'pr.unlock': 'Abrir con llave',
    'pr.stairs': 'Tomar las escaleras',
    'pr.stairsDown': 'Bajar las escaleras',
    'pr.stairsUp': 'Subir las escaleras',
    'pr.ladderDown': 'Bajar por la escalerilla',
    'pr.ladderUp': 'Subir por la escalerilla',
    'door.otto': 'El despacho de Otto Brandt',
    'lock.otto': 'Cerrado con llave desde 1964. La llave tiene que estar en algún lugar del archivo.',
    'door.concourse': 'El vestíbulo',
    'lock.concourse': 'Cerrado desde el otro lado.',
    'door.bridge': 'El puente',
    'lock.bridge': 'Cerrado con llave. El capitán tiene la llave.',
    'door.cage': 'La jaula',
    'lock.cage': 'La reja de la jaula. Sin corriente no se mueve nada.',
    'door.fire': 'La puerta cortafuegos',
    'lock.fire': 'Acuñada. Desde este lado.',
    'door.signe': 'Stuegata 4',
    'lock.signe': 'Cerrado con llave. Dentro arde una lámpara.',
    'door.ghost': 'El tren fantasma',
    // tipos de documento
    'kind.telegram': 'Telegrama',
    'kind.transcript': 'Transcripción',
    'kind.clipping': 'Periódico',
    // subtítulos de sonidos
    'hint.flash': 'F enciende y apaga la linterna.',
    'cap.chute': '[un paquete cae por el conducto]',
    'cap.tube': '[el tubo neumático golpea]',
    'cap.bellFar': '[una campana, a lo lejos en la niebla]',
    'cap.doorShut': '[una puerta se cierra en algún sitio]',
    'cap.stepsFar': '[pasos, lejos]',
    'cap.organ': '[un órgano de feria empieza a sonar solo]',
    'cap.organStop': '[el órgano se frena y se calla]',
    'cap.choir': '[un coro, cantando]',
    'cap.knocks': '[siete golpes, sobre acero]',
    'cap.ice': '[el hielo cruje, a lo lejos]',
    'cap.brake': '[frenos chirriando]',
    'cap.laugh': '[risas]',
    'cap.toll': '[una campana dobla]',
    'cap.breath': '[una respiración, justo detrás de ti]',
    'cap.train': '[el tren, a toda velocidad]',
    'cap.pa': '[un timbre; la megafonía chisporrotea]',
  });
})(typeof window !== 'undefined' ? window : globalThis);
