/* Noyau de l’histoire en français : personnages, répliques communes, morts, astuces, fins, générique. */
(function (root) {
  'use strict';
  root.PB.I18N.register('fr', 'story', {
    chars: {
      sam: { name: 'Sam', pos: 'de Sam', role: 'Conduit de nuit pour Tri-County Movers, 20 ans. 13 ans en 1987, le cinquième membre de la bande. Vous.' },
      walt: { name: 'Walt', pos: 'de Walt', role: 'Propriétaire de la salle d’arcade Starlight. Technicien radar dans l’armée de l’air, puis réparateur de télés. Disparu depuis mars 1992.' },
      lily: { name: 'Lily', pos: 'de Lily', role: 'La fille de Walt. Morte en octobre 1983, à neuf ans. Score : 3 190.' },
      danny: { name: 'Danny', pos: 'de Danny', role: '16 ans en 1987. Bruyant, sans peur, toujours en tête du tableau des scores. Avait le double des clés de Walt.' },
      rosie: { name: 'Rosie', pos: 'de Rosie', role: '15 ans en 1987. Celle qui organisait tout. Rêvait de sa propre émission de radio.' },
      nell: { name: 'Nell', pos: 'de Nell', role: '15 ans en 1987. Discrète, dessinait des BD, grosses lunettes. Ne s’est jamais pardonné un après-midi à la piscine.' },
      toby: { name: 'Toby', pos: 'de Toby', role: '13 ans en 1987. Le meilleur ami de Sam. Avait peur du noir.' },
      eddie: { name: 'Eddie', pos: 'd’Eddie', role: 'Assistant de Walt de 1984 à 1988. Est entré les chercher en juin 1993. A une fille qu’il n’a jamais tenue dans ses bras.' },
      nora: { name: 'Nora', pos: 'de Nora', role: 'La petite sœur de Walt.' },
      frank: { name: 'Frank Dobbs', pos: 'de Dobbs', role: 'Inspecteur de la police de Harlow, 1987.' },
      june: { name: 'June', pos: 'de June', role: 'La femme d’Eddie. Réceptionniste de nuit au Blue Moon Motor Inn.' },
      theo: { name: 'Theo', pos: 'de Theo', role: 'Le petit frère de Nell.' },
      maggie: { name: 'Maggie', pos: 'de Maggie', role: 'La mère de Toby.' },
      ruth: { name: 'Ruth', pos: 'de Ruth', role: 'La femme de Walt jusqu’en 1985.' },
      ray: { name: 'Ray', pos: 'de Ray', role: 'Le père de Danny.' },
      carol: { name: 'Carol', pos: 'de Carol', role: 'La mère de Rosie.' },
      ann: { name: 'Ann', pos: 'd’Ann', role: 'La mère de Sam.' },
    },
    speakers: { sam: 'SAM', eddie: 'EDDIE', walt: 'WALT', danny: 'DANNY', rosie: 'ROSIE', nell: 'NELL', toby: 'TOBY', lily: 'LILY', june: 'JUNE', radio: 'RADIO', voice: '???' },
    items: {},
    obj: {
      ghost: 'Rapporter l’objet {pos} à son autel (facultatif)',
    },
    recap: {
      prolog: 'La salle d’arcade Starlight, la veille de la vente aux enchères. La borne n° 7 tournait sans être branchée, et elle connaissait mon nom. PLAYER 1: SAM — CONTINUE?',
      lobby: 'Des salles jaunes sans fin : le jeu qui attend un joueur. Quelque chose de rond et de pâle y mange dans le noir. Eddie est vivant, au talkie-walkie, à l’intérieur depuis 1993.',
      mill: 'L’entrepôt du père de Danny. Danny s’est lancé à ma poursuite en hurlant « Tu as lâché ! ». Je lui ai rendu la montre de son père ; il s’est arrêté, et il s’est souvenu de son nom.',
      pipes: 'Les tunnels d’orage. Notre fort. Règle numéro quatre : personne ne rentre seul. Cette règle, c’est moi qui l’ai écrite.',
      pool: 'La piscine où Theo a failli se noyer pendant que Nell finissait un dessin. Elle attend depuis des années d’être pardonnée. Theo lui a pardonné dès sa toute première lettre.',
      office: 'Le bureau de la mère de Rosie, cent-sept-trois. Sur sa cassette, à 0 h 40, quelqu’un frappe à la porte de derrière de l’arcade. Rosie : « Tiens, regardez qui revient en rampant. »',
      school: 'Le 16 avril 1987. Le pacte : les cinq mains sur le joystick, personne ne lâche. Cinq initiales en bas. La dernière est la mienne.',
      dark: 'Le noir, trois groupes électrogènes et un briquet en laiton. La dernière page de Toby dit que Sam a fait demi-tour. De ce demi-tour, je ne gardais aucun souvenir.',
      mall: 'Le plus beau samedi de 1986 : cinq gamins dans un photomaton, et l’un d’eux, c’est moi, en train de rire. Les mannequins ne bougeaient que quand je détournais les yeux.',
      motel: 'Le souvenir d’Eddie, pas le mien. La chambre 12, et son carnet : UN QUI ENTRE, UN QUI SORT. Il lui faut quelqu’un pour rester à sa place. Il voulait que ce soit moi.',
      hospital: 'Saint Agnes, octobre 1983. Lily a demandé à son père un jeu qui ne finit jamais, pour que personne n’ait jamais à partir. Walt l’a construit.',
      maple: 'Ma rue. La voix de ma mère sur le répondeur à 2 h 50 du matin, qui demande où je suis. À 21 h 40, je n’ai pas pris le chemin de la maison.',
      workshop: 'La cave de Walt et la cassette de 3 h 17. Cinq mains sur le joystick, et l’une d’elles a lâché. La mienne.',
      maze: 'Le niveau 255, la maison elle-même. Les Spectres qui se souviennent marchent à mes côtés, en lumières de couleur.',
      killscreen: 'Le niveau 256. Le côté cassé. Une prise qui demande cinq mains, et une porte qui en laisse sortir un seul.',
    },
    memento: {
      danny: { name: 'La montre de Danny', line: 'Une montre en acier au verre fêlé, arrêtée à 3 h 17. Gravé au dos : « RAY KOWALSKI — 25 ANS — HARLOW MILL ».' },
      rosie: { name: 'La cassette de Rosie', line: 'Un baladeur violet avec une cassette dedans. L’étiquette dit FACE B : POUR APRÈS. La face B est vierge.' },
      nell: { name: 'Les lunettes de Nell', line: 'De lourdes lunettes, un verre fêlé. Elles s’embuent dans votre main, comme si quelqu’un venait de souffler dessus.' },
      toby: { name: 'Le briquet de Toby', line: 'Un vieux briquet en laiton. Gravé : « TOBY — POUR QUE TU NE RESTES JAMAIS DANS LE NOIR. PAPI ».' },
    },
    freed: {
      danny: ['DANNY : « 3 h 17. Ma montre s’est arrêtée. Moi, jamais. »', 'DANNY : « …Te revoilà. T’en as mis, du temps, Keller. Vas-y. Je m’occupe du gros. »'],
      rosie: ['ROSIE : « La face B. On devait l’enregistrer après. Après avoir gagné. »', 'ROSIE : « J’ai toujours couru devant tout le monde. Maintenant, je marche à côté de toi. »'],
      nell: ['NELL : « Mes lunettes. Tout est si… net. »', 'NELL : « J’arrête d’attendre d’être sûre. Je viens avec toi. »'],
      toby: ['TOBY : « Le briquet de papi… » (La flamme prend. Pour la première fois, vous voyez son visage : un gamin de treize ans, des taches de rousseur.)', 'TOBY : « …Me regarde pas encore, Sam. Marche. Je suis juste derrière toi. »'],
    },
    shrine: {
      quiet: 'L’autel est silencieux. La bougie continue de brûler.',
      missing: 'Un petit autel. Une photo de {name} dans un cadre, et une place vide où quelque chose devrait se trouver.',
    },
    mono: {
      watcherSeen: 'Au loin, quelque chose de grand et de noir se tient debout. La tête penchée sur le côté. Ça compte.',
      hide: 'Retiens ton souffle.',
      hideLocker: 'Retiens ton souffle. Ne bouge pas.',
      fearHigh: 'J’arrive plus à respirer…',
      lowBattery: 'La pile est en train de mourir.',
      freed: '{name} ne me poursuit plus.',
      eaterFlicker: 'Les lumières baissent. C’est tout près. Je l’entends mâcher.',
    },
    ghostHelp: {
      danny: 'DANNY : « Cours ! Je le tiens ! »',
      amberWatch: 'TOBY : « Me regarde pas… s’il te plaît, me regarde pas… »',
    },
    deaths: {
      eater: ['DÉVORATION', 'Le Dévoreur est plus rapide que vous en ligne droite et lent dans les virages. Prenez les coins, et guettez le bruit de mastication.'],
      red: ['CAPTURE', 'Danny ne s’arrête jamais et n’abandonne jamais une poursuite. Brisez sa ligne de vue et mettez un coin entre vous.'],
      violet: ['VOIE COUPÉE', 'Rosie va là où vous allez, pas là où vous êtes. Changez de direction quand elle disparaît.'],
      teal: ['NOYADE', 'Nell entend l’eau. Évitez les flaques et longez les bords.'],
      amber: ['IMMOBILE', 'Toby ne peut pas bouger tant que vous le regardez. Gardez les yeux, ou la lampe, sur lui.'],
      grinner: ['ÇA A SOURI', 'Les Ricaneurs fondent à la lumière. Gardez la lampe braquée sur eux ou lâchez un bâton lumineux.'],
      watcher: ['LE COMPTE EST BON', 'Le Compteur ne bouge que lorsque vous ne le regardez pas. Ne lui tournez jamais le dos longtemps.'],
      crawler: ['AU FOND', 'Les Rampants reculent devant la lumière, puis vous contournent. Gardez le dos au mur, et ne tenez pas l’un d’eux trop longtemps dans le faisceau.'],
      monitor: ['PAS DE BILLET DE SORTIE', 'Le Surveillant ne voit que ce que touche sa lampe. Entrez dans un casier avant que le faisceau ne vous trouve.'],
      mannequin: ['LA POSE', 'Les mannequins ne bougent que lorsque personne ne regarde. Reculez s’il le faut.'],
      neighbor: ['PORTE OUVERTE', 'Le Voisin se rapproche quand vous lui tournez le dos. Votre lampe le fait reculer. Ne répondez jamais à la voix.'],
      chompy: ['GROS CÂLIN', 'Chompy est lent mais ne s’arrête jamais. Éclairez-lui les yeux et il se cache le visage.'],
    },
    tips: [
      'Le Dévoreur est plus rapide que vous dans un couloir droit, mais lent dans les virages. Prenez les coins.',
      'Courir fait du bruit. Marcher accroupi est presque silencieux, et accroupi, on ouvre les portes sans bruit.',
      'Si les lumières baissent et clignotent, le Dévoreur est tout près.',
      'Une lanterne fait fuir tout ce qui vous entoure pendant quelques secondes.',
      'Les magnétophones sauvegardent la partie et rejouent un souvenir.',
      'On peut se cacher sous les bureaux, les lits et les comptoirs, et dans les casiers. Si rien ne vous voit entrer, rien ne cherchera.',
      'Rapportez à chaque Spectre son objet sur son autel, et il cessera de vous chasser. La fin en dépend.',
      'Un Star Pop calme les nerfs et rend le souffle.',
      'M ouvre la carte des endroits explorés.',
      'La lampe torche mange les piles. Les bâtons lumineux (G) éclairent un coin, et leur cliquetis éloigne les chasseurs de vous.',
      'Continuez à regarder celui couleur d’ambre. Mais pas trop longtemps.',
      'Lily a laissé huit dessins derrière elle. Certains sont bien cachés.',
      'Eddie connaît cet endroit mieux que personne. Ça ne veut pas dire qu’il vous dit tout.',
      'Les casiers vous cachent entièrement. Si quelque chose approche, maintenez Maj pour retenir votre souffle.',
      'Les mannequins ne peuvent pas bouger tant que vous les regardez.',
      'Le Voisin utilise des voix que vous connaissez. Ne répondez pas.',
      'Walt a arraché cinq pages de son journal. Elles comptent plus qu’il n’y paraît.',
      'Un tiroir entrouvert d’un doigt contient quelque chose. Un coffre dont la porte n’est pas enclenchée aussi.',
      'Maintenez V (ou le bouton du milieu de la souris) pour regarder par-dessus votre épaule en courant.',
      'Plus le silence dure, plus ils approchent. Le jeu n’aime pas attendre.',
    ],
    endings: {
      exit: {
        title: 'SORTIE', subtitle: 'Mauvaise fin — Encore une fois',
        lines: [
          'Vous prenez la porte. Derrière vous, Eddie crie votre nom, puis la porte se ferme et les cris restent de l’autre côté.',
          'De l’air froid. La pluie. Vous ouvrez les yeux sur la moquette mouillée de l’arcade. C’est le matin. Les rideaux de fer sont à moitié levés.',
          'La borne n° 7 tourne toujours. Sur l’écran de démonstration, cinq Spectres flottent maintenant dans la maison. Le cinquième porte une veste de travail.',
          'Les déménageurs la chargent à midi. Le chauffeur racontera plus tard qu’il a entendu quelqu’un frapper de l’intérieur de la borne, tout le long de la Route 9.',
          'Le camion n’arrive jamais à la vente aux enchères.',
          'Vous vous étiez juré de ne plus jamais les abandonner. La deuxième fois a été plus facile. C’est ça, le pire.',
        ],
      },
      deal: {
        title: 'LE MARCHÉ', subtitle: 'Fin sombre — Un qui entre, un qui sort',
        lines: [
          'Vous tenez la porte. Eddie vous regarde une longue seconde. « Je leur dirai. Je dirai à tout le monde qui tu étais. »',
          'Il passe. La porte se referme doucement, comme la fin d’une cassette.',
          'Quelque part à Harlow, à l’aube, un homme trempé entre dans une cuisine, et une petite fille d’un an le fixe depuis sa chaise haute.',
          'La maison est silencieuse. Au loin, quelque chose de rond recommence à mâcher.',
          'Vous n’êtes pas le Joueur. Vous n’êtes pas un Spectre. Vous êtes la personne qui est restée. Les étoiles brillent. Vous savez où se trouve chacune d’elles.',
          'Sur le tableau des scores d’une arcade vide, d’une écriture que personne ne sait expliquer, une nouvelle ligne : SAM — JOUE ENCORE.',
        ],
      },
      plug: {
        title: 'GAME OVER', subtitle: 'Bonne fin — Personne ne lâche',
        lines: [
          'Quatre lumières de couleur se referment sur vos mains. Rouge, violet, turquoise, ambre. Cinq mains, comme le disait le pacte.',
          'Vous tirez. La prise sort. Pour la première fois depuis 1987, le bourdonnement s’arrête.',
          'Dans le noir, tout près, une voix humaine et fatiguée : « Je n’ai plus faim, Sam. Enfin. »',
          'Vous vous réveillez sur la moquette de l’arcade. L’aube passe à travers la vitre.',
          'Quatre gamins en blousons de 1987 sont assis par terre, ils clignent des yeux. Toby vous regarde longtemps. « Sam ? …T’as vieilli. » Puis il vous serre dans ses bras si fort que ça fait mal.',
          'Sur Maple Street, une lumière de porche allumée depuis sept ans s’éteint.',
          'Eddie rentre chez lui à pied par les rues vides. Il ne court pas. Il veut se souvenir du chemin.',
          'La borne n° 7 est éteinte. Une ligne reste gravée dans le verre : GAME OVER — 5 PLAYERS.',
        ],
      },
      lil: {
        title: 'LIL', subtitle: 'Vraie fin — Les noms au tableau',
        lines: [
          'Vous posez huit dessins sur le cœur. Du crayon gras sur du papier : l’arcade, un Chompy orange avec des cornes, une fenêtre d’hôpital, un papa.',
          'Le Dévoreur cesse de mâcher. Le silence dure longtemps. Puis, d’une voix que vous connaissez depuis 1985 : « …C’est Lily qui a dessiné ça. »',
          'Walt se tient là où était le Dévoreur, maigre, gris, redevenu lui-même. « Baisse les mains. Celle-ci, c’est à moi de la tirer. Ça l’a toujours été. »',
          'Quatre lumières de couleur se referment sur ses mains. Il tire. La maison se replie comme du papier.',
          'La dernière chose que vous voyez, c’est une petite fille en chemise d’hôpital qui lui prend la main, et tous les deux qui s’en vont dans le noir entre les étoiles.',
          'L’aube. Quatre gamins sur la moquette de l’arcade. Eddie à la cabine téléphonique dehors, qui rit et pleure en même temps. « June ? June, c’est moi. »',
          'Une semaine plus tard, Nora ouvre l’arcade une dernière fois et trouve le tableau des scores réécrit d’une main qu’elle connaît. 1 LIL. 2 DAN. 3 ROS. 4 NEL. 5 TOB. 6 SAM. 7 WALT.',
          'La lumière du porche de Toby s’éteint. Sur Maple Street, deux personnes qui ne sont plus des enfants restent assises sur le trottoir à parler jusqu’à midi. Sam lui raconte tout. Il savait déjà.',
        ],
      },
    },
    scrawl: {
      yellow: ['QUI EST RENTRÉ ?', 'IL EST TOUJOURS 3 H 17', 'NE LÂCHE PAS', 'CINQ MAINS', 'JE L’ENTENDS MÂCHER', 'COMPTE LES PORTES'],
      dark: ['LAISSE LA LUMIÈRE', 'SAM ?', 'ÇA SOURIT QUAND TU CLIGNES', 'J’AI PAS PEUR'],
      office: ['OÙ SONT PASSÉS LES AUTRES', '107.3', 'FACE B'],
      hospital: ['SILENCE SVP', 'ELLE DESSINAIT SUR TOUT', '207'],
      motel: ['UN ENTRE UN SORT', 'NE RÉPONDS PAS', '3:17'],
      school: ['PERSONNE NE LÂCHE', 'D R N T S', 'SAM ÉTAIT LÀ'],
      concrete: ['TU AS LÂCHÉ', 'DAN #1', '3:17'],
      pool: ['UNE SECONDE', 'JE SURVEILLAIS'],
      mall: ['AMIS POUR TOUJOURS', 'MÊME SI'],
      tunnel: ['PERSONNE NE RENTRE SEUL', 'D+T+S'],
      workshop: ['NE DÉBRANCHE PAS', '2 5 6'],
    },
    photoLabels: { fort: 'LE FORT. JOUR D’OUVERTURE.', chompy: 'LIL & CHOMPY' },
    credits: [
      ['LEVEL 256', 'La salle d’arcade Starlight'],
      ['Un jeu d’horreur à la première personne', ''],
      ['Dédié à', 'tous ceux qui ont un jour lâché quelque chose, et qui sont revenus le chercher'],
      ['Hungry House', 'un jeu d’arcade imaginaire de 1981, créé pour cette histoire'],
      ['Son', 'synthétisé en direct, pas un seul enregistrement'],
      ['Textures et modèles', 'procéduraux, pas un seul fichier image'],
      ['Aux joueurs', 'ne mettez jamais de jeton dans la borne n° 7 après minuit'],
    ],
  });
})(typeof window !== 'undefined' ? window : globalThis);
