/* Noyau de l’histoire en français : personnages, locuteurs, répliques communes, morts, conseils, générique, inscriptions.
   Les fichiers de chapitre ajoutent documents, objectifs, pensées, radio et résumés ; lake.js ajoute les fins.
   La bible de l’histoire est docs/STORY.md. */
(function (root) {
  'use strict';
  root.PB.I18N.register('fr', 'story', {
    chars: {
      ada: { name: 'Ada', pos: 'd’Ada', role: 'Ada Lind, 31 ans. Employée de nuit au Dépôt 9, le bureau des objets trouvés sous la gare centrale de Halvard, depuis 1990. Vous.' },
      wren: { name: 'Wren', pos: 'de Wren', role: 'Wren Lind, la petite sœur d’Ada. Sept ans. Disparue sur la glace du lac Ostra le 14 janvier 1979.' },
      otto: { name: 'Otto', pos: 'd’Otto', role: 'Otto Brandt, employé de nuit au Dépôt 9 de 1946 à 1964, année où il est descendu par le monte-charge. Sur le canal neuf.' },
      ingrid: { name: 'Ingrid', pos: 'd’Ingrid', role: 'Ingrid Lind, la grand-mère des filles, « Mamie ». Née à Gammel Ostra. Morte en 1996.' },
      clerk: { name: 'L’Employée de nuit', pos: 'de l’Employée de nuit', role: 'Tient l’Index tout au fond du Dessous. Signe ses notes « A. »' },
    },
    speakers: { ada: 'ADA', otto: 'OTTO', radio: 'RADIO', lyle: 'LYLE HARDY', clerk: 'L’EMPLOYÉE', wren: 'WREN', voice: '???' },
    items: {},
    obj: {},
    memento: {},
    freed: {},
    shrine: {},
    ghostHelp: {},
    mono: {
      hide: 'Retiens ton souffle.',
      hideLocker: 'Retiens ton souffle. Ne bouge pas.',
      fearHigh: 'Je n’arrive plus à respirer...',
      lowBattery: 'La pile est en train de mourir.',
      eaterFlicker: 'Les lumières baissent. C’est tout près. Je l’entends mâcher.',
      watcherSeen: 'Quelque chose de grand, tout au bout, immobile.',
    },
    // [ce qui s’affiche à l’écran, ce qu’il faut faire autrement]
    deaths: {
      eater: ['DÉVORÉE', 'Le Dévoreur est rapide en ligne droite et lent dans les virages. Une lumière perdue toute fraîche en main le fait reculer quelques secondes.'],
      sorter: ['RANGÉE', 'Ce qui trie les archives dans le noir poursuit son travail. Ne vous mettez pas entre lui et les étagères.'],
      wallpaperMan: ['TAPISSÉE', 'Les hommes plats ne quittent le mur que dans votre dos. Passez devant eux en les regardant.'],
      hummer: ['BOURDONNÉE', 'Là où le bourdonnement enfle et où les lampes vacillent, quelque chose écoute. Marchez lentement et évitez les endroits bruyants.'],
      drowned: ['ENTRAÎNÉE AU FOND', 'Les Noyés attendent sous l’eau et vous y entendent. Restez hors de l’eau, et n’y restez jamais immobile.'],
      passenger: ['RACCOMPAGNÉE À SA PLACE', 'Les passagers se réveillent quand une lumière s’attarde sur eux. Gardez votre lampe loin de leur visage et ne les frôlez pas.'],
      bellman: ['SONNÉE', 'Sur le pont découvert, le Sonneur vous entend. Quand la cloche se met à sonner, il chasse : mettez-vous à couvert et restez bas.'],
      pines: ['EMPORTÉE DANS LES ARBRES', 'Les pins ne bougent que lorsque vous bougez. Près d’eux, restez immobile et laissez-les se désintéresser de vous.'],
      stag: ['RENVERSÉE', 'Le cerf charge en ligne droite. Mettez un arbre ou une voiture entre vous, et il s’assommera tout seul.'],
      usher: ['CONDUITE À SA PLACE', 'Une ouvreuse ne voit que dans son faisceau rouge. Restez hors de la lumière et ne passez jamais devant elle.'],
      burrower: ['TIRÉE SOUS TERRE', 'Les fouisseurs sentent vos pas à travers la terre. Sur la terre battue, accroupissez-vous ; sur les rails et les planches, vous êtes à l’abri.'],
      lamplighter: ['LA LAMPE DANS LES YEUX', 'Les porteurs de lampe vont vers toute lumière. Éteignez la vôtre et laissez-les passer.'],
      crawler: ['ATTRAPÉE PAR LE HAUT', 'Les rampeurs des boisages attendent dans la charpente. Levez les yeux avant de passer dessous, et restez bas.'],
      frozen: ['GELÉE', 'Les clients gelés ne bougent que près de la chaleur. Réchauffez-vous, puis éloignez-vous du feu avant qu’ils se lèvent.'],
      cold: ['GELÉE', 'Dehors, le froid entre vite. Allez d’abri en abri et réchauffez-vous près d’un feu.'],
      whiteout: ['AVALÉE PAR LA NEIGE', 'Dans la tempête, vous ne voyez que ses traces. Elle vous entend : marchez, ne courez pas, restez près des abris.'],
      cook: ['ACCROCHÉE', 'Le Cuisinier ne quitte jamais la cuisine. Attendez qu’il vous tourne le dos au fond, puis passez.'],
      silted: ['ENGLOUTIE DANS LA BOUE', 'Restez trop longtemps immobile sur la boue, et l’un d’eux se dresse à côté de vous. Continuez de bouger.'],
      longone: ['EMPORTÉE DANS LA RIVIÈRE', 'Les Longs attendent dans les puits, les fossés et la rivière. Accroupissez-vous en longeant l’eau.'],
      choir: ['ASSISE DANS LES BANCS', 'Tant que le chœur chante, il ne voit rien. Marchez doucement derrière eux ; ne courez jamais, ne passez jamais devant.'],
      water: ['NOYÉE', 'L’eau monte de plus en plus vite. Gagnez les hauteurs, et grimpez.'],
      conductor: ['DESCENDUE DU TRAIN', 'Sans billet valable, le Contrôleur vous fait descendre. Quand sa lanterne arrive dans le couloir, éteignez votre lampe et glissez-vous sous une couchette.'],
      sleeper: ['TIRÉE DANS UNE COUCHETTE', 'Les dormeurs ne voient pas. Un pas devant leur compartiment les réveille : passez accroupie, et ne bougez plus quand l’un d’eux est debout.'],
      underhand: ['TIRÉE ENTRE LES VOITURES', 'Ne vous arrêtez jamais sur une passerelle. Traversez vite, et ouvrez la porte suivante avant de mettre le pied sur les plaques.'],
      mask: ['VISAGES', 'Les masques ne bougent que lorsque personne ne les regarde. Gardez-les devant vous et reculez.'],
      horse: ['PIÉTINÉE', 'Les chevaux ne courent que tant que l’orgue joue. Quand la musique s’arrête, eux aussi : c’est là que vous bougez.'],
      lotte: ['SOULEVÉE', 'Lotte ne voit pas. Elle entend, et elle ne s’arrête jamais de rire : restez loin du rire et soyez silencieuse.'],
      hush: ['RÉDUITE AU SILENCE', 'Près du Silence, tout son s’éteint. Quand vous ne vous entendez plus, il est tout près. Éloignez-vous, lentement.'],
      underice: ['À TRAVERS LA GLACE', 'Ne courez jamais sur la glace sombre au-dessus de l’ancienne rivière. Marchez, et ce qui est dessous reste dessous.'],
    },
    tips: [
      'Courir fait du bruit. Marcher accroupie est presque silencieux.',
      'Au fond de chaque étagère, il y a un mensonge. Trouvez la chose perdue et remettez-la à sa place, et l’endroit vous laisse partir.',
      'La plupart entendent mieux qu’ils ne voient. Éteignez votre lampe quand quelque chose est proche.',
      'Vous pouvez vous cacher sous les lits, les couchettes et les bureaux. Si rien ne vous a vue entrer, rien ne viendra regarder.',
      'Cachée, maintenez Maj pour retenir votre souffle. À bout de souffle, vous haletez.',
      'Maintenez V pour regarder par-dessus votre épaule en courant.',
      'Lisez tout. Ceux qui ont écrit ces choses vous disent comment sortir.',
      'Wren a laissé huit dessins, un sur la plupart des étagères. Certains sont bien cachés.',
      'Otto parle sur le canal neuf quand il a quelque chose à vous dire. Il a généralement raison.',
      'M ouvre une carte des lieux où vous êtes passée.',
    ],
    photoLabels: {},
    credits: [
      ['LEVEL 256', 'une histoire d’horreur à la première personne, en neuf étagères'],
      ['Pour', 'tous ceux à qui l’on a dit que ce n’était la faute de personne'],
      ['Lieux', 'Halvard, le lac Ostra et le Dessous sont inventés ; tous ceux qui s’y trouvent aussi'],
      ['Son', 'synthétisé en direct : pas un seul enregistrement'],
      ['Images et modèles', 'procéduraux : pas un seul fichier image'],
      ['Le Dépôt 9', 'est ouvert toutes les nuits. Renseignez-vous au guichet.'],
    ],
    // Inscriptions griffonnées sur les murs du Dessous
    scrawl: {
      yellow: ['QUI EST REVENU LE CHERCHER ?', 'IL EST TOUJOURS 02:56', 'RÉCLAMATION 256', 'ON NE SAUTE PAS D’ÉTAGÈRE', 'CHERCHE LE MENSONGE', 'PERSONNE N’A DEMANDÉ', 'CLASSÉ SOUS : OUBLIÉ'],
      dark: ['GARDE LA LUMIÈRE', 'IL MANGE CE QUE TU AS CESSÉ DE CHERCHER', 'ADA ?'],
      concrete: ['À GARDER POUR : ADA LIND', '256', 'NON RÉCLAMÉ'],
    },
  });
})(typeof window !== 'undefined' ? window : globalThis);
