/* Interface en français. */
(function (root) {
  'use strict';
  root.PB.I18N.register('fr', 'ui', {
    'game.title': 'LEVEL 256',
    'game.subtitle': 'LA SALLE D’ARCADE STARLIGHT',
    'game.aria': 'Vue du jeu',
    'noscript': 'Ce jeu a besoin de JavaScript.',

    'boot.tip': 'ASTUCE',
    'boot.init': 'Démarrage…',
    'boot.fonts': 'Chargement des polices…',
    'boot.sounds': 'Enregistrement des sons…',
    'boot.voices': 'Enregistrement des voix…',
    'boot.prep': 'Préparation du niveau…',
    'boot.noThree': 'Le moteur 3D (three.js) n’a pas pu se charger. Vérifiez votre connexion Internet et rechargez la page.',
    'boot.error': 'Erreur au démarrage : {msg}',
    'boot.noWebgl': 'La carte graphique n’a pas pu démarrer la 3D (WebGL 2). Mettez à jour le pilote graphique, puis relancez le jeu.',
    'load.textures': 'Tissage des textures… ({n}/{m})',
    'load.walls': 'Montage des murs…',
    'load.bake': 'Cuisson de la lumière…',
    'load.fixtures': 'Pose des néons…',
    'load.props': 'Installation des meubles…',
    'load.decals': 'Taches et éraflures…',
    'load.shaders': 'Compilation des shaders…',
    'load.ready': 'Prêt',
    'load.error': 'Erreur de chargement : {msg}',

    'first.title': 'Avant de commencer',
    'first.lang': 'Langue',
    'first.bright': 'Réglez la luminosité jusqu’à ce que le symbole de gauche soit à peine visible et celui de droite bien visible.',
    'first.phones': 'À jouer au casque, dans une pièce sombre.',
    'first.go': 'Continuer',

    'menu.continue': 'Continuer',
    'menu.new': 'Nouvelle partie',
    'menu.levels': 'Chapitres',
    'menu.settings': 'Options',
    'menu.archive': 'Archives',
    'menu.help': 'Comment jouer',
    'menu.quit': 'Quitter le jeu',
    'menu.credit': 'Harlow · 30 novembre 1994 · 2 h 11',
    'menu.foot': 'À jouer au casque, dans le noir.',
    'menu.footDone': 'Fins : {list} · morts {deaths}',

    'confirm.title': 'Nouvelle partie ?',
    'confirm.body': 'Votre progression sauvegardée sera écrasée. Les documents trouvés restent dans les archives.',
    'confirm.yes': 'Oui, tout recommencer',
    'confirm.no': 'Annuler',

    'diff.title': 'Difficulté',
    'diff.easy': 'Facile',
    'diff.easyDesc': 'Pour l’histoire. Les créatures sont plus lentes et moins attentives. Une fois par chapitre, vous échappez à une prise.',
    'diff.normal': 'Normal',
    'diff.normalDesc': 'Tel que prévu. Une seule prise vous renvoie à la dernière sauvegarde.',
    'diff.nightmare': 'Cauchemar',
    'diff.nightmareDesc': 'Créatures plus rapides à l’ouïe plus fine. Les piles se vident vite. La peur arrive plus tôt.',
    'diff.time': 'Durée estimée : 4 à 6 heures pour qui lit chaque document et libère les quatre Spectres.',

    'levels.title': 'Chapitres',
    'levels.locked': 'Verrouillé',

    'common.back': 'Retour',
    'common.on': 'Oui',
    'common.off': 'Non',

    'settings.title': 'Options',
    'settings.reset': 'Par défaut',
    'settings.reloadNote': 'Les options marquées * s’appliquent au prochain chargement de chapitre.',
    'tab.screen': 'Écran',
    'set.displayMode': 'Mode d’affichage',
    'set.displayMode.help': 'Le plein écran masque le navigateur. Échap ou F11 pour en sortir ; Alt+Entrée bascule en jeu.',
    'opt.windowed': 'Fenêtré',
    'opt.fullscreen': 'Plein écran',
    'set.resolution': 'Résolution',
    'set.resolution.help': 'La taille de l’image rendue. Native utilise votre écran ; toute autre taille est adaptée à la fenêtre selon le mode de mise à l’échelle ci-dessous.',
    'opt.native': 'Native (écran)',
    'set.scaleMode': 'Mise à l’échelle',
    'set.scaleMode.help': 'Comment afficher une résolution dont les proportions diffèrent de la fenêtre.',
    'opt.fit': 'Ajuster (proportions, bandes noires)',
    'opt.stretch': 'Étirer',
    'opt.fill': 'Remplir (bords rognés)',
    'set.upscale': 'Filtre de mise à l’échelle',
    'set.upscale.help': 'Lisse mélange les pixels à l’agrandissement ; Pixel les garde nets et carrés (look rétro en basse résolution).',
    'opt.smooth': 'Lisse',
    'opt.pixel': 'Pixel',
    'set.sharpen': 'Netteté',
    'set.sharpen.help': 'Accentuation adaptative au contraste de l’image finale. Utile sous la résolution native et avec l’anticrénelage.',
    'set.fpsLimit': 'Limite d’images par seconde',
    'set.fpsLimit.help': 'Plafonne les images par seconde. Une limite plus basse garde la carte graphique au frais et le rythme d’affichage régulier.',
    'opt.unlimited': 'Illimitée',
    'set.vsync': 'Synchro verticale',
    'set.vsync.help': 'Activée : les images suivent le rafraîchissement de l’écran, sans déchirement. Désactivée : le jeu dessine aussi vite que possible, jusqu’à la limite d’images. Dans un navigateur, le navigateur lui-même attend toujours l’écran : Désactivée ne supprime donc que l’attente propre au jeu ; la version de bureau coupe entièrement la synchronisation (après redémarrage).',
    'tab.graphics': 'Graphismes',
    'tab.display': 'Image',
    'tab.audio': 'Audio',
    'tab.controls': 'Commandes',
    'tab.gameplay': 'Jeu',
    'preset.low': 'Bas',
    'preset.medium': 'Moyen',
    'preset.high': 'Élevé',
    'preset.ultra': 'Ultra',
    'preset.extreme': 'Extrême',
    'preset.custom': 'Personnalisé',
    'opt.off': 'Désactivé',
    'opt.low': 'Bas',
    'opt.medium': 'Moyen',
    'opt.high': 'Élevé',
    'opt.ultra': 'Ultra',
    'opt.extreme': 'Extrême',
    'opt.shadow1': 'Bas (1024)',
    'opt.shadow2': 'Élevé (2048)',
    'opt.shadow3': 'Ultra (4096)',
    'opt.small': 'Petit',
    'opt.large': 'Grand',
    'opt.full': 'Complet',
    'opt.reduced': 'Réduit',

    'set.preset': 'Préréglage de qualité',
    'set.preset.help': 'Modifie d’un coup toutes les options graphiques ci-dessous. Extrême vise les cartes graphiques haut de gamme ; Ultra+ va au-delà (ombres 8192, éclairage précalculé le plus dense, modèles les plus fins, profondeur de champ) et s’adresse aux PC les plus puissants.',
    'set.renderScale': 'Échelle de résolution',
    'set.renderScale.help': 'Au-delà de 100 %, le rendu se fait en plus haute résolution puis est réduit : image plus nette, charge bien plus lourde pour la carte graphique.',
    'set.textureRes': 'Résolution des textures',
    'set.shadows': 'Ombres',
    'set.antialias': 'Anticrénelage',
    'set.lightmapRes': 'Qualité de l’éclairage précalculé',
    'set.lightmapRes.help': 'Finesse de la lumière douce précalculée et de ses ombres.',
    'set.dynLights': 'Lumières dynamiques',
    'set.bloom': 'Flou lumineux (bloom)',
    'set.bloomStrength': 'Intensité du bloom',
    'set.volumetric': 'Lumière volumétrique et poussière',
    'set.ao': 'Occlusion ambiante (SSAO)',
    'set.ao.help': 'Ombres de contact douces dans les coins, sous les meubles et entre les carreaux.',
    'set.ssr': 'Réflexions en espace écran',
    'set.ssr.help': 'De vraies réflexions sur les sols mouillés, le carrelage, le verre et le métal poli.',
    'set.volumetric.help': 'Rayons de lumière, faisceau de la lampe torche et poussière en suspension calculés par lancer de rayons. Très lourd en Extrême.',
    'set.motionBlur': 'Flou de mouvement',
    'set.lensDirt': 'Saleté sur l’objectif',
    'set.lensDirt.help': 'Des traces sur l’objectif qui accrochent la lumière vive.',
    'set.particles': 'Densité des particules',
    'set.viewDist': 'Distance d’affichage',
    'set.anisotropy': 'Filtrage anisotrope',
    'set.brightness': 'Luminosité',
    'set.brightness.help': 'Réglez-la pour que les coins les plus sombres soient à peine visibles.',
    'set.contrast': 'Contraste',
    'set.saturation': 'Saturation des couleurs',
    'set.fov': 'Champ de vision',
    'set.headBob': 'Balancement de la tête',
    'set.shake': 'Tremblement de caméra',
    'set.grain': 'Grain de film',
    'set.chromatic': 'Aberration chromatique',
    'set.vignette': 'Vignettage',
    'set.vhs': 'Aspect caméscope (VHS)',
    'set.vhs.help': 'Montre le jeu comme à travers le viseur d’un caméscope de 1994.',
    'set.reduceFlicker': 'Réduire les clignotements',
    'set.reduceFlicker.help': 'Adoucit les lumières qui clignotent et les flashs à l’écran pour les joueurs sensibles à la lumière.',
    'set.crosshair': 'Point de visée',
    'set.subtitles': 'Sous-titres',
    'set.captions': 'Sous-titres des sons',
    'set.captions.help': 'Affiche les sons importants sous forme de texte, comme [mastication au loin].',
    'set.subtitleSize': 'Taille des sous-titres',
    'set.master': 'Volume général',
    'set.music': 'Musique',
    'set.sfx': 'Effets',
    'set.ambience': 'Ambiance (bourdonnement, gouttes, pluie)',
    'set.entities': 'Sons des créatures',
    'set.voice': 'Voix et radio',
    'set.hrtf': 'Audio 3D (HRTF, casque conseillé)',
    'set.mouseSens': 'Sensibilité de la souris',
    'set.invertY': 'Inverser l’axe vertical',
    'set.touchSens': 'Sensibilité tactile',
    'set.toggleCrouch': 'S’accroupir : appuyer au lieu de maintenir',
    'set.toggleSprint': 'Courir : appuyer au lieu de maintenir',
    'set.lang': 'Langue',
    'set.difficulty': 'Difficulté',
    'set.difficulty.help': 'Agit sur la vitesse et l’ouïe des créatures et sur les piles de la lampe torche.',
    'set.jumpscare': 'Jump scares',
    'set.hints': 'Indices',

    'archive.title': 'Archives',
    'archive.count': '{n} / {m} documents',
    'archive.notFound': 'Pas encore trouvé',
    'kind.note': 'Note',
    'kind.letter': 'Lettre',
    'kind.diary': 'Page de journal',
    'kind.tape': 'Enregistrement',
    'kind.photo': 'Photographie',
    'kind.screen': 'Écran d’ordinateur',
    'kind.phone': 'Message téléphonique',
    'kind.printout': 'Listing',
    'kind.wall': 'Inscription au mur',
    'kind.notice': 'Avis',
    'kind.memory': 'Souvenir',
    'kind.drawing': 'Dessin',
    'kind.card': 'Carte',
    'kind.report': 'Rapport',
    'kind.flyer': 'Prospectus',
    'kind.doc': 'Document',

    'help.title': 'Comment jouer',
    'help.kbm': 'Clavier et souris',
    'help.walk': 'Marcher',
    'help.mouse': 'Souris',
    'help.look': 'Regarder autour (cliquer pour capturer)',
    'help.sprint': 'Courir (bruyant, coûte du souffle)',
    'help.crouch': 'S’accroupir (presque silencieux)',
    'help.interact': 'Interagir, lire, prendre, se cacher',
    'help.flash': 'Lampe torche',
    'help.drink': 'Boire un Star Pop',
    'help.throw': 'Lancer un bâton lumineux',
    'help.lean': 'Se pencher à gauche / à droite (regarder au coin)',
    'help.map': 'Carte',
    'help.bag': 'Objets / journal',
    'bag.items': 'OBJETS',
    'bag.journal': 'JOURNAL',
    'bag.close': 'Fermer (I / J)',
    'bag.empty': 'Vos poches sont vides.',
    'bag.inspectHint': 'Faites glisser pour le retourner.',
    'bag.now': 'EN CE MOMENT',
    'bag.story': 'L’HISTOIRE JUSQU’ICI',
    'bag.docs': 'TROUVÉ ICI',
    'bag.noDocs': 'Rien trouvé ici pour l’instant. Regardez mieux.',
    'bag.people': 'PERSONNES',
    'bag.freed': 'en paix',
    'bag.hunting': 'chasse encore',
    'bag.stats': 'Documents {a} / {b}   ·   Dessins de Lily {c} / {d}',
    'bag.n.flashlight': 'Lampe torche',
    'bag.d.flashlight': 'Une lourde lampe torche en acier, sortie de la camionnette de l’arcade. Pile : {n} %. Elle faiblit avant de mourir.',
    'bag.n.battery': 'Piles de rechange',
    'bag.d.battery': 'Des piles pour la lampe torche. R les met en place ; une lampe à plat les reçoit automatiquement.',
    'bag.n.almond': 'Star Pop',
    'bag.d.almond': 'Une canette du soda à la cerise de l’arcade, encore froide, allez savoir comment. Le sucre et les bulles calment les mains. À boire avec Q.',
    'bag.n.glow': 'Bâtons lumineux',
    'bag.d.glow': 'Pliez-en un et lancez-le avec G. Rampants et Ricaneurs ne franchissent pas la lumière verte.',
    'bag.d.officeKey': 'La clé du bureau de Walt, prise dans la caisse. Le laiton est usé jusqu’au lisse.',
    'bag.d.token': 'Un jeton Starlight percé d’une étoile. Uniquement pour la borne n° 7.',
    'bag.n.fuse': 'Fusibles',
    'bag.d.fuse': 'De lourds fusibles en céramique pour le vieux tableau de l’usine.',
    'bag.n.fuel': 'Bidons de gazole',
    'bag.d.fuel': 'Du gazole pour les groupes électrogènes. Il clapote fort. Marchez lentement.',
    'bag.d.keycard': 'Une carte de sécurité à bande magnétique. La photo de quelqu’un a été grattée.',
    'bag.d.key': 'Une clé avec une étiquette en papier. Elle ouvre quelque chose ici.',
    'help.pause': 'Pause',
    'help.touch': 'Tactile',
    'help.touchText': 'Stick de déplacement en bas à gauche, glissez sur la droite de l’écran pour regarder. Les boutons à droite : interagir, lampe torche, courir, s’accroupir, carte.',
    'help.survive': 'Rester en vie',
    'help.tip1': '<b>Le Dévoreur</b> est plus rapide que vous en ligne droite et lent dans les virages. Prenez les coins.',
    'help.tip2': 'Quand les néons se mettent à clignoter, <b>il est tout près</b>.',
    'help.tip3': 'Prenez une <b>lanterne</b> et tout vous fuit pendant quelques secondes.',
    'help.tip4': '<b>Le rouge</b> ne s’arrête jamais. <b>Le violet</b> vous coupe la route. <b>Le turquoise</b> entend l’eau et saute d’un endroit à l’autre. <b>L’ambre</b> se fige tant que vous le regardez.',
    'help.tip5': 'Vous pouvez <b>vous cacher</b> sous les bureaux et dans les casiers. Si rien ne vous voit entrer, rien ne vous trouvera.',
    'help.tip6': 'Les <b>magnétophones</b> sauvegardent la partie. La sauvegarde automatique a lieu aux objectifs, quand vous êtes en sécurité.',
    'help.tip7': 'Rapportez à chaque Spectre son objet, <b>à son autel</b>. La fin en dépend.',

    'pause.title': 'Pause',
    'pause.resume': 'Reprendre',
    'pause.map': 'Carte',
    'pause.journal': 'Journal',
    'pause.archive': 'Archives',
    'pause.settings': 'Options',
    'pause.help': 'Comment jouer',
    'pause.load': 'Charger la dernière sauvegarde',
    'pause.menu': 'Menu principal',

    'note.close': 'Fermer',
    'note.closeKey': 'Fermer (E)',

    'map.close': 'Fermer',
    'map.closeKey': 'Fermer (M)',
    'map.objective': 'Objectif',
    'map.tape': 'Cassette',
    'map.doc': 'Document',
    'map.shrine': 'Autel',
    'map.supply': 'Provisions',
    'map.locked': 'Porte verrouillée',

    'kp.label': 'SÉCURITÉ',
    'kp.clear': 'EFF',
    'kp.enter': 'OK',
    'kp.open': 'OUVERT',
    'kp.error': 'ERREUR',
    'kp.close': 'Annuler (Échap)',

    'cab.help': 'Flèches ou WASD · Entrée pour commencer · P pour la pause ·',
    'cab.exit': 'Quitter la borne (Échap)',

    'choice.back': 'Reculer',
    'card.skip': 'Cliquez ou appuyez sur E pour continuer',

    'death.retry': 'Reprendre à la dernière sauvegarde',
    'death.menu': 'Menu principal',

    'end.menu': 'Menu principal',
    'end.skip': 'Passer',
    'end.time': 'temps de jeu',
    'end.deaths': 'morts',
    'end.docs': 'documents',
    'end.freed': 'Spectres libérés',
    'end.drawings': 'dessins trouvés',

    'hud.objective': 'OBJECTIF',
    'hud.rec': 'REC',
    'hud.stamina': 'SOUFFLE',
    'hud.battery': 'LUMIÈRE',
    'hud.power': 'COURANT {t}',
    'hud.fps': '{n} IPS',

    'touch.pause': 'Pause',
    'touch.bag': 'SAC',
    'touch.map': 'CARTE',
    'touch.drink': 'BOIRE',
    'touch.throw': 'LANCER',
    'touch.crouch': 'ACCROUPI',
    'touch.sprint': 'COURIR',
    'touch.flash': 'LAMPE',
    'touch.tap': 'TOUCHER',

    'inv.battery': 'PILE ×{n}',
    'inv.almond': 'STAR POP ×{n}',
    'inv.glow': 'BÂTON LUMINEUX ×{n}',
    'inv.officeKey': 'CLÉ DU BUREAU',
    'inv.token': 'JETON D’OR',
    'inv.fuses': 'FUSIBLE ×{n}',
    'inv.fuel': 'GAZOLE ×{n}',
    'inv.keycard': 'CARTE DE SÉCURITÉ',
    'inv.pellets': 'LANTERNE ×{n}',

    'n.added': 'Ajouté aux archives : {title}',
    'n.saved': 'Partie sauvegardée',
    'n.batteryIn': 'Pile neuve dans la lampe torche',
    'n.batterySpare': 'Pile de rechange',
    'n.noSpare': 'Aucune pile de rechange.',
    'n.batteryFull': 'La pile est encore pleine.',
    'hint.reload': 'R : changer les piles de la lampe torche',
    'touch.reload': 'PILES',
    'help.reload': 'Changer les piles de la lampe torche',
    'help.lookBack': 'Regarder derrière soi en courant (maintenir)',
    'n.batterySwap': 'Vous avez mis une pile de rechange',
    'n.almond': 'Star Pop (Q pour boire)',
    'n.glow': 'Bâton lumineux (G pour lancer)',
    'n.found': 'Trouvé : {name}',
    'n.drank': 'Vous buvez le Star Pop. Votre respiration se calme.',
    'n.noAlmond': 'Vous n’avez pas de Star Pop.',
    'n.noGlow': 'Vous n’avez pas de bâton lumineux.',
    'n.slow': 'Le jeu tourne lentement. Pause › Options › Graphismes permet de baisser la qualité.',
    'n.lockFail': 'Impossible de capturer la souris. Maintenez le bouton gauche et faites glisser pour regarder.',
    'n.flashDead': 'Votre lampe torche s’est éteinte.',
    'n.holdBreath': 'Quelque chose est tout près. Maintenez Maj pour retenir votre souffle.',
    'n.heardBreath': 'Il a entendu votre respiration.',
    'n.noFlash': 'Vous n’avez pas de lampe torche.',
    'n.noBattery': 'La pile est morte. Trouvez-en une autre.',
    'n.grace': 'C’était moins une ! (Facile : une fois par chapitre)',
    'n.freed': '{name} est libre',
    'n.ghostBack': '{name} a reculé',
    'n.cabinetHi': 'Vos initiales sont au tableau des scores : SAM',
    'n.perfect': 'Vous avez mangé toutes les étoiles. Partie parfaite.',
    'n.fruit': 'Un prix est apparu devant la maison',
    'n.diesel': 'Bidon de gazole',
    'n.drawing': 'Dessin de Lily ({n}/8)',

    'pr.read': 'Lire : {title}',
    'pr.readWall': 'Lire l’inscription',
    'pr.screen': 'Regarder l’écran',
    'pr.tape': 'Écouter la cassette (sauvegarde la partie)',
    'pr.battery': 'Prendre la pile',
    'pr.almond': 'Prendre le Star Pop',
    'pr.glow': 'Prendre le bâton lumineux',
    'pr.flashlight': 'Prendre la lampe torche',
    'pr.token': 'Prendre le jeton',
    'pr.fuse': 'Prendre le fusible',
    'pr.fuel': 'Prendre le bidon de gazole',
    'pr.keycard': 'Prendre la carte de sécurité',
    'pr.take': 'Prendre : {name}',
    'pr.pellet': 'Prendre la lanterne',
    'pr.phoneRing': 'Répondre au téléphone',
    'pr.phone': 'Décrocher le combiné',
    'pr.cabinetFree': 'Jouer à la borne (FREE PLAY)',
    'pr.doorLocked': '{name} (verrouillée)',
    'pr.doorOpen': 'Ouvrir la porte',
    'pr.doorClose': 'Fermer la porte',
    'pr.drawerOpen': 'Ouvrir le tiroir',
    'pr.drawerClose': 'Fermer le tiroir',
    'pr.safeOpen': 'Ouvrir le coffre',
    'pr.safeClose': 'Fermer le coffre',
    'pr.safeLocked': 'Coffre (entrer la combinaison)',
    'pr.hide': 'Se cacher dessous',
    'pr.hideLocker': 'Se cacher dans le casier',
    'pr.unhide': 'Sortir',
    'pr.shrineLook': 'Regarder l’autel',
    'pr.shrinePlace': 'Déposer l’objet sur l’autel',
    'pr.drawing': 'Prendre le dessin de Lily',

    'door.default': 'Porte',
    'door.office': 'Porte du bureau',
    'door.storage': 'Réserve',
    'door.wc': 'Toilettes',
    'door.front': 'Porte d’entrée',
    'door.elevator': 'Monte-charge',
    'door.security': 'Poste de sécurité',
    'door.stair': 'Escalier de secours',
    'door.house': 'La maison des Spectres',
    'door.service': 'Ascenseur de service',
    'lock.service': 'L’ascenseur est mort. Les trois groupes électrogènes doivent tourner.',
    'door.exit': 'SORTIE',
    'door.room': 'Chambre {n}',
    'door.jammed': 'Porte',
    'lock.jammed': 'Coincée. La poignée tourne, mais quelque chose la retient de l’autre côté.',
    'lock.exit': 'La SORTIE est verrouillée. Pas encore.',
    'door.pressure': 'Porte étanche',
    'lock.pressure': 'La porte étanche ne bouge pas. La vapeur siffle derrière.',
    'door.janitor': 'Concierge',
    'lock.janitor': 'Un cadenas à combinaison. Trois chiffres.',
    'door.fireExit': 'Sortie de secours',
    'lock.fireExit': 'Une lourde chaîne et un cadenas. Le concierge a les clés.',
    'lock.fireExitMotel': 'La barre ne cède pas. Quelqu’un l’a bloquée de l’extérieur.',
    'door.gym': 'Gymnase',
    'door.mallExit': 'Portes du centre commercial',
    'lock.mallExit': 'Fermé pour la nuit. Au loin, le photomaton bourdonne.',
    'door.room12': 'Chambre 12',
    'lock.room12': 'Verrouillée. La plaque est polie, comme si quelqu’un la touchait tous les jours.',
    'door.room207': 'Chambre 207',
    'lock.room207': 'Verrouillée. Une affichette en papier : SILENCE SVP. Un soleil au crayon gras dessus.',
    'door.elevatorH': 'Ascenseur',
    'lock.elevatorH': 'L’ascenseur attend, portes fermées. Il attend quelque chose.',
    'door.samHouse': 'Votre maison',
    'door.tobyHouse': 'La maison de Toby',
    'door.neighbor': 'Porte d’entrée',
    'lock.neighbor': 'Verrouillée. Les rideaux bougent quand vous détournez les yeux.',
    'door.alley': 'Porte sur la ruelle',
    'lock.alley': 'Verrouillée. Pas avant un arrêt au coin de la rue.',
    'door.kernel': 'Porte en acier',
    'lock.kernel': 'De l’acier, et verrouillée. Une plaque de laiton : KERNEL — W. SEULEMENT.',
    'lock.default': 'Verrouillée.',
    'lock.office': 'Verrouillée. Une plaque de laiton sur la porte : « W. — GÉRANT ».',
    'lock.front': 'Cadenassée de l’extérieur. Les déménageurs ont la clé.',
    'lock.elevator': 'Le monte-charge n’a pas de courant. Le bouton d’appel est mort.',
    'lock.security': 'Le clavier demande un code à quatre chiffres.',
    'lock.stair': 'Le voyant du lecteur de carte est rouge. Il faut une carte de sécurité.',
    'lock.house': 'Un rideau de lumière violette. Quatre lanternes le tiennent fermé.',

    'cap.front': 'devant',
    'cap.back': 'derrière',
    'cap.left': 'à gauche',
    'cap.right': 'à droite',
    'cap.phone': '[un téléphone sonne]',
    'cap.drag': '[des pas traînants tout près]',
    'cap.moan': '[un gémissement]',
    'cap.farSteps': '[des pas ailleurs dans le bâtiment]',
    'cap.thud': '[quelque chose tombe, loin]',
    'cap.buzz': '[un néon grésille]',
    'cap.whisper': '[chuchotements]',
    'cap.giggle': '[un gloussement dans le noir]',
    'cap.radio': '[grésillement radio]',
    'cap.thunder': '[tonnerre]',
    'cap.hiss': '[un sifflement mouillé qui s’éloigne]',
    'cap.skitter': '[un grattement sur la brique]',
    'cap.whistle': '[un sifflet strident]',
    'cap.plastic': '[du plastique qui craque]',
    'cap.bite': '[des dents qui claquent tout près]',
    'cap.biteFar': '[mastication au loin]',
    'cap.callName': '[quelqu’un vous appelle avec la voix de Toby]',
    'cap.heavySteps': '[des pas lourds, un couinement de caoutchouc]',
    'cap.pipe': '[un tuyau résonne quelque part dans les tunnels]',
    'cap.locker': '[un casier claque au bout du couloir]',
    'cap.knock': '[trois coups, quelque part au bout du couloir]',
    'cap.beep': '[un moniteur bipe dans une chambre vide]',
    'cap.arc': '[l’électricité claque derrière la porte en acier]',
    'cap.pop': '[un tube éclate]',
    'cap.slam': '[une porte claque derrière vous]',
    'cap.run': '[quelqu’un court, hors de vue]',
    'cap.callJune': '[une voix de femme au bout du couloir : « Eddie ? Eddie, c’est toi ? »]',
    'cap.car': '[une voiture file en sifflant sur la route mouillée]',
    'cap.door': '[une porte, quelque part]',
    'cap.drip': '[des gouttes]',
    'cap.hum': '[bourdonnement des néons]',
    'tab.access': 'Accessibilité',
    'tab.perf': 'Performances',
    'set.perfOverlay': 'Affichage des performances',
    'set.perfOverlay.help': 'Montre comment tourne le jeu. IPS seules ; Simple ajoute le temps par image, les temps CPU et GPU par image et leur charge ; Détaillé ajoute un graphe du temps par image, les appels de dessin, les triangles, la mémoire, la résolution de rendu et votre carte graphique. Le temps GPU demande un navigateur qui expose les requêtes de minutage GPU (la version de bureau le fait toujours).',
    'set.perfCorner': 'Position de l’affichage',
    'set.perfCorner.help': 'Le coin de l’écran où se place l’affichage des performances.',
    'opt.perfFps': 'IPS seules',
    'opt.perfBasic': 'Simple',
    'opt.perfDetailed': 'Détaillé',
    'opt.cornerTR': 'En haut à droite',
    'opt.cornerTL': 'En haut à gauche',
    'opt.cornerBR': 'En bas à droite',
    'opt.cornerBL': 'En bas à gauche',
    'preset.ultraplus': 'Ultra+',
    'opt.ultraplus': 'Ultra+',
    'opt.shadow4': 'Ultra+ (8192)',
    'set.modelDetail': 'Détail des modèles',
    'set.modelDetail.help': 'La finesse avec laquelle sont construits les créatures, les mains et les autres modèles sculptés. Plus haut, c’est plus lisse de près et plus long à charger. Ultra+ est pour les processeurs les plus rapides.',
    'set.clutter': 'Objets de détail',
    'set.clutter.help': 'Combien de petites choses remplissent les pièces : tableaux, photos, calendriers, cartons, papiers, bouteilles. Plus rend chaque pièce habitée ; moins ménage les machines anciennes.',
    'set.dof': 'Profondeur de champ',
    'set.dof.help': 'Floute ce qui est loin de l’endroit que vous regardez, comme un objectif. La mise au point suit le centre de l’écran. Les réglages élevés prennent plus d’échantillons pour un flou plus doux et plus propre.',
    'set.textureRes.help': 'La netteté des surfaces : murs, sols, bois, tissu. Plus haut demande plus de mémoire vidéo.',
    'set.shadows.help': 'Les ombres de votre lampe torche et des lampadaires dehors. Plus haut est plus net. Ultra+ utilise une carte d’ombres 8192 et demande beaucoup de mémoire vidéo.',
    'set.antialias.help': 'Lisse les bords crénelés. Le MSAA est le plus propre ; le FXAA est léger et adoucit un peu toute l’image ; les deux ensemble donnent le plus lisse.',
    'set.dynLights.help': 'Combien de lampes proches peuvent éclairer à la fois les objets en mouvement et les créatures.',
    'set.bloom.help': 'La lueur douce autour des lumières vives et des écrans.',
    'set.bloomStrength.help': 'La force de cette lueur.',
    'set.motionBlur.help': 'Floute l’image quand vous tournez vite. Vos mains et ce que vous tenez restent nets.',
    'set.particles.help': 'Poussière dans l’air, pluie, étincelles et gouttes.',
    'set.viewDist.help': 'Jusqu’où les objets sont dessinés et jusqu’où le brouillard laisse voir.',
    'set.anisotropy.help': 'Garde les sols et les murs nets vus en angle rasant. Coûte très peu.',
    'set.contrast.help': 'L’écart entre les parties sombres et claires de l’image.',
    'set.saturation.help': 'La force des couleurs. Plus bas, on se rapproche d’une vieille photo.',
    'set.fov.help': 'La largeur de votre vision. Plus large montre plus, mais tout paraît plus loin.',
    'set.headBob.help': 'L’amplitude du balancement de la vue à chaque pas. Baissez-le s’il vous donne la nausée.',
    'set.shake.help': 'Tremblement de la caméra lors des frayeurs, des chocs et de la course.',
    'set.grain.help': 'Grain de film sur l’image.',
    'set.chromatic.help': 'Des franges colorées sur les bords de l’image, comme avec un objectif bon marché.',
    'set.vignette.help': 'Assombrissement vers les coins de l’écran.',
    'set.crosshair.help': 'Un petit point au centre de l’écran pour viser les objets à prendre.',
    'set.subtitles.help': 'Affiche ce qui se dit : talkie-walkie, cassettes, pensées.',
    'set.subtitleSize.help': 'La taille des sous-titres et des sous-titres de sons.',
    'set.master.help': 'Le volume d’ensemble.',
    'set.music.help': 'Le volume de la musique.',
    'set.sfx.help': 'Pas, portes, objets et tout ce que vous faites.',
    'set.ambience.help': 'Les pièces, la pluie, le bourdonnement et les bruits du bâtiment.',
    'set.entities.help': 'Les créatures : leurs pas, leur souffle et leurs voix.',
    'set.voice.help': 'Talkie-walkie, cassettes et pensées.',
    'set.hrtf.help': 'Place les sons autour de vous en trois dimensions. Idéal au casque ; à couper sur des enceintes.',
    'set.mouseSens.help': 'La vitesse à laquelle la vue tourne avec la souris.',
    'set.invertY.help': 'Monter la souris fait regarder vers le bas.',
    'set.touchSens.help': 'La vitesse à laquelle la vue tourne quand vous glissez sur un écran tactile.',
    'set.toggleCrouch.help': 'Appuyez une fois pour vous accroupir et une fois pour vous relever, au lieu de maintenir la touche.',
    'set.toggleSprint.help': 'Appuyez une fois pour courir et une fois pour marcher, au lieu de maintenir la touche.',
    'set.lang.help': 'La langue des menus, des sous-titres et de chaque document du jeu.',
    'set.jumpscare.help': 'Réduit conserve chaque frayeur mais adoucit les flashs et les sons les plus violents.',
    'set.hints.help': 'De courts conseils quand quelque chose de nouveau arrive.',
    'perf.frame': 'Image',
    'perf.low1': '1 % bas',
    'perf.cpu': 'CPU',
    'perf.cpuUse': 'Charge CPU',
    'perf.gpu': 'GPU',
    'perf.gpuUse': 'Charge GPU',
    'perf.na': 'n.d.',
    'perf.draws': 'Appels de dessin',
    'perf.tris': 'Triangles',
    'perf.textures': 'Textures',
    'perf.programs': 'Shaders',
    'perf.res': 'Rendu',
    'perf.heap': 'Mémoire JS',
    'perf.sysCpu': 'CPU système',
    'perf.appCpu': 'CPU du jeu',
    'perf.procMem': 'Mémoire du jeu',
    'perf.card': 'Carte graphique',
    'settings.revert': 'Annuler',
    'settings.keys': '↑↓ choisir · ←→ modifier · Q/E onglets · Retour arrière annuler · Échap retour',
    'settings.impact': 'Coût en performances',
    'impact.0': 'Aucun',
    'impact.1': 'Faible',
    'impact.2': 'Moyen',
    'impact.3': 'Élevé',
    'impact.4': 'Très élevé',
    'impact.5': 'Extrême',
    'settings.gpuLoad': 'Charge GPU estimée',
    'settings.vram': 'Mémoire vidéo estimée',
    'settings.reloadBadge': 'S’applique au prochain chargement de chapitre',
    'settings.restartBadge': 'S’applique au redémarrage du jeu',
    'settings.restartNow': 'Redémarrer maintenant',
  });
})(typeof window !== 'undefined' ? window : globalThis);
