/* Interface française pour l’histoire d’Ada Lind : remplace ce qui appartenait à l’ancienne histoire et ajoute
   ce dont les neuf étagères ont besoin (portes, escaliers, types de documents, sous-titres). Chargé après ui.js. */
(function (root) {
  'use strict';
  root.PB.I18N.register('fr', 'ui', {
    'game.subtitle': 'OBJETS TROUVÉS',
    'menu.credit': 'Halvard · 13 janvier 1998 · 02:56',
    'diff.time': 'Durée de jeu estimée : 5 à 7 heures pour qui lit chaque document et trouve les huit dessins.',
    'set.vhs.help': 'Montre le jeu comme à travers un vieux caméscope familial.',
    'help.drink': 'Sucer un sucre d’orge',
    'bag.stats': 'Documents {a} / {b}   ·   Dessins de Wren {c} / {d}',
    'bag.d.flashlight': 'Une lourde lampe torche gainée de caoutchouc, prise sous le guichet du Dépôt 9. Pile : {n} %. Elle faiblit avant de mourir.',
    'bag.n.almond': 'Sucre d’orge',
    'bag.d.almond': 'Un sucre d’orge torsadé tiré de la boîte sous le guichet, gardé pour les mauvaises nuits. Le sucre calme les mains. À sucer avec Q.',
    'bag.d.officeKey': 'Une petite clé en laiton, polie par l’usage.',
    'bag.d.token': 'Un jeton en laiton.',
    'help.padText': 'Stick gauche : marcher. Stick droit : regarder. A : interagir. B : s’accroupir. X : changer les piles. Y : lampe. LB / RB : se pencher. RT ou clic du stick gauche : courir. LT : bâton lumineux. Clic du stick droit : regarder derrière. Croix : ↑ journal, ↓ sucre d’orge, → objets. Affichage : carte. Menu : pause. Dans les menus, la croix déplace, A valide et B revient.',
    'help.tip7': 'Au fond de chaque lieu, il y a un mensonge. <b>Remettez la chose perdue à sa place</b>, et le chemin s’ouvre.',
    'map.shrine': 'Réclamation',
    'end.freed': 'Étagères réclamées',
    'end.claimed': 'Étagères réclamées',
    'inv.almond': 'SUCRE D’ORGE ×{n}',
    'inv.token': 'JETON',
    'n.almond': 'Sucre d’orge (Q pour le sucer)',
    'n.drank': 'Vous sucez le sucre d’orge. Votre respiration se calme.',
    'n.noAlmond': 'Vous n’avez pas de sucre d’orge.',
    'n.drawing': 'Dessin de Wren ({n}/8)',
    'pr.almond': 'Prendre le sucre d’orge',
    'pr.drawing': 'Prendre le dessin de Wren',
    'door.house': 'La maison',
    'touch.drink': 'SUCRE',
    'inv.pellets': 'LUMIÈRES PERDUES ×{n}',
    'pr.pellet': 'Prendre la lumière perdue',
    'lock.house': 'Un rideau de lumière. Quatre lumières perdues le tiennent fermé.',
    'help.tip1': '<b>Écoutez avant de regarder.</b> Chaque créature a sa propre règle : certaines entendent, certaines ne voient que la lumière, certaines ne bougent que si personne ne les regarde. Les documents vous disent lesquelles.',
    'help.tip2': 'Quand les lumières se mettent à bégayer, ou que le son se retire du monde, <b>quelque chose est proche</b>.',
    'help.tip3': 'Dans le Dessous, prenez une <b>lumière perdue</b> et le Dévoreur se tient à distance quelques secondes.',
    'help.tip4': 'Chaque étagère a <b>ses propres créatures</b> : un contrôleur qui vérifie les billets, des chevaux qui ne courent que tant que l’orgue joue, des pins qui ne bougent que lorsque vous bougez. Apprenez la règle de chacune.',
    'help.tip5': 'Vous pouvez vous <b>cacher</b> sous les lits, les couchettes et les bureaux, et dans les casiers. Si rien ne vous a vue entrer, rien ne viendra regarder.',
    'help.tip6': 'Le jeu <b>sauvegarde tout seul</b> à chaque objectif, quand vous êtes en sécurité.',
    'set.subtitles.help': 'Affiche ce qui se dit : canal neuf, cassettes, pensées.',
    'set.voice.help': 'Canal neuf, cassettes et pensées.',
    // portes et passages des neuf étagères
    'pr.unlock': 'Déverrouiller',
    'pr.stairs': 'Prendre l’escalier',
    'pr.stairsDown': 'Descendre l’escalier',
    'pr.stairsUp': 'Monter l’escalier',
    'pr.ladderDown': 'Descendre l’échelle',
    'pr.ladderUp': 'Monter à l’échelle',
    'door.otto': 'Le bureau d’Otto Brandt',
    'lock.otto': 'Fermé à clé depuis 1964. La clé doit être quelque part dans les archives.',
    'door.concourse': 'Le hall',
    'lock.concourse': 'Fermé de l’autre côté.',
    'door.bridge': 'La passerelle',
    'lock.bridge': 'Fermée à clé. C’est le capitaine qui a la clé.',
    'door.cage': 'La cage',
    'lock.cage': 'La grille de la cage. Sans courant, rien ne bouge.',
    'door.fire': 'La porte coupe-feu',
    'lock.fire': 'Coincée par une cale. De ce côté-ci.',
    'door.signe': 'Stuegata 4',
    'lock.signe': 'Fermé à clé. Une lampe brûle à l’intérieur.',
    'door.ghost': 'Le train fantôme',
    // types de documents
    'kind.telegram': 'Télégramme',
    'kind.transcript': 'Transcription',
    'kind.clipping': 'Journal',
    // sous-titres des sons
    'hint.flash': 'F allume et éteint la lampe.',
    'cap.chute': '[un colis tombe dans la goulotte]',
    'cap.tube': '[le tube pneumatique cogne]',
    'cap.bellFar': '[une cloche, au loin dans le brouillard]',
    'cap.doorShut': '[une porte se ferme quelque part]',
    'cap.stepsFar': '[des pas, loin]',
    'cap.organ': '[un orgue de foire se met à jouer tout seul]',
    'cap.organStop': '[l’orgue ralentit et se tait]',
    'cap.choir': '[un chœur, qui chante]',
    'cap.knocks': '[sept coups, sur de l’acier]',
    'cap.ice': '[la glace craque, au loin]',
    'cap.brake': '[des freins qui hurlent]',
    'cap.laugh': '[des rires]',
    'cap.toll': '[une cloche sonne le glas]',
    'cap.breath': '[une respiration, juste derrière vous]',
    'cap.train': '[le train, à pleine vitesse]',
    'cap.pa': '[un carillon ; le haut-parleur grésille]',
  });
})(typeof window !== 'undefined' ? window : globalThis);
