/* Türkçe hikâye çekirdeği: karakterler, ortak replikler, ölümler, ipuçları, sonlar, jenerik.
   Hikâye kılavuzu docs/STORY.md’dir. */
(function (root) {
  'use strict';
  root.PB.I18N.register('tr', 'story', {
    chars: {
      sam: { name: 'Sam', pos: 'Sam’in', role: 'Tri-County Nakliyat’ın gece şoförü, 20 yaşında. 1987’de 13 yaşındaydı, beşinci müdavim. Sen.' },
      walt: { name: 'Walt', pos: 'Walt’ın', role: 'Starlight Oyun Salonu’nun sahibi. Önce hava kuvvetlerinde radar teknisyeni, sonra televizyon tamircisi. Mart 1992’den beri kayıp.' },
      lily: { name: 'Lily', pos: 'Lily’nin', role: 'Walt’ın kızı. Ekim 1983’te dokuz yaşında öldü. Puanı: 3.190.' },
      danny: { name: 'Danny', pos: 'Danny’nin', role: '1987’de 16 yaşında. Gürültücü, korkusuz, rekor tablosunda bir numara. Walt’ın yedek anahtarı ondaydı.' },
      rosie: { name: 'Rosie', pos: 'Rosie’nin', role: '1987’de 15 yaşında. Planları hep o yapardı. Kendi radyo programını istiyordu.' },
      nell: { name: 'Nell', pos: 'Nell’in', role: '1987’de 15 yaşında. Sessiz, çizgi roman çizen, kalın gözlüklü. Havuzdaki o öğleden sonra için kendini hiç affetmedi.' },
      toby: { name: 'Toby', pos: 'Toby’nin', role: '1987’de 13 yaşında. Sam’in en yakın arkadaşı. Karanlıktan korkardı.' },
      eddie: { name: 'Eddie', pos: 'Eddie’nin', role: 'Walt’ın 1984–1988 arası yardımcısı. Haziran 1993’te onların peşinden içeri girdi. Hiç kucağına almadığı bir kızı var.' },
      nora: { name: 'Nora', pos: 'Nora’nın', role: 'Walt’ın küçük kız kardeşi.' },
      frank: { name: 'Frank Dobbs', pos: 'Dobbs’un', role: 'Harlow polisinde dedektif, 1987.' },
      june: { name: 'June', pos: 'June’un', role: 'Eddie’nin karısı. Blue Moon Motelinde gece resepsiyonisti.' },
      theo: { name: 'Theo', pos: 'Theo’nun', role: 'Nell’in küçük kardeşi.' },
      maggie: { name: 'Maggie', pos: 'Maggie’nin', role: 'Toby’nin annesi.' },
      ruth: { name: 'Ruth', pos: 'Ruth’un', role: '1985’e kadar Walt’ın karısı.' },
      ray: { name: 'Ray', pos: 'Ray’in', role: 'Danny’nin babası.' },
      carol: { name: 'Carol', pos: 'Carol’ın', role: 'Rosie’nin annesi.' },
      ann: { name: 'Ann', pos: 'Ann’in', role: 'Sam’in annesi.' },
    },
    speakers: { sam: 'SAM', eddie: 'EDDIE', walt: 'WALT', danny: 'DANNY', rosie: 'ROSIE', nell: 'NELL', toby: 'TOBY', lily: 'LILY', june: 'JUNE', radio: 'TELSİZ', voice: '???' },
    items: {},
    obj: {
      ghost: '{pos} eşyasını sunağa götür (isteğe bağlı)',
    },
    recap: {
      prolog: 'Starlight Oyun Salonu, açık artırmadan önceki gece. 7 numaralı makine fişi prizde değilken çalışıyordu ve adımı biliyordu. PLAYER 1: SAM — CONTINUE?',
      lobby: 'Hiç bitmeyen sarı odalar: oyuncusunu bekleyen oyun. Karanlıkta yuvarlak, soluk bir şey yiyor. Eddie yaşıyor; telsizde, 1993’ten beri içeride.',
      mill: 'Danny’nin babasının deposu. Danny beni "Bıraktın!" diye bağırarak kovaladı. Babasının saatini geri verdim; durdu ve adını hatırladı.',
      pipes: 'Yağmur suyu tünelleri. Kalemiz. Dördüncü kural: kimse eve yalnız gitmez. O kuralı ben yazmıştım.',
      pool: 'Nell bir resmi bitirirken Theo’nun neredeyse boğulduğu havuz. Yıllardır affedilmeyi bekliyor. Theo onu daha ilk mektubunda affetmişti.',
      office: 'Rosie’nin annesinin ofisi, bir-sıfır-yedi-üç. Kasetinde, gece 12:40’ta salonun arka kapısı çalınıyor. Rosie: "Bakın kim sürünerek geri gelmiş."',
      school: '16 Nisan 1987. Anlaşma: beş el birden kolda, kimse bırakmıyor. Altta beş imza. Sonuncusu benim.',
      dark: 'Karanlık, üç jeneratör ve pirinç bir çakmak. Toby’nin son sayfası Sam’in geri döndüğünü yazıyor. Geri döndüğümü hatırlamıyordum.',
      mall: '1986’nın en güzel cumartesisi: tek bir fotoğraf kabininde beş çocuk ve biri benim, gülüyorum. Mankenler sadece başımı çevirince kıpırdadı.',
      motel: 'Eddie’nin anısı, benim değil. Oda 12 ve defteri: BİRİ GİRER, BİRİ ÇIKAR. Yerine birinin kalması gerekiyor. O kişinin ben olmasını istiyordu.',
      hospital: 'St. Agnes, Ekim 1983. Lily babasından hiç bitmeyen bir oyun istedi, kimse gitmek zorunda kalmasın diye. Walt onu yaptı.',
      maple: 'Benim sokağım. Gece 2:50’de telesekreterde annemin sesi, neredesin diye soruyor. 21:40’ta eve gitmedim.',
      workshop: 'Walt’ın bodrumu ve 3:17 kaseti. Kolda beş el vardı ve biri bıraktı. Benimki.',
      maze: '255. seviye, evin kendisi. Hatırlayan hayaletler renkli ışıklar olarak yanımda yürüyor.',
      killscreen: '256. seviye. Bozuk taraf. Beş el isteyen bir fiş ve birini dışarı bırakan bir kapı.',
    },
    memento: {
      danny: { name: 'Danny’nin saati', line: 'Camı çatlak çelik bir kol saati, 3:17’de durmuş. Arkasına kazınmış: "RAY KOWALSKI — 25 YIL — HARLOW DEĞİRMENİ".' },
      rosie: { name: 'Rosie’nin kaseti', line: 'İçinde kaset olan mor bir walkman. Etiketinde: B YÜZÜ: SONRASI İÇİN. B yüzü boş.' },
      nell: { name: 'Nell’in gözlüğü', line: 'Kalın bir gözlük, bir camı çatlak. Elinde buğulanıyor, sanki biri az önce üstüne nefes vermiş.' },
      toby: { name: 'Toby’nin çakmağı', line: 'Eski pirinç bir çakmak. Üstüne kazınmış: "TOBY — HİÇ KARANLIKTA KALMAYASIN DİYE. DEDEN".' },
    },
    freed: {
      danny: ['DANNY: "3:17. Saatim durdu. Ben hiç durmadım."', 'DANNY: "...Geri geldin. Epey sürdü, Keller. Git. Koca şeyi ben oyalarım."'],
      rosie: ['ROSIE: "B yüzü. Sonra kaydedecektik. Kazandıktan sonra."', 'ROSIE: "Hep herkesin önünde koştum. Artık yanında yürüyeceğim."'],
      nell: ['NELL: "Gözlüğüm. Her şey öyle... net ki."', 'NELL: "Emin olmayı beklemekten vazgeçtim. Seninle geliyorum."'],
      toby: ['TOBY: "Dedemin çakmağı..." (Alev tutuşuyor. Yüzünü ilk defa görüyorsun: on üç yaşında, çilli bir çocuk.)', 'TOBY: "...Bana henüz bakma Sam. Sadece yürü. Hemen arkandayım."'],
    },
    shrine: {
      quiet: 'Sunak sessiz. Mum yanmaya devam ediyor.',
      missing: 'Küçük bir sunak. Çerçevede {pos} bir fotoğrafı ve bir şeyin durması gereken boş bir yer.',
    },
    mono: {
      watcherSeen: 'Uzakta, uzun ve kapkara bir şey duruyor. Başı bir yana eğik. Sayıyor.',
      hide: 'Nefesini tut.',
      hideLocker: 'Nefesini tut. Kıpırdama.',
      fearHigh: 'Nefes alamıyorum...',
      lowBattery: 'Pil bitiyor.',
      freed: '{name} artık beni kovalamıyor.',
      eaterFlicker: 'Işıklar sönükleşiyor. Yakında. Çiğnediğini duyabiliyorum.',
    },
    ghostHelp: {
      danny: 'DANNY: "Koş! Onu ben tutuyorum!"',
      amberWatch: 'TOBY: "Bakma bana... lütfen bakma..."',
    },
    deaths: {
      eater: ['YENDİN', 'Yiyici düz koridorda senden hızlı, dönüşlerde yavaştır. Köşe dön ve çiğneme sesini dinle.'],
      red: ['YAKALANDIN', 'Danny hiç durmaz, kovalamayı asla bırakmaz. Görüş hattını kır, aranıza bir köşe koy.'],
      violet: ['ÖNÜN KESİLDİ', 'Rosie senin olduğun yere değil, gideceğin yere gider. Gözden kaybolduğunda yön değiştir.'],
      teal: ['DİBE ÇEKİLDİN', 'Nell suyu duyar. Su birikintilerinden uzak dur, kenarlardan yürü.'],
      amber: ['DONAKALDIN', 'Toby sen ona bakarken kıpırdayamaz. Gözünü ya da ışığını üstünde tut.'],
      grinner: ['GÜLÜMSEDİ', 'Sırıtanlar ışıkta erir. Feneri üstlerinde tut ya da bir ışık çubuğu bırak.'],
      watcher: ['SAYILDIN', 'Sayıcı sadece sen bakmazken hareket eder. Ona uzun süre sırtını dönme.'],
      crawler: ['SÜRÜKLENDİN', 'Sürüngenler ışıktan geri çekilir, sonra etrafından dolaşır. Sırtını duvara ver, birini ışıkta çok uzun tutma.'],
      monitor: ['İZİN KÂĞIDI YOK', 'Koridor Gözcüsü sadece fenerinin değdiği yeri görür. Işık seni bulmadan bir dolaba gir.'],
      mannequin: ['POZ VERDİN', 'Mankenler sadece kimse bakmazken kıpırdar. Gerekirse geri geri yürü.'],
      neighbor: ['İÇERİ ALDIN', 'Komşu sen sırtını dönünce yaklaşır. Fenerin onu geri çekilmeye zorlar. Sese asla cevap verme.'],
      chompy: ['KOCAMAN SARILMA', 'Chompy yavaştır ama hiç durmaz. Gözlerine ışık tutarsan yüzünü saklar.'],
    },
    tips: [
      'Yiyici düz koridorda senden hızlıdır ama dönüşlerde yavaşlar. Köşe dön.',
      'Koşmak gürültülüdür. Eğilerek yürümek neredeyse sessizdir; eğilince kapıları da sessizce açarsın.',
      'Işıklar sönükleşip titremeye başladıysa Yiyici yakındadır.',
      'Bir fener aldığında her şey birkaç saniyeliğine senden kaçar.',
      'Kaset çalarlar oyunu kaydeder ve bir anıyı dinletir.',
      'Masaların, yatakların ve tezgâhların altına, dolapların içine saklanabilirsin. Girerken seni gören olmadıysa kimse bakmaz.',
      'Her hayaletin eşyasını kendi sunağına götürürsen seni avlamayı bırakır. Son buna bağlı.',
      'Bir Star Pop sinirlerini yatıştırır ve nefesini toparlar.',
      'M tuşu keşfettiğin yerlerin haritasını açar.',
      'Fener pili hızlı bitirir. Işık çubukları (G) bir köşeyi aydınlatır; düşerken çıkardıkları ses avcıları senden uzaklaştırır.',
      'Kehribar renkli olana bakmaya devam et. Ama çok uzun değil.',
      'Lily geride sekiz çizim bıraktı. Bazıları çok iyi saklanmış.',
      'Eddie burayı herkesten iyi bilir. Bu, sana her şeyi anlattığı anlamına gelmez.',
      'Dolaplar seni tamamen saklar. Bir şey yaklaşınca nefesini tutmak için Shift’e basılı tut.',
      'Mankenler sen onlara bakarken kıpırdayamaz.',
      'Komşu tanıdığın sesleri kullanır. Cevap verme.',
      'Walt günlüğünden beş sayfa kopardı. Göründüklerinden daha önemliler.',
      'Parmak kalınlığında aralık bırakılmış bir çekmecede bir şey vardır. Kapısı kilitlenmemiş bir kasada da.',
      'Koşarken omzunun üstünden arkana bakmak için V’yi (ya da orta fare tuşunu) basılı tut.',
      'Ne kadar uzun sessizlik olursa o kadar yaklaşırlar. Oyun beklemeyi sevmez.',
    ],
    endings: {
      exit: {
        title: 'ÇIKIŞ', subtitle: 'Kötü son — Yine',
        lines: [
          'Kapıdan geçiyorsun. Arkanda Eddie adını haykırıyor, sonra kapı kapanıyor ve haykırış öbür tarafta kalıyor.',
          'Soğuk hava. Yağmur. Gözlerini salonun ıslak halısında açıyorsun. Sabah olmuş. Kepenkler yarı açık.',
          '7 numaralı makine hâlâ çalışıyor. Tanıtım ekranında artık beş hayalet dolaşıyor. Beşincisinin üstünde bir iş ceketi var.',
          'Nakliyeciler onu öğlen kamyona yüklüyor. Şoför sonradan, 9 numaralı yol boyunca makinenin içinden birinin vurduğunu duyduğunu anlatacak.',
          'Kamyon açık artırmaya hiç varmıyor.',
          'Onları bir daha asla bırakmayacağına söz vermiştin. İkincisi daha kolay oldu. En kötüsü de bu.',
        ],
      },
      deal: {
        title: 'ANLAŞMA', subtitle: 'Karanlık son — Biri girer, biri çıkar',
        lines: [
          'Kapıyı tutuyorsun. Eddie uzun bir an sana bakıyor. "Onlara anlatacağım. Hepsine senin kim olduğunu anlatacağım."',
          'İçeri adım atıyor. Kapı yavaşça kapanıyor, biten bir kaset gibi.',
          'Harlow’da bir yerde, şafak vakti sırılsıklam bir adam bir mutfağa giriyor; mama sandalyesindeki bir yaşında bir kız ona bakakalıyor.',
          'Ev sessiz. Uzakta yuvarlak bir şey yeniden çiğnemeye başlıyor.',
          'Oyuncu değilsin. Hayalet değilsin. Kalan kişisin. Yıldızlar parlıyor. Her birinin nerede olduğunu biliyorsun.',
          'Boş bir oyun salonundaki rekor tablosunda, kimsenin açıklayamadığı bir el yazısıyla yeni bir satır: SAM — HÂLÂ OYNUYOR.',
        ],
      },
      plug: {
        title: 'OYUN BİTTİ', subtitle: 'İyi son — Kimse bırakmaz',
        lines: [
          'Dört renkli ışık ellerinin üstüne kapanıyor. Kırmızı, mor, turkuaz, kehribar. Anlaşmada yazdığı gibi beş el.',
          'Çekiyorsun. Fiş çıkıyor. 1987’den beri ilk kez uğultu susuyor.',
          'Karanlıkta, çok yakından, yorgun ama insan bir ses: "Doydum Sam. Sonunda."',
          'Salonun halısında uyanıyorsun. Şafak camdan içeri süzülüyor.',
          'Yerde, 1987’nin montlarıyla dört çocuk oturmuş, gözlerini kırpıştırıyor. Toby sana uzun uzun bakıyor. "Sam? ...Yaşlanmışsın." Sonra sana canını acıtacak kadar sıkı sarılıyor.',
          'Maple Sokağı’nda yedi yıldır yanan bir veranda lambası sönüyor.',
          'Eddie boş sokaklardan eve yürüyor. Koşmuyor. Yolu hatırlamak istiyor.',
          '7 numaralı makine kapkara. Camda tek bir satır yanık kalmış: GAME OVER — 5 PLAYERS.',
        ],
      },
      lil: {
        title: 'LIL', subtitle: 'Gerçek son — Tablodaki isimler',
        lines: [
          'Sekiz çizimi çekirdeğin üstüne bırakıyorsun. Kâğıtta pastel boya: salon, boynuzlu turuncu bir Chompy, bir hastane penceresi, bir baba.',
          'Yiyici çiğnemeyi bırakıyor. Uzun süre sessiz kalıyor. Sonra çocukluğundan hatırladığın bir sesle: "...Bunları Lily çizmişti."',
          'Yiyici’nin olduğu yerde Walt duruyor: zayıf, gri ve kendisi. "İndir ellerini evlat. Bunu ben çekeceğim. Hep benim işimdi."',
          'Dört renkli ışık onun ellerinin üstüne kapanıyor. Çekiyor. Ev kâğıt gibi katlanıyor.',
          'Son gördüğün şey, hastane önlüklü küçük bir kızın onun elini tutması ve ikisinin yıldızların arasındaki karanlığa yürümesi.',
          'Şafak. Salonun halısında dört çocuk. Dışarıda ankesörlü telefonda Eddie, hem gülüyor hem ağlıyor. "June? June, benim."',
          'Bir hafta sonra Nora salonu son bir kez açıyor ve rekor tablosunu tanıdığı bir el yazısıyla yeniden yazılmış buluyor. 1 LIL. 2 DAN. 3 ROS. 4 NEL. 5 TOB. 6 SAM. 7 WALT.',
          'Toby’nin veranda lambası sönüyor. Maple Sokağı’nda artık çocuk olmayan iki kişi kaldırıma oturup öğlene kadar konuşuyor. Sam ona her şeyi anlatıyor. O zaten biliyordu.',
        ],
      },
    },
    credits: [
      ['LEVEL 256', 'Starlight Oyun Salonu'],
      ['Birinci şahıs bir korku oyunu', ''],
      ['Adanmıştır', 'bir şeyi bırakıp sonra onun için geri dönen herkese'],
      ['Hungry House', 'bu hikâye için yaratılmış, kurgusal bir 1981 salon oyunu'],
      ['Ses', 'anlık olarak sentezlendi, tek bir kayıt yok'],
      ['Doku ve modeller', 'hepsi prosedürel, tek bir resim dosyası yok'],
      ['Oyunculara', 'gece yarısından sonra 7 numaralı makineye asla jeton atmayın'],
    ],
  });
})(typeof window !== 'undefined' ? window : globalThis);
