/* Türkçe hikâye çekirdeği: karakterler, ortak replikler, ölümler, ipuçları, sonlar, jenerik. */
(function (root) {
  'use strict';
  root.PB.I18N.register('tr', 'story', {
    chars: {
      sam: { name: 'Sam', pos: 'Sam’in', role: 'Otomat taşıyıcısı, 20 yaşında. 1987’de 13 yaşındaydı, beşinci müdavim. Sen.' },
      walt: { name: 'Walt', pos: 'Walt’ın', role: 'Starlight atari salonunun sahibi. Eski hava kuvvetleri radar teknisyeni. Mart 1992’den beri kayıp.' },
      lily: { name: 'Lily', pos: 'Lily’nin', role: 'Walt’ın kızı. Ekim 1983’te, dokuz yaşında öldü.' },
      billy: { name: 'Billy', pos: 'Billy’nin', role: '1987’de 16 yaşında. Gürültücü, korkusuz, rekor tablosunda bir numara.' },
      penny: { name: 'Penny', pos: 'Penny’nin', role: '1987’de 15 yaşında. Planlayıcı. Radyo DJ’i olmak istiyordu.' },
      ivy: { name: 'Ivy', pos: 'Ivy’nin', role: '1987’de 15 yaşında. Sessiz, çizgi roman çizen, hiçbir şeyden emin olamayan.' },
      clyde: { name: 'Clyde', pos: 'Clyde’ın', role: '1987’de 13 yaşında. Sam’in en yakın arkadaşı. Karanlıktan korkar.' },
      eddie: { name: 'Eddie', pos: 'Eddie’nin', role: 'Walt’ın 1984–1988 arası yardımcısı. Haziran 1993’te onların peşinden içeri girdi.' },
      nora: { name: 'Nora', pos: 'Nora’nın', role: 'Walt’ın kız kardeşi.' },
      frank: { name: 'Frank', pos: 'Frank’in', role: 'Harlow polisi dedektifi, 1987.' },
      june: { name: 'June', pos: 'June’un', role: 'Eddie’nin karısı.' },
      theo: { name: 'Theo', pos: 'Theo’nun', role: 'Ivy’nin küçük kardeşi.' },
      maggie: { name: 'Maggie', pos: 'Maggie’nin', role: 'Clyde’ın annesi.' },
      ruth: { name: 'Ruth', pos: 'Ruth’un', role: '1985’e kadar Walt’ın karısı.' },
    },
    speakers: { sam: 'SAM', eddie: 'EDDIE', walt: 'WALT', billy: 'BILLY', penny: 'PENNY', ivy: 'IVY', clyde: 'CLYDE', lily: 'LILY', radio: 'TELSİZ', voice: '???' },
    items: {},
    recap: {
      prolog: 'Starlight Oyun Salonu, açık artırmadan önceki gece. 7 numaralı makineye son bir kez bakmaya geldim, o da bana baktı. 255. seviye. Sonra zemin yok oldu.',
      lobby: 'Hiç bitmeyen sarı odalar. Yiyici sese göre avlanıyor. Telsizde 1993’ten Eddie. Dört güç hapı aşağı inen yolu açtı.',
      mill: 'Billy’nin babasının fabrikası. Billy beni herkesi kovaladığı gibi kovaladı. Saatini geri verdim; durdu ve hatırladı.',
      pipes: 'Yağmur suyu tünelleri. Kalemiz. Dördüncü kural: kimse eve yalnız gitmez. Buharı boşalttım, sürüngenler geçmeme izin verdi.',
      pool: 'Theo’nun yaralandığı havuz. Ivy emin olmak için on yıl bekledi. Gözlüğünü geri verdim, yeniden görebildi.',
      office: 'Penny’nin annesinin ofisi. Bir-sıfır-yedi-üç, onun radyo istasyonu. Kasetinin B yüzü hâlâ boş.',
      school: '16 Nisan 1987. Beşimizin birlikte olduğu son gün. Clyde’a hiç vermediğim not hâlâ 217 numaralı dolaba bantlıydı.',
      dark: 'Karanlık. Üç jeneratör ve bir çakmak. Karanlıktan hep Clyde korkardı. Artık korkmuyor.',
      mall: '1986’nın en güzel cumartesisi: tek bir fotoğraf kabininde beş çocuk. Mankenler sadece başımı çevirince kıpırdadı.',
      motel: 'Eddie’nin anısı, benim değil. Oda 12. BİRİ GİRER, BİRİ ÇIKAR. Kapıyı benim tutmamı istedi. Hiç kucağına almadığı bir kızı var.',
      hospital: 'St. Agnes, Ekim 1983. Walt’ın kızı Lily, dokuz yaşında, 3.190 puan. Bütün bunları kimse bir daha gitmesin diye yaptı.',
      maple: 'Benim sokağım, Clyde’a kaybol dediğim gece. Geri dönecektim. Uyuyakaldım.',
      workshop: 'Walt’ın bodrumu. Eddie gece yarısı filmi için arka kapıyı açık bıraktı; Walt, Billy’ye bir anahtar verdi. İki, beş, altı: sayaç 256’yı gösteriyor.',
      maze: '255. seviye, oyunun kendisi. Dört renkli ışık artık beni avlamıyor, peşimden geliyor.',
      killscreen: '256. seviye. Bozuk taraf. Bir fiş, bir kapı ve bir seçim.',
    },
    memento: {
      billy: { name: 'Billy’nin saati', line: 'Camı çatlak bir kol saati. Akrep ve yelkovan 3:17’de donmuş. Arkasında: "Fabrikada 25 yıl için."' },
      penny: { name: 'Penny’nin kaseti', line: 'İçinde kaset olan pembe bir walkman. El yazısı etiket: "B YÜZÜ: SONRASI İÇİN". B yüzü boş.' },
      ivy: { name: 'Ivy’nin gözlüğü', line: 'Kalın bir gözlük, bir camı çatlak. Buğulanmış, sanki biri az önce üstüne nefes vermiş.' },
      clyde: { name: 'Clyde’ın çakmağı', line: 'Eski pirinç bir çakmak. Üstüne kazınmış: "Clyde’a, hiç karanlıkta kalmayasın diye. —Dedesi".' },
    },
    freed: {
      billy: ['BILLY: "3:17. Saatim durmuş. Ben hiç durmadım."', 'BILLY: "Hepsini buraya ben sürükledim. Ben ve o anahtar. Git. Artık seni kovalamayacağım."'],
      penny: ['PENNY: "B yüzü. Hiç kaydedemedik."', 'PENNY: "Hep herkesin önünde koştum. Bu sefer yanında yürüyeceğim."'],
      ivy: ['IVY: "Gözlüğüm! Her şey... net."', 'IVY: "Emin olmayı beklemekten yoruldum. Seninle geliyorum."'],
      clyde: ['CLYDE: "Dedemin çakmağı..." (Alev tutuşuyor. Yüzünü ilk defa görüyorsun: bir çocuk.)', 'CLYDE: "...Bana henüz bakma Sam. Sadece yürü."'],
    },
    shrine: {
      quiet: 'Sunak sessiz. Mum yanmaya devam ediyor.',
      missing: 'Küçük bir sunak. Çerçevede {pos} fotoğrafı. Burada bir şey eksik.',
    },
    mono: {
      watcherSeen: 'Uzakta, uzun ve kapkara bir şey duruyor. Başı bir yana eğik. Sayıyor.',
      hide: 'Nefesini tut.',
      fearHigh: 'Nefes alamıyorum...',
      lowBattery: 'Pil bitiyor.',
      freed: '{name} artık beni kovalamıyor. Işığı yumuşadı.',
      eaterFlicker: 'Işıklar titriyor. Yakında.',
    },
    ghostHelp: {
      billy: 'BILLY: "Koş! Onu ben tutuyorum!"',
      clydeWatch: 'CLYDE: "Bakma bana... lütfen bakma..."',
    },
    deaths: {
      pacman: ['YUTULDUN', 'Yutucu seni buldu. Köşeleri kullan: düz koridorlarda senden hızlı, dönüşlerde yavaş.'],
      blinky: ['YAKALANDIN', 'Billy hiç durmaz. Görüş hattını kır ve köşe dön.'],
      pinky: ['PUSUYA DÜŞTÜN', 'Penny baktığın yöne doğru önünü keser. Arkana bakarak yürümeyi dene.'],
      inky: ['KAYBOLDUN', 'Ivy, sen suda ses çıkardıkça yaklaşır. Kenarlardan yürü.'],
      clyde: ['DONDUN', 'Clyde sen bakarken kıpırdayamaz. Işığını onun üstünde tut.'],
      grinner: ['GÜLÜMSEDİ', 'Sırıtkanlar ışıktan kaçar. Feneri üzerlerinde tut ya da ışık çubuğu at.'],
      watcher: ['SAYILDIN', 'Sayaç sen bakmazken yaklaşır. Ona uzun süre sırtını dönme.'],
      crawler: ['AŞAĞI ÇEKİLDİN', 'Sürüngenler ışıktan nefret eder. Feneri üzerlerinde tut ya da arkana bir ışık çubuğu bırak.'],
      monitor: ['KORİDOR İZNİ YOK', 'Koridor Gözcüsü sadece fenerinin değdiği yeri görür. Işık seni bulmadan bir dolaba gir.'],
      mannequin: ['POZ VERDİN', 'Mankenler sadece kimse bakmazken kıpırdar. Gerekirse geri geri yürü.'],
      neighbor: ['İÇERİ ALDIN', 'Komşu, sen sırtını dönünce yaklaşır. Fenerin onu geri adım attırır.'],
      chompy: ['KOCAMAN SARILMA', 'Chompy yavaştır ama hiç durmaz. Gözlerine ışık tut, yüzünü saklar.'],
    },
    tips: [
      'Yutucu düz koridorda senden hızlıdır ama dönüşlerde yavaşlar. Köşe dön.',
      'Koşmak ses çıkarır. Eğilerek yürümek neredeyse sessizdir.',
      'Işıklar titremeye başladıysa Yutucu yakındadır.',
      'Güç hapı yuttuğunda her şey sekiz saniyeliğine senden kaçar.',
      'Kaset çalarlar oyunu kaydeder ve bir anıyı dinletir.',
      'Masaların altına ve dolapların içine saklanabilirsin. Seni girerken görmedilerse bulamazlar.',
      'Hayaletlerin eşyalarını türbelerine götürürsen seni avlamayı bırakırlar. Son için önemli.',
      'Badem suyu korkunu yatıştırır ve nefesini toparlar.',
      'M tuşu keşfettiğin yerlerin haritasını açar.',
      'Karanlıkta fener pili hızlı biter. G ile yere ışık çubuğu bırak.',
      'Turuncu olana bakmaya devam et. Ama çok uzun değil.',
      'Lily geride sekiz çizim bıraktı. Bazıları çok iyi saklanmış.',
      'Eddie bu yer hakkında çok şey biliyor. Söylediği her şey tüm gerçek değil.',
      'Grafik ayarlarından çözünürlük ölçeğini %200’e kadar çıkarabilirsin.',
      'Dolaplar seni tamamen saklar. Koridor gözcüleri onları hiç kontrol etmez.',
      'Mankenler sen onlara bakarken kıpırdayamaz. Sen de sonsuza kadar bakamazsın.',
      'Komşu tanıdığın sesleri kullanır. Cevap verme.',
      'Walt günlüğünden beş sayfa kopardı. Göründüklerinden daha önemliler.',
      'Sürüngenler unutulmuş şeyleri yer. Işığı açık tut, unutulmazsın.',
    ],
    endings: {
      exit: {
        title: 'ÇIKIŞ', subtitle: 'Kötü son — Tek başına',
        lines: [
          'Kapı arkandan kapanıyor. Soğuk hava. Yağmur kokusu.',
          'Gözlerini açtığında salonun ıslak zeminindesin. Sabah olmuş. Kepenkler yarı açık.',
          '7 numaralı kabin hâlâ çalışıyor. Ekranda dört hayalet, labirentin ortasında bekliyor.',
          'Nakliyeciler onu öğlen kamyona yüklüyor. Şoför sonradan arka kasadan bir ses duyduğunu söyleyecek. Vaka, vaka.',
          'Kamyon müzayedeye hiç varmıyor.',
          'Onları bir daha asla bırakmayacağına söz vermiştin. Onları yine bıraktın.',
        ],
      },
      deal: {
        title: 'ANLAŞMA', subtitle: 'Karanlık son — Biri çıkar, biri kalır',
        lines: [
          'Kapıyı tutuyorsun. Eddie uzun bir an sana bakıyor. "Onlara anlatacağım. Hepsine seni anlatacağım."',
          'İçeri adım atıyor. Kapı kendi kendine, yavaşça kapanıyor. Biten bir kaset gibi.',
          'Harlow’da bir yerde, şafak vakti sırılsıklam bir adam bir mutfağa giriyor ve bir yaşındaki bir kız ona bakıyor.',
          'Açsın.',
          'Labirent sessiz. Noktalar parlıyor. Her birinin nerede olduğunu tam olarak biliyorsun.',
          'Boş bir atari salonundaki rekor tablosunda yeni bir satır yanıyor: 7 SAM.',
        ],
      },
      plug: {
        title: 'OYUN BİTTİ', subtitle: 'İyi son — Herkes evine dönüyor',
        lines: [
          'Dört renkli ışık ellerinin üstüne kapanıyor. Kırmızı, pembe, mavi, turuncu. Birlikte çekiyorsunuz.',
          'Fiş çıkıyor. Ses kesiliyor. Vızıltı ilk defa susuyor.',
          'Karanlıkta çok yakından, yorgun ama insan bir ses: "Doydum Sam. Sonunda doydum."',
          'Salonun zemininde uyanıyorsun. Şafak camdan içeri süzülüyor.',
          'Halının üstünde, 1987’nin montlarıyla dört çocuk oturmuş, gözlerini kırpıştırıyor. Clyde sana bakıyor. "Sam? ...Yaşlanmışsın."',
          'Dışarıda yağmur dinmiş. Maple Sokağı’nda yedi yıldır yanan bir veranda lambası sonunda sönüyor.',
          'Eddie boş sokaklardan eve yürüyor. Koşmuyor. Yolu hatırlamak istiyor.',
          '7 numaralı kabin kapkara. Ekranda tek bir satır kalmış: OYUN BİTTİ — 5 OYUNCU.',
        ],
      },
      lil: {
        title: 'LIL', subtitle: 'Gerçek son — Tablodaki isimler',
        lines: [
          'Sekiz çizimi çekirdeğin üstüne bırakıyorsun. Kâğıt üstünde pastel boya: salon, sarı bir kostüm, bir hastane penceresi, bir baba.',
          'Yutucu duruyor. Uzun süre sessiz kalıyor. Sonra 1985’ten hatırladığın bir sesle: "...Bunları Lily çizmişti."',
          'Yutucu’nun olduğu yerde Walt duruyor. Zayıf, gri ve kendisi. "İndir ellerini Sam. Bunu ben çekeceğim."',
          'Fişi çekiyor. Labirent kâğıt gibi katlanıyor.',
          'Son gördüğün şey, hastane önlüklü küçük bir kızın onun elini tutması ve ikisinin noktaların arasındaki karanlığa yürümesi.',
          'Şafak. Salonun halısında dört çocuk. Dışarıda kaldırımda Eddie, bir ankesörlü telefona gülüp ağlıyor. "June? June, benim."',
          'Bir hafta sonra Nora salonu son bir kez açıyor ve rekor tablosunu tanıdığı bir el yazısıyla yeniden yazılmış buluyor. 1 LIL. 2 BLY. 3 PNY. 4 IVY. 5 CLY. 6 SAM. 7 WLT.',
          'Clyde’ın veranda lambası sönüyor. Maple Sokağı’nda artık çocuk olmayan iki çocuk kaldırıma oturup öğlene kadar konuşuyor.',
        ],
      },
    },
    credits: [
      ['PACMAN: ARKA ODALAR', ''],
      ['Bir kaçış ve korku oyunu', ''],
      ['Adanmıştır', 'Starlight atari salonuna son jetonunu atan herkese'],
      ['Klasik labirent', '1980 atari orijinaline saygıyla'],
      ['Ses', 'tarayıcında anlık olarak üretildi'],
      ['Dokular', 'hepsi prosedürel, tek bir resim dosyası yok'],
      ['Oyunculara', 'gece yarısından sonra hiçbir Pacman kabinine jeton atmayın'],
    ],
  });
})(typeof window !== 'undefined' ? window : globalThis);
