/* Türkçe arayüz metinleri. */
(function (root) {
  'use strict';
  root.PB.I18N.register('tr', 'ui', {
    'game.title': 'PACMAN',
    'game.subtitle': 'ARKA ODALAR',
    'game.aria': 'Oyun görüntüsü',
    'noscript': 'Bu oyun için JavaScript gerekiyor.',

    'boot.init': 'Başlatılıyor…',
    'boot.fonts': 'Yazı tipleri yükleniyor…',
    'boot.prep': 'Bölüm hazırlanıyor…',
    'boot.noThree': '3D motoru (three.js) yüklenemedi. İnternet bağlantını kontrol edip sayfayı yenile.',
    'boot.error': 'Başlatma hatası: {msg}',
    'load.textures': 'Dokular dokunuyor… ({n}/{m})',
    'load.walls': 'Duvarlar örülüyor…',
    'load.bake': 'Işık pişiriliyor…',
    'load.fixtures': 'Floresanlar takılıyor…',
    'load.props': 'Eşyalar yerleştiriliyor…',
    'load.decals': 'Lekeler ve izler…',
    'load.shaders': 'Gölgelendiriciler derleniyor…',
    'load.ready': 'Hazır',
    'load.error': 'Yükleme hatası: {msg}',

    'first.title': 'Başlamadan önce',
    'first.lang': 'Dil',
    'first.bright': 'Parlaklığı, soldaki simge zar zor, sağdaki ise net görünene kadar ayarla.',
    'first.phones': 'En iyisi kulaklıkla, karanlık bir odada.',
    'first.go': 'Devam',

    'menu.continue': 'Devam et',
    'menu.new': 'Yeni oyun',
    'menu.levels': 'Bölümler',
    'menu.settings': 'Ayarlar',
    'menu.archive': 'Arşiv',
    'menu.help': 'Nasıl oynanır',
    'menu.credit': 'Harlow · 30 Kasım 1994 · 02:11',
    'menu.foot': 'Kulaklıkla, karanlıkta oyna.',
    'menu.footDone': 'Sonlar: {list} · ölüm {deaths}',

    'confirm.title': 'Yeni oyun?',
    'confirm.body': 'Kayıtlı ilerlemenin üzerine yazılacak. Bulduğun belgeler arşivde kalır.',
    'confirm.yes': 'Evet, baştan başla',
    'confirm.no': 'Vazgeç',

    'diff.title': 'Zorluk',
    'diff.easy': 'Kolay',
    'diff.easyDesc': 'Hikâyeye odaklan. Yaratıklar daha yavaş ve daha az dikkatli. Her bölümde bir kez yakalanmaktan kurtulursun.',
    'diff.normal': 'Normal',
    'diff.normalDesc': 'Tasarlandığı gibi. Tek yakalanma, son kayda dönüş.',
    'diff.nightmare': 'Kâbus',
    'diff.nightmareDesc': 'Daha hızlı, daha keskin kulaklı yaratıklar. Piller çabuk biter. Korku daha erken basar.',
    'diff.time': 'Tahmini oyun süresi: tüm belgeleri okuyan ve dört hayaleti kurtaran biri için 4–6 saat.',

    'levels.title': 'Bölümler',
    'levels.locked': 'Kilitli',

    'common.back': 'Geri',
    'common.on': 'Açık',
    'common.off': 'Kapalı',

    'settings.title': 'Ayarlar',
    'settings.reset': 'Varsayılanlar',
    'settings.reloadNote': '* işaretli ayarlar bir sonraki bölüm yüklemesinde uygulanır.',
    'tab.graphics': 'Grafik',
    'tab.display': 'Görüntü',
    'tab.audio': 'Ses',
    'tab.controls': 'Kontroller',
    'tab.gameplay': 'Oynanış',
    'preset.low': 'Düşük',
    'preset.medium': 'Orta',
    'preset.high': 'Yüksek',
    'preset.ultra': 'Ultra',
    'preset.extreme': 'Aşırı',
    'preset.custom': 'Özel',
    'opt.off': 'Kapalı',
    'opt.low': 'Düşük',
    'opt.medium': 'Orta',
    'opt.high': 'Yüksek',
    'opt.ultra': 'Ultra',
    'opt.extreme': 'Aşırı',
    'opt.shadow1': 'Düşük (1024)',
    'opt.shadow2': 'Yüksek (2048)',
    'opt.shadow3': 'Ultra (4096)',
    'opt.small': 'Küçük',
    'opt.large': 'Büyük',
    'opt.full': 'Tam',
    'opt.reduced': 'Azaltılmış',

    'set.preset': 'Kalite ön ayarı',
    'set.preset.help': 'Aşağıdaki grafik ayarlarını tek seferde değiştirir. Aşırı, üst seviye ekran kartları için.',
    'set.renderScale': 'Çözünürlük ölçeği',
    'set.renderScale.help': '%100 üstü daha yüksek çözünürlükte çizip küçültür: daha keskin görüntü, çok daha fazla GPU yükü.',
    'set.textureRes': 'Doku çözünürlüğü',
    'set.shadows': 'Gölgeler',
    'set.antialias': 'Kenar yumuşatma',
    'set.lightmapRes': 'Pişmiş ışık kalitesi',
    'set.lightmapRes.help': 'Yumuşak pişmiş ışığın ve gölgelerin detayı.',
    'set.dynLights': 'Dinamik ışıklar',
    'set.bloom': 'Işıma (bloom)',
    'set.bloomStrength': 'Işıma şiddeti',
    'set.volumetric': 'Hacimsel ışık ve toz',
    'set.ao': 'Ortam kapatma (SSAO)',
    'set.ao.help': 'Köşelerde, mobilyaların altında ve fayans aralarında yumuşak temas gölgeleri.',
    'set.ssr': 'Ekran alanı yansımaları',
    'set.ssr.help': 'Islak zeminlerde, fayanslarda, camda ve parlak metalde gerçek yansımalar.',
    'set.volumetric.help': 'Işın izlemeli ışık huzmeleri, el feneri ışını ve süzülen toz. Aşırı ayarda çok ağırdır.',
    'set.motionBlur': 'Hareket bulanıklığı',
    'set.lensDirt': 'Lens kiri',
    'set.lensDirt.help': 'Parlak ışığı yakalayan kamera merceği lekeleri.',
    'set.particles': 'Parçacık yoğunluğu',
    'set.viewDist': 'Görüş mesafesi',
    'set.anisotropy': 'Anizotropik süzme',
    'set.showFps': 'FPS göstergesi',
    'set.brightness': 'Parlaklık',
    'set.brightness.help': 'En karanlık köşeler zar zor görünecek şekilde ayarla.',
    'set.contrast': 'Kontrast',
    'set.saturation': 'Renk doygunluğu',
    'set.fov': 'Görüş alanı',
    'set.headBob': 'Kafa sallanması',
    'set.shake': 'Kamera sarsıntısı',
    'set.grain': 'Film greni',
    'set.chromatic': 'Renk sapması',
    'set.vignette': 'Kenar kararması',
    'set.vhs': 'El kamerası (VHS) görünümü',
    'set.vhs.help': 'Oyunu 1994 model bir el kamerasının vizöründen gösterir.',
    'set.reduceFlicker': 'Yanıp sönmeyi azalt',
    'set.reduceFlicker.help': 'Işığa duyarlı oyuncular için titreşen ışıkları ve ekran flaşlarını yumuşatır.',
    'set.crosshair': 'Nişangâh noktası',
    'set.subtitles': 'Altyazılar',
    'set.captions': 'Ses altyazıları',
    'set.captions.help': 'Önemli sesleri [uzakta çiğneme sesi] gibi yazıyla gösterir.',
    'set.subtitleSize': 'Altyazı boyutu',
    'set.master': 'Ana ses',
    'set.music': 'Müzik',
    'set.sfx': 'Efektler',
    'set.ambience': 'Ortam (uğultu, damlalar, yağmur)',
    'set.entities': 'Yaratık sesleri',
    'set.voice': 'Sesler ve telsiz',
    'set.hrtf': '3D ses (HRTF, kulaklık önerilir)',
    'set.mouseSens': 'Fare hassasiyeti',
    'set.invertY': 'Dikey bakışı ters çevir',
    'set.touchSens': 'Dokunmatik bakış hassasiyeti',
    'set.toggleCrouch': 'Eğilme: basılı tutmak yerine aç/kapa',
    'set.toggleSprint': 'Koşma: basılı tutmak yerine aç/kapa',
    'set.lang': 'Dil',
    'set.difficulty': 'Zorluk',
    'set.difficulty.help': 'Yaratıkların hızını, duyuşunu ve fener pilini etkiler.',
    'set.jumpscare': 'Ani korkutmalar',
    'set.hints': 'İpuçları',

    'archive.title': 'Arşiv',
    'archive.count': '{n} / {m} belge',
    'archive.notFound': 'Henüz bulunmadı',
    'kind.note': 'Not',
    'kind.letter': 'Mektup',
    'kind.diary': 'Defter sayfası',
    'kind.tape': 'Kaset kaydı',
    'kind.photo': 'Fotoğraf',
    'kind.screen': 'Bilgisayar ekranı',
    'kind.phone': 'Telefon mesajı',
    'kind.printout': 'Çıktı',
    'kind.wall': 'Duvar yazısı',
    'kind.notice': 'Duyuru',
    'kind.memory': 'Anı',
    'kind.drawing': 'Çizim',
    'kind.card': 'Kart',
    'kind.report': 'Rapor',
    'kind.flyer': 'El ilanı',
    'kind.doc': 'Belge',

    'help.title': 'Nasıl oynanır',
    'help.kbm': 'Klavye ve fare',
    'help.walk': 'Yürü',
    'help.mouse': 'Fare',
    'help.look': 'Etrafına bak (tıklayınca kilitlenir)',
    'help.sprint': 'Koş (gürültülü, nefes tüketir)',
    'help.crouch': 'Eğil (neredeyse sessiz)',
    'help.interact': 'Etkileşim, oku, al, saklan',
    'help.flash': 'Fener',
    'help.drink': 'Badem suyu iç',
    'help.throw': 'Işık çubuğu at',
    'help.map': 'Harita',
    'help.pause': 'Duraklat',
    'help.touch': 'Dokunmatik',
    'help.touchText': 'Sol altta yürüme çubuğu, ekranın sağında parmağını sürükleyerek bakış. Sağdaki düğmeler: etkileşim, fener, koş, eğil, harita.',
    'help.survive': 'Hayatta kalmak',
    'help.tip1': '<b>Yutucu</b> düz koridorlarda senden hızlı, dönüşlerde yavaş. Köşe dön.',
    'help.tip2': 'Floresanlar titremeye başladıysa <b>o yakında</b>.',
    'help.tip3': '<b>Güç hapı</b> yutunca her şey birkaç saniye senden kaçar.',
    'help.tip4': '<b>Kırmızı</b> hiç durmaz. <b>Pembe</b> önüne geçer. <b>Mavi</b> kestirilemez. <b>Turuncu</b> ise sen bakarken donar.',
    'help.tip5': 'Masaların altına ve dolapların içine <b>saklanabilirsin</b>. Seni girerken görmedilerse bulamazlar.',
    'help.tip6': '<b>Kaset çalarlar</b> oyunu kaydeder. Otomatik kayıt, hedeflerde ve güvendeyken yapılır.',
    'help.tip7': 'Her hayaletin eşyasını <b>türbesine</b> götür. Son buna bağlı.',

    'pause.title': 'Duraklatıldı',
    'pause.resume': 'Devam et',
    'pause.map': 'Harita',
    'pause.archive': 'Arşiv',
    'pause.settings': 'Ayarlar',
    'pause.help': 'Nasıl oynanır',
    'pause.load': 'Son kayıttan yükle',
    'pause.menu': 'Ana menü',

    'note.close': 'Kapat',
    'note.closeKey': 'Kapat (E)',

    'map.close': 'Kapat',
    'map.closeKey': 'Kapat (M)',
    'map.objective': 'Hedef',
    'map.tape': 'Kaset',
    'map.doc': 'Belge',
    'map.shrine': 'Türbe',
    'map.supply': 'Malzeme',
    'map.locked': 'Kilitli kapı',

    'kp.label': 'GÜVENLİK',
    'kp.clear': 'SİL',
    'kp.enter': 'GİR',
    'kp.open': 'AÇIK',
    'kp.error': 'HATA',
    'kp.close': 'Vazgeç (Esc)',

    'cab.help': 'Ok tuşları veya WASD · Enter başla · P duraklat ·',
    'cab.exit': 'Kabinden ayrıl (Esc)',

    'choice.back': 'Geri çekil',
    'card.skip': 'Geçmek için tıkla veya E',

    'death.retry': 'Son kayıttan devam et',
    'death.menu': 'Ana menü',

    'end.menu': 'Ana menü',
    'end.skip': 'Geç',
    'end.time': 'oyun süresi',
    'end.deaths': 'ölüm',
    'end.docs': 'belge',
    'end.freed': 'kurtarılan hayalet',
    'end.drawings': 'bulunan çizim',

    'hud.objective': 'HEDEF',
    'hud.rec': 'KAYIT',
    'hud.stamina': 'NEFES',
    'hud.battery': 'FENER',
    'hud.power': 'GÜÇ {t}',
    'hud.fps': '{n} FPS',

    'touch.pause': 'Duraklat',
    'touch.map': 'HARİTA',
    'touch.drink': 'İÇ',
    'touch.throw': 'AT',
    'touch.crouch': 'EĞİL',
    'touch.sprint': 'KOŞ',
    'touch.flash': 'FENER',
    'touch.tap': 'DOKUN',

    'inv.battery': 'PİL ×{n}',
    'inv.almond': 'BADEM SUYU ×{n}',
    'inv.glow': 'IŞIK ÇUBUĞU ×{n}',
    'inv.officeKey': 'OFİS ANAHTARI',
    'inv.token': 'ALTIN JETON',
    'inv.fuses': 'SİGORTA ×{n}',
    'inv.fuel': 'MAZOT ×{n}',
    'inv.keycard': 'GÜVENLİK KARTI',
    'inv.pellets': 'GÜÇ HAPI ×{n}',

    'n.added': 'Arşive eklendi: {title}',
    'n.saved': 'Oyun kaydedildi',
    'n.batteryIn': 'Fenere yeni pil taktın',
    'n.batterySpare': 'Yedek pil',
    'n.batterySwap': 'Yedek pili taktın',
    'n.almond': 'Badem suyu (Q ile iç)',
    'n.glow': 'Işık çubuğu (G ile at)',
    'n.found': 'Bulundu: {name}',
    'n.drank': 'Badem suyunu içiyorsun. Nefesin düzeliyor.',
    'n.noAlmond': 'Badem suyun yok.',
    'n.noGlow': 'Işık çubuğun yok.',
    'n.slow': 'Oyun yavaş çalışıyor. Duraklat › Ayarlar › Grafik’ten kaliteyi düşürebilirsin.',
    'n.lockFail': 'Fare kilitlenemedi. Sol tuşu basılı tutup sürükleyerek etrafına bak.',
    'n.flashDead': 'Fenerin söndü.',
    'n.grace': 'Kıl payı kurtuldun! (Kolay: bölüm başına bir kez)',
    'n.freed': '{name} özgür',
    'n.ghostBack': '{name} geri çekildi',
    'n.cabinetHi': 'Baş harflerin rekor tablosuna yazıldı: SAM',
    'n.perfect': 'Bütün pelletleri yedin. Mükemmel oyun.',
    'n.fruit': 'Evin önünde bir meyve belirdi',
    'n.diesel': 'Mazot bidonu',
    'n.drawing': 'Lily’nin çizimi ({n}/8)',

    'pr.read': 'Oku: {title}',
    'pr.readWall': 'Yazıyı oku',
    'pr.screen': 'Ekrana bak',
    'pr.tape': 'Kaseti dinle (oyunu kaydeder)',
    'pr.battery': 'Pili al',
    'pr.almond': 'Badem suyunu al',
    'pr.glow': 'Işık çubuğunu al',
    'pr.flashlight': 'Feneri al',
    'pr.token': 'Jetonu al',
    'pr.fuse': 'Sigortayı al',
    'pr.fuel': 'Mazot bidonunu al',
    'pr.keycard': 'Güvenlik kartını al',
    'pr.take': 'Al: {name}',
    'pr.pellet': 'Güç hapını yut',
    'pr.phoneRing': 'Telefonu aç',
    'pr.phone': 'Ahizeyi kaldır',
    'pr.cabinetFree': 'Kabinde oyna (BEDAVA)',
    'pr.doorLocked': '{name} (kilitli)',
    'pr.doorOpen': 'Kapıyı aç',
    'pr.doorClose': 'Kapıyı kapat',
    'pr.hide': 'Masanın altına saklan',
    'pr.unhide': 'Saklandığın yerden çık',
    'pr.shrineLook': 'Sunağa bak',
    'pr.shrinePlace': 'Eşyayı sunağa bırak',
    'pr.drawing': 'Lily’nin çizimini al',

    'door.default': 'Kapı',
    'door.office': 'Ofis kapısı',
    'door.storage': 'Depo',
    'door.wc': 'Tuvalet',
    'door.front': 'Giriş kapısı',
    'door.elevator': 'Yük asansörü',
    'door.security': 'Güvenlik odası',
    'door.stair': 'Yangın merdiveni',
    'door.house': 'Hayalet evi',
    'door.service': 'Servis asansörü',
    'lock.service': 'Asansör ölü. Üç jeneratörün de çalışması gerekiyor.',
    'door.exit': 'ÇIKIŞ',
    'lock.default': 'Kilitli.',
    'lock.office': 'Kilitli. Kapıda pirinç bir levha: "W. — MÜDÜR".',
    'lock.front': 'Dışarıdan asma kilitle kapatılmış. Anahtar nakliyecilerde.',
    'lock.elevator': 'Asansörün elektriği yok. Çağrı düğmesi ölü.',
    'lock.security': 'Tuş takımı dört haneli bir şifre istiyor.',
    'lock.stair': 'Kart okuyucunun ışığı kırmızı. Güvenlik kartı gerekiyor.',
    'lock.house': 'Pembe bir enerji perdesi. Dört güç hapı onu kapalı tutuyor.',

    'cap.front': 'önünde',
    'cap.back': 'arkanda',
    'cap.left': 'solunda',
    'cap.right': 'sağında',
    'cap.waka': '[yakında çiğneme sesi: vaka, vaka]',
    'cap.wakaFar': '[uzakta çiğneme sesi]',
    'cap.phone': '[bir telefon çalıyor]',
    'cap.drag': '[yakında sürüklenen ayak sesleri]',
    'cap.moan': '[bir inleme]',
    'cap.thud': '[uzakta bir şey düştü]',
    'cap.buzz': '[bir floresan çıtırdıyor]',
    'cap.whisper': '[fısıltı]',
    'cap.giggle': '[karanlıkta kıkırdama]',
    'cap.radio': '[telsiz cızırtısı]',
    'cap.thunder': '[gök gürültüsü]',
    'cap.door': '[bir yerlerde bir kapı]',
    'cap.drip': '[damlama]',
    'cap.hum': '[floresan vızıltısı]',
  });
})(typeof window !== 'undefined' ? window : globalThis);
