/* Türkçe arayüz metinleri. */
(function (root) {
  'use strict';
  root.PB.I18N.register('tr', 'ui', {
    'game.title': 'PACMAN',
    'game.subtitle': 'ARKA ODALAR',
    'game.aria': 'Oyun görüntüsü',
    'noscript': 'Bu oyun için JavaScript gerekiyor.',

    'boot.init': 'Başlatılıyor…',
    'boot.fonts': 'Yazı tipleri yükleniyor…',
    'boot.sounds': 'Sesler kaydediliyor…',
    'boot.voices': 'Sesler (konuşmalar) kaydediliyor…',
    'boot.prep': 'Bölüm hazırlanıyor…',
    'boot.noThree': '3D motoru (three.js) yüklenemedi. İnternet bağlantını kontrol edip sayfayı yenile.',
    'boot.error': 'Başlatma hatası: {msg}',
    'load.textures': 'Dokular dokunuyor… ({n}/{m})',
    'load.walls': 'Duvarlar örülüyor…',
    'load.bake': 'Işık pişiriliyor…',
    'load.fixtures': 'Floresanlar takılıyor…',
    'load.props': 'Eşyalar yerleştiriliyor…',
    'load.decals': 'Lekeler ve izler…',
    'load.shaders': 'Gölgelendiriciler derleniyor…',
    'load.ready': 'Hazır',
    'load.error': 'Yükleme hatası: {msg}',

    'first.title': 'Başlamadan önce',
    'first.lang': 'Dil',
    'first.bright': 'Parlaklığı, soldaki simge zar zor, sağdaki ise net görünene kadar ayarla.',
    'first.phones': 'En iyisi kulaklıkla, karanlık bir odada.',
    'first.go': 'Devam',

    'menu.continue': 'Devam et',
    'menu.new': 'Yeni oyun',
    'menu.levels': 'Bölümler',
    'menu.settings': 'Ayarlar',
    'menu.archive': 'Arşiv',
    'menu.help': 'Nasıl oynanır',
    'menu.credit': 'Harlow · 30 Kasım 1994 · 02:11',
    'menu.foot': 'Kulaklıkla, karanlıkta oyna.',
    'menu.footDone': 'Sonlar: {list} · ölüm {deaths}',

    'confirm.title': 'Yeni oyun?',
    'confirm.body': 'Kayıtlı ilerlemenin üzerine yazılacak. Bulduğun belgeler arşivde kalır.',
    'confirm.yes': 'Evet, baştan başla',
    'confirm.no': 'Vazgeç',

    'diff.title': 'Zorluk',
    'diff.easy': 'Kolay',
    'diff.easyDesc': 'Hikâyeye odaklan. Yaratıklar daha yavaş ve daha az dikkatli. Her bölümde bir kez yakalanmaktan kurtulursun.',
    'diff.normal': 'Normal',
    'diff.normalDesc': 'Tasarlandığı gibi. Tek yakalanma, son kayda dönüş.',
    'diff.nightmare': 'Kâbus',
    'diff.nightmareDesc': 'Daha hızlı, daha keskin kulaklı yaratıklar. Piller çabuk biter. Korku daha erken basar.',
    'diff.time': 'Tahmini oyun süresi: tüm belgeleri okuyan ve dört hayaleti kurtaran biri için 4–6 saat.',

    'levels.title': 'Bölümler',
    'levels.locked': 'Kilitli',

    'common.back': 'Geri',
    'common.on': 'Açık',
    'common.off': 'Kapalı',

    'settings.title': 'Ayarlar',
    'settings.reset': 'Varsayılanlar',
    'settings.reloadNote': '* işaretli ayarlar bir sonraki bölüm yüklemesinde uygulanır.',
    'tab.screen': 'Ekran',
    'set.displayMode': 'Görüntü modu',
    'set.displayMode.help': 'Tam ekran tarayıcıyı gizler. Esc ya da F11 ile çıkılır; oyunda Alt+Enter açıp kapatır.',
    'opt.windowed': 'Pencere',
    'opt.fullscreen': 'Tam ekran',
    'set.resolution': 'Çözünürlük',
    'set.resolution.help': 'Çizilen görüntünün boyutu. Yerel, ekranının çözünürlüğüdür; diğer boyutlar aşağıdaki ölçekleme moduyla pencereye ölçeklenir.',
    'opt.native': 'Yerel (ekran)',
    'set.scaleMode': 'Ölçekleme modu',
    'set.scaleMode.help': 'Pencereden farklı en-boy oranındaki bir çözünürlüğün nasıl gösterileceği.',
    'opt.fit': 'Sığdır (oranı koru, siyah şerit)',
    'opt.stretch': 'Uzat (ekranı doldur)',
    'opt.fill': 'Doldur (kenarları kırp)',
    'set.upscale': 'Ölçekleme filtresi',
    'set.upscale.help': 'Yumuşak, ölçeklerken pikselleri harmanlar; Piksel onları keskin ve kare tutar (düşük çözünürlükte retro görünüm).',
    'opt.smooth': 'Yumuşak',
    'opt.pixel': 'Piksel',
    'set.sharpen': 'Keskinleştirme',
    'set.sharpen.help': 'Son görüntüye kontrasta duyarlı keskinleştirme. Yerel altı çözünürlükte ve kenar yumuşatmayla işe yarar.',
    'set.fpsLimit': 'FPS sınırı',
    'set.fpsLimit.help': 'Saniyedeki kare sayısını sınırlar. Düşük sınır ekran kartını serin tutar, kare akışını düzenler.',
    'opt.unlimited': 'Sınırsız',
    'set.vsync': 'Dikey senkron (V-Sync)',
    'set.vsync.help': 'Açık: kareler monitör tazeleme hızına bağlıdır (yırtılma yok, akıcı). Kapalı: kareler olabildiğince hızlı (ya da sınıra kadar) çizilir, giriş gecikmesi en düşük olur.',
    'tab.graphics': 'Grafik',
    'tab.display': 'Görüntü',
    'tab.audio': 'Ses',
    'tab.controls': 'Kontroller',
    'tab.gameplay': 'Oynanış',
    'preset.low': 'Düşük',
    'preset.medium': 'Orta',
    'preset.high': 'Yüksek',
    'preset.ultra': 'Ultra',
    'preset.extreme': 'Aşırı',
    'preset.custom': 'Özel',
    'opt.off': 'Kapalı',
    'opt.low': 'Düşük',
    'opt.medium': 'Orta',
    'opt.high': 'Yüksek',
    'opt.ultra': 'Ultra',
    'opt.extreme': 'Aşırı',
    'opt.shadow1': 'Düşük (1024)',
    'opt.shadow2': 'Yüksek (2048)',
    'opt.shadow3': 'Ultra (4096)',
    'opt.small': 'Küçük',
    'opt.large': 'Büyük',
    'opt.full': 'Tam',
    'opt.reduced': 'Azaltılmış',

    'set.preset': 'Kalite ön ayarı',
    'set.preset.help': 'Aşağıdaki grafik ayarlarını tek seferde değiştirir. Aşırı, üst seviye ekran kartları için.',
    'set.renderScale': 'Çözünürlük ölçeği',
    'set.renderScale.help': '%100 üstü daha yüksek çözünürlükte çizip küçültür: daha keskin görüntü, çok daha fazla GPU yükü.',
    'set.textureRes': 'Doku çözünürlüğü',
    'set.shadows': 'Gölgeler',
    'set.antialias': 'Kenar yumuşatma',
    'set.lightmapRes': 'Pişmiş ışık kalitesi',
    'set.lightmapRes.help': 'Yumuşak pişmiş ışığın ve gölgelerin detayı.',
    'set.dynLights': 'Dinamik ışıklar',
    'set.bloom': 'Işıma (bloom)',
    'set.bloomStrength': 'Işıma şiddeti',
    'set.volumetric': 'Hacimsel ışık ve toz',
    'set.ao': 'Ortam kapatma (SSAO)',
    'set.ao.help': 'Köşelerde, mobilyaların altında ve fayans aralarında yumuşak temas gölgeleri.',
    'set.ssr': 'Ekran alanı yansımaları',
    'set.ssr.help': 'Islak zeminlerde, fayanslarda, camda ve parlak metalde gerçek yansımalar.',
    'set.volumetric.help': 'Işın izlemeli ışık huzmeleri, el feneri ışını ve süzülen toz. Aşırı ayarda çok ağırdır.',
    'set.motionBlur': 'Hareket bulanıklığı',
    'set.lensDirt': 'Lens kiri',
    'set.lensDirt.help': 'Parlak ışığı yakalayan kamera merceği lekeleri.',
    'set.particles': 'Parçacık yoğunluğu',
    'set.viewDist': 'Görüş mesafesi',
    'set.anisotropy': 'Anizotropik süzme',
    'set.showFps': 'FPS göstergesi',
    'set.brightness': 'Parlaklık',
    'set.brightness.help': 'En karanlık köşeler zar zor görünecek şekilde ayarla.',
    'set.contrast': 'Kontrast',
    'set.saturation': 'Renk doygunluğu',
    'set.fov': 'Görüş alanı',
    'set.headBob': 'Kafa sallanması',
    'set.shake': 'Kamera sarsıntısı',
    'set.grain': 'Film greni',
    'set.chromatic': 'Renk sapması',
    'set.vignette': 'Kenar kararması',
    'set.vhs': 'El kamerası (VHS) görünümü',
    'set.vhs.help': 'Oyunu 1994 model bir el kamerasının vizöründen gösterir.',
    'set.reduceFlicker': 'Yanıp sönmeyi azalt',
    'set.reduceFlicker.help': 'Işığa duyarlı oyuncular için titreşen ışıkları ve ekran flaşlarını yumuşatır.',
    'set.crosshair': 'Nişangâh noktası',
    'set.subtitles': 'Altyazılar',
    'set.captions': 'Ses altyazıları',
    'set.captions.help': 'Önemli sesleri [uzakta çiğneme sesi] gibi yazıyla gösterir.',
    'set.subtitleSize': 'Altyazı boyutu',
    'set.master': 'Ana ses',
    'set.music': 'Müzik',
    'set.sfx': 'Efektler',
    'set.ambience': 'Ortam (uğultu, damlalar, yağmur)',
    'set.entities': 'Yaratık sesleri',
    'set.voice': 'Sesler ve telsiz',
    'set.hrtf': '3D ses (HRTF, kulaklık önerilir)',
    'set.mouseSens': 'Fare hassasiyeti',
    'set.invertY': 'Dikey bakışı ters çevir',
    'set.touchSens': 'Dokunmatik bakış hassasiyeti',
    'set.toggleCrouch': 'Eğilme: basılı tutmak yerine aç/kapa',
    'set.toggleSprint': 'Koşma: basılı tutmak yerine aç/kapa',
    'set.lang': 'Dil',
    'set.difficulty': 'Zorluk',
    'set.difficulty.help': 'Yaratıkların hızını, duyuşunu ve fener pilini etkiler.',
    'set.jumpscare': 'Ani korkutmalar',
    'set.hints': 'İpuçları',

    'archive.title': 'Arşiv',
    'archive.count': '{n} / {m} belge',
    'archive.notFound': 'Henüz bulunmadı',
    'kind.note': 'Not',
    'kind.letter': 'Mektup',
    'kind.diary': 'Defter sayfası',
    'kind.tape': 'Kaset kaydı',
    'kind.photo': 'Fotoğraf',
    'kind.screen': 'Bilgisayar ekranı',
    'kind.phone': 'Telefon mesajı',
    'kind.printout': 'Çıktı',
    'kind.wall': 'Duvar yazısı',
    'kind.notice': 'Duyuru',
    'kind.memory': 'Anı',
    'kind.drawing': 'Çizim',
    'kind.card': 'Kart',
    'kind.report': 'Rapor',
    'kind.flyer': 'El ilanı',
    'kind.doc': 'Belge',

    'help.title': 'Nasıl oynanır',
    'help.kbm': 'Klavye ve fare',
    'help.walk': 'Yürü',
    'help.mouse': 'Fare',
    'help.look': 'Etrafına bak (tıklayınca kilitlenir)',
    'help.sprint': 'Koş (gürültülü, nefes tüketir)',
    'help.crouch': 'Eğil (neredeyse sessiz)',
    'help.interact': 'Etkileşim, oku, al, saklan',
    'help.flash': 'Fener',
    'help.drink': 'Badem suyu iç',
    'help.throw': 'Işık çubuğu at',
    'help.lean': 'Sola / sağa eğil (köşeden bak)',
    'help.map': 'Harita',
    'help.bag': 'Eşyalar / günlük',
    'bag.items': 'EŞYALAR',
    'bag.journal': 'GÜNLÜK',
    'bag.close': 'Kapat (I / J)',
    'bag.empty': 'Cepler boş.',
    'bag.inspectHint': 'Çevirmek için sürükle.',
    'bag.now': 'ŞU AN',
    'bag.story': 'ŞİMDİYE KADAR',
    'bag.docs': 'BURADA BULUNANLAR',
    'bag.noDocs': 'Burada henüz bir şey bulmadın. Daha dikkatli bak.',
    'bag.people': 'KİŞİLER',
    'bag.freed': 'huzurda',
    'bag.hunting': 'hâlâ avlanıyor',
    'bag.stats': 'Belgeler {a} / {b}   ·   Lily’nin çizimleri {c} / {d}',
    'bag.n.flashlight': 'Fener',
    'bag.d.flashlight': 'Atari kamyonetinden ağır, çelik bir fener. Pil: %{n}. Ölmeden önce kararır.',
    'bag.n.battery': 'Yedek piller',
    'bag.d.battery': 'Fener için büyük boy piller. R ile takılır; ışık ölünce kendiliğinden takılır.',
    'bag.n.almond': 'Badem suyu',
    'bag.d.almond': 'Bulanık, tatlı bir su şişesi. Titremeyi yatıştırır. Q ile iç.',
    'bag.n.glow': 'Işık çubukları',
    'bag.d.glow': 'Kır ve G ile at. Sürüngenler ve sırıtkanlar yeşil ışığı geçmez.',
    'bag.d.officeKey': 'Walt’ın ofis anahtarı, kasadan. Pirinci aşınıp pürüzsüzleşmiş.',
    'bag.d.token': 'Ortasında yıldız delik açılmış bir Starlight jetonu. Sadece 7 numaralı makine.',
    'bag.n.fuse': 'Sigortalar',
    'bag.d.fuse': 'Fabrikanın eski panosu için ağır seramik sigortalar.',
    'bag.n.fuel': 'Mazot bidonları',
    'bag.d.fuel': 'Jeneratörler için mazot. Çalkalanırken ses çıkarıyor. Yavaş yürü.',
    'bag.d.keycard': 'Manyetik şeritli bir güvenlik kartı. Birinin fotoğrafı kazınmış.',
    'bag.d.key': 'Kâğıt etiketli bir anahtar. Burada bir şeyi açıyor.',
    'help.pause': 'Duraklat',
    'help.touch': 'Dokunmatik',
    'help.touchText': 'Sol altta yürüme çubuğu, ekranın sağında parmağını sürükleyerek bakış. Sağdaki düğmeler: etkileşim, fener, koş, eğil, harita.',
    'help.survive': 'Hayatta kalmak',
    'help.tip1': '<b>Yutucu</b> düz koridorlarda senden hızlı, dönüşlerde yavaş. Köşe dön.',
    'help.tip2': 'Floresanlar titremeye başladıysa <b>o yakında</b>.',
    'help.tip3': '<b>Güç hapı</b> yutunca her şey birkaç saniye senden kaçar.',
    'help.tip4': '<b>Kırmızı</b> hiç durmaz. <b>Pembe</b> önüne geçer. <b>Mavi</b> kestirilemez. <b>Turuncu</b> ise sen bakarken donar.',
    'help.tip5': 'Masaların altına ve dolapların içine <b>saklanabilirsin</b>. Seni girerken görmedilerse bulamazlar.',
    'help.tip6': '<b>Kaset çalarlar</b> oyunu kaydeder. Otomatik kayıt, hedeflerde ve güvendeyken yapılır.',
    'help.tip7': 'Her hayaletin eşyasını <b>türbesine</b> götür. Son buna bağlı.',

    'pause.title': 'Duraklatıldı',
    'pause.resume': 'Devam et',
    'pause.map': 'Harita',
    'pause.journal': 'Günlük',
    'pause.archive': 'Arşiv',
    'pause.settings': 'Ayarlar',
    'pause.help': 'Nasıl oynanır',
    'pause.load': 'Son kayıttan yükle',
    'pause.menu': 'Ana menü',

    'note.close': 'Kapat',
    'note.closeKey': 'Kapat (E)',

    'map.close': 'Kapat',
    'map.closeKey': 'Kapat (M)',
    'map.objective': 'Hedef',
    'map.tape': 'Kaset',
    'map.doc': 'Belge',
    'map.shrine': 'Türbe',
    'map.supply': 'Malzeme',
    'map.locked': 'Kilitli kapı',

    'kp.label': 'GÜVENLİK',
    'kp.clear': 'SİL',
    'kp.enter': 'GİR',
    'kp.open': 'AÇIK',
    'kp.error': 'HATA',
    'kp.close': 'Vazgeç (Esc)',

    'cab.help': 'Ok tuşları veya WASD · Enter başla · P duraklat ·',
    'cab.exit': 'Kabinden ayrıl (Esc)',

    'choice.back': 'Geri çekil',
    'card.skip': 'Geçmek için tıkla veya E',

    'death.retry': 'Son kayıttan devam et',
    'death.menu': 'Ana menü',

    'end.menu': 'Ana menü',
    'end.skip': 'Geç',
    'end.time': 'oyun süresi',
    'end.deaths': 'ölüm',
    'end.docs': 'belge',
    'end.freed': 'kurtarılan hayalet',
    'end.drawings': 'bulunan çizim',

    'hud.objective': 'HEDEF',
    'hud.rec': 'KAYIT',
    'hud.stamina': 'NEFES',
    'hud.battery': 'FENER',
    'hud.power': 'GÜÇ {t}',
    'hud.fps': '{n} FPS',

    'touch.pause': 'Duraklat',
    'touch.bag': 'ÇANTA',
    'touch.map': 'HARİTA',
    'touch.drink': 'İÇ',
    'touch.throw': 'AT',
    'touch.crouch': 'EĞİL',
    'touch.sprint': 'KOŞ',
    'touch.flash': 'FENER',
    'touch.tap': 'DOKUN',

    'inv.battery': 'PİL ×{n}',
    'inv.almond': 'BADEM SUYU ×{n}',
    'inv.glow': 'IŞIK ÇUBUĞU ×{n}',
    'inv.officeKey': 'OFİS ANAHTARI',
    'inv.token': 'ALTIN JETON',
    'inv.fuses': 'SİGORTA ×{n}',
    'inv.fuel': 'MAZOT ×{n}',
    'inv.keycard': 'GÜVENLİK KARTI',
    'inv.pellets': 'GÜÇ HAPI ×{n}',

    'n.added': 'Arşive eklendi: {title}',
    'n.saved': 'Oyun kaydedildi',
    'n.batteryIn': 'Fenere yeni pil taktın',
    'n.batterySpare': 'Yedek pil',
    'n.noSpare': 'Yedek pilin yok.',
    'n.batteryFull': 'Pil hâlâ dolu.',
    'hint.reload': 'R: fenerin pillerini değiştir',
    'touch.reload': 'PİL',
    'help.reload': 'Fenerin pillerini değiştir',
    'n.batterySwap': 'Yedek pili taktın',
    'n.almond': 'Badem suyu (Q ile iç)',
    'n.glow': 'Işık çubuğu (G ile at)',
    'n.found': 'Bulundu: {name}',
    'n.drank': 'Badem suyunu içiyorsun. Nefesin düzeliyor.',
    'n.noAlmond': 'Badem suyun yok.',
    'n.noGlow': 'Işık çubuğun yok.',
    'n.slow': 'Oyun yavaş çalışıyor. Duraklat › Ayarlar › Grafik’ten kaliteyi düşürebilirsin.',
    'n.lockFail': 'Fare kilitlenemedi. Sol tuşu basılı tutup sürükleyerek etrafına bak.',
    'n.flashDead': 'Fenerin söndü.',
    'n.holdBreath': 'Bir şey yakında. Nefesini tutmak için Shift’e basılı tut.',
    'n.heardBreath': 'Nefesini duydu.',
    'n.noFlash': 'Fenerin yok.',
    'n.noBattery': 'Pil bitti. Yedek pil bul.',
    'n.grace': 'Kıl payı kurtuldun! (Kolay: bölüm başına bir kez)',
    'n.freed': '{name} özgür',
    'n.ghostBack': '{name} geri çekildi',
    'n.cabinetHi': 'Baş harflerin rekor tablosuna yazıldı: SAM',
    'n.perfect': 'Bütün pelletleri yedin. Mükemmel oyun.',
    'n.fruit': 'Evin önünde bir meyve belirdi',
    'n.diesel': 'Mazot bidonu',
    'n.drawing': 'Lily’nin çizimi ({n}/8)',

    'pr.read': 'Oku: {title}',
    'pr.readWall': 'Yazıyı oku',
    'pr.screen': 'Ekrana bak',
    'pr.tape': 'Kaseti dinle (oyunu kaydeder)',
    'pr.battery': 'Pili al',
    'pr.almond': 'Badem suyunu al',
    'pr.glow': 'Işık çubuğunu al',
    'pr.flashlight': 'Feneri al',
    'pr.token': 'Jetonu al',
    'pr.fuse': 'Sigortayı al',
    'pr.fuel': 'Mazot bidonunu al',
    'pr.keycard': 'Güvenlik kartını al',
    'pr.take': 'Al: {name}',
    'pr.pellet': 'Güç hapını yut',
    'pr.phoneRing': 'Telefonu aç',
    'pr.phone': 'Ahizeyi kaldır',
    'pr.cabinetFree': 'Kabinde oyna (BEDAVA)',
    'pr.doorLocked': '{name} (kilitli)',
    'pr.doorOpen': 'Kapıyı aç',
    'pr.doorClose': 'Kapıyı kapat',
    'pr.hide': 'Altına saklan',
    'pr.hideLocker': 'Dolaba saklan',
    'pr.unhide': 'Saklandığın yerden çık',
    'pr.shrineLook': 'Sunağa bak',
    'pr.shrinePlace': 'Eşyayı sunağa bırak',
    'pr.drawing': 'Lily’nin çizimini al',

    'door.default': 'Kapı',
    'door.office': 'Ofis kapısı',
    'door.storage': 'Depo',
    'door.wc': 'Tuvalet',
    'door.front': 'Giriş kapısı',
    'door.elevator': 'Yük asansörü',
    'door.security': 'Güvenlik odası',
    'door.stair': 'Yangın merdiveni',
    'door.house': 'Hayalet evi',
    'door.service': 'Servis asansörü',
    'lock.service': 'Asansör ölü. Üç jeneratörün de çalışması gerekiyor.',
    'door.exit': 'ÇIKIŞ',
    'door.room': 'Oda {n}',
    'door.jammed': 'Kapı',
    'lock.jammed': 'Sıkışmış. Kol dönüyor ama öbür taraftan bir şey tutuyor.',
    'lock.exit': 'ÇIKIŞ kilitli. Henüz değil.',
    'door.pressure': 'Basınç kapısı',
    'lock.pressure': 'Basınç kapısı yerinden kıpırdamıyor. Arkasında buhar tıslıyor.',
    'door.janitor': 'Hademe',
    'lock.janitor': 'Şifreli bir kilit. Üç hane.',
    'door.fireExit': 'Yangın çıkışı',
    'lock.fireExit': 'Kalın bir zincir ve bir asma kilit. Anahtarlar hademede.',
    'lock.fireExitMotel': 'Bar itilmiyor. Biri dışarıdan sıkıştırmış.',
    'door.gym': 'Spor salonu',
    'door.mallExit': 'AVM kapıları',
    'lock.mallExit': 'Gece için kilitli. Uzakta fotoğraf kabini uğulduyor.',
    'door.room12': 'Oda 12',
    'lock.room12': 'Kilitli. Numara plakası parlatılmış, sanki biri her gün dokunuyormuş gibi.',
    'door.room207': 'Oda 207',
    'lock.room207': 'Kilitli. Kâğıt bir tabela: LÜTFEN SESSİZ OLUN. Üstüne pastel boyayla bir güneş çizilmiş.',
    'door.elevatorH': 'Asansör',
    'lock.elevatorH': 'Asansör kapıları kapalı bekliyor. Bir şeyi bekliyor.',
    'door.samHouse': 'Senin evin',
    'door.clydeHouse': 'Clyde’ın evi',
    'door.neighbor': 'Ön kapı',
    'lock.neighbor': 'Kilitli. Başını çevirince perdeler kıpırdıyor.',
    'door.alley': 'Ara sokak kapısı',
    'lock.alley': 'Kilitli. Köşede durmadan olmaz.',
    'door.kernel': 'Çelik kapı',
    'lock.kernel': 'Çelik ve kilitli. Pirinç bir plaka: KERNEL — SADECE W.',
    'lock.default': 'Kilitli.',
    'lock.office': 'Kilitli. Kapıda pirinç bir levha: "W. — MÜDÜR".',
    'lock.front': 'Dışarıdan asma kilitle kapatılmış. Anahtar nakliyecilerde.',
    'lock.elevator': 'Asansörün elektriği yok. Çağrı düğmesi ölü.',
    'lock.security': 'Tuş takımı dört haneli bir şifre istiyor.',
    'lock.stair': 'Kart okuyucunun ışığı kırmızı. Güvenlik kartı gerekiyor.',
    'lock.house': 'Pembe bir enerji perdesi. Dört güç hapı onu kapalı tutuyor.',

    'cap.front': 'önünde',
    'cap.back': 'arkanda',
    'cap.left': 'solunda',
    'cap.right': 'sağında',
    'cap.waka': '[yakında çiğneme sesi: vaka, vaka]',
    'cap.wakaFar': '[uzakta çiğneme sesi]',
    'cap.phone': '[bir telefon çalıyor]',
    'cap.drag': '[yakında sürüklenen ayak sesleri]',
    'cap.moan': '[bir inleme]',
    'cap.thud': '[uzakta bir şey düştü]',
    'cap.buzz': '[bir floresan çıtırdıyor]',
    'cap.whisper': '[fısıltı]',
    'cap.giggle': '[karanlıkta kıkırdama]',
    'cap.radio': '[telsiz cızırtısı]',
    'cap.thunder': '[gök gürültüsü]',
    'cap.hiss': '[ıslak bir tıslama, uzaklaşıyor]',
    'cap.skitter': '[tuğlanın üstünde tıkırdayan bacaklar]',
    'cap.whistle': '[bir düdük çığlık atıyor]',
    'cap.plastic': '[plastik gıcırtısı]',
    'cap.callName': '[biri Clyde’ın sesiyle adını sesleniyor]',
    'cap.heavySteps': '[ağır ayak sesleri, lastik gıcırtısı]',
    'cap.pipe': '[tünellerde bir yerde bir boru çınlıyor]',
    'cap.locker': '[koridorun ilerisinde bir dolap çarpıyor]',
    'cap.knock': '[koridorun ilerisinde bir yerde üç kez kapı çalınıyor]',
    'cap.beep': '[boş bir odada bir monitör bipliyor]',
    'cap.arc': '[çelik kapının arkasında elektrik çatırdıyor]',
    'cap.pop': '[bir floresan patlıyor]',
    'cap.slam': '[arkanda bir kapı çarpıyor]',
    'cap.run': '[görünmeyen biri koşuyor]',
    'cap.callJune': '[koridorun ucundan bir kadın sesi: "Eddie? Eddie, sen misin?"]',
    'cap.car': '[ıslak sokaktan bir araba geçiyor]',
    'cap.door': '[bir yerlerde bir kapı]',
    'cap.drip': '[damlama]',
    'cap.hum': '[floresan vızıltısı]',
  });
})(typeof window !== 'undefined' ? window : globalThis);
