/* Türkçe arayüz metni, Ada Lind’in hikâyesi için: eski hikâyeye ait olanları değiştirir, dokuz rafın
   ihtiyaç duyduklarını ekler (kapılar, merdivenler, belge türleri, altyazılar). ui.js’ten sonra yüklenir. */
(function (root) {
  'use strict';
  root.PB.I18N.register('tr', 'ui', {
    'game.subtitle': 'KAYIP EŞYA',
    'menu.credit': 'Halvard · 13 Ocak 1998 · 02:56',
    'diff.time': 'Tahmini oynanış süresi: her belgeyi okuyan ve sekiz resmin hepsini bulan biri için 5–7 saat.',
    'set.vhs.help': 'Oyunu eski bir ev video kamerasından bakıyormuş gibi gösterir.',
    'help.drink': 'Bir arpa şekeri ye',
    'bag.stats': 'Belgeler {a} / {b}   ·   Wren’in resimleri {c} / {d}',
    'bag.d.flashlight': 'Depo 9 tezgâhının altından ağır, lastik kaplı bir el feneri. Pil: %{n}. Sönmeden önce kararır.',
    'bag.n.almond': 'Arpa şekeri',
    'bag.d.almond': 'Tezgâhın altındaki tenekeden, kötü geceler için saklanmış bir burgu arpa şekeri. Şeker ellerinin titremesini dindirir. Q ile ye.',
    'bag.d.officeKey': 'Küçük, aşınıp pürüzsüzleşmiş pirinç bir anahtar.',
    'bag.d.token': 'Pirinç bir jeton.',
    'help.padText': 'Sol çubuk: yürü. Sağ çubuk: bak. A: etkileşim. B: çömel. X: pil değiştir. Y: fener. LB / RB: eğil. RT ya da sol çubuğa basmak: koş. LT: ışık çubuğu. Sağ çubuğa basmak: arkana bak. Yön tuşları: ↑ günlük, ↓ arpa şekeri, → eşyalar. View: harita. Menu: duraklat. Menülerde yön tuşları gezdirir, A seçer, B geri döner.',
    'help.tip7': 'Her yerin dibinde bir yalan vardır. <b>Kayıp şeyi ait olduğu yere geri koy</b>, yol açılır.',
    'map.shrine': 'Talep',
    'end.freed': 'Talep edilen raflar',
    'end.claimed': 'Talep edilen raflar',
    'inv.almond': 'ARPA ŞEKERİ ×{n}',
    'inv.token': 'JETON',
    'n.almond': 'Arpa şekeri (yemek için Q)',
    'n.drank': 'Arpa şekerini yiyorsun. Nefesin düzene giriyor.',
    'n.noAlmond': 'Hiç arpa şekerin yok.',
    'n.drawing': 'Wren’in resmi ({n}/8)',
    'pr.almond': 'Arpa şekerini al',
    'pr.drawing': 'Wren’in resmini al',
    'door.house': 'Ev',
    'touch.drink': 'ŞEKER',
    'inv.pellets': 'KAYIP IŞIK ×{n}',
    'pr.pellet': 'Kayıp ışığı al',
    'lock.house': 'Bir ışık perdesi. Dört kayıp ışık onu kapalı tutuyor.',
    'help.tip1': '<b>Bakmadan önce dinle.</b> Her yaratığın kendi kuralı var: kimi duyar, kimi yalnızca ışığı görür, kimi yalnızca kimse bakmazken kıpırdar. Hangisinin hangisi olduğunu belgeler söyler.',
    'help.tip2': 'Işıklar kekelemeye başladığında ya da dünyadaki ses çekildiğinde, <b>bir şey yakındadır</b>.',
    'help.tip3': 'Aşağısı’nda bir <b>kayıp ışık</b> al; Yiyici birkaç saniye senden uzak durur.',
    'help.tip4': 'Her rafın <b>kendi yaratıkları</b> var: bilet kontrol eden bir kondüktör, yalnızca org çalarken koşan atlar, yalnızca sen kıpırdarken kıpırdayan çamlar. Her birinin kuralını öğren.',
    'help.tip5': 'Yatakların, ranzaların, masaların altına ve dolaplara <b>saklanabilirsin</b>. İçeri girdiğini bir şey görmediyse hiçbir şey bakmaz.',
    'help.tip6': 'Oyun her görevde, güvendeyken <b>kendiliğinden kaydeder</b>.',
    'set.subtitles.help': 'Söylenenleri gösterir: dokuzuncu kanal, kasetler, düşünceler.',
    'set.voice.help': 'Dokuzuncu kanal, kasetler ve düşünceler.',
    // dokuz raftaki kapılar ve geçitler
    'pr.unlock': 'Kilidi aç',
    'pr.stairs': 'Merdivenden git',
    'pr.stairsDown': 'Merdivenden in',
    'pr.stairsUp': 'Merdivenden çık',
    'pr.ladderDown': 'Merdivenden aşağı in',
    'pr.ladderUp': 'Merdivene tırman',
    'door.otto': 'Otto Brandt’ın odası',
    'lock.otto': '1964’ten beri kilitli. Anahtar arşivde bir yerde olmalı.',
    'door.concourse': 'Gar holü',
    'lock.concourse': 'Öbür taraftan kilitli.',
    'door.bridge': 'Köprüüstü',
    'lock.bridge': 'Kilitli. Anahtar kaptanda.',
    'door.cage': 'Kafes',
    'lock.cage': 'Kafesin kapısı. Elektrik olmadan hiçbir şey kıpırdamaz.',
    'door.fire': 'Yangın kapısı',
    'lock.fire': 'Takozla sıkıştırılmış. Bu taraftan.',
    'door.signe': 'Stuegata 4',
    'lock.signe': 'Kilitli. İçeride bir lamba yanıyor.',
    'door.ghost': 'Hayalet treni',
    // belge türleri
    'kind.telegram': 'Telgraf',
    'kind.transcript': 'Döküm',
    'kind.clipping': 'Gazete',
    // seslerin altyazıları
    'hint.flash': 'F feneri açar ve kapatır.',
    'cap.chute': '[oluktan bir paket düşüyor]',
    'cap.tube': '[pnömatik boru gümlüyor]',
    'cap.bellFar': '[sisin içinde bir çan]',
    'cap.doorShut': '[bir yerde bir kapı kapanıyor]',
    'cap.stepsFar': '[uzakta ayak sesleri]',
    'cap.organ': '[bir panayır orgu kendi kendine çalmaya başlıyor]',
    'cap.organStop': '[org yavaşlayıp susuyor]',
    'cap.choir': '[bir koro, şarkı söylüyor]',
    'cap.knocks': '[çelik üstünde yedi vuruş]',
    'cap.ice': '[buz çatlıyor, uzaklarda]',
    'cap.brake': '[frenler çığlık atıyor]',
    'cap.laugh': '[kahkaha]',
    'cap.toll': '[bir çan vuruyor]',
    'cap.breath': '[nefes sesi, tam arkanda]',
    'cap.train': '[tren, son hızla]',
    'cap.pa': '[bir zil; anons hoparlörü cızırdıyor]',
  });
})(typeof window !== 'undefined' ? window : globalThis);
