/* 简体中文界面。 */
(function (root) {
  'use strict';
  root.PB.I18N.register('zh-CN', 'ui', {
    'game.title': 'LEVEL 256',
    'game.subtitle': '星光游戏厅',
    'game.aria': '游戏画面',
    'noscript': '本游戏需要 JavaScript。',

    'boot.tip': '提示',
    'boot.init': '正在启动…',
    'boot.fonts': '正在加载字体…',
    'boot.sounds': '正在录制音效…',
    'boot.voices': '正在录制人声…',
    'boot.prep': '正在准备关卡…',
    'boot.noThree': '3D 引擎（three.js）加载失败。请检查网络连接后刷新页面。',
    'boot.error': '启动错误：{msg}',
    'boot.noWebgl': '显卡无法启动 3D（WebGL 2）。请更新显卡驱动，然后重新启动游戏。',
    'load.textures': '正在编织纹理…（{n}/{m}）',
    'load.walls': '正在砌墙…',
    'load.bake': '正在烘焙光照…',
    'load.fixtures': '正在挂上日光灯…',
    'load.props': '正在摆放家具…',
    'load.decals': '污渍与刮痕…',
    'load.shaders': '正在编译着色器…',
    'load.ready': '就绪',
    'load.error': '加载错误：{msg}',

    'first.title': '开始之前',
    'first.lang': '语言',
    'first.bright': '调整亮度，直到左侧符号几乎看不见、右侧符号清晰可见。',
    'first.phones': '建议戴上耳机，在黑暗的房间里游玩。',
    'first.go': '继续',

    'menu.continue': '继续游戏',
    'menu.new': '新游戏',
    'menu.levels': '章节',
    'menu.settings': '设置',
    'menu.archive': '档案',
    'menu.help': '游戏说明',
    'menu.quit': '退出游戏',
    'menu.credit': '哈洛 · 1994 年 11 月 30 日 · 凌晨 2:11',
    'menu.foot': '请戴上耳机，在黑暗中游玩。',
    'menu.footDone': '结局：{list} · 死亡 {deaths} 次',

    'confirm.title': '开始新游戏？',
    'confirm.body': '已保存的进度将被覆盖。已找到的文件会保留在档案中。',
    'confirm.yes': '是的，重新开始',
    'confirm.no': '取消',

    'diff.title': '难度',
    'diff.easy': '简单',
    'diff.easyDesc': '专注于故事。怪物更慢、更迟钝。每章有一次机会从抓捕中挣脱。',
    'diff.normal': '普通',
    'diff.normalDesc': '按设计的体验。被抓住一次就会回到上一个存档。',
    'diff.nightmare': '噩梦',
    'diff.nightmareDesc': '怪物更快、听觉更灵敏。电池消耗很快。恐惧来得更早。',
    'diff.time': '预计游玩时间：阅读全部文件并解放四个游魂，约需 4–6 小时。',

    'levels.title': '章节',
    'levels.locked': '未解锁',

    'common.back': '返回',
    'common.on': '开',
    'common.off': '关',

    'settings.title': '设置',
    'settings.reset': '恢复默认',
    'settings.reloadNote': '带 * 的设置将在下次载入章节时生效。',
    'tab.screen': '屏幕',
    'set.displayMode': '显示模式',
    'set.displayMode.help': '全屏会隐藏浏览器。按 Esc 或 F11 退出；游戏中按 Alt+Enter 切换。',
    'opt.windowed': '窗口',
    'opt.fullscreen': '全屏',
    'set.resolution': '分辨率',
    'set.resolution.help': '渲染画面的尺寸。“原生”使用你的屏幕分辨率；其他尺寸会按下方的缩放模式适配窗口。',
    'opt.native': '原生（屏幕）',
    'set.scaleMode': '缩放模式',
    'set.scaleMode.help': '当分辨率的比例与窗口不同时如何显示。',
    'opt.fit': '适应（保持比例，黑边）',
    'opt.stretch': '拉伸填满',
    'opt.fill': '填充（裁切边缘）',
    'set.upscale': '缩放滤镜',
    'set.upscale.help': '“平滑”在放大时混合像素；“像素”保持像素锐利方正（低分辨率下的复古效果）。',
    'opt.smooth': '平滑',
    'opt.pixel': '像素',
    'set.sharpen': '锐化',
    'set.sharpen.help': '对最终画面进行对比度自适应锐化。在低于原生分辨率或开启抗锯齿时有帮助。',
    'set.fpsLimit': '帧率上限',
    'set.fpsLimit.help': '限制每秒帧数。较低的上限能让显卡保持凉爽、帧间隔更平稳。',
    'opt.unlimited': '无限制',
    'set.vsync': '垂直同步',
    'set.vsync.help': '开：画面跟随显示器刷新率，不会撕裂。关：游戏尽可能快地绘制，直到帧率上限。在网页浏览器中，浏览器本身总会等待显示器，因此“关”只去掉游戏自身的等待；桌面版会彻底关闭同步（重启后生效）。',
    'tab.graphics': '图形',
    'tab.display': '画面',
    'tab.audio': '音频',
    'tab.controls': '操作',
    'tab.gameplay': '游戏',
    'preset.low': '低',
    'preset.medium': '中',
    'preset.high': '高',
    'preset.ultra': '超高',
    'preset.extreme': '极致',
    'preset.custom': '自定义',
    'opt.off': '关',
    'opt.low': '低',
    'opt.medium': '中',
    'opt.high': '高',
    'opt.ultra': '超高',
    'opt.extreme': '极致',
    'opt.shadow1': '低（1024）',
    'opt.shadow2': '高（2048）',
    'opt.shadow3': '超高（4096）',
    'opt.small': '小',
    'opt.large': '大',
    'opt.full': '完整',
    'opt.reduced': '减弱',

    'set.preset': '画质预设',
    'set.preset.help': '一次性更改下方所有图形设置。“极致”面向高端显卡；“超高+”更进一步（8192 阴影、最密集的光照烘焙、最精细的模型、景深），适合最强的电脑。',
    'set.renderScale': '分辨率缩放',
    'set.renderScale.help': '高于 100% 时以更高分辨率渲染再缩小：画面更清晰，显卡负担大幅增加。',
    'set.textureRes': '纹理分辨率',
    'set.shadows': '阴影',
    'set.antialias': '抗锯齿',
    'set.lightmapRes': '烘焙光照质量',
    'set.lightmapRes.help': '预先计算的柔和光照及其阴影的精细程度。',
    'set.dynLights': '动态光源',
    'set.bloom': '泛光',
    'set.bloomStrength': '泛光强度',
    'set.volumetric': '体积光与灰尘',
    'set.ao': '环境光遮蔽（SSAO）',
    'set.ao.help': '角落、家具下方和瓷砖之间的柔和接触阴影。',
    'set.ssr': '屏幕空间反射',
    'set.ssr.help': '湿地板、瓷砖、玻璃和抛光金属上的真实反射。',
    'set.volumetric.help': '光线步进计算的光柱、手电筒光束和飘浮的灰尘。“极致”下非常吃性能。',
    'set.motionBlur': '动态模糊',
    'set.lensDirt': '镜头污渍',
    'set.lensDirt.help': '镜头上的污迹，会在强光下显现。',
    'set.particles': '粒子密度',
    'set.viewDist': '可视距离',
    'set.anisotropy': '各向异性过滤',
    'set.brightness': '亮度',
    'set.brightness.help': '调到最暗的角落刚好能看见为止。',
    'set.contrast': '对比度',
    'set.saturation': '色彩饱和度',
    'set.fov': '视野',
    'set.headBob': '头部晃动',
    'set.shake': '镜头震动',
    'set.grain': '胶片颗粒',
    'set.chromatic': '色差',
    'set.vignette': '暗角',
    'set.vhs': '摄像机（VHS）效果',
    'set.vhs.help': '让游戏看起来像透过 1994 年摄像机的取景器。',
    'set.reduceFlicker': '减少闪烁',
    'set.reduceFlicker.help': '为对光敏感的玩家减弱闪烁的灯光和屏幕闪光。',
    'set.crosshair': '准星',
    'set.subtitles': '字幕',
    'set.captions': '声音字幕',
    'set.captions.help': '以文字显示重要声音，例如 [远处的咀嚼声]。',
    'set.subtitleSize': '字幕大小',
    'set.master': '主音量',
    'set.music': '音乐',
    'set.sfx': '音效',
    'set.ambience': '环境音（嗡鸣、滴水、雨声）',
    'set.entities': '怪物声音',
    'set.voice': '人声与对讲机',
    'set.hrtf': '3D 音频（HRTF，建议佩戴耳机）',
    'set.mouseSens': '鼠标灵敏度',
    'set.invertY': '反转垂直视角',
    'set.touchSens': '触屏灵敏度',
    'set.padSens': '手柄灵敏度',
    'set.toggleCrouch': '蹲下：按一下切换，而非按住',
    'set.toggleSprint': '奔跑：按一下切换，而非按住',
    'set.lang': '语言',
    'set.difficulty': '难度',
    'set.difficulty.help': '影响怪物的速度、听觉以及手电筒的电量。',
    'set.jumpscare': '突发惊吓',
    'set.hints': '提示',

    'archive.title': '档案',
    'archive.count': '{n} / {m} 份文件',
    'archive.notFound': '尚未找到',
    'kind.note': '便条',
    'kind.letter': '信件',
    'kind.diary': '日记页',
    'kind.tape': '磁带录音',
    'kind.photo': '照片',
    'kind.screen': '电脑屏幕',
    'kind.phone': '电话留言',
    'kind.printout': '打印件',
    'kind.wall': '墙上的字',
    'kind.notice': '告示',
    'kind.memory': '回忆',
    'kind.drawing': '画',
    'kind.card': '卡片',
    'kind.report': '报告',
    'kind.flyer': '传单',
    'kind.doc': '文件',

    'help.title': '游戏说明',
    'help.kbm': '键盘与鼠标',
    'help.walk': '行走',
    'help.mouse': '鼠标',
    'help.look': '环顾四周（点击锁定鼠标）',
    'help.sprint': '奔跑（声音大，消耗气息）',
    'help.crouch': '蹲下（几乎无声）',
    'help.interact': '互动、阅读、拾取、躲藏',
    'help.flash': '手电筒',
    'help.drink': '喝一罐 Star Pop',
    'help.throw': '扔出荧光棒',
    'help.lean': '向左 / 向右探身（窥视拐角）',
    'help.map': '地图',
    'help.bag': '物品 / 日志',
    'bag.items': '物品',
    'bag.journal': '日志',
    'bag.close': '关闭（I / J）',
    'bag.empty': '口袋里空空如也。',
    'bag.inspectHint': '拖动以翻转查看。',
    'bag.now': '当前',
    'bag.story': '故事至今',
    'bag.docs': '在此找到',
    'bag.noDocs': '这里还什么都没找到。再仔细看看。',
    'bag.people': '人物',
    'bag.freed': '已安息',
    'bag.hunting': '仍在猎杀',
    'bag.stats': '文件 {a} / {b}   ·   莉莉的画 {c} / {d}',
    'bag.n.flashlight': '手电筒',
    'bag.d.flashlight': '一支沉重的钢制手电筒，来自游戏厅的货车。电量：{n}%。熄灭前会先变暗。',
    'bag.n.battery': '备用电池',
    'bag.d.battery': '手电筒用的大号电池。按 R 更换；手电筒没电时会自动换上。',
    'bag.n.almond': 'Star Pop',
    'bag.d.almond': '一罐游戏厅自家的樱桃汽水，不知为何还是冰的。糖分和气泡能让双手稳下来。按 Q 喝。',
    'bag.n.glow': '荧光棒',
    'bag.d.glow': '掰亮一根，按 G 扔出。爬行者和咧嘴怪不会穿过绿光。',
    'bag.d.officeKey': '沃尔特办公室的钥匙，来自收银机。黄铜已被磨得光滑。',
    'bag.d.token': '一枚打了星形孔的星光代币。只能用于 7 号机台。',
    'bag.n.fuse': '保险丝',
    'bag.d.fuse': '沉重的陶瓷保险丝，用于工厂的旧配电箱。',
    'bag.n.fuel': '柴油桶',
    'bag.d.fuel': '发电机用的柴油。晃动声很大。慢慢走。',
    'bag.d.keycard': '一张带磁条的门禁卡。上面某人的照片被刮掉了。',
    'bag.d.key': '一把挂着纸标签的钥匙。能打开这里的某样东西。',
    'help.pause': '暂停',
    'help.touch': '触屏',
    'help.pad': '手柄',
    'help.touchText': '左下角是移动摇杆，在屏幕右半边拖动来环顾。右侧按钮：互动、手电筒、奔跑、蹲下、地图。',
    'help.padText': '左摇杆：行走。右摇杆：环顾。A：互动。B：蹲下。X：更换电池。Y：手电筒。LB / RB：探身。RT 或按下左摇杆：奔跑。LT：荧光棒。按下右摇杆：回头看。十字键：↑ 日志，↓ Star Pop，→ 物品。View：地图。Menu：暂停。在菜单中，十字键移动，A 确认，B 返回。',
    'help.survive': '活下去',
    'help.tip1': '<b>吞噬者</b>在直走廊里比你快，转弯时却很慢。多拐弯。',
    'help.tip2': '日光灯开始闪烁时，<b>它就在附近</b>。',
    'help.tip3': '拿起一盏<b>灯笼</b>，几秒内一切都会躲着你。',
    'help.tip4': '<b>红色</b>永不停歇。<b>紫色</b>会堵住你的去路。<b>青色</b>能听见水声，并在各处闪现。<b>琥珀色</b>在你注视时会一动不动。',
    'help.tip5': '你可以<b>躲</b>在桌子底下和储物柜里。只要没被看见躲进去，就不会被找到。',
    'help.tip6': '<b>录音机</b>用来存档。达成目标且安全时会自动存档。',
    'help.tip7': '把每个游魂的遗物<b>带到它的神龛</b>。结局取决于此。',

    'pause.title': '暂停',
    'pause.resume': '继续',
    'pause.map': '地图',
    'pause.journal': '日志',
    'pause.archive': '档案',
    'pause.settings': '设置',
    'pause.help': '游戏说明',
    'pause.load': '读取上一个存档',
    'pause.menu': '主菜单',

    'note.close': '关闭',
    'note.closeKey': '关闭（E）',

    'map.close': '关闭',
    'map.closeKey': '关闭（M）',
    'map.objective': '目标',
    'map.tape': '磁带',
    'map.doc': '文件',
    'map.shrine': '神龛',
    'map.supply': '补给',
    'map.locked': '上锁的门',

    'kp.label': '安保',
    'kp.clear': '删除',
    'kp.enter': '确认',
    'kp.open': '已开',
    'kp.error': '错误',
    'kp.close': '取消（Esc）',

    'cab.help': '方向键或 WASD · Enter 开始 · P 暂停 ·',
    'cab.exit': '离开机台（Esc）',

    'choice.back': '后退',
    'card.skip': '点击或按 E 继续',

    'death.retry': '从上一个存档继续',
    'death.menu': '主菜单',

    'end.menu': '主菜单',
    'end.skip': '跳过',
    'end.time': '游戏时间',
    'end.deaths': '死亡',
    'end.docs': '文件',
    'end.freed': '解放的游魂',
    'end.drawings': '找到的画',

    'hud.objective': '目标',
    'hud.rec': 'REC',
    'hud.stamina': '气息',
    'hud.battery': '电量',
    'hud.power': '电力 {t}',
    'hud.fps': '{n} FPS',

    'touch.pause': '暂停',
    'touch.bag': '背包',
    'touch.map': '地图',
    'touch.drink': '喝',
    'touch.throw': '扔',
    'touch.crouch': '蹲',
    'touch.sprint': '跑',
    'touch.flash': '灯',
    'touch.tap': '点击',

    'inv.battery': '电池 ×{n}',
    'inv.almond': 'STAR POP ×{n}',
    'inv.glow': '荧光棒 ×{n}',
    'inv.officeKey': '办公室钥匙',
    'inv.token': '金代币',
    'inv.fuses': '保险丝 ×{n}',
    'inv.fuel': '柴油 ×{n}',
    'inv.keycard': '门禁卡',
    'inv.pellets': '灯笼 ×{n}',

    'n.added': '已加入档案：{title}',
    'n.saved': '游戏已保存',
    'n.batteryIn': '手电筒换上了新电池',
    'n.batterySpare': '备用电池',
    'n.noSpare': '没有备用电池。',
    'n.batteryFull': '电池还是满的。',
    'hint.reload': 'R：更换手电筒电池',
    'touch.reload': '电池',
    'help.reload': '更换手电筒电池',
    'help.lookBack': '奔跑时回头看（按住）',
    'n.batterySwap': '换上了备用电池',
    'n.almond': 'Star Pop（按 Q 喝）',
    'n.glow': '荧光棒（按 G 扔）',
    'n.found': '找到：{name}',
    'n.drank': '你喝下 Star Pop。呼吸平稳下来。',
    'n.noAlmond': '你没有 Star Pop。',
    'n.noGlow': '你没有荧光棒。',
    'n.slow': '游戏运行缓慢。可在 暂停 › 设置 › 图形 中降低画质。',
    'n.lockFail': '无法锁定鼠标。按住左键拖动来环顾四周。',
    'n.flashDead': '手电筒熄灭了。',
    'n.holdBreath': '有东西在附近。按住 Shift 屏住呼吸。',
    'n.heardBreath': '它听见你的呼吸了。',
    'n.noFlash': '你没有手电筒。',
    'n.noBattery': '电池没电了。找一节备用的。',
    'n.grace': '好险！（简单难度：每章一次）',
    'n.freed': '{name} 已得到安息',
    'n.ghostBack': '{name} 退开了',
    'n.cabinetHi': '你的名字缩写上了高分榜：SAM',
    'n.perfect': '你吃掉了所有星星。完美通关。',
    'n.fruit': '房子前出现了一个奖品',
    'n.diesel': '柴油桶',
    'n.drawing': '莉莉的画（{n}/8）',

    'pr.read': '阅读：{title}',
    'pr.readWall': '阅读墙上的字',
    'pr.screen': '看屏幕',
    'pr.tape': '播放磁带（存档）',
    'pr.battery': '拿起电池',
    'pr.almond': '拿起 Star Pop',
    'pr.glow': '拿起荧光棒',
    'pr.flashlight': '拿起手电筒',
    'pr.token': '拿起代币',
    'pr.fuse': '拿起保险丝',
    'pr.fuel': '拿起柴油桶',
    'pr.keycard': '拿起门禁卡',
    'pr.take': '拿起：{name}',
    'pr.pellet': '拿起灯笼',
    'pr.phoneRing': '接电话',
    'pr.phone': '拿起听筒',
    'pr.cabinetFree': '玩这台机器（FREE PLAY）',
    'pr.doorLocked': '{name}（已上锁）',
    'pr.doorOpen': '开门',
    'pr.doorClose': '关门',
    'pr.drawerOpen': '打开抽屉',
    'pr.drawerClose': '关上抽屉',
    'pr.safeOpen': '打开保险箱',
    'pr.safeClose': '关上保险箱',
    'pr.safeLocked': '保险箱（输入密码）',
    'pr.hide': '躲到下面',
    'pr.hideLocker': '躲进储物柜',
    'pr.unhide': '出来',
    'pr.shrineLook': '查看神龛',
    'pr.shrinePlace': '把遗物放在神龛上',
    'pr.drawing': '拿起莉莉的画',

    'door.default': '门',
    'door.office': '办公室的门',
    'door.storage': '储藏室',
    'door.wc': '洗手间',
    'door.front': '正门',
    'door.elevator': '货运电梯',
    'door.security': '保安室',
    'door.stair': '消防楼梯',
    'door.house': '游魂之屋',
    'door.service': '员工电梯',
    'lock.service': '电梯没反应。三台发电机都得运转起来。',
    'door.exit': '出口',
    'door.room': '{n} 号房',
    'door.jammed': '门',
    'lock.jammed': '卡住了。门把手能转，但另一边有东西抵着。',
    'lock.exit': '出口锁着。还不行。',
    'door.pressure': '密封门',
    'lock.pressure': '密封门纹丝不动。门后蒸汽嘶嘶作响。',
    'door.janitor': '杂务工',
    'lock.janitor': '一把密码锁。三位数。',
    'door.fireExit': '紧急出口',
    'lock.fireExit': '一条粗铁链和一把挂锁。钥匙在杂务工那里。',
    'lock.fireExitMotel': '推杆推不动。有人从外面把它卡住了。',
    'door.gym': '体育馆',
    'door.mallExit': '商场大门',
    'lock.mallExit': '夜间关闭。远处的自拍照相亭嗡嗡作响。',
    'door.room12': '12 号房',
    'lock.room12': '锁着。门牌被擦得锃亮，好像每天都有人摸它。',
    'door.room207': '207 病房',
    'lock.room207': '锁着。一张纸牌：请保持安静。上面用蜡笔画了个太阳。',
    'door.elevatorH': '电梯',
    'lock.elevatorH': '电梯门紧闭，在等待着。它在等什么东西。',
    'door.samHouse': '你的家',
    'door.tobyHouse': '托比的家',
    'door.neighbor': '正门',
    'lock.neighbor': '锁着。你一移开视线，窗帘就会动。',
    'door.alley': '通往小巷的门',
    'lock.alley': '锁着。要先去街角站一站。',
    'door.kernel': '钢门',
    'lock.kernel': '钢制，上了锁。一块黄铜牌：KERNEL — 仅限 W.',
    'lock.default': '锁着。',
    'lock.office': '锁着。门上有块黄铜牌：“W. — 经理”。',
    'lock.front': '从外面挂了锁。钥匙在搬家公司的人手里。',
    'lock.elevator': '电梯没电。呼叫按钮毫无反应。',
    'lock.security': '键盘要求输入四位数密码。',
    'lock.stair': '读卡器亮着红灯。需要一张门禁卡。',
    'lock.house': '一道紫色的光幕。四盏灯笼将它封住。',

    'cap.front': '前方',
    'cap.back': '后方',
    'cap.left': '左侧',
    'cap.right': '右侧',
    'cap.phone': '[电话铃响]',
    'cap.drag': '[附近有拖沓的脚步声]',
    'cap.moan': '[一声呻吟]',
    'cap.farSteps': '[楼里别处传来脚步声]',
    'cap.thud': '[远处有东西倒下]',
    'cap.buzz': '[日光灯噼啪作响]',
    'cap.whisper': '[低语]',
    'cap.giggle': '[黑暗中传来咯咯笑声]',
    'cap.radio': '[对讲机杂音]',
    'cap.thunder': '[雷声]',
    'cap.hiss': '[湿漉漉的嘶声，渐渐远去]',
    'cap.skitter': '[砖墙上窸窸窣窣的爬动声]',
    'cap.whistle': '[刺耳的哨声]',
    'cap.plastic': '[塑料嘎吱作响]',
    'cap.bite': '[附近牙齿合拢的声音]',
    'cap.biteFar': '[远处的咀嚼声]',
    'cap.callName': '[有人用托比的声音叫你的名字]',
    'cap.heavySteps': '[沉重的脚步声，橡胶的吱吱声]',
    'cap.pipe': '[隧道某处传来管道的鸣响]',
    'cap.locker': '[走廊尽头一扇柜门砰地关上]',
    'cap.knock': '[走廊某处传来三下敲击声]',
    'cap.beep': '[空病房里监护仪在嘀嘀响]',
    'cap.arc': '[钢门后电流噼啪作响]',
    'cap.pop': '[一根灯管爆裂]',
    'cap.slam': '[身后的门砰地关上]',
    'cap.run': '[有人在视线外奔跑]',
    'cap.callJune': '[走廊尽头一个女人的声音：“埃迪？埃迪，是你吗？”]',
    'cap.car': '[一辆车嘶嘶地驶过湿漉漉的街道]',
    'cap.door': '[某处的门声]',
    'cap.drip': '[滴水声]',
    'cap.hum': '[日光灯的嗡鸣]',
    'tab.access': '辅助功能',
    'tab.perf': '性能',
    'set.perfOverlay': '性能信息',
    'set.perfOverlay.help': '显示游戏的运行情况。“仅 FPS”；“基础”加上每帧耗时、每帧 CPU 与 GPU 时间以及各自的占用；“详细”再加上帧时间曲线、绘制调用、三角形数、内存、渲染分辨率和你的显卡。GPU 时间需要浏览器支持 GPU 计时查询（桌面版始终支持）。',
    'set.perfCorner': '信息位置',
    'set.perfCorner.help': '性能信息显示在屏幕的哪个角落。',
    'opt.perfFps': '仅 FPS',
    'opt.perfBasic': '基础',
    'opt.perfDetailed': '详细',
    'opt.cornerTR': '右上',
    'opt.cornerTL': '左上',
    'opt.cornerBR': '右下',
    'opt.cornerBL': '左下',
    'preset.ultraplus': '超高+',
    'opt.ultraplus': '超高+',
    'opt.shadow4': '超高+（8192）',
    'set.modelDetail': '模型精度',
    'set.modelDetail.help': '怪物、双手和其他雕塑模型的精细程度。越高近看越平滑，章节载入也越久。“超高+”适合最快的处理器。',
    'set.clutter': '细节物件',
    'set.clutter.help': '房间里有多少小物件：画、照片、日历、纸箱、纸张、瓶子。越多越有生活气息；越少对旧电脑越友好。',
    'set.dof': '景深',
    'set.dof.help': '像相机镜头一样，模糊离你注视点较远的东西。焦点跟随屏幕中心。更高的设置采样更多，模糊更柔和干净。',
    'set.textureRes.help': '表面的清晰度：墙壁、地板、木头、布料。越高需要越多显存。',
    'set.shadows.help': '手电筒和户外路灯投下的阴影。越高越清晰。“超高+”使用 8192 阴影贴图，需要大量显存。',
    'set.antialias.help': '平滑锯齿边缘。MSAA 最干净；FXAA 开销低，会让整个画面略微柔化；两者同时开启最平滑。',
    'set.dynLights.help': '附近有多少盏灯能同时照亮移动的物体和怪物。',
    'set.bloom.help': '明亮灯光和屏幕周围的柔和光晕。',
    'set.bloomStrength.help': '光晕的强度。',
    'set.motionBlur.help': '快速转身时画面变模糊。双手和手中的东西保持清晰。',
    'set.particles.help': '空气中的灰尘、雨、火花和水滴。',
    'set.viewDist.help': '物体绘制的距离，以及雾气允许你看多远。',
    'set.anisotropy.help': '以斜角观察时保持地板和墙壁清晰。几乎不耗性能。',
    'set.contrast.help': '画面暗部与亮部之间的差别。',
    'set.saturation.help': '色彩的浓淡。越低越像老照片。',
    'set.fov.help': '视野的宽度。越宽看到的越多，但一切都会显得更远。',
    'set.headBob.help': '走路时视角晃动的幅度。如感到晕眩请调低。',
    'set.shake.help': '受惊、撞击和奔跑时的镜头震动。',
    'set.grain.help': '画面上的胶片颗粒。',
    'set.chromatic.help': '画面边缘的彩色镶边，就像廉价镜头那样。',
    'set.vignette.help': '屏幕四角逐渐变暗。',
    'set.crosshair.help': '屏幕中央的小点，帮助你对准可拾取的物品。',
    'set.subtitles.help': '显示说话的内容：对讲机、磁带、心声。',
    'set.subtitleSize.help': '字幕和声音字幕的大小。',
    'set.master.help': '总音量。',
    'set.music.help': '配乐音量。',
    'set.sfx.help': '脚步、门、物品以及你做的一切。',
    'set.ambience.help': '房间、雨声、嗡鸣和建筑本身的声音。',
    'set.entities.help': '怪物的脚步、呼吸和声音。',
    'set.voice.help': '对讲机、磁带和心声。',
    'set.hrtf.help': '让声音在你周围立体地分布。最适合耳机；使用音箱时请关闭。',
    'set.mouseSens.help': '用鼠标转动视角的速度。',
    'set.invertY.help': '鼠标向上移动时视角向下。',
    'set.touchSens.help': '在触摸屏上拖动时视角转动的速度。',
    'set.padSens.help': '用手柄右摇杆转动视角的速度。',
    'set.toggleCrouch.help': '按一下蹲下，再按一下站起，无需按住按键。',
    'set.toggleSprint.help': '按一下奔跑，再按一下行走，无需按住按键。',
    'set.lang.help': '菜单、字幕和游戏中所有文件的语言。',
    'set.jumpscare.help': '“减弱”保留每一次惊吓，但让最强烈的闪光和声音柔和一些。',
    'set.hints.help': '有新情况发生时显示简短提示。',
    'perf.frame': '帧',
    'perf.low1': '1% 最低',
    'perf.cpu': 'CPU',
    'perf.cpuUse': 'CPU 占用',
    'perf.gpu': 'GPU',
    'perf.gpuUse': 'GPU 占用',
    'perf.na': '无',
    'perf.draws': '绘制调用',
    'perf.tris': '三角形',
    'perf.textures': '纹理',
    'perf.programs': '着色器',
    'perf.res': '渲染',
    'perf.heap': 'JS 内存',
    'perf.sysCpu': '系统 CPU',
    'perf.appCpu': '游戏 CPU',
    'perf.procMem': '游戏内存',
    'perf.card': '显卡',
    'settings.revert': '撤销',
    'settings.keys': '↑↓ 选择 · ←→ 更改 · Q/E 切换标签 · Backspace 撤销 · Esc 返回',
    'settings.impact': '性能开销',
    'impact.0': '无',
    'impact.1': '低',
    'impact.2': '中',
    'impact.3': '高',
    'impact.4': '很高',
    'impact.5': '极高',
    'settings.gpuLoad': '预计 GPU 负载',
    'settings.vram': '预计显存',
    'settings.reloadBadge': '下次载入章节时生效',
    'settings.restartBadge': '重启游戏后生效',
    'settings.restartNow': '立即重启',
  });
})(typeof window !== 'undefined' ? window : globalThis);
