/* 简体中文界面，用于艾达·林德的故事：替换属于旧故事的内容，并补充九层架子所需的内容
   （门、楼梯、文档类型、字幕）。在 ui.js 之后加载。 */
(function (root) {
  'use strict';
  root.PB.I18N.register('zh-CN', 'ui', {
    'game.subtitle': '失物招领',
    'menu.credit': '哈尔瓦德 · 1998年1月13日 · 02:56',
    'diff.time': '预计游戏时长：读完每份文档并找到全部八幅画，约需5–7小时。',
    'set.vhs.help': '让游戏看起来像是透过一台老式家用摄像机拍的。',
    'help.drink': '吃一颗麦芽糖',
    'bag.stats': '文档 {a} / {b}   ·   雷恩的画 {c} / {d}',
    'bag.d.flashlight': '一支包着橡胶的沉重手电，从九号库柜台底下拿的。电量：{n}%。熄灭之前会先变暗。',
    'bag.n.almond': '麦芽糖',
    'bag.d.almond': '一颗拧成麻花的麦芽糖，来自柜台下的铁盒，留着熬难熬的夜。糖能让手不再发抖。按 Q 吃。',
    'bag.d.officeKey': '一把小小的黄铜钥匙，已经磨得发亮。',
    'bag.d.token': '一枚黄铜代币。',
    'help.padText': '左摇杆：行走。右摇杆：环顾。A：互动。B：蹲下。X：换电池。Y：手电。LB / RB：探身。RT 或按下左摇杆：奔跑。LT：荧光棒。按下右摇杆：回头看。十字键：↑ 日志，↓ 麦芽糖，→ 物品。视图键：地图。菜单键：暂停。在菜单中十字键移动，A 确认，B 返回。',
    'help.tip7': '每个地方的底下都压着一个谎言。<b>把失物放回它该在的地方</b>，路就会打开。',
    'map.shrine': '认领处',
    'end.freed': '已认领的架子',
    'end.claimed': '已认领的架子',
    'inv.almond': '麦芽糖 ×{n}',
    'inv.token': '代币',
    'n.almond': '麦芽糖（按 Q 吃）',
    'n.drank': '你吃下麦芽糖。呼吸平稳下来。',
    'n.noAlmond': '你没有麦芽糖了。',
    'n.drawing': '雷恩的画（{n}/8）',
    'pr.almond': '拿起麦芽糖',
    'pr.drawing': '拿起雷恩的画',
    'door.house': '房子',
    'touch.drink': '糖',
    'inv.pellets': '失落之灯 ×{n}',
    'pr.pellet': '拿起失落之灯',
    'lock.house': '一道光幕。四盏失落之灯把它锁住。',
    'help.tip1': '<b>先听，再看。</b>每种生物都有自己的规则：有的靠听，有的只看得见光，有的只在没人看着时才动。文档会告诉你谁是谁。',
    'help.tip2': '当灯光开始结巴，或者世界里的声音退去时，<b>就有东西在附近</b>。',
    'help.tip3': '在地底，拿起一盏<b>失落之灯</b>，吞噬者会有几秒钟远离你。',
    'help.tip4': '每层架子都有<b>自己的生物</b>：查票的列车员，只在管风琴演奏时奔跑的马，只在你移动时移动的松树。弄清每一种的规则。',
    'help.tip5': '你可以<b>躲</b>在床、铺位和书桌下面，也可以躲进柜子里。如果没有东西看见你钻进去，就不会有东西来找。',
    'help.tip6': '游戏会在每个目标完成、你安全时<b>自动存档</b>。',
    'set.subtitles.help': '显示说出的话：九频道、磁带、内心独白。',
    'set.voice.help': '九频道、磁带和内心独白。',
    // 九层架子上的门与通道
    'pr.unlock': '开锁',
    'pr.stairs': '走楼梯',
    'pr.stairsDown': '下楼梯',
    'pr.stairsUp': '上楼梯',
    'pr.ladderDown': '顺梯子爬下去',
    'pr.ladderUp': '顺梯子爬上去',
    'door.otto': '奥托·勃兰特的办公室',
    'lock.otto': '自1964年起就锁着。钥匙一定在档案室里的某个地方。',
    'door.concourse': '车站大厅',
    'lock.concourse': '从另一边锁上了。',
    'door.bridge': '驾驶台',
    'lock.bridge': '锁着。钥匙在船长那里。',
    'door.cage': '罐笼',
    'lock.cage': '罐笼的栅门。没有电，什么都动不了。',
    'door.fire': '防火门',
    'lock.fire': '被楔死了。从这一边。',
    'door.signe': '斯图加塔街4号',
    'lock.signe': '锁着。里面点着一盏灯。',
    'door.ghost': '鬼屋列车',
    // 文档类型
    'kind.telegram': '电报',
    'kind.transcript': '记录稿',
    'kind.clipping': '报纸',
    // 声音字幕
    'hint.flash': '按 F 开关手电。',
    'cap.chute': '[一个包裹从滑道上掉下来]',
    'cap.tube': '[气动管道咚咚作响]',
    'cap.bellFar': '[一口钟，在远处的雾里]',
    'cap.doorShut': '[某处有扇门关上了]',
    'cap.stepsFar': '[脚步声，很远]',
    'cap.organ': '[一台游乐场管风琴自己奏响了]',
    'cap.organStop': '[管风琴慢下来，停了]',
    'cap.choir': '[一个唱诗班在唱歌]',
    'cap.knocks': '[七下敲击，敲在钢上]',
    'cap.ice': '[冰在远处开裂]',
    'cap.brake': '[刹车尖叫]',
    'cap.laugh': '[笑声]',
    'cap.toll': '[一口钟在鸣响]',
    'cap.breath': '[呼吸声，就在你身后]',
    'cap.train': '[列车全速行驶]',
    'cap.pa': '[一声提示音；广播喇叭沙沙作响]',
  });
})(typeof window !== 'undefined' ? window : globalThis);
