/* Rdzeń fabuły po polsku: postacie, wspólne kwestie, śmierci, wskazówki, zakończenia, napisy końcowe.
   Płeć Sam nigdy nie pada, więc teksty unikają form rodzajowych dla Sam (czas teraźniejszy, konstrukcje bezosobowe)
   i odmiany imienia w przypadkach zależnych. */
(function (root) {
  'use strict';
  root.PB.I18N.register('pl', 'story', {
    chars: {
      sam: { name: 'Sam', pos: 'Sam', role: 'Nocny kierowca w Tri-County Movers, 20 lat. W 1987 roku trzynaście, piąta osoba w paczce. Ty.' },
      walt: { name: 'Walt', pos: 'Walta', role: 'Właściciel salonu gier Starlight. Technik radarowy w lotnictwie, potem naprawiacz telewizorów. Zaginiony od marca 1992.' },
      lily: { name: 'Lily', pos: 'Lily', role: 'Córka Walta. Zmarła w październiku 1983 roku, w wieku dziewięciu lat. Wynik: 3190.' },
      danny: { name: 'Danny', pos: 'Danny’ego', role: 'W 1987 roku szesnaście lat. Głośny, nieustraszony, zawsze pierwszy na liście wyników. Miał zapasowy klucz Walta.' },
      rosie: { name: 'Rosie', pos: 'Rosie', role: 'W 1987 roku piętnaście lat. Ta, która wszystko planowała. Chciała mieć własną audycję w radiu.' },
      nell: { name: 'Nell', pos: 'Nell', role: 'W 1987 roku piętnaście lat. Cicha, rysowała komiksy, grube okulary. Nigdy nie wybaczyła sobie jednego popołudnia na basenie.' },
      toby: { name: 'Toby', pos: 'Toby’ego', role: 'W 1987 roku trzynaście lat. Sam i on: najlepsi przyjaciele. Bał się ciemności.' },
      eddie: { name: 'Eddie', pos: 'Eddiego', role: 'Pomocnik Walta w latach 1984–1988. Wszedł po nich w czerwcu 1993. Ma córkę, której nigdy nie trzymał na rękach.' },
      nora: { name: 'Nora', pos: 'Nory', role: 'Młodsza siostra Walta.' },
      frank: { name: 'Frank Dobbs', pos: 'Dobbsa', role: 'Detektyw policji w Harlow, 1987.' },
      june: { name: 'June', pos: 'June', role: 'Żona Eddiego. Nocna recepcjonistka w Blue Moon Motor Inn.' },
      theo: { name: 'Theo', pos: 'Theo', role: 'Młodszy brat Nell.' },
      maggie: { name: 'Maggie', pos: 'Maggie', role: 'Mama Toby’ego.' },
      ruth: { name: 'Ruth', pos: 'Ruth', role: 'Żona Walta do 1985 roku.' },
      ray: { name: 'Ray', pos: 'Raya', role: 'Ojciec Danny’ego.' },
      carol: { name: 'Carol', pos: 'Carol', role: 'Mama Rosie.' },
      ann: { name: 'Ann', pos: 'Ann', role: 'Mama. Sam jest jej dzieckiem.' },
    },
    speakers: { sam: 'SAM', eddie: 'EDDIE', walt: 'WALT', danny: 'DANNY', rosie: 'ROSIE', nell: 'NELL', toby: 'TOBY', lily: 'LILY', june: 'JUNE', radio: 'RADIO', voice: '???' },
    items: {},
    obj: {
      ghost: 'Zanieś pamiątkę {pos} do kapliczki (opcjonalnie)',
    },
    recap: {
      prolog: 'Salon gier Starlight, noc przed licytacją. Automat nr 7 działał bez wtyczki w gniazdku i znał moje imię. PLAYER 1: SAM — CONTINUE?',
      lobby: 'Żółte pokoje bez końca: gra, która czeka na gracza. Coś okrągłego i bladego je tam w ciemności. Eddie żyje, jest na krótkofalówce, w środku od 1993 roku.',
      mill: 'Magazyn ojca Danny’ego. Danny goni mnie z krzykiem: „Twoja ręka puściła!”. Oddaję mu zegarek jego ojca; zatrzymuje się i przypomina sobie swoje imię.',
      pipes: 'Kanały burzowe. Nasza twierdza. Zasada czwarta: nikt nie wraca do domu sam. Ta zasada wyszła spod mojej ręki.',
      pool: 'Basen, na którym Theo o mało nie utonął, kiedy Nell kończyła rysunek. Od lat czeka na przebaczenie. Theo przebaczył jej już w pierwszym liście.',
      office: 'Biuro mamy Rosie, sto siedem i trzy dziesiąte. Na jej taśmie o 0:40 ktoś puka do tylnych drzwi salonu. Rosie: „No proszę, kto tu wraca na czworakach”.',
      school: '16 kwietnia 1987. Pakt: wszystkie pięć rąk na drążku, nikt nie puszcza. Pięć inicjałów na dole. Ostatnie są moje.',
      dark: 'Ciemność, trzy generatory i mosiężna zapalniczka. Na ostatniej stronie Toby pisze, że Sam zawraca. Tego powrotu nie ma w mojej pamięci.',
      mall: 'Najlepsza sobota 1986 roku: piątka dzieciaków w fotobudce, a jedno z nich to ja, roześmiane. Manekiny ruszały się tylko wtedy, gdy odwracało się od nich wzrok.',
      motel: 'Wspomnienie Eddiego, nie moje. Pokój 12 i jego notes: JEDEN WCHODZI, JEDEN WYCHODZI. Potrzebuje kogoś, kto zostanie na jego miejscu. Chciał, żeby padło na mnie.',
      hospital: 'St. Agnes, październik 1983. Lily poprosiła tatę o grę, która nigdy się nie kończy, żeby nikt nigdy nie musiał odchodzić. Walt ją zbudował.',
      maple: 'Moja ulica. Głos mamy na sekretarce o 2:50 w nocy, pyta, gdzie jestem. O 21:40 nie było mnie w domu.',
      workshop: 'Piwnica Walta i taśma z 3:17. Pięć rąk na drążku, a jedna puściła. Moja.',
      maze: 'Poziom 255, sam dom. Zjawy, które pamiętają, idą obok mnie jako kolorowe światła.',
      killscreen: 'Poziom 256. Zepsuta strona. Wtyczka, która potrzebuje pięciu rąk, i drzwi, które wypuszczają jedną osobę.',
    },
    memento: {
      danny: { name: 'Zegarek Danny’ego', line: 'Stalowy zegarek z pękniętym szkiełkiem, stanął o 3:17. Na odwrocie grawer: „RAY KOWALSKI — 25 LAT — HARLOW MILL”.' },
      rosie: { name: 'Kaseta Rosie', line: 'Fioletowy walkman z kasetą w środku. Na naklejce: STRONA B: NA POTEM. Strona B jest pusta.' },
      nell: { name: 'Okulary Nell', line: 'Ciężkie okulary, jedno szkło pęknięte. Parują ci w dłoni, jakby ktoś przed chwilą na nie chuchnął.' },
      toby: { name: 'Zapalniczka Toby’ego', line: 'Stara mosiężna zapalniczka. Grawer: „TOBY — ŻEBYŚ NIGDY NIE SIEDZIAŁ PO CIEMKU. DZIADEK”.' },
    },
    freed: {
      danny: ['DANNY: „3:17. Mój zegarek stanął. Ja nigdy”.', 'DANNY: „…No proszę, jesteś. Długo ci zeszło, Keller. Idź. Zajmę tego dużego”.'],
      rosie: ['ROSIE: „Strona B. Mieliśmy ją nagrać potem. Jak już wygramy”.', 'ROSIE: „Zawsze biegłam przed wszystkimi. Teraz pójdę obok ciebie”.'],
      nell: ['NELL: „Moje okulary. Wszystko jest takie… ostre”.', 'NELL: „Nie czekam już, aż będę pewna. Idę z tobą”.'],
      toby: ['TOBY: „Zapalniczka dziadka…” (Płomień się zajmuje. Pierwszy raz widzisz jego twarz: dzieciak, trzynaście lat, piegi.)', 'TOBY: „…Nie patrz jeszcze na mnie, Sam. Po prostu idź. Jestem tuż za tobą”.'],
    },
    shrine: {
      quiet: 'Kapliczka milczy. Świeca pali się dalej.',
      missing: 'Mała kapliczka. Oprawione zdjęcie {pos} i puste miejsce, gdzie czegoś brakuje.',
    },
    mono: {
      watcherSeen: 'Daleko stoi coś wysokiego i czarnego. Głowę ma przechyloną na bok. Liczy.',
      hide: 'Wstrzymaj oddech.',
      hideLocker: 'Wstrzymaj oddech. Nie ruszaj się.',
      fearHigh: 'Nie mogę oddychać…',
      lowBattery: 'Bateria umiera.',
      freed: '{name} już mnie nie ściga.',
      eaterFlicker: 'Światła przygasają. To jest blisko. Słychać, jak przeżuwa.',
    },
    ghostHelp: {
      danny: 'DANNY: „Uciekaj! Mam go!”',
      amberWatch: 'TOBY: „Nie patrz na mnie… proszę, nie patrz…”',
    },
    deaths: {
      eater: ['POŻARCIE', 'Pożeracz jest szybszy od ciebie na prostej i wolny na zakrętach. Bierz zakręty i nasłuchuj przeżuwania.'],
      red: ['SCHWYTANIE', 'Danny nigdy się nie zatrzymuje i nigdy nie odpuszcza pościgu. Przerwij jego linię wzroku i postaw między wami róg.'],
      violet: ['ODCIĘTA DROGA', 'Rosie biegnie tam, dokąd zmierzasz, a nie tam, gdzie jesteś. Zmień kierunek, kiedy zniknie.'],
      teal: ['POD WODĘ', 'Nell słyszy wodę. Omijaj kałuże i trzymaj się krawędzi.'],
      amber: ['BEZRUCH', 'Toby nie może się ruszyć, dopóki na niego patrzysz. Nie spuszczaj z niego oczu ani światła.'],
      grinner: ['TO SIĘ UŚMIECHNĘŁO', 'Szczerzacze topnieją w świetle. Trzymaj na nich latarkę albo rzuć świetlik.'],
      watcher: ['RACHUNEK', 'Liczący rusza się tylko wtedy, gdy na niego nie patrzysz. Nie odwracaj się do niego plecami na długo.'],
      crawler: ['NA DNO', 'Pełzacze cofają się przed światłem, a potem zachodzą cię z boku. Stój plecami do ściany i nie trzymaj żadnego zbyt długo w snopie światła.'],
      monitor: ['BEZ PRZEPUSTKI', 'Dyżurny widzi tylko to, na co pada światło jego latarki. Schowaj się w szafce, zanim snop cię znajdzie.'],
      mannequin: ['POZA', 'Manekiny ruszają się tylko wtedy, gdy nikt nie patrzy. W razie czego idź tyłem.'],
      neighbor: ['OTWARTE DRZWI', 'Sąsiad podchodzi bliżej, kiedy stoisz do niego plecami. Latarka zmusza go do cofnięcia się. Nigdy nie odpowiadaj na głos.'],
      chompy: ['WIELKI UŚCISK', 'Chompy jest powolny, ale nigdy nie przestaje iść. Poświeć mu w oczy, a zasłoni twarz.'],
    },
    tips: [
      'Pożeracz jest szybszy od ciebie w prostym korytarzu, ale wolny na zakrętach. Bierz zakręty.',
      'Bieganie jest głośne. Chodzenie w kucki jest prawie bezgłośne, a w kucki otwierasz drzwi po cichu.',
      'Jeśli światła przygasają i migają, Pożeracz jest blisko.',
      'Lampion sprawia, że przez kilka sekund wszystko przed tobą ucieka.',
      'Magnetofony zapisują grę i odtwarzają wspomnienie.',
      'Możesz chować się pod biurkami, łóżkami i ladami oraz w szafkach. Jeśli nic nie widzi, jak wchodzisz, nic nie będzie szukać.',
      'Zanieś każdej Zjawie jej pamiątkę do kapliczki, a przestanie na ciebie polować. Od tego zależy zakończenie.',
      'Star Pop uspokaja nerwy i oddaje oddech.',
      'M otwiera mapę zbadanych miejsc.',
      'Latarka pożera baterie. Świetliki (G) oświetlają kąt, a ich brzęk odciąga łowców od ciebie.',
      'Patrz dalej na tego bursztynowego. Ale nie za długo.',
      'Lily zostawiła osiem rysunków. Niektóre są dobrze ukryte.',
      'Eddie zna to miejsce lepiej niż ktokolwiek. To nie znaczy, że mówi ci wszystko.',
      'Szafki ukrywają cię całkowicie. Kiedy coś podchodzi, przytrzymaj Shift, żeby wstrzymać oddech.',
      'Manekiny nie mogą się ruszać, dopóki na nie patrzysz.',
      'Sąsiad mówi głosami, które znasz. Nie odpowiadaj.',
      'Walt wyrwał pięć stron ze swojego pamiętnika. Znaczą więcej, niż się wydaje.',
      'Szuflada uchylona na szerokość palca coś w sobie ma. Sejf z niedomkniętymi drzwiczkami też.',
      'Przytrzymaj V (albo środkowy przycisk myszy), żeby w biegu spojrzeć przez ramię.',
      'Im dłużej jest cicho, tym bliżej podchodzą. Gra nie lubi czekać.',
    ],
    endings: {
      exit: {
        title: 'WYJŚCIE', subtitle: 'Złe zakończenie — Znowu',
        lines: [
          'Wybierasz drzwi. Za tobą Eddie krzyczy twoje imię, a potem drzwi się zamykają i krzyk zostaje po drugiej stronie.',
          'Zimne powietrze. Deszcz. Otwierasz oczy na mokrej wykładzinie salonu. Jest rano. Rolety są do połowy podniesione.',
          'Automat nr 7 wciąż działa. Na ekranie demonstracyjnym po domu snuje się teraz pięć Zjaw. Piąta ma na sobie kurtkę roboczą.',
          'Ludzie od przeprowadzki ładują go w południe. Kierowca opowie później, że przez całą Route 9 słyszał, jak ktoś puka od środka automatu.',
          'Ciężarówka nigdy nie dojeżdża na licytację.',
          'Obietnica, że już nigdy ich nie zostawisz, padła dawno temu. Za drugim razem było łatwiej. To jest najgorsze.',
        ],
      },
      deal: {
        title: 'UMOWA', subtitle: 'Mroczne zakończenie — Jeden wchodzi, jeden wychodzi',
        lines: [
          'Trzymasz drzwi. Eddie patrzy na ciebie przez długą sekundę. „Opowiem im o tobie. Opowiem wszystkim”.',
          'Przechodzi. Drzwi zamykają się cicho, jak koniec taśmy.',
          'Gdzieś w Harlow o świcie przemoczony mężczyzna wchodzi do kuchni, a roczna dziewczynka wpatruje się w niego ze swojego wysokiego krzesełka.',
          'Dom milczy. Gdzieś daleko coś okrągłego znów zaczyna przeżuwać.',
          'Nie jesteś Graczem. Nie jesteś Zjawą. Jesteś tą osobą, która została. Gwiazdy świecą. Wiesz, gdzie jest każda z nich.',
          'Na liście wyników w pustym salonie, pismem, którego nikt nie potrafi wyjaśnić, pojawia się nowa linijka: SAM — WCIĄŻ GRA.',
        ],
      },
      plug: {
        title: 'GAME OVER', subtitle: 'Dobre zakończenie — Nikt nie puszcza',
        lines: [
          'Cztery kolorowe światła zamykają się na twoich dłoniach. Czerwone, fioletowe, turkusowe, bursztynowe. Pięć rąk, jak mówił pakt.',
          'Ciągniesz. Wtyczka wychodzi. Pierwszy raz od 1987 roku buczenie milknie.',
          'W ciemności, bardzo blisko, zmęczony, ludzki głos: „Jestem syty, Sam. Nareszcie”.',
          'Budzisz się na wykładzinie salonu. Przez szybę wpada świt.',
          'Czworo dzieciaków w kurtkach z 1987 roku siedzi na podłodze i mruga. Toby długo na ciebie patrzy. „Sam? …Ile ci lat przybyło”. Potem przytula cię tak mocno, że aż boli.',
          'Na Maple Street gaśnie światło na ganku, które paliło się przez siedem lat.',
          'Eddie wraca do domu pustymi ulicami. Nie biegnie. Chce zapamiętać drogę.',
          'Automat nr 7 jest ciemny. W szkle zostaje wypalona jedna linijka: GAME OVER — 5 PLAYERS.',
        ],
      },
      lil: {
        title: 'LIL', subtitle: 'Prawdziwe zakończenie — Imiona na liście',
        lines: [
          'Kładziesz osiem rysunków na rdzeniu. Kredka na papierze: salon gier, pomarańczowy Chompy z rogami, szpitalne okno, tatuś.',
          'Pożeracz przestaje przeżuwać. Długo panuje cisza. Potem głosem, który pamiętasz z 1985 roku: „…To rysowała Lily”.',
          'Walt stoi tam, gdzie był Pożeracz, chudy i szary, znowu sobą. „Opuść ręce. Tę wtyczkę wyciągam ja. Zawsze to było moje zadanie”.',
          'Cztery kolorowe światła zamykają się na jego dłoniach. Ciągnie. Dom składa się jak papier.',
          'Ostatnie, co widzisz, to mała dziewczynka w szpitalnej koszuli, która bierze go za rękę, i jak oboje odchodzą w ciemność między gwiazdami.',
          'Świt. Czworo dzieciaków na wykładzinie salonu. Eddie przy budce telefonicznej na zewnątrz, śmieje się i płacze naraz. „June? June, to ja”.',
          'Tydzień później Nora otwiera salon ostatni raz i znajduje listę wyników przepisaną pismem, które zna. 1 LIL. 2 DAN. 3 ROS. 4 NEL. 5 TOB. 6 SAM. 7 WALT.',
          'Światło na ganku Toby’ego gaśnie. Na Maple Street dwie osoby, które nie są już dziećmi, siedzą na krawężniku i rozmawiają do południa. Sam opowiada mu wszystko. On już wiedział.',
        ],
      },
    },
    scrawl: {
      yellow: ['KTO WRÓCIŁ DO DOMU?', 'ZAWSZE JEST 3:17', 'NIE PUSZCZAJ', 'PIĘĆ RĄK', 'SŁYSZĘ, JAK PRZEŻUWA', 'POLICZ DRZWI'],
      dark: ['NIE GAŚ ŚWIATŁA', 'SAM?', 'UŚMIECHA SIĘ, GDY MRUGASZ', 'NIE BOJĘ SIĘ'],
      office: ['GDZIE WSZYSCY SIĘ PODZIALI', '107.3', 'STRONA B'],
      hospital: ['PROSZĘ O CISZĘ', 'RYSOWAŁA NA WSZYSTKIM', '207'],
      motel: ['JEDEN WCHODZI JEDEN WYCHODZI', 'NIE ODPOWIADAJ', '3:17'],
      school: ['NIKT NIE PUSZCZA', 'D R N T S', 'SAM TU BYWA'],
      concrete: ['TWOJA RĘKA PUŚCIŁA', 'DAN #1', '3:17'],
      pool: ['JEDNA SEKUNDA', 'PILNOWAŁAM'],
      mall: ['PRZYJACIELE NA ZAWSZE', 'NAWET JEŚLI'],
      tunnel: ['NIKT NIE WRACA DO DOMU SAM', 'D+T+S'],
      workshop: ['NIE WYCIĄGAJ WTYCZKI', '2 5 6'],
    },
    photoLabels: { fort: 'TWIERDZA. DZIEŃ OTWARCIA.', chompy: 'LIL & CHOMPY' },
    credits: [
      ['LEVEL 256', 'Salon gier Starlight'],
      ['Horror z perspektywy pierwszej osoby', ''],
      ['Dedykowane', 'wszystkim, którzy kiedyś coś puścili, a potem po to wrócili'],
      ['Hungry House', 'fikcyjna gra automatowa z 1981 roku, stworzona na potrzeby tej historii'],
      ['Dźwięk', 'syntezowany na żywo, ani jednego nagrania'],
      ['Tekstury i modele', 'proceduralne, ani jednego pliku graficznego'],
      ['Do graczy', 'nigdy nie wrzucajcie żetonu do automatu nr 7 po północy'],
    ],
  });
})(typeof window !== 'undefined' ? window : globalThis);
