/* Rdzeń historii po polsku: postacie, mówiący, wspólne kwestie, śmierci, wskazówki, napisy końcowe, napisy na ścianach.
   Pliki rozdziałów dodają dokumenty, cele, myśli, krótkofalówkę i streszczenia; lake.js dodaje zakończenia.
   Biblia historii to docs/STORY.md. */
(function (root) {
  'use strict';
  root.PB.I18N.register('pl', 'story', {
    chars: {
      ada: { name: 'Ada', pos: 'Ady', role: 'Ada Lind, 31 lat. Od 1990 roku nocna urzędniczka w Składnicy 9, biurze rzeczy znalezionych pod Dworcem Centralnym w Halvard. Ty.' },
      wren: { name: 'Wren', pos: 'Wren', role: 'Wren Lind, młodsza siostra Ady. Siedem lat. Zaginęła na lodzie jeziora Ostra 14 stycznia 1979 roku.' },
      otto: { name: 'Otto', pos: 'Ottona', role: 'Otto Brandt, nocny urzędnik Składnicy 9 od 1946 do 1964 roku, kiedy zjechał windą towarową. Na kanale dziewiątym.' },
      ingrid: { name: 'Ingrid', pos: 'Ingrid', role: 'Ingrid Lind, babcia dziewczynek. Urodzona w Gammel Ostra. Zmarła w 1996 roku.' },
      clerk: { name: 'Nocna Urzędniczka', pos: 'Nocnej Urzędniczki', role: 'Prowadzi Indeks na samym dnie Podspodu. Podpisuje notatki literą „A.”' },
    },
    speakers: { ada: 'ADA', otto: 'OTTO', radio: 'RADIO', lyle: 'LYLE HARDY', clerk: 'URZĘDNICZKA', wren: 'WREN', voice: '???' },
    items: {},
    obj: {},
    memento: {},
    freed: {},
    shrine: {},
    ghostHelp: {},
    mono: {
      hide: 'Wstrzymaj oddech.',
      hideLocker: 'Wstrzymaj oddech. Nie ruszaj się.',
      fearHigh: 'Nie mogę oddychać...',
      lowBattery: 'Bateria się kończy.',
      eaterFlicker: 'Światła przygasają. Jest blisko. Słyszę, jak przeżuwa.',
      watcherSeen: 'Coś wysokiego na samym końcu, zupełnie nieruchome.',
    },
    // [co pokazuje ekran, co zrobić inaczej]
    deaths: {
      eater: ['POŻARTA', 'Pożeracz jest szybki na prostej i wolny na zakrętach. Świeżo podniesione zgubione światło w dłoni każe mu się cofnąć na kilka sekund.'],
      sorter: ['POSORTOWANA', 'To, co sortuje archiwum po ciemku, dalej robi swoje. Nie wchodź między to a regały.'],
      wallpaperMan: ['ZATAPETOWANA', 'Płascy ludzie schodzą ze ściany tylko za twoimi plecami. Mijaj ich, patrząc na nich.'],
      hummer: ['ZAGŁUSZONA', 'Tam, gdzie buczenie narasta, a światła migoczą, coś nasłuchuje. Idź powoli i trzymaj się z dala od głośnych miejsc.'],
      drowned: ['WCIĄGNIĘTA NA DNO', 'Topielcy czekają pod wodą i słyszą cię w niej. Trzymaj się z dala od wody i nigdy nie stój w niej w miejscu.'],
      passenger: ['ODPROWADZONA NA MIEJSCE', 'Pasażerowie budzą się, gdy zatrzyma się na nich światło. Nie świeć im w twarze i nie ocieraj się o nich.'],
      bellman: ['ZADZWONIONA', 'Na otwartym pokładzie Dzwonnik cię słyszy. Kiedy dzwon zaczyna bić, on poluje: schowaj się i nie wstawaj.'],
      pines: ['ZABRANA MIĘDZY DRZEWA', 'Sosny ruszają się tylko wtedy, gdy ty się ruszasz. Blisko nich stój w miejscu i pozwól im stracić zainteresowanie.'],
      stag: ['STRATOWANA', 'Jeleń szarżuje w linii prostej. Postaw między wami drzewo albo samochód, a sam się ogłuszy.'],
      usher: ['ODPROWADZONA DO FOTELA', 'Bileter widzi tylko w swoim czerwonym snopie. Trzymaj się poza światłem i nigdy nie przechodź przed nim.'],
      burrower: ['WCIĄGNIĘTA POD ZIEMIĘ', 'Ryjce czują twoje kroki przez ziemię. Na ziemnej podłodze kucaj; na szynach i deskach jesteś bezpieczna.'],
      lamplighter: ['LAMPA W OCZY', 'Lampiarze idą do każdego światła. Zgaś swoje i pozwól im przejść.'],
      crawler: ['SPADŁO Z GÓRY', 'Pełzacze z obudowy czekają w belkach stropu. Spójrz w górę, zanim pod nimi przejdziesz, i trzymaj się nisko.'],
      frozen: ['ZAMARZNIĘTA', 'Zamarznięci goście ruszają się tylko blisko ciepła. Ogrzej się i odejdź od ognia, zanim wstaną.'],
      cold: ['ZAMARZNIĘTA', 'Na zewnątrz zimno wchodzi szybko. Idź od schronienia do schronienia i grzej się przy ogniu.'],
      whiteout: ['POCHŁONIĘTA PRZEZ ŚNIEG', 'W zamieci widzisz tylko jego ślady. Ono cię słyszy: idź, nie biegnij, i trzymaj się blisko schronienia.'],
      cook: ['NA HAKU', 'Kucharz nigdy nie wychodzi z kuchni. Poczekaj, aż odwróci się plecami w drugim końcu, i wtedy przejdź.'],
      silted: ['WCIĄGNIĘTA W BŁOTO', 'Postój za długo na błocie, a jeden z nich wyrośnie obok ciebie. Nie przestawaj się ruszać.'],
      longone: ['ZABRANA DO RZEKI', 'Długie czekają w studniach, rowach i w rzece. Kucaj, kiedy mijasz wodę.'],
      choir: ['POSADZONA W ŁAWCE', 'Dopóki chór śpiewa, nic nie widzi. Idź cicho za ich plecami; nigdy nie biegnij, nigdy nie przechodź przed nimi.'],
      water: ['UTONIĘTA', 'Woda podnosi się coraz szybciej. Idź wyżej i wspinaj się.'],
      conductor: ['WYSADZONA Z POCIĄGU', 'Bez ważnego biletu Konduktor wysadzi cię z pociągu. Gdy jego latarka pojawi się na korytarzu, zgaś swoją i wejdź pod kuszetkę.'],
      sleeper: ['WCIĄGNIĘTA NA KUSZETKĘ', 'Śpiący nie widzą. Krok przed ich przedziałem ich budzi: przechodź skulona i zamieraj, gdy któryś wstanie.'],
      underhand: ['WCIĄGNIĘTA MIĘDZY WAGONY', 'Nigdy nie stawaj w przejściu między wagonami. Przechodź szybko i otwieraj następne drzwi, zanim staniesz na płytach.'],
      mask: ['TWARZE', 'Maski ruszają się tylko wtedy, gdy nikt na nie nie patrzy. Trzymaj je przed sobą i cofaj się.'],
      horse: ['STRATOWANA', 'Konie biegną tylko wtedy, gdy gra katarynka. Gdy muzyka cichnie, one też stają: wtedy ruszaj się ty.'],
      lotte: ['PODNIESIONA', 'Lotte nie widzi. Słyszy i nigdy nie przestaje się śmiać: trzymaj się z dala od śmiechu i bądź cicho.'],
      hush: ['UCISZONA', 'Przy Ciszy gaśnie każdy dźwięk. Kiedy przestajesz słyszeć samą siebie, jest bardzo blisko. Odejdź, powoli.'],
      underice: ['POD LÓD', 'Nigdy nie biegnij po ciemnym lodzie nad starym korytem. Idź, a to, co pod spodem, zostanie pod spodem.'],
    },
    tips: [
      'Bieganie jest głośne. Chodzenie w kucki jest prawie bezgłośne.',
      'Na dnie każdej półki leży kłamstwo. Znajdź zgubioną rzecz i odłóż ją tam, gdzie jej miejsce, a to miejsce cię wypuści.',
      'Większość z nich lepiej słyszy, niż widzi. Gaś latarkę, gdy coś jest blisko.',
      'Możesz chować się pod łóżkami, kuszetkami i biurkami. Jeśli nic nie widziało, jak wchodzisz, nic nie zajrzy.',
      'W kryjówce przytrzymaj Shift, żeby wstrzymać oddech. Gdy zabraknie ci tchu, zaczniesz łapać powietrze.',
      'Przytrzymaj V, żeby obejrzeć się przez ramię w biegu.',
      'Czytaj wszystko. Ludzie, którzy to napisali, mówią ci, jak się wydostać.',
      'Wren zostawiła osiem rysunków, prawie na każdej półce po jednym. Niektóre są dobrze schowane.',
      'Otto odzywa się na kanale dziewiątym, kiedy ma coś do powiedzenia. Zwykle ma rację.',
      'M otwiera mapę miejsc, w których byłaś.',
    ],
    photoLabels: {},
    credits: [
      ['LEVEL 256', 'opowieść grozy w pierwszej osobie, w dziewięciu półkach'],
      ['Dla', 'wszystkich, którym powiedziano, że to niczyja wina'],
      ['Miejsca', 'Halvard, jezioro Ostra i Podspód są zmyślone; tak samo wszyscy, którzy się w nich znajdują'],
      ['Dźwięk', 'syntezowany na żywo: ani jednego nagrania'],
      ['Obrazy i modele', 'proceduralne: ani jednego pliku graficznego'],
      ['Składnica 9', 'jest otwarta co noc. Proszę pytać w okienku.'],
    ],
    // Napisy nabazgrane na ścianach Podspodu
    scrawl: {
      yellow: ['KTO PO TO WRÓCIŁ?', 'ZAWSZE JEST 02:56', 'ODBIÓR 256', 'NIE DA SIĘ POMINĄĆ PÓŁKI', 'SZUKAJ KŁAMSTWA', 'NIKT NIE ZAPYTAŁ', 'W AKTACH: ZAPOMNIANE'],
      dark: ['NIE GAŚ ŚWIATŁA', 'ZJADA TO, CZEGO PRZESTAŁAŚ SZUKAĆ', 'ADA?'],
      concrete: ['ZACHOWAĆ DLA: ADY LIND', '256', 'NIEODEBRANE'],
    },
  });
})(typeof window !== 'undefined' ? window : globalThis);
