/* Interfejs po polsku. */
(function (root) {
  'use strict';
  root.PB.I18N.register('pl', 'ui', {
    'game.title': 'LEVEL 256',
    'game.subtitle': 'SALON GIER STARLIGHT',
    'game.aria': 'Widok gry',
    'noscript': 'Ta gra wymaga JavaScriptu.',

    'boot.tip': 'WSKAZÓWKA',
    'boot.init': 'Uruchamianie…',
    'boot.fonts': 'Wczytywanie czcionek…',
    'boot.sounds': 'Nagrywanie dźwięków…',
    'boot.voices': 'Nagrywanie głosów…',
    'boot.prep': 'Przygotowywanie poziomu…',
    'boot.noThree': 'Nie udało się wczytać silnika 3D (three.js). Sprawdź połączenie z internetem i odśwież stronę.',
    'boot.error': 'Błąd uruchamiania: {msg}',
    'boot.noWebgl': 'Karta graficzna nie uruchomiła grafiki 3D (WebGL 2). Zaktualizuj sterownik karty graficznej i uruchom grę ponownie.',
    'load.textures': 'Tkanie tekstur… ({n}/{m})',
    'load.walls': 'Stawianie ścian…',
    'load.bake': 'Wypalanie światła…',
    'load.fixtures': 'Wieszanie świetlówek…',
    'load.props': 'Ustawianie mebli…',
    'load.decals': 'Plamy i rysy…',
    'load.shaders': 'Kompilowanie shaderów…',
    'load.ready': 'Gotowe',
    'load.error': 'Błąd wczytywania: {msg}',

    'first.title': 'Zanim zaczniesz',
    'first.lang': 'Język',
    'first.bright': 'Ustaw jasność tak, żeby lewy symbol był ledwo widoczny, a prawy wyraźnie widoczny.',
    'first.phones': 'Najlepiej w słuchawkach, w ciemnym pokoju.',
    'first.go': 'Dalej',

    'menu.continue': 'Kontynuuj',
    'menu.new': 'Nowa gra',
    'menu.levels': 'Rozdziały',
    'menu.settings': 'Ustawienia',
    'menu.archive': 'Archiwum',
    'menu.help': 'Jak grać',
    'menu.quit': 'Wyjdź z gry',
    'menu.credit': 'Harlow · 30 listopada 1994 · 2:11',
    'menu.foot': 'Graj w słuchawkach, po ciemku.',
    'menu.footDone': 'Zakończenia: {list} · śmierci {deaths}',

    'confirm.title': 'Nowa gra?',
    'confirm.body': 'Zapisany postęp zostanie nadpisany. Znalezione dokumenty zostaną w archiwum.',
    'confirm.yes': 'Tak, od nowa',
    'confirm.no': 'Anuluj',

    'diff.title': 'Poziom trudności',
    'diff.easy': 'Łatwy',
    'diff.easyDesc': 'Dla historii. Stwory są wolniejsze i mniej czujne. Raz na rozdział udaje się wyrwać z uchwytu.',
    'diff.normal': 'Normalny',
    'diff.normalDesc': 'Tak, jak to zaprojektowano. Jedno złapanie oznacza powrót do ostatniego zapisu.',
    'diff.nightmare': 'Koszmar',
    'diff.nightmareDesc': 'Szybsze stwory o czulszym słuchu. Baterie szybko się wyczerpują. Strach przychodzi wcześniej.',
    'diff.time': 'Szacowany czas gry: 4–6 godzin przy czytaniu każdego dokumentu i uwolnieniu wszystkich czterech Zjaw.',

    'levels.title': 'Rozdziały',
    'levels.locked': 'Zablokowany',

    'common.back': 'Wróć',
    'common.on': 'Wł.',
    'common.off': 'Wył.',

    'settings.title': 'Ustawienia',
    'settings.reset': 'Domyślne',
    'settings.reloadNote': 'Ustawienia oznaczone * zadziałają przy następnym wczytaniu rozdziału.',
    'tab.screen': 'Ekran',
    'set.displayMode': 'Tryb wyświetlania',
    'set.displayMode.help': 'Pełny ekran ukrywa przeglądarkę. Esc lub F11 go wyłącza; Alt+Enter przełącza w trakcie gry.',
    'opt.windowed': 'Okno',
    'opt.fullscreen': 'Pełny ekran',
    'set.resolution': 'Rozdzielczość',
    'set.resolution.help': 'Rozmiar renderowanego obrazu. Natywna to rozdzielczość ekranu; każdy inny rozmiar zostanie dopasowany do okna według trybu skalowania poniżej.',
    'opt.native': 'Natywna (ekran)',
    'set.scaleMode': 'Tryb skalowania',
    'set.scaleMode.help': 'Jak pokazać rozdzielczość o innych proporcjach niż okno.',
    'opt.fit': 'Dopasuj (proporcje, czarne pasy)',
    'opt.stretch': 'Rozciągnij',
    'opt.fill': 'Wypełnij (przytnij krawędzie)',
    'set.upscale': 'Filtr skalowania',
    'set.upscale.help': 'Gładki miesza piksele przy powiększaniu; Piksel zostawia je ostre i kwadratowe (retro przy niskiej rozdzielczości).',
    'opt.smooth': 'Gładki',
    'opt.pixel': 'Piksel',
    'set.sharpen': 'Wyostrzanie',
    'set.sharpen.help': 'Wyostrzanie zależne od kontrastu w gotowym obrazie. Pomaga poniżej rozdzielczości natywnej i przy wygładzaniu krawędzi.',
    'set.fpsLimit': 'Limit klatek',
    'set.fpsLimit.help': 'Ogranicza liczbę klatek na sekundę. Niższy limit utrzymuje kartę graficzną w chłodzie, a tempo klatek równe.',
    'opt.unlimited': 'Bez limitu',
    'set.vsync': 'Synchronizacja pionowa',
    'set.vsync.help': 'Wł.: klatki idą za odświeżaniem monitora, bez rozrywania obrazu. Wył.: gra rysuje tak szybko, jak może, do limitu klatek. W przeglądarce sama przeglądarka zawsze czeka na monitor, więc Wył. usuwa tylko własne czekanie gry; wersja na komputer wyłącza synchronizację całkowicie (po ponownym uruchomieniu).',
    'tab.graphics': 'Grafika',
    'tab.display': 'Obraz',
    'tab.audio': 'Dźwięk',
    'tab.controls': 'Sterowanie',
    'tab.gameplay': 'Rozgrywka',
    'preset.low': 'Niskie',
    'preset.medium': 'Średnie',
    'preset.high': 'Wysokie',
    'preset.ultra': 'Ultra',
    'preset.extreme': 'Ekstremalne',
    'preset.custom': 'Własne',
    'opt.off': 'Wył.',
    'opt.low': 'Niskie',
    'opt.medium': 'Średnie',
    'opt.high': 'Wysokie',
    'opt.ultra': 'Ultra',
    'opt.extreme': 'Ekstremalne',
    'opt.shadow1': 'Niskie (1024)',
    'opt.shadow2': 'Wysokie (2048)',
    'opt.shadow3': 'Ultra (4096)',
    'opt.small': 'Małe',
    'opt.large': 'Duże',
    'opt.full': 'Pełne',
    'opt.reduced': 'Ograniczone',

    'set.preset': 'Profil jakości',
    'set.preset.help': 'Zmienia naraz wszystkie ustawienia grafiki poniżej. Ekstremalne to profil dla mocnych kart graficznych; Ultra+ idzie dalej (cienie 8192, najgęstsze wypalanie światła, najdokładniejsze modele, głębia ostrości) i jest dla najmocniejszych komputerów.',
    'set.renderScale': 'Skala rozdzielczości',
    'set.renderScale.help': 'Powyżej 100% obraz renderuje się w wyższej rozdzielczości i jest zmniejszany: ostrzejszy obraz, dużo większe obciążenie karty graficznej.',
    'set.textureRes': 'Rozdzielczość tekstur',
    'set.shadows': 'Cienie',
    'set.antialias': 'Wygładzanie krawędzi',
    'set.lightmapRes': 'Jakość wypalonego oświetlenia',
    'set.lightmapRes.help': 'Szczegółowość miękkiego, wstępnie obliczonego światła i jego cieni.',
    'set.dynLights': 'Światła dynamiczne',
    'set.bloom': 'Poświata (bloom)',
    'set.bloomStrength': 'Siła poświaty',
    'set.volumetric': 'Światło wolumetryczne i kurz',
    'set.ao': 'Okluzja otoczenia (SSAO)',
    'set.ao.help': 'Miękkie cienie kontaktowe w kątach, pod meblami i między płytkami.',
    'set.ssr': 'Odbicia w przestrzeni ekranu',
    'set.ssr.help': 'Prawdziwe odbicia na mokrej podłodze, kafelkach, szkle i polerowanym metalu.',
    'set.volumetric.help': 'Smugi światła, snop latarki i unoszący się kurz liczone metodą ray marchingu. Bardzo wymagające na Ekstremalnych.',
    'set.motionBlur': 'Rozmycie ruchu',
    'set.lensDirt': 'Brud na obiektywie',
    'set.lensDirt.help': 'Smugi na obiektywie kamery, które łapią mocne światło.',
    'set.particles': 'Gęstość cząsteczek',
    'set.viewDist': 'Zasięg widzenia',
    'set.anisotropy': 'Filtrowanie anizotropowe',
    'set.brightness': 'Jasność',
    'set.brightness.help': 'Ustaw tak, by najciemniejsze kąty były ledwo widoczne.',
    'set.contrast': 'Kontrast',
    'set.saturation': 'Nasycenie kolorów',
    'set.fov': 'Pole widzenia',
    'set.headBob': 'Kołysanie głowy',
    'set.shake': 'Drgania kamery',
    'set.grain': 'Ziarno filmu',
    'set.chromatic': 'Aberracja chromatyczna',
    'set.vignette': 'Winieta',
    'set.vhs': 'Wygląd kamery (VHS)',
    'set.vhs.help': 'Pokazuje grę jak przez wizjer kamery wideo z 1994 roku.',
    'set.reduceFlicker': 'Mniej migotania',
    'set.reduceFlicker.help': 'Łagodzi migające światła i błyski na ekranie dla osób wrażliwych na światło.',
    'set.crosshair': 'Celownik',
    'set.subtitles': 'Napisy',
    'set.captions': 'Napisy dźwiękowe',
    'set.captions.help': 'Pokazuje ważne dźwięki jako tekst, na przykład [odległe przeżuwanie].',
    'set.subtitleSize': 'Rozmiar napisów',
    'set.master': 'Głośność ogólna',
    'set.music': 'Muzyka',
    'set.sfx': 'Efekty',
    'set.ambience': 'Otoczenie (buczenie, kapanie, deszcz)',
    'set.entities': 'Dźwięki stworów',
    'set.voice': 'Głosy i radio',
    'set.hrtf': 'Dźwięk 3D (HRTF, zalecane słuchawki)',
    'set.mouseSens': 'Czułość myszy',
    'set.invertY': 'Odwróć oś pionową',
    'set.touchSens': 'Czułość dotyku',
    'set.toggleCrouch': 'Kucanie: przełączanie zamiast przytrzymania',
    'set.toggleSprint': 'Bieg: przełączanie zamiast przytrzymania',
    'set.lang': 'Język',
    'set.difficulty': 'Poziom trudności',
    'set.difficulty.help': 'Wpływa na szybkość i słuch stworów oraz na baterię latarki.',
    'set.jumpscare': 'Jump scare’y',
    'set.hints': 'Podpowiedzi',

    'archive.title': 'Archiwum',
    'archive.count': '{n} / {m} dokumentów',
    'archive.notFound': 'Jeszcze nie znaleziono',
    'kind.note': 'Liścik',
    'kind.letter': 'List',
    'kind.diary': 'Strona dziennika',
    'kind.tape': 'Nagranie na kasecie',
    'kind.photo': 'Zdjęcie',
    'kind.screen': 'Ekran komputera',
    'kind.phone': 'Wiadomość na sekretarce',
    'kind.printout': 'Wydruk',
    'kind.wall': 'Napis na ścianie',
    'kind.notice': 'Ogłoszenie',
    'kind.memory': 'Wspomnienie',
    'kind.drawing': 'Rysunek',
    'kind.card': 'Kartka',
    'kind.report': 'Raport',
    'kind.flyer': 'Ulotka',
    'kind.doc': 'Dokument',

    'help.title': 'Jak grać',
    'help.kbm': 'Klawiatura i mysz',
    'help.walk': 'Chodzenie',
    'help.mouse': 'Mysz',
    'help.look': 'Rozglądanie się (kliknij, by złapać kursor)',
    'help.sprint': 'Bieg (głośny, zużywa oddech)',
    'help.crouch': 'Kucanie (prawie bezgłośne)',
    'help.interact': 'Użyj, czytaj, weź, schowaj się',
    'help.flash': 'Latarka',
    'help.drink': 'Wypij Star Popa',
    'help.throw': 'Rzuć świetlik',
    'help.lean': 'Wychyl się w lewo / w prawo (zajrzyj za róg)',
    'help.map': 'Mapa',
    'help.bag': 'Przedmioty / dziennik',
    'bag.items': 'PRZEDMIOTY',
    'bag.journal': 'DZIENNIK',
    'bag.close': 'Zamknij (I / J)',
    'bag.empty': 'Kieszenie są puste.',
    'bag.inspectHint': 'Przeciągnij, żeby obrócić.',
    'bag.now': 'TERAZ',
    'bag.story': 'DOTYCHCZASOWA HISTORIA',
    'bag.docs': 'ZNALEZIONE TUTAJ',
    'bag.noDocs': 'Tu jeszcze nic nie znaleziono. Przyjrzyj się uważniej.',
    'bag.people': 'LUDZIE',
    'bag.freed': 'w spokoju',
    'bag.hunting': 'wciąż poluje',
    'bag.stats': 'Dokumenty {a} / {b}   ·   Rysunki Lily {c} / {d}',
    'bag.n.flashlight': 'Latarka',
    'bag.d.flashlight': 'Ciężka stalowa latarka z furgonetki salonu. Bateria: {n}%. Zanim zgaśnie, najpierw przygasa.',
    'bag.n.battery': 'Zapasowe baterie',
    'bag.d.battery': 'Duże baterie do latarki. R je wymienia; rozładowana latarka dostaje je sama.',
    'bag.n.almond': 'Star Pop',
    'bag.d.almond': 'Puszka wiśniowej oranżady z salonu, nie wiadomo jakim cudem wciąż zimna. Cukier i bąbelki uspokajają ręce. Pije się ją klawiszem Q.',
    'bag.n.glow': 'Świetliki',
    'bag.d.glow': 'Złam jeden i rzuć go klawiszem G. Pełzacze i Szczerzacze nie przejdą przez zielone światło.',
    'bag.d.officeKey': 'Klucz do biura Walta, z kasy fiskalnej. Mosiądz jest wytarty do gładkości.',
    'bag.d.token': 'Żeton Starlight z wybitą gwiazdą. Tylko do automatu nr 7.',
    'bag.n.fuse': 'Bezpieczniki',
    'bag.d.fuse': 'Ciężkie ceramiczne bezpieczniki do starej rozdzielni młyna.',
    'bag.n.fuel': 'Kanistry z ropą',
    'bag.d.fuel': 'Ropa do generatorów. Głośno chlupocze. Idź powoli.',
    'bag.d.keycard': 'Karta dostępu z paskiem magnetycznym. Czyjeś zdjęcie zostało zdrapane.',
    'bag.d.key': 'Klucz z papierową zawieszką. Otwiera coś tutaj.',
    'help.pause': 'Pauza',
    'help.touch': 'Dotyk',
    'help.touchText': 'Gałka ruchu w lewym dolnym rogu, przeciągaj po prawej stronie ekranu, żeby się rozglądać. Przyciski po prawej: użyj, latarka, bieg, kucanie, mapa.',
    'help.survive': 'Jak przeżyć',
    'help.tip1': '<b>Pożeracz</b> jest szybszy od ciebie w prostym korytarzu i wolny na zakrętach. Bierz zakręty.',
    'help.tip2': 'Kiedy świetlówki zaczynają migać, <b>jest blisko</b>.',
    'help.tip3': 'Weź <b>lampion</b>, a przez kilka sekund wszystko będzie przed tobą uciekać.',
    'help.tip4': '<b>Czerwony</b> nigdy się nie zatrzymuje. <b>Fioletowy</b> odcina drogę. <b>Turkusowy</b> słyszy wodę i przeskakuje z miejsca na miejsce. <b>Bursztynowy</b> zamiera, dopóki na niego patrzysz.',
    'help.tip5': 'Możesz się <b>schować</b> pod biurkami i w szafkach. Jeśli nikt nie widzi, jak wchodzisz, nikt cię nie znajdzie.',
    'help.tip6': '<b>Magnetofony</b> zapisują grę. Autozapis następuje przy celach, kiedy jest bezpiecznie.',
    'help.tip7': 'Zanieś każdej Zjawie jej pamiątkę <b>do jej kapliczki</b>. Od tego zależy zakończenie.',

    'pause.title': 'Pauza',
    'pause.resume': 'Wznów',
    'pause.map': 'Mapa',
    'pause.journal': 'Dziennik',
    'pause.archive': 'Archiwum',
    'pause.settings': 'Ustawienia',
    'pause.help': 'Jak grać',
    'pause.load': 'Wczytaj ostatni zapis',
    'pause.menu': 'Menu główne',

    'note.close': 'Zamknij',
    'note.closeKey': 'Zamknij (E)',

    'map.close': 'Zamknij',
    'map.closeKey': 'Zamknij (M)',
    'map.objective': 'Cel',
    'map.tape': 'Kaseta',
    'map.doc': 'Dokument',
    'map.shrine': 'Kapliczka',
    'map.supply': 'Zapasy',
    'map.locked': 'Zamknięte drzwi',

    'kp.label': 'OCHRONA',
    'kp.clear': 'USUŃ',
    'kp.enter': 'OK',
    'kp.open': 'OTWARTE',
    'kp.error': 'BŁĄD',
    'kp.close': 'Anuluj (Esc)',

    'cab.help': 'Strzałki lub WASD · Enter, by zacząć · P, by zatrzymać ·',
    'cab.exit': 'Odejdź od automatu (Esc)',

    'choice.back': 'Cofnij się',
    'card.skip': 'Kliknij lub naciśnij E, by kontynuować',

    'death.retry': 'Kontynuuj od ostatniego zapisu',
    'death.menu': 'Menu główne',

    'end.menu': 'Menu główne',
    'end.skip': 'Pomiń',
    'end.time': 'czas gry',
    'end.deaths': 'śmierci',
    'end.docs': 'dokumenty',
    'end.freed': 'uwolnione Zjawy',
    'end.drawings': 'znalezione rysunki',

    'hud.objective': 'CEL',
    'hud.rec': 'REC',
    'hud.stamina': 'ODDECH',
    'hud.battery': 'ŚWIATŁO',
    'hud.power': 'PRĄD {t}',
    'hud.fps': '{n} FPS',

    'touch.pause': 'Pauza',
    'touch.bag': 'TORBA',
    'touch.map': 'MAPA',
    'touch.drink': 'PIJ',
    'touch.throw': 'RZUĆ',
    'touch.crouch': 'KUCNIJ',
    'touch.sprint': 'BIEGNIJ',
    'touch.flash': 'LATARKA',
    'touch.tap': 'DOTKNIJ',

    'inv.battery': 'BATERIA ×{n}',
    'inv.almond': 'STAR POP ×{n}',
    'inv.glow': 'ŚWIETLIK ×{n}',
    'inv.officeKey': 'KLUCZ DO BIURA',
    'inv.token': 'ZŁOTY ŻETON',
    'inv.fuses': 'BEZPIECZNIK ×{n}',
    'inv.fuel': 'ROPA ×{n}',
    'inv.keycard': 'KARTA DOSTĘPU',
    'inv.pellets': 'LAMPION ×{n}',

    'n.added': 'Dodano do archiwum: {title}',
    'n.saved': 'Gra zapisana',
    'n.batteryIn': 'Nowa bateria w latarce',
    'n.batterySpare': 'Zapasowa bateria',
    'n.noSpare': 'Brak zapasowych baterii.',
    'n.batteryFull': 'Bateria jest jeszcze pełna.',
    'hint.reload': 'R: wymień baterie w latarce',
    'touch.reload': 'BAT',
    'help.reload': 'Wymiana baterii w latarce',
    'help.lookBack': 'Spojrzenie za siebie w biegu (przytrzymaj)',
    'n.batterySwap': 'Zapasowa bateria założona',
    'n.almond': 'Star Pop (Q, by wypić)',
    'n.glow': 'Świetlik (G, by rzucić)',
    'n.found': 'Znaleziono: {name}',
    'n.drank': 'Pijesz Star Popa. Oddech się uspokaja.',
    'n.noAlmond': 'Nie masz Star Popa.',
    'n.noGlow': 'Nie masz świetlików.',
    'n.slow': 'Gra działa wolno. W menu Pauza › Ustawienia › Grafika możesz obniżyć jakość.',
    'n.lockFail': 'Nie udało się złapać kursora. Przytrzymaj lewy przycisk i przeciągaj, żeby się rozglądać.',
    'n.flashDead': 'Latarka zgasła.',
    'n.holdBreath': 'Coś jest blisko. Przytrzymaj Shift, żeby wstrzymać oddech.',
    'n.heardBreath': 'Usłyszało twój oddech.',
    'n.noFlash': 'Nie masz latarki.',
    'n.noBattery': 'Bateria padła. Znajdź zapasową.',
    'n.grace': 'Było blisko! (Łatwy: raz na rozdział)',
    'n.freed': '{name} odnajduje spokój',
    'n.ghostBack': '{name} się wycofuje',
    'n.cabinetHi': 'Twoje inicjały trafiły na listę rekordów: SAM',
    'n.perfect': 'Wszystkie gwiazdy zjedzone. Idealna gra.',
    'n.fruit': 'Przed domem pojawiła się nagroda',
    'n.diesel': 'Kanister z ropą',
    'n.drawing': 'Rysunek Lily ({n}/8)',

    'pr.read': 'Przeczytaj: {title}',
    'pr.readWall': 'Przeczytaj napis',
    'pr.screen': 'Spójrz na ekran',
    'pr.tape': 'Odtwórz kasetę (zapisuje grę)',
    'pr.battery': 'Weź baterię',
    'pr.almond': 'Weź Star Popa',
    'pr.glow': 'Weź świetlik',
    'pr.flashlight': 'Weź latarkę',
    'pr.token': 'Weź żeton',
    'pr.fuse': 'Weź bezpiecznik',
    'pr.fuel': 'Weź kanister z ropą',
    'pr.keycard': 'Weź kartę dostępu',
    'pr.take': 'Weź: {name}',
    'pr.pellet': 'Weź lampion',
    'pr.phoneRing': 'Odbierz telefon',
    'pr.phone': 'Podnieś słuchawkę',
    'pr.cabinetFree': 'Zagraj na automacie (FREE PLAY)',
    'pr.doorLocked': '{name} (zamknięte)',
    'pr.doorOpen': 'Otwórz drzwi',
    'pr.doorClose': 'Zamknij drzwi',
    'pr.drawerOpen': 'Otwórz szufladę',
    'pr.drawerClose': 'Zamknij szufladę',
    'pr.safeOpen': 'Otwórz sejf',
    'pr.safeClose': 'Zamknij sejf',
    'pr.safeLocked': 'Sejf (wpisz szyfr)',
    'pr.hide': 'Schowaj się pod spodem',
    'pr.hideLocker': 'Schowaj się w szafce',
    'pr.unhide': 'Wyjdź',
    'pr.shrineLook': 'Przyjrzyj się kapliczce',
    'pr.shrinePlace': 'Zostaw pamiątkę w kapliczce',
    'pr.drawing': 'Weź rysunek Lily',

    'door.default': 'Drzwi',
    'door.office': 'Drzwi do biura',
    'door.storage': 'Magazynek',
    'door.wc': 'Toaleta',
    'door.front': 'Drzwi wejściowe',
    'door.elevator': 'Winda towarowa',
    'door.security': 'Pokój ochrony',
    'door.stair': 'Schody przeciwpożarowe',
    'door.house': 'Dom Zjaw',
    'door.service': 'Winda służbowa',
    'lock.service': 'Winda jest martwa. Wszystkie trzy generatory muszą pracować.',
    'door.exit': 'WYJŚCIE',
    'door.room': 'Pokój {n}',
    'door.jammed': 'Drzwi',
    'lock.jammed': 'Zaklinowane. Klamka się obraca, ale coś trzyma drzwi z drugiej strony.',
    'lock.exit': 'WYJŚCIE jest zamknięte. Jeszcze nie.',
    'door.pressure': 'Drzwi ciśnieniowe',
    'lock.pressure': 'Drzwi ciśnieniowe ani drgną. Za nimi syczy para.',
    'door.janitor': 'Woźny',
    'lock.janitor': 'Kłódka na szyfr. Trzy cyfry.',
    'door.fireExit': 'Wyjście ewakuacyjne',
    'lock.fireExit': 'Gruby łańcuch i kłódka. Klucze ma woźny.',
    'lock.fireExitMotel': 'Pręt nie ustępuje. Ktoś zablokował go od zewnątrz.',
    'door.gym': 'Sala gimnastyczna',
    'door.mallExit': 'Drzwi centrum handlowego',
    'lock.mallExit': 'Zamknięte na noc. W oddali brzęczy fotobudka.',
    'door.room12': 'Pokój 12',
    'lock.room12': 'Zamknięte. Tabliczka z numerem jest wypolerowana, jakby ktoś dotykał jej codziennie.',
    'door.room207': 'Pokój 207',
    'lock.room207': 'Zamknięte. Papierowa kartka: PROSZĘ O CISZĘ. Narysowane na niej kredką słońce.',
    'door.elevatorH': 'Winda',
    'lock.elevatorH': 'Winda czeka z zamkniętymi drzwiami. Na coś czeka.',
    'door.samHouse': 'Twój dom',
    'door.tobyHouse': 'Dom Toby’ego',
    'door.neighbor': 'Drzwi wejściowe',
    'lock.neighbor': 'Zamknięte. Firanki poruszają się, kiedy odwracasz wzrok.',
    'door.alley': 'Drzwi na zaułek',
    'lock.alley': 'Zamknięte. Nie przed postojem na rogu.',
    'door.kernel': 'Stalowe drzwi',
    'lock.kernel': 'Stal i zamek. Mosiężna tabliczka: KERNEL — TYLKO W.',
    'lock.default': 'Zamknięte.',
    'lock.office': 'Zamknięte. Mosiężna tabliczka na drzwiach: „W. — KIEROWNIK”.',
    'lock.front': 'Zamknięte na kłódkę od zewnątrz. Klucz mają ludzie od przeprowadzki.',
    'lock.elevator': 'Winda nie ma prądu. Przycisk przywołania jest martwy.',
    'lock.security': 'Klawiatura chce czterocyfrowego kodu.',
    'lock.stair': 'Lampka czytnika kart świeci na czerwono. Potrzebna karta dostępu.',
    'lock.house': 'Fioletowa kurtyna światła. Trzymają ją zamkniętą cztery lampiony.',

    'cap.front': 'z przodu',
    'cap.back': 'z tyłu',
    'cap.left': 'z lewej',
    'cap.right': 'z prawej',
    'cap.phone': '[dzwoni telefon]',
    'cap.drag': '[szurające kroki w pobliżu]',
    'cap.moan': '[jęk]',
    'cap.farSteps': '[kroki gdzieś indziej w budynku]',
    'cap.thud': '[coś upada, daleko]',
    'cap.buzz': '[trzeszczy świetlówka]',
    'cap.whisper': '[szept]',
    'cap.giggle': '[chichot w ciemności]',
    'cap.radio': '[szum radia]',
    'cap.thunder': '[grzmot]',
    'cap.hiss': '[mokry syk, oddala się]',
    'cap.skitter': '[chrobot na cegłach]',
    'cap.whistle': '[przenikliwy gwizdek]',
    'cap.plastic': '[trzeszczy plastik]',
    'cap.bite': '[zęby kłapią w pobliżu]',
    'cap.biteFar': '[odległe przeżuwanie]',
    'cap.callName': '[ktoś woła cię po imieniu głosem Toby’ego]',
    'cap.heavySteps': '[ciężkie kroki, pisk gumy]',
    'cap.pipe': '[gdzieś w tunelach dzwoni rura]',
    'cap.locker': '[w głębi korytarza trzaska szafka]',
    'cap.knock': '[trzy stuknięcia, gdzieś w głębi korytarza]',
    'cap.beep': '[monitor pika w pustym pokoju]',
    'cap.arc': '[za stalowymi drzwiami trzaska prąd]',
    'cap.pop': '[pęka świetlówka]',
    'cap.slam': '[za tobą trzaskają drzwi]',
    'cap.run': '[ktoś biegnie, poza zasięgiem wzroku]',
    'cap.callJune': '[kobiecy głos w głębi korytarza: „Eddie? Eddie, to ty?”]',
    'cap.car': '[samochód przejeżdża z sykiem po mokrej ulicy]',
    'cap.door': '[gdzieś drzwi]',
    'cap.drip': '[kapanie]',
    'cap.hum': '[buczenie świetlówek]',
    'tab.access': 'Dostępność',
    'tab.perf': 'Wydajność',
    'set.perfOverlay': 'Nakładka wydajności',
    'set.perfOverlay.help': 'Pokazuje, jak działa gra. Tylko FPS; Podstawowa dodaje czas klatki, czas CPU i GPU na klatkę oraz ich obciążenie; Szczegółowa dodaje wykres czasu klatek, wywołania rysowania, trójkąty, pamięć, rozdzielczość renderowania i twoją kartę graficzną. Czas GPU wymaga przeglądarki udostępniającej zapytania o czas GPU (wersja na komputer robi to zawsze).',
    'set.perfCorner': 'Położenie nakładki',
    'set.perfCorner.help': 'W którym rogu ekranu jest nakładka wydajności.',
    'opt.perfFps': 'Tylko FPS',
    'opt.perfBasic': 'Podstawowa',
    'opt.perfDetailed': 'Szczegółowa',
    'opt.cornerTR': 'Prawy górny',
    'opt.cornerTL': 'Lewy górny',
    'opt.cornerBR': 'Prawy dolny',
    'opt.cornerBL': 'Lewy dolny',
    'preset.ultraplus': 'Ultra+',
    'opt.ultraplus': 'Ultra+',
    'opt.shadow4': 'Ultra+ (8192)',
    'set.modelDetail': 'Szczegółowość modeli',
    'set.modelDetail.help': 'Jak dokładnie zbudowane są stwory, dłonie i inne rzeźbione modele. Wyżej wygląda gładziej z bliska i wydłuża wczytywanie rozdziału. Ultra+ jest dla najszybszych procesorów.',
    'set.clutter': 'Obiekty detali',
    'set.clutter.help': 'Ile drobiazgów wypełnia pomieszczenia: obrazy, zdjęcia, kalendarze, pudła, papiery, butelki. Więcej sprawia, że każde wnętrze wygląda na zamieszkane; mniej oszczędza starsze komputery.',
    'set.dof': 'Głębia ostrości',
    'set.dof.help': 'Rozmywa to, co jest daleko od miejsca, na które patrzysz, jak obiektyw aparatu. Ostrość podąża za środkiem ekranu. Wyższe ustawienia biorą więcej próbek dla gładszego, czystszego rozmycia.',
    'set.textureRes.help': 'Ostrość powierzchni: ścian, podłóg, drewna, tkanin. Wyżej wymaga więcej pamięci wideo.',
    'set.shadows.help': 'Cienie rzucane przez latarkę i lampy na zewnątrz. Wyżej są ostrzejsze. Ultra+ używa mapy cieni 8192 i wymaga dużo pamięci wideo.',
    'set.antialias.help': 'Wygładza poszarpane krawędzie. MSAA jest najczystsze; FXAA jest tanie i lekko zmiękcza cały obraz; oba naraz dają najgładszy efekt.',
    'set.dynLights.help': 'Ile lamp w pobliżu może jednocześnie oświetlać poruszające się rzeczy i stwory.',
    'set.bloom.help': 'Miękka poświata wokół jasnych świateł i ekranów.',
    'set.bloomStrength.help': 'Jak silna jest ta poświata.',
    'set.motionBlur.help': 'Rozmywa obraz przy szybkich obrotach. Dłonie i to, co w nich trzymasz, zostają ostre.',
    'set.particles.help': 'Kurz w powietrzu, deszcz, iskry i krople.',
    'set.viewDist.help': 'Jak daleko rysowane są obiekty i jak daleko pozwala widzieć mgła.',
    'set.anisotropy.help': 'Utrzymuje ostrość podłóg i ścian widzianych pod ostrym kątem. Kosztuje bardzo mało.',
    'set.contrast.help': 'Różnica między ciemnymi a jasnymi częściami obrazu.',
    'set.saturation.help': 'Jak mocne są kolory. Mniej przypomina stare zdjęcie.',
    'set.fov.help': 'Jak szeroko widzisz. Szerzej pokazuje więcej, ale wszystko wydaje się dalej.',
    'set.headBob.help': 'Jak bardzo widok kołysze się przy krokach. Zmniejsz, jeśli robi ci się niedobrze.',
    'set.shake.help': 'Drgania kamery przy przestrachach, uderzeniach i biegu.',
    'set.grain.help': 'Ziarno filmu na obrazie.',
    'set.chromatic.help': 'Kolorowe obwódki na krawędziach obrazu, jak w tanim obiektywie.',
    'set.vignette.help': 'Przyciemnienie w stronę rogów ekranu.',
    'set.crosshair.help': 'Mała kropka na środku ekranu, która pomaga celować w rzeczy do podniesienia.',
    'set.subtitles.help': 'Pokazuje, co mówią ludzie: krótkofalówka, kasety, myśli.',
    'set.subtitleSize.help': 'Rozmiar napisów i napisów dźwiękowych.',
    'set.master.help': 'Ogólna głośność.',
    'set.music.help': 'Głośność muzyki.',
    'set.sfx.help': 'Kroki, drzwi, przedmioty i wszystko, co robisz.',
    'set.ambience.help': 'Pomieszczenia, deszcz, buczenie i odgłosy budynku.',
    'set.entities.help': 'Stwory: ich kroki, oddech i głosy.',
    'set.voice.help': 'Krótkofalówka, kasety i myśli.',
    'set.hrtf.help': 'Rozmieszcza dźwięki wokół ciebie w trzech wymiarach. Najlepiej w słuchawkach; na głośnikach wyłącz.',
    'set.mouseSens.help': 'Jak szybko widok obraca się myszą.',
    'set.invertY.help': 'Ruch myszy w górę kieruje wzrok w dół.',
    'set.touchSens.help': 'Jak szybko obraca się widok przy przeciąganiu po ekranie dotykowym.',
    'set.toggleCrouch.help': 'Jedno naciśnięcie – kucnięcie, drugie – wstanie, zamiast przytrzymywania klawisza.',
    'set.toggleSprint.help': 'Jedno naciśnięcie – bieg, drugie – marsz, zamiast przytrzymywania klawisza.',
    'set.lang.help': 'Język menu, napisów i wszystkich dokumentów w grze.',
    'set.jumpscare.help': 'Ograniczone zostawia każdy przestrach, ale łagodzi najgłośniejsze błyski i dźwięki.',
    'set.hints.help': 'Krótkie wskazówki, gdy dzieje się coś nowego.',
    'perf.frame': 'Klatka',
    'perf.low1': '1% najniższych',
    'perf.cpu': 'CPU',
    'perf.cpuUse': 'Obciążenie CPU',
    'perf.gpu': 'GPU',
    'perf.gpuUse': 'Obciążenie GPU',
    'perf.na': 'b.d.',
    'perf.draws': 'Wywołania rysowania',
    'perf.tris': 'Trójkąty',
    'perf.textures': 'Tekstury',
    'perf.programs': 'Shadery',
    'perf.res': 'Render',
    'perf.heap': 'Pamięć JS',
    'perf.sysCpu': 'CPU systemu',
    'perf.appCpu': 'CPU gry',
    'perf.procMem': 'Pamięć gry',
    'perf.card': 'Karta graficzna',
    'settings.revert': 'Cofnij',
    'settings.keys': '↑↓ wybór · ←→ zmiana · Q/E zakładki · Backspace cofnij · Esc wróć',
    'settings.impact': 'Koszt wydajności',
    'impact.0': 'Brak',
    'impact.1': 'Niski',
    'impact.2': 'Średni',
    'impact.3': 'Wysoki',
    'impact.4': 'Bardzo wysoki',
    'impact.5': 'Ekstremalny',
    'settings.gpuLoad': 'Szacowane obciążenie GPU',
    'settings.vram': 'Szacowana pamięć wideo',
    'settings.reloadBadge': 'Zadziała przy następnym wczytaniu rozdziału',
    'settings.restartBadge': 'Zadziała po ponownym uruchomieniu gry',
    'settings.restartNow': 'Uruchom ponownie teraz',
  });
})(typeof window !== 'undefined' ? window : globalThis);
