/* Polski interfejs dla historii Ady Lind: zastępuje to, co należało do starej historii, i dodaje to,
   czego potrzebuje dziewięć półek (drzwi, schody, rodzaje dokumentów, napisy). Wczytywany po ui.js. */
(function (root) {
  'use strict';
  root.PB.I18N.register('pl', 'ui', {
    'game.subtitle': 'RZECZY ZNALEZIONE',
    'menu.credit': 'Halvard · 13 stycznia 1998 · 02:56',
    'diff.time': 'Szacowany czas gry: 5–7 godzin dla kogoś, kto czyta każdy dokument i znajduje wszystkie osiem rysunków.',
    'set.vhs.help': 'Pokazuje grę jak przez starą domową kamerę wideo.',
    'help.drink': 'Zjedz cukierek jęczmienny',
    'bag.stats': 'Dokumenty {a} / {b}   ·   Rysunki Wren {c} / {d}',
    'bag.d.flashlight': 'Ciężka, gumowana latarka spod okienka Składnicy 9. Bateria: {n}%. Zanim zgaśnie, przygasa.',
    'bag.n.almond': 'Cukierek jęczmienny',
    'bag.d.almond': 'Skręcony cukierek jęczmienny z puszki pod okienkiem, odłożony na złe noce. Cukier uspokaja ręce. Zjedz klawiszem Q.',
    'bag.d.officeKey': 'Mały mosiężny klucz, wytarty do gładkości.',
    'bag.d.token': 'Mosiężny żeton.',
    'help.padText': 'Lewa gałka: chodzenie. Prawa gałka: rozglądanie. A: interakcja. B: kucnięcie. X: wymiana baterii. Y: latarka. LB / RB: wychylenie. RT lub wciśnięcie lewej gałki: bieg. LT: świetlik. Wciśnięcie prawej gałki: spojrzenie za siebie. Krzyżak: ↑ dziennik, ↓ cukierek, → przedmioty. Widok: mapa. Menu: pauza. W menu krzyżak przesuwa, A wybiera, B wraca.',
    'help.tip7': 'Na dnie każdego miejsca leży kłamstwo. <b>Odłóż zgubioną rzecz tam, gdzie jej miejsce</b>, a droga się otworzy.',
    'map.shrine': 'Odbiór',
    'end.freed': 'Odebrane półki',
    'end.claimed': 'Odebrane półki',
    'inv.almond': 'CUKIEREK ×{n}',
    'inv.token': 'ŻETON',
    'n.almond': 'Cukierek jęczmienny (Q, żeby zjeść)',
    'n.drank': 'Zjadasz cukierek jęczmienny. Oddech się uspokaja.',
    'n.noAlmond': 'Nie masz cukierków jęczmiennych.',
    'n.drawing': 'Rysunek Wren ({n}/8)',
    'pr.almond': 'Weź cukierek jęczmienny',
    'pr.drawing': 'Weź rysunek Wren',
    'door.house': 'Dom',
    'touch.drink': 'CUKIER',
    'inv.pellets': 'ZGUBIONE ŚWIATŁA ×{n}',
    'pr.pellet': 'Weź zgubione światło',
    'lock.house': 'Zasłona ze światła. Trzymają ją zamkniętą cztery zgubione światła.',
    'help.tip1': '<b>Słuchaj, zanim spojrzysz.</b> Każde stworzenie ma swoją zasadę: jedne słyszą, inne widzą tylko światło, jeszcze inne ruszają się tylko wtedy, gdy nikt nie patrzy. Dokumenty mówią, które jest które.',
    'help.tip2': 'Kiedy światła zaczynają się jąkać albo dźwięk ucieka ze świata, <b>coś jest blisko</b>.',
    'help.tip3': 'W Podspodzie weź <b>zgubione światło</b>, a Pożeracz przez kilka sekund trzyma się od ciebie z daleka.',
    'help.tip4': 'Każda półka ma <b>swoje stworzenia</b>: konduktora, który sprawdza bilety, konie, które biegną tylko wtedy, gdy gra katarynka, sosny, które ruszają się tylko wtedy, gdy ty się ruszasz. Poznaj zasadę każdego z nich.',
    'help.tip5': 'Możesz <b>chować się</b> pod łóżkami, kuszetkami i biurkami oraz w szafkach. Jeśli nic nie widziało, jak wchodzisz, nic nie zajrzy.',
    'help.tip6': 'Gra <b>zapisuje się sama</b> przy każdym celu, kiedy jesteś bezpieczna.',
    'set.subtitles.help': 'Pokazuje, co jest mówione: kanał dziewiąty, kasety, myśli.',
    'set.voice.help': 'Kanał dziewiąty, kasety i myśli.',
    // drzwi i przejścia na dziewięciu półkach
    'pr.unlock': 'Otwórz kluczem',
    'pr.stairs': 'Idź schodami',
    'pr.stairsDown': 'Zejdź po schodach',
    'pr.stairsUp': 'Wejdź po schodach',
    'pr.ladderDown': 'Zejdź po drabinie',
    'pr.ladderUp': 'Wejdź po drabinie',
    'door.otto': 'Gabinet Ottona Brandta',
    'lock.otto': 'Zamknięty od 1964 roku. Klucz musi być gdzieś w archiwum.',
    'door.concourse': 'Hala dworca',
    'lock.concourse': 'Zamknięte od drugiej strony.',
    'door.bridge': 'Mostek',
    'lock.bridge': 'Zamknięty. Klucz ma kapitan.',
    'door.cage': 'Klatka',
    'lock.cage': 'Krata klatki. Bez prądu nic się nie ruszy.',
    'door.fire': 'Drzwi przeciwpożarowe',
    'lock.fire': 'Zaklinowane. Z tej strony.',
    'door.signe': 'Stuegata 4',
    'lock.signe': 'Zamknięte. W środku pali się lampa.',
    'door.ghost': 'Pociąg widmo',
    // rodzaje dokumentów
    'kind.telegram': 'Telegram',
    'kind.transcript': 'Zapis',
    'kind.clipping': 'Gazeta',
    // napisy do dźwięków
    'hint.flash': 'F włącza i wyłącza latarkę.',
    'cap.chute': '[paczka spada zsypem]',
    'cap.tube': '[łomocze poczta pneumatyczna]',
    'cap.bellFar': '[dzwon, daleko we mgle]',
    'cap.doorShut': '[gdzieś zamykają się drzwi]',
    'cap.stepsFar': '[kroki, daleko]',
    'cap.organ': '[jarmarczna katarynka zaczyna grać sama]',
    'cap.organStop': '[katarynka zwalnia i milknie]',
    'cap.choir': '[śpiewa chór]',
    'cap.knocks': '[siedem uderzeń w stal]',
    'cap.ice': '[lód trzeszczy, daleko]',
    'cap.brake': '[piszczą hamulce]',
    'cap.laugh': '[śmiech]',
    'cap.toll': '[bije dzwon]',
    'cap.breath': '[oddech, tuż za tobą]',
    'cap.train': '[pociąg, pełnym pędem]',
    'cap.pa': '[gong; trzeszczy megafon]',
  });
})(typeof window !== 'undefined' ? window : globalThis);
