/* Deutscher Story-Kern: Figuren, gemeinsame Zeilen, Tode, Tipps, Enden, Abspann. Die Kapiteldateien ergänzen den Rest. */
(function (root) {
  'use strict';
  root.PB.I18N.register('de', 'story', {
    chars: {
      sam: { name: 'Sam', pos: 'Sams', role: 'Fährt nachts für Tri-County Movers, 20. War 1987 dreizehn und das fünfte Mitglied der Clique. Du.' },
      walt: { name: 'Walt', pos: 'Walts', role: 'Besitzer der Starlight-Spielhalle. Radartechniker bei der Air Force, dann Fernsehmechaniker. Vermisst seit März 1992.' },
      lily: { name: 'Lily', pos: 'Lilys', role: 'Walts Tochter. Starb im Oktober 1983 mit neun Jahren. Punktestand: 3.190.' },
      danny: { name: 'Danny', pos: 'Dannys', role: '1987 sechzehn. Laut, furchtlos, immer ganz oben auf der Punkteliste. Hatte Walts Ersatzschlüssel.' },
      rosie: { name: 'Rosie', pos: 'Rosies', role: '1987 fünfzehn. Die Planerin. Wollte ihre eigene Radiosendung.' },
      nell: { name: 'Nell', pos: 'Nells', role: '1987 fünfzehn. Still, zeichnete Comics, dicke Brille. Hat sich einen Nachmittag im Schwimmbad nie verziehen.' },
      toby: { name: 'Toby', pos: 'Tobys', role: '1987 dreizehn. Sams bester Freund. Hatte Angst im Dunkeln.' },
      eddie: { name: 'Eddie', pos: 'Eddies', role: 'Walts Gehilfe 1984–1988. Ging im Juni 1993 hinein, um sie zu holen. Hat eine Tochter, die er nie im Arm hatte.' },
      nora: { name: 'Nora', pos: 'Noras', role: 'Walts jüngere Schwester.' },
      frank: { name: 'Frank Dobbs', pos: 'Dobbs’', role: 'Kriminalbeamter der Polizei von Harlow, 1987.' },
      june: { name: 'June', pos: 'Junes', role: 'Eddies Frau. Nachtportier im Blue Moon Motor Inn.' },
      theo: { name: 'Theo', pos: 'Theos', role: 'Nells kleiner Bruder.' },
      maggie: { name: 'Maggie', pos: 'Maggies', role: 'Tobys Mutter.' },
      ruth: { name: 'Ruth', pos: 'Ruths', role: 'Walts Frau bis 1985.' },
      ray: { name: 'Ray', pos: 'Rays', role: 'Dannys Vater.' },
      carol: { name: 'Carol', pos: 'Carols', role: 'Rosies Mutter.' },
      ann: { name: 'Ann', pos: 'Anns', role: 'Sams Mutter.' },
    },
    speakers: { sam: 'SAM', eddie: 'EDDIE', walt: 'WALT', danny: 'DANNY', rosie: 'ROSIE', nell: 'NELL', toby: 'TOBY', lily: 'LILY', june: 'JUNE', radio: 'FUNK', voice: '???' },
    items: {},
    obj: {
      ghost: 'Bring {pos} Andenken zum Schrein (optional)',
    },
    recap: {
      prolog: 'Die Starlight-Spielhalle, die Nacht vor der Versteigerung. Automat Nr. 7 lief, ohne dass ein Stecker in der Wand war, und er kannte meinen Namen. PLAYER 1: SAM — CONTINUE?',
      lobby: 'Gelbe Räume ohne Ende: das Spiel, das auf einen Spieler wartet. Etwas Rundes, Blasses frisst dort im Dunkeln. Eddie lebt, am Funkgerät, drinnen seit 1993.',
      mill: 'Das Lagerhaus von Dannys Vater. Danny jagte mich und schrie: „Du hast losgelassen!“ Ich gab ihm die Uhr seines Vaters zurück, und er blieb stehen und erinnerte sich an seinen Namen.',
      pipes: 'Die Regenwassertunnel. Unsere Festung. Regel vier: Niemand geht allein nach Hause. Diese Regel stammt von mir.',
      pool: 'Das Schwimmbad, in dem Theo fast ertrunken wäre, während Nell eine Zeichnung fertig machte. Sie wartet seit Jahren auf Vergebung. Theo hat ihr schon im allerersten Brief vergeben.',
      office: 'Das Büro von Rosies Mutter, hundertsieben-komma-drei. Auf ihrem Band klopft um 0:40 Uhr jemand an die Hintertür der Spielhalle. Rosie: „Sieh mal an, wer da zurückgekrochen kommt.“',
      school: '16. April 1987. Der Pakt: alle fünf Hände am Joystick, niemand lässt los. Fünf Initialen darunter. Die letzte ist meine.',
      dark: 'Die Dunkelheit, drei Generatoren und ein Messingfeuerzeug. Auf Tobys letzter Seite steht, dass Sam zurückkam. Ich wusste nichts mehr davon, dass ich zurückgekommen war.',
      mall: 'Der schönste Samstag von 1986: fünf Kinder in einem Fotoautomaten, und eins davon bin ich, lachend. Die Schaufensterpuppen bewegten sich nur, wenn ich wegsah.',
      motel: 'Eddies Erinnerung, nicht meine. Zimmer 12 und sein Notizbuch: EINER REIN, EINER RAUS. Er braucht jemanden, der an seiner Stelle bleibt. Er wollte, dass ich das bin.',
      hospital: 'St. Agnes, Oktober 1983. Lily wünschte sich von ihrem Vater ein Spiel, das nie endet, damit nie jemand gehen muss. Walt hat es gebaut.',
      maple: 'Meine Straße. Die Stimme meiner Mutter auf dem Anrufbeantworter, um 2:50 Uhr morgens, sie fragt, wo ich bin. Ich bin um 21:40 Uhr nicht nach Hause gegangen.',
      workshop: 'Walts Keller und das Band von 3:17 Uhr. Fünf Hände am Joystick, und eine davon ließ los. Meine.',
      maze: 'Level 255, das Haus selbst. Die Spuke, die sich erinnern, gehen als farbige Lichter neben mir.',
      killscreen: 'Level 256. Die kaputte Seite. Ein Stecker, der fünf Hände braucht, und eine Tür, die einen hinauslässt.',
    },
    memento: {
      danny: { name: 'Dannys Uhr', line: 'Eine stählerne Armbanduhr mit gesprungenem Glas, stehen geblieben um 3:17. Auf der Rückseite eingraviert: „RAY KOWALSKI — 25 JAHRE — HARLOW MILL“.' },
      rosie: { name: 'Rosies Mixtape', line: 'Ein violetter Kassettenspieler mit einer Kassette. Auf dem Etikett steht SEITE B: FÜR DANACH. Seite B ist leer.' },
      nell: { name: 'Nells Brille', line: 'Eine schwere Brille, ein Glas gesprungen. Sie beschlägt in deiner Hand, als hätte gerade jemand darauf gehaucht.' },
      toby: { name: 'Tobys Feuerzeug', line: 'Ein altes Messingfeuerzeug. Eingraviert: „TOBY — DAMIT DU NIE IM DUNKELN SITZT. OPA“.' },
    },
    freed: {
      danny: ['DANNY: „3:17. Meine Uhr ist stehen geblieben. Ich nie.“', 'DANNY: „…Du bist zurückgekommen. Hat ja lange genug gedauert, Keller. Geh. Ich beschäftige den Großen.“'],
      rosie: ['ROSIE: „Seite B. Die wollten wir danach aufnehmen. Nachdem wir gewonnen haben.“', 'ROSIE: „Ich bin immer allen vorausgerannt. Jetzt gehe ich neben dir.“'],
      nell: ['NELL: „Meine Brille. Alles ist so… scharf.“', 'NELL: „Ich warte nicht mehr darauf, sicher zu sein. Ich komme mit.“'],
      toby: ['TOBY: „Opas Feuerzeug…“ (Die Flamme fängt. Zum ersten Mal siehst du sein Gesicht: ein Kind, dreizehn, Sommersprossen.)', 'TOBY: „…Sieh mich noch nicht an, Sam. Geh einfach. Ich bin direkt hinter dir.“'],
    },
    shrine: {
      quiet: 'Der Schrein ist still. Die Kerze brennt weiter.',
      missing: 'Ein kleiner Schrein. Ein gerahmtes Foto von {name} und ein leerer Platz, an den etwas gehört.',
    },
    mono: {
      watcherSeen: 'Weit weg steht etwas Großes, Schwarzes. Den Kopf zur Seite geneigt. Es zählt.',
      hide: 'Halt die Luft an.',
      hideLocker: 'Halt die Luft an. Nicht bewegen.',
      fearHigh: 'Ich krieg keine Luft…',
      lowBattery: 'Die Batterie gibt den Geist auf.',
      freed: '{name} jagt mich nicht mehr.',
      eaterFlicker: 'Die Lichter werden schwächer. Es ist nah. Ich höre es kauen.',
    },
    ghostHelp: {
      danny: 'DANNY: „Lauf! Ich hab ihn!“',
      amberWatch: 'TOBY: „Sieh mich nicht an… bitte sieh mich nicht an…“',
    },
    deaths: {
      eater: ['GEFRESSEN', 'Der Fresser ist auf gerader Strecke schneller als du und in Kurven langsam. Nimm die Ecken und horch auf das Kauen.'],
      red: ['GEFASST', 'Danny hört nie auf und gibt keine Verfolgung auf. Brich seine Sichtlinie und bring eine Ecke zwischen euch.'],
      violet: ['ABGESCHNITTEN', 'Rosie läuft dorthin, wohin du willst, nicht dorthin, wo du bist. Wechsle die Richtung, wenn sie verschwindet.'],
      teal: ['HINABGEZOGEN', 'Nell hört Wasser. Halt dich aus den Pfützen heraus und geh an den Rändern entlang.'],
      amber: ['ERSTARRT', 'Toby kann sich nicht bewegen, solange du ihn ansiehst. Behalte ihn im Blick oder im Licht.'],
      grinner: ['ES HAT GELÄCHELT', 'Grinser schmelzen im Licht. Halt die Taschenlampe auf sie oder wirf ein Knicklicht.'],
      watcher: ['GEZÄHLT', 'Der Zähler bewegt sich nur, wenn du nicht hinsiehst. Kehr ihm nie lange den Rücken zu.'],
      crawler: ['HINUNTERGEZERRT', 'Kriecher weichen vor Licht zurück und kreisen dich dann ein. Bleib mit dem Rücken zur Wand und halt keinen zu lange im Lichtkegel fest.'],
      monitor: ['KEIN PASSIERSCHEIN', 'Die Pausenaufsicht sieht nur, was ihre Taschenlampe trifft. Rein in einen Spind, bevor der Strahl dich findet.'],
      mannequin: ['IN POSE GEBRACHT', 'Schaufensterpuppen bewegen sich nur, solange niemand hinsieht. Geh notfalls rückwärts.'],
      neighbor: ['HEREINGELASSEN', 'Der Nachbar kommt näher, solange du ihm den Rücken zukehrst. Deine Taschenlampe lässt ihn zurückweichen. Antworte nie auf die Stimme.'],
      chompy: ['GROSSE UMARMUNG', 'Chompy ist langsam, hört aber nie auf. Leuchte ihm in die Augen, dann versteckt es das Gesicht.'],
    },
    tips: [
      'Der Fresser ist in geraden Gängen schneller als du, aber in Kurven langsam. Nimm die Ecken.',
      'Rennen ist laut. Geduckt gehen ist fast lautlos, und geduckt öffnest du Türen leise.',
      'Wenn die Lichter schwächer werden und flackern, ist der Fresser nah.',
      'Eine Laterne lässt für ein paar Sekunden alles vor dir fliehen.',
      'Kassettenrekorder speichern dein Spiel und spielen eine Erinnerung ab.',
      'Du kannst dich unter Tischen, Betten und Tresen und in Spinden verstecken. Wenn nichts dich hineingehen sah, sucht nichts nach dir.',
      'Bring jedem Spuk sein Andenken zum Schrein, dann hört er auf, dich zu jagen. Davon hängt das Ende ab.',
      'Ein Star Pop beruhigt die Nerven und gibt dir deinen Atem zurück.',
      'M öffnet eine Karte der Orte, die du erkundet hast.',
      'Die Taschenlampe frisst Batterien. Knicklichter (G) erhellen eine Ecke, und ihr Klappern lockt Jäger von dir weg.',
      'Sieh den Bernsteinfarbenen weiter an. Aber nicht zu lange.',
      'Lily hat acht Zeichnungen hinterlassen. Manche sind gut versteckt.',
      'Eddie kennt diesen Ort besser als jeder andere. Das heißt nicht, dass er dir alles erzählt.',
      'Spinde verstecken dich vollständig. Kommt etwas nah, halt Shift gedrückt, um die Luft anzuhalten.',
      'Schaufensterpuppen können sich nicht bewegen, solange du sie ansiehst.',
      'Der Nachbar benutzt Stimmen, die du kennst. Antworte nicht.',
      'Walt hat fünf Seiten aus seinem Tagebuch gerissen. Sie sind wichtiger, als sie scheinen.',
      'Eine Schublade, die einen Fingerbreit offen steht, hat etwas darin. Ebenso ein Tresor, dessen Tür nicht eingerastet ist.',
      'Halte V (oder die mittlere Maustaste), um beim Rennen über die Schulter zu sehen.',
      'Je länger es still ist, desto näher kommen sie. Das Spiel wartet nicht gern.',
    ],
    endings: {
      exit: {
        title: 'EXIT', subtitle: 'Schlechtes Ende — Schon wieder',
        lines: [
          'Du nimmst die Tür. Hinter dir schreit Eddie deinen Namen, dann ist die Tür zu und das Schreien auf der anderen Seite.',
          'Kalte Luft. Regen. Du öffnest die Augen auf dem nassen Teppich der Spielhalle. Es ist Morgen. Die Rollläden sind halb offen.',
          'Automat Nr. 7 läuft immer noch. Im Demo-Bildschirm treiben jetzt fünf Spuke durchs Haus. Der fünfte trägt eine Arbeitsjacke.',
          'Die Möbelpacker laden ihn um zwölf ein. Der Fahrer wird später sagen, er habe die ganze Route 9 entlang jemanden von innen gegen den Automaten klopfen hören.',
          'Der Lastwagen kommt nie bei der Versteigerung an.',
          'Du hattest dir geschworen, sie nie wieder im Stich zu lassen. Beim zweiten Mal war es leichter. Das ist das Schlimmste daran.',
        ],
      },
      deal: {
        title: 'DER HANDEL', subtitle: 'Dunkles Ende — Einer rein, einer raus',
        lines: [
          'Du hältst die Tür. Eddie sieht dich eine lange Sekunde an. „Ich erzähle es ihnen. Ich erzähle allen, wer du warst.“',
          'Er geht hindurch. Die Tür schließt sich leise, wie das Ende eines Bandes.',
          'Irgendwo in Harlow betritt im Morgengrauen ein triefnasser Mann eine Küche, und ein einjähriges Mädchen starrt ihn aus seinem Hochstuhl an.',
          'Das Haus ist still. Weit weg fängt etwas Rundes wieder an zu kauen.',
          'Du bist nicht der Spieler. Du bist kein Spuk. Du bist die Person, die geblieben ist. Die Sterne leuchten. Du weißt, wo jeder einzelne liegt.',
          'Auf der Punkteliste in einer leeren Spielhalle steht, in einer Schrift, die niemand erklären kann, eine neue Zeile: SAM — SPIELT NOCH.',
        ],
      },
      plug: {
        title: 'GAME OVER', subtitle: 'Gutes Ende — Niemand lässt los',
        lines: [
          'Vier farbige Lichter schließen sich um deine Hände. Rot, Violett, Türkis, Bernstein. Fünf Hände, wie es im Pakt stand.',
          'Du ziehst. Der Stecker kommt heraus. Zum ersten Mal seit 1987 hört das Brummen auf.',
          'Im Dunkeln, ganz nah, eine müde, menschliche Stimme: „Ich bin satt, Sam. Endlich.“',
          'Du wachst auf dem Teppich der Spielhalle auf. Durch das Glas kommt die Dämmerung.',
          'Vier Kinder in Jacken von 1987 sitzen blinzelnd auf dem Boden. Toby sieht dich lange an. „Sam? …Du bist alt geworden.“ Dann umarmt er dich so fest, dass es wehtut.',
          'In der Maple Street geht ein Verandalicht aus, das sieben Jahre lang gebrannt hat.',
          'Eddie geht durch die leeren Straßen nach Hause. Er rennt nicht. Er will sich den Weg merken.',
          'Automat Nr. 7 ist dunkel. Eine Zeile bleibt ins Glas gebrannt: GAME OVER — 5 PLAYERS.',
        ],
      },
      lil: {
        title: 'LIL', subtitle: 'Wahres Ende — Die Namen auf der Liste',
        lines: [
          'Du legst acht Zeichnungen auf den Kern. Wachsmalstift auf Papier: die Spielhalle, ein orangefarbener Chompy mit Hörnern, ein Krankenhausfenster, ein Papa.',
          'Der Fresser hört auf zu kauen. Lange ist es still. Dann, mit einer Stimme, die du aus dem Jahr 1985 kennst: „…Die hat Lily gemalt.“',
          'Walt steht da, wo der Fresser war, dünn und grau und er selbst. „Nimm die Hände runter, Kind. Diesen Stecker ziehe ich. Das war immer meine Aufgabe.“',
          'Vier farbige Lichter schließen sich um seine Hände. Er zieht. Das Haus faltet sich zusammen wie Papier.',
          'Das Letzte, was du siehst, ist ein kleines Mädchen im Krankenhaushemd, das seine Hand nimmt, und wie die beiden ins Dunkel zwischen den Sternen gehen.',
          'Morgengrauen. Vier Kinder auf dem Teppich der Spielhalle. Eddie draußen am Münztelefon, lachend und weinend zugleich. „June? June, ich bin’s.“',
          'Eine Woche später schließt Nora die Spielhalle ein letztes Mal auf und findet die Punkteliste neu beschrieben, in einer Handschrift, die sie kennt. 1 LIL. 2 DAN. 3 ROS. 4 NEL. 5 TOB. 6 SAM. 7 WALT.',
          'Tobys Verandalicht geht aus. In der Maple Street sitzen zwei, die keine Kinder mehr sind, auf dem Bordstein und reden bis Mittag. Sam erzählt ihm alles. Er wusste es schon.',
        ],
      },
    },
    scrawl: {
      yellow: ['WER IST NACH HAUSE GEGANGEN?', 'ES IST IMMER 3:17', 'LASS NICHT LOS', 'FÜNF HÄNDE', 'ICH HÖRE ES KAUEN', 'ZÄHL DIE TÜREN'],
      dark: ['LASS DAS LICHT AN', 'SAM?', 'ES LÄCHELT, WENN DU BLINZELST', 'ICH HAB KEINE ANGST'],
      office: ['WO SIND ALLE HIN', '107.3', 'SEITE B'],
      hospital: ['BITTE RUHE', 'SIE HAT ALLES BEMALT', '207'],
      motel: ['EINER REIN EINER RAUS', 'NICHT ANTWORTEN', '3:17'],
      school: ['NIEMAND LÄSST LOS', 'D R N T S', 'SAM WAR HIER'],
      concrete: ['DU HAST LOSGELASSEN', 'DAN #1', '3:17'],
      pool: ['EINE SEKUNDE', 'ICH HAB AUFGEPASST'],
      mall: ['FREUNDE FÜR IMMER', 'AUCH WENN'],
      tunnel: ['NIEMAND GEHT ALLEIN NACH HAUSE', 'D+T+S'],
      workshop: ['ZIEH NICHT DEN STECKER', '2 5 6'],
    },
    photoLabels: { fort: 'DIE FESTUNG. ERÖFFNUNGSTAG.', chompy: 'LIL & CHOMPY' },
    credits: [
      ['LEVEL 256', 'Die Starlight-Spielhalle'],
      ['Ein Horrorspiel aus der Ich-Perspektive', ''],
      ['Gewidmet', 'allen, die je etwas losgelassen haben und dafür zurückgekommen sind'],
      ['Hungry House', 'ein erfundenes Automatenspiel von 1981, gemacht für diese Geschichte'],
      ['Klang', 'live erzeugt, keine einzige Aufnahme'],
      ['Texturen und Modelle', 'prozedural, keine einzige Bilddatei'],
      ['An die Spieler', 'werft nach Mitternacht nie eine Marke in Automat Nr. 7'],
    ],
  });
})(typeof window !== 'undefined' ? window : globalThis);
