/* Deutscher Story-Kern: Figuren, Sprecher, gemeinsame Zeilen, Tode, Tipps, Abspann, Wandschriften.
   Die Kapiteldateien fügen Dokumente, Ziele, Gedanken, Funk und Rückblicke hinzu; lake.js die Enden.
   Die Story-Bibel ist docs/STORY.md. */
(function (root) {
  'use strict';
  root.PB.I18N.register('de', 'story', {
    chars: {
      ada: { name: 'Ada', pos: 'Adas', role: 'Ada Lind, 31. Seit 1990 Nachtschicht in Depot 9, dem Fundbüro unter dem Hauptbahnhof Halvard. Du.' },
      wren: { name: 'Wren', pos: 'Wrens', role: 'Wren Lind, Adas kleine Schwester. Sieben. Verschwand am 14. Januar 1979 auf dem Eis des Ostra-Sees.' },
      otto: { name: 'Otto', pos: 'Ottos', role: 'Otto Brandt, Nachtbeamter in Depot 9 von 1946 bis 1964, als er mit dem Lastenaufzug hinunterfuhr. Auf Kanal neun.' },
      ingrid: { name: 'Ingrid', pos: 'Ingrids', role: 'Ingrid Lind, die Großmutter der Mädchen, „Oma“. Geboren in Gammel Ostra. Gestorben 1996.' },
      clerk: { name: 'Die Nachtbeamtin', pos: 'der Nachtbeamtin', role: 'Führt den Index ganz unten im Darunter. Unterschreibt ihre Notizen mit „A.“' },
    },
    speakers: { ada: 'ADA', otto: 'OTTO', radio: 'FUNK', lyle: 'LYLE HARDY', clerk: 'DIE BEAMTIN', wren: 'WREN', voice: '???' },
    items: {},
    obj: {},
    memento: {},
    freed: {},
    shrine: {},
    ghostHelp: {},
    mono: {
      hide: 'Halt die Luft an.',
      hideLocker: 'Halt die Luft an. Nicht bewegen.',
      fearHigh: 'Ich krieg keine Luft...',
      lowBattery: 'Die Batterie stirbt.',
      eaterFlicker: 'Die Lichter gehen aus. Es ist nah. Ich höre es kauen.',
      watcherSeen: 'Etwas Großes am anderen Ende, ganz still.',
    },
    // [was auf dem Bildschirm steht, was man anders machen sollte]
    deaths: {
      eater: ['GEFRESSEN', 'Der Fresser ist auf geraden Strecken schnell und in Kurven langsam. Ein frisches verlorenes Licht in der Hand lässt ihn ein paar Sekunden zurückweichen.'],
      sorter: ['EINSORTIERT', 'Was im Dunkeln das Archiv sortiert, macht einfach weiter. Gerate nicht zwischen es und die Regale.'],
      wallpaperMan: ['ÜBERTAPEZIERT', 'Die flachen Männer lösen sich nur hinter deinem Rücken von der Wand. Geh an ihnen vorbei und sieh sie dabei an.'],
      hummer: ['WEGGESUMMT', 'Wo das Summen anschwillt und das Licht flackert, lauscht etwas. Geh langsam und meide die lauten Stellen.'],
      drowned: ['HINABGEZOGEN', 'Die Ertrunkenen warten unter Wasser und hören dich darin. Bleib aus dem Wasser und steh nie still darin.'],
      passenger: ['ZUM PLATZ GEBRACHT', 'Die Passagiere wachen auf, wenn Licht auf ihnen ruht. Halte die Lampe von ihren Gesichtern fern und streife sie nicht.'],
      bellman: ['GELÄUTET', 'Auf dem offenen Deck hört dich der Glöckner. Wenn die Glocke läutet, jagt er: geh in Deckung und bleib unten.'],
      pines: ['IN DIE BÄUME GEHOLT', 'Die Kiefern bewegen sich nur, während du dich bewegst. In ihrer Nähe: stillstehen und warten, bis sie das Interesse verlieren.'],
      stag: ['ÜBERRANNT', 'Der Hirsch greift in gerader Linie an. Bring einen Baum oder ein Auto zwischen euch, dann betäubt er sich selbst.'],
      usher: ['ZUM PLATZ GEFÜHRT', 'Ein Platzanweiser sieht nur in seinem roten Strahl. Bleib aus dem Licht und kreuze nie vor ihm.'],
      burrower: ['IN DIE ERDE GEZERRT', 'Wühler spüren deine Schritte durch den Boden. Auf Erdboden duck dich; auf Schienen und Planken bist du sicher.'],
      lamplighter: ['LAMPE IN DEN AUGEN', 'Lampenträger gehen zu jedem Licht. Mach deine Lampe aus und lass sie vorbeigehen.'],
      crawler: ['VON OBEN GEPACKT', 'Gebälkkriecher warten im Dachgebälk. Sieh nach oben, bevor du darunter gehst, und bleib unten.'],
      frozen: ['ERFROREN', 'Die erfrorenen Gäste rühren sich nur nahe der Wärme. Wärm dich auf und geh vom Feuer weg, bevor sie aufstehen.'],
      cold: ['ERFROREN', 'Draußen kriecht die Kälte schnell hinein. Geh von Unterschlupf zu Unterschlupf und wärm dich an einem Feuer.'],
      whiteout: ['VOM SCHNEE VERSCHLUCKT', 'Im Sturm siehst du nur seine Spuren. Es hört dich: geh, renn nicht, und bleib nahe am Schutz.'],
      cook: ['AM HAKEN', 'Der Koch verlässt die Küche nie. Warte, bis er dir am hinteren Ende den Rücken zukehrt, dann geh.'],
      silted: ['IN DEN SCHLAMM GEZOGEN', 'Bleib zu lange auf dem Schlamm stehen, und einer von ihnen steigt neben dir auf. Bleib in Bewegung.'],
      longone: ['IN DEN FLUSS GEHOLT', 'Die Langen warten in Brunnen, Gräben und im Fluss. Duck dich, wenn du am Wasser vorbeigehst.'],
      choir: ['IN DIE BANK GESETZT', 'Solange der Chor singt, sieht er nichts. Geh leise hinter ihnen; renn nie, geh nie vor ihnen vorbei.'],
      water: ['ERTRUNKEN', 'Das Wasser steigt immer schneller. Such höheren Grund und klettere.'],
      conductor: ['AUS DEM ZUG GESETZT', 'Ohne gültige Fahrkarte setzt dich der Schaffner aus dem Zug. Kommt seine Lampe den Gang herunter, mach die Taschenlampe aus und kriech unter eine Pritsche.'],
      sleeper: ['IN DIE KOJE GEZOGEN', 'Schläfer sehen nicht. Ein Schritt vor ihrem Abteil weckt sie: schleich geduckt vorbei und halt still, wenn einer wach ist.'],
      underhand: ['ZWISCHEN DIE WAGEN GEZERRT', 'Bleib nie auf einem Übergang stehen. Geh schnell hinüber und öffne die nächste Tür, bevor du auf die Platten trittst.'],
      mask: ['GESICHTER', 'Die Masken bewegen sich nur, wenn niemand hinsieht. Behalte sie vor dir und weiche rückwärts zurück.'],
      horse: ['NIEDERGETRAMPELT', 'Die Pferde laufen nur, solange die Orgel spielt. Hört die Musik auf, stehen sie: dann bewegst du dich.'],
      lotte: ['HOCHGEHOBEN', 'Lotte ist blind. Sie hört, und sie hört nie auf zu lachen: halt dich vom Lachen fern und sei leise.'],
      hush: ['VERSTUMMT', 'In der Nähe der Stille verklingt jedes Geräusch. Hörst du dich selbst nicht mehr, ist sie ganz nah. Geh weg, langsam.'],
      underice: ['DURCHS EIS', 'Renn nie auf dem dunklen Eis über dem alten Fluss. Geh, und was darunter ist, bleibt darunter.'],
    },
    tips: [
      'Rennen ist laut. Geduckt gehen ist fast lautlos.',
      'Auf dem Grund jedes Regals liegt eine Lüge. Finde das Verlorene und bring es dorthin zurück, wo es hingehört, und der Ort lässt dich gehen.',
      'Die meisten hören besser, als sie sehen. Mach die Lampe aus, wenn etwas nah ist.',
      'Du kannst dich unter Betten, Pritschen und Tischen verstecken. Hat dich nichts hineingehen sehen, sucht auch nichts.',
      'Halte im Versteck Shift gedrückt, um die Luft anzuhalten. Geht dir die Luft aus, schnappst du laut nach Atem.',
      'Halte V gedrückt, um beim Rennen über die Schulter zu sehen.',
      'Lies alles. Die Leute, die das geschrieben haben, sagen dir, wie du hinauskommst.',
      'Wren hat acht Zeichnungen hinterlassen, auf den meisten Regalen eine. Manche sind gut versteckt.',
      'Otto meldet sich auf Kanal neun, wenn er dir etwas zu sagen hat. Meistens hat er recht.',
      'M öffnet eine Karte der Orte, an denen du warst.',
    ],
    photoLabels: {},
    credits: [
      ['LEVEL 256', 'eine Horrorgeschichte in der Ich-Perspektive, in neun Regalen'],
      ['Für', 'alle, denen gesagt wurde, es sei niemandes Schuld gewesen'],
      ['Orte', 'Halvard, der Ostra-See und das Darunter sind erfunden; ebenso alle, die darin vorkommen'],
      ['Ton', 'live synthetisiert: keine einzige Aufnahme'],
      ['Bilder und Modelle', 'prozedural: keine einzige Bilddatei'],
      ['Depot 9', 'hat jede Nacht geöffnet. Fragen Sie am Schalter.'],
    ],
    // An die Wände des Darunter gekritzelt
    scrawl: {
      yellow: ['WER KAM ZURÜCK, UM ES ZU HOLEN?', 'ES IST IMMER 02:56', 'ANSPRUCH 256', 'KEIN REGAL WIRD ÜBERSPRUNGEN', 'SUCH DIE LÜGE', 'NIEMAND HAT GEFRAGT', 'ABGELEGT UNTER: VERGESSEN'],
      dark: ['LASS DAS LICHT AN', 'ES FRISST, WAS DU NICHT MEHR SUCHST', 'ADA?'],
      concrete: ['AUFBEWAHREN FÜR: ADA LIND', '256', 'NICHT ABGEHOLT'],
    },
  });
})(typeof window !== 'undefined' ? window : globalThis);
