/* Deutsche Oberfläche. */
(function (root) {
  'use strict';
  root.PB.I18N.register('de', 'ui', {
    'game.title': 'LEVEL 256',
    'game.subtitle': 'DIE STARLIGHT-SPIELHALLE',
    'game.aria': 'Spielansicht',
    'noscript': 'Dieses Spiel braucht JavaScript.',

    'boot.tip': 'TIPP',
    'boot.init': 'Startet…',
    'boot.fonts': 'Schriften werden geladen…',
    'boot.sounds': 'Geräusche werden aufgenommen…',
    'boot.voices': 'Stimmen werden aufgenommen…',
    'boot.prep': 'Level wird vorbereitet…',
    'boot.noThree': 'Die 3D-Engine (three.js) konnte nicht geladen werden. Prüfe deine Internetverbindung und lade die Seite neu.',
    'boot.error': 'Fehler beim Start: {msg}',
    'boot.noWebgl': 'Die Grafikkarte konnte 3D (WebGL 2) nicht starten. Aktualisiere den Grafiktreiber und starte das Spiel dann neu.',
    'load.textures': 'Texturen werden gewebt… ({n}/{m})',
    'load.walls': 'Wände werden hochgezogen…',
    'load.bake': 'Licht wird gebacken…',
    'load.fixtures': 'Leuchtstoffröhren werden aufgehängt…',
    'load.props': 'Möbel werden aufgestellt…',
    'load.decals': 'Flecken und Kratzer…',
    'load.shaders': 'Shader werden kompiliert…',
    'load.ready': 'Bereit',
    'load.error': 'Fehler beim Laden: {msg}',

    'first.title': 'Bevor du anfängst',
    'first.lang': 'Sprache',
    'first.bright': 'Stelle die Helligkeit so ein, dass das linke Zeichen kaum und das rechte deutlich zu sehen ist.',
    'first.phones': 'Am besten mit Kopfhörern, in einem dunklen Raum.',
    'first.go': 'Weiter',

    'menu.continue': 'Fortsetzen',
    'menu.new': 'Neues Spiel',
    'menu.levels': 'Kapitel',
    'menu.settings': 'Einstellungen',
    'menu.archive': 'Archiv',
    'menu.help': 'Anleitung',
    'menu.quit': 'Spiel beenden',
    'menu.credit': 'Harlow · 30. November 1994 · 2:11 Uhr',
    'menu.foot': 'Mit Kopfhörern spielen, im Dunkeln.',
    'menu.footDone': 'Enden: {list} · Tode {deaths}',

    'confirm.title': 'Neues Spiel?',
    'confirm.body': 'Dein gespeicherter Fortschritt wird überschrieben. Gefundene Dokumente bleiben im Archiv.',
    'confirm.yes': 'Ja, neu anfangen',
    'confirm.no': 'Abbrechen',

    'diff.title': 'Schwierigkeit',
    'diff.easy': 'Leicht',
    'diff.easyDesc': 'Für die Geschichte. Die Kreaturen sind langsamer und weniger wachsam. Einmal pro Kapitel entkommst du einem Griff.',
    'diff.normal': 'Normal',
    'diff.normalDesc': 'So wie gedacht. Wirst du gepackt, geht es zurück zum letzten Speicherstand.',
    'diff.nightmare': 'Albtraum',
    'diff.nightmareDesc': 'Schnellere Kreaturen mit schärferem Gehör. Batterien sind schnell leer. Die Angst setzt früher ein.',
    'diff.time': 'Geschätzte Spielzeit: 4–6 Stunden, wenn du jedes Dokument liest und alle vier Spuke befreist.',

    'levels.title': 'Kapitel',
    'levels.locked': 'Gesperrt',

    'common.back': 'Zurück',
    'common.on': 'An',
    'common.off': 'Aus',

    'settings.title': 'Einstellungen',
    'settings.reset': 'Standard',
    'settings.reloadNote': 'Mit * markierte Einstellungen gelten, sobald das nächste Kapitel lädt.',
    'tab.screen': 'Bildschirm',
    'set.displayMode': 'Anzeigemodus',
    'set.displayMode.help': 'Vollbild blendet den Browser aus. Esc oder F11 beendet es; Alt+Enter schaltet im Spiel um.',
    'opt.windowed': 'Fenster',
    'opt.fullscreen': 'Vollbild',
    'set.resolution': 'Auflösung',
    'set.resolution.help': 'Die Größe des gerenderten Bildes. Nativ nutzt deinen Bildschirm; jede andere Größe wird mit dem Skalierungsmodus unten ins Fenster eingepasst.',
    'opt.native': 'Nativ (Bildschirm)',
    'set.scaleMode': 'Skalierungsmodus',
    'set.scaleMode.help': 'Wie eine Auflösung mit anderem Seitenverhältnis als das Fenster gezeigt wird.',
    'opt.fit': 'Einpassen (Seitenverhältnis, schwarze Balken)',
    'opt.stretch': 'Strecken',
    'opt.fill': 'Füllen (Ränder beschneiden)',
    'set.upscale': 'Skalierungsfilter',
    'set.upscale.help': 'Weich mischt die Pixel beim Skalieren; Pixel hält sie scharf und eckig (Retro-Look bei niedriger Auflösung).',
    'opt.smooth': 'Weich',
    'opt.pixel': 'Pixel',
    'set.sharpen': 'Nachschärfen',
    'set.sharpen.help': 'Kontrastadaptives Schärfen des fertigen Bildes. Hilft unterhalb der nativen Auflösung und mit Kantenglättung.',
    'set.fpsLimit': 'Bildratenbegrenzung',
    'set.fpsLimit.help': 'Begrenzt die Bilder pro Sekunde. Niedrigere Grenzen halten die Grafikkarte kühl und die Bildausgabe gleichmäßig.',
    'opt.unlimited': 'Unbegrenzt',
    'set.vsync': 'V-Sync',
    'set.vsync.help': 'An: Die Bilder folgen der Bildwiederholrate des Monitors, ohne Tearing. Aus: Das Spiel zeichnet so schnell es kann, bis zur Bildratenbegrenzung. Im Webbrowser wartet der Browser selbst immer auf den Monitor, Aus entfernt also nur das eigene Warten des Spiels; die Desktop-Version schaltet die Synchronisierung ganz ab (nach einem Neustart).',
    'tab.graphics': 'Grafik',
    'tab.display': 'Bild',
    'tab.audio': 'Audio',
    'tab.controls': 'Steuerung',
    'tab.gameplay': 'Spiel',
    'preset.low': 'Niedrig',
    'preset.medium': 'Mittel',
    'preset.high': 'Hoch',
    'preset.ultra': 'Ultra',
    'preset.extreme': 'Extrem',
    'preset.custom': 'Eigene',
    'opt.off': 'Aus',
    'opt.low': 'Niedrig',
    'opt.medium': 'Mittel',
    'opt.high': 'Hoch',
    'opt.ultra': 'Ultra',
    'opt.extreme': 'Extrem',
    'opt.shadow1': 'Niedrig (1024)',
    'opt.shadow2': 'Hoch (2048)',
    'opt.shadow3': 'Ultra (4096)',
    'opt.small': 'Klein',
    'opt.large': 'Groß',
    'opt.full': 'Voll',
    'opt.reduced': 'Reduziert',

    'set.preset': 'Qualitätsstufe',
    'set.preset.help': 'Ändert alle Grafikeinstellungen darunter auf einmal. Extrem ist für starke Grafikkarten gedacht; Ultra+ geht darüber hinaus (8192er-Schatten, das dichteste Licht-Backing, die feinsten Modelle, Tiefenunschärfe) und ist für die stärksten PCs.',
    'set.renderScale': 'Auflösungsskalierung',
    'set.renderScale.help': 'Über 100 % wird in höherer Auflösung gerendert und verkleinert: schärferes Bild, viel mehr Last für die Grafikkarte.',
    'set.textureRes': 'Texturauflösung',
    'set.shadows': 'Schatten',
    'set.antialias': 'Kantenglättung',
    'set.lightmapRes': 'Qualität des gebackenen Lichts',
    'set.lightmapRes.help': 'Detail des weichen, vorberechneten Lichts und seiner Schatten.',
    'set.dynLights': 'Dynamische Lichter',
    'set.bloom': 'Bloom',
    'set.bloomStrength': 'Bloom-Stärke',
    'set.volumetric': 'Volumetrisches Licht und Staub',
    'set.ao': 'Umgebungsverdeckung (SSAO)',
    'set.ao.help': 'Weiche Kontaktschatten in Ecken, unter Möbeln und zwischen Fliesen.',
    'set.ssr': 'Bildschirmraum-Spiegelungen',
    'set.ssr.help': 'Echte Spiegelungen auf nassen Böden, Fliesen, Glas und poliertem Metall.',
    'set.volumetric.help': 'Per Raymarching berechnete Lichtstrahlen, der Lichtkegel der Taschenlampe und schwebender Staub. Auf Extrem sehr aufwendig.',
    'set.motionBlur': 'Bewegungsunschärfe',
    'set.lensDirt': 'Schmutz auf der Linse',
    'set.lensDirt.help': 'Schlieren auf der Kameralinse, die helles Licht einfangen.',
    'set.particles': 'Partikeldichte',
    'set.viewDist': 'Sichtweite',
    'set.anisotropy': 'Anisotrope Filterung',
    'set.brightness': 'Helligkeit',
    'set.brightness.help': 'Stelle sie so ein, dass die dunkelsten Ecken gerade noch zu erkennen sind.',
    'set.contrast': 'Kontrast',
    'set.saturation': 'Farbsättigung',
    'set.fov': 'Sichtfeld',
    'set.headBob': 'Kopfbewegung',
    'set.shake': 'Kamerawackeln',
    'set.grain': 'Filmkorn',
    'set.chromatic': 'Chromatische Aberration',
    'set.vignette': 'Vignette',
    'set.vhs': 'Camcorder-Look (VHS)',
    'set.vhs.help': 'Zeigt das Spiel wie durch den Sucher eines Camcorders von 1994.',
    'set.reduceFlicker': 'Flackern verringern',
    'set.reduceFlicker.help': 'Mildert flackernde Lichter und Bildschirmblitze für lichtempfindliche Spieler.',
    'set.crosshair': 'Zielpunkt',
    'set.subtitles': 'Untertitel',
    'set.captions': 'Geräuschuntertitel',
    'set.captions.help': 'Zeigt wichtige Geräusche als Text, etwa [fernes Kauen].',
    'set.subtitleSize': 'Untertitelgröße',
    'set.master': 'Gesamtlautstärke',
    'set.music': 'Musik',
    'set.sfx': 'Effekte',
    'set.ambience': 'Umgebung (Brummen, Tropfen, Regen)',
    'set.entities': 'Kreaturengeräusche',
    'set.voice': 'Stimmen und Funk',
    'set.hrtf': '3D-Audio (HRTF, Kopfhörer empfohlen)',
    'set.mouseSens': 'Mausempfindlichkeit',
    'set.invertY': 'Vertikale Achse umkehren',
    'set.touchSens': 'Touch-Empfindlichkeit',
    'set.toggleCrouch': 'Ducken: umschalten statt halten',
    'set.toggleSprint': 'Rennen: umschalten statt halten',
    'set.lang': 'Sprache',
    'set.difficulty': 'Schwierigkeit',
    'set.difficulty.help': 'Beeinflusst Tempo und Gehör der Kreaturen und die Batterie der Taschenlampe.',
    'set.jumpscare': 'Jumpscares',
    'set.hints': 'Hinweise',

    'archive.title': 'Archiv',
    'archive.count': '{n} / {m} Dokumente',
    'archive.notFound': 'Noch nicht gefunden',
    'kind.note': 'Notiz',
    'kind.letter': 'Brief',
    'kind.diary': 'Tagebuchseite',
    'kind.tape': 'Tonbandaufnahme',
    'kind.photo': 'Foto',
    'kind.screen': 'Computerbildschirm',
    'kind.phone': 'Telefonnachricht',
    'kind.printout': 'Ausdruck',
    'kind.wall': 'Schrift an der Wand',
    'kind.notice': 'Aushang',
    'kind.memory': 'Erinnerung',
    'kind.drawing': 'Zeichnung',
    'kind.card': 'Karte',
    'kind.report': 'Bericht',
    'kind.flyer': 'Flugblatt',
    'kind.doc': 'Dokument',

    'help.title': 'Anleitung',
    'help.kbm': 'Tastatur und Maus',
    'help.walk': 'Gehen',
    'help.mouse': 'Maus',
    'help.look': 'Umsehen (klicken, um den Zeiger zu fangen)',
    'help.sprint': 'Rennen (laut, kostet Atem)',
    'help.crouch': 'Ducken (fast lautlos)',
    'help.interact': 'Benutzen, lesen, nehmen, verstecken',
    'help.flash': 'Taschenlampe',
    'help.drink': 'Einen Star Pop trinken',
    'help.throw': 'Ein Knicklicht werfen',
    'help.lean': 'Nach links / rechts lehnen (um Ecken spähen)',
    'help.map': 'Karte',
    'help.bag': 'Gegenstände / Tagebuch',
    'bag.items': 'GEGENSTÄNDE',
    'bag.journal': 'TAGEBUCH',
    'bag.close': 'Schließen (I / J)',
    'bag.empty': 'Deine Taschen sind leer.',
    'bag.inspectHint': 'Ziehen, um es zu drehen.',
    'bag.now': 'GERADE JETZT',
    'bag.story': 'WAS BISHER GESCHAH',
    'bag.docs': 'HIER GEFUNDEN',
    'bag.noDocs': 'Hier noch nichts gefunden. Sieh genauer hin.',
    'bag.people': 'PERSONEN',
    'bag.freed': 'in Frieden',
    'bag.hunting': 'jagt noch',
    'bag.stats': 'Dokumente {a} / {b}   ·   Lilys Zeichnungen {c} / {d}',
    'bag.n.flashlight': 'Taschenlampe',
    'bag.d.flashlight': 'Eine schwere Stahltaschenlampe aus dem Transporter der Spielhalle. Batterie: {n} %. Sie wird schwächer, bevor sie ausgeht.',
    'bag.n.battery': 'Ersatzbatterien',
    'bag.d.battery': 'Monozellen für die Taschenlampe. R setzt sie ein; eine leere Lampe bekommt sie automatisch.',
    'bag.n.almond': 'Star Pop',
    'bag.d.almond': 'Eine Dose der hauseigenen Kirschlimo der Spielhalle, irgendwie noch kalt. Zucker und Kohlensäure beruhigen die Hände. Mit Q trinken.',
    'bag.n.glow': 'Knicklichter',
    'bag.d.glow': 'Knick eins und wirf es mit G. Kriecher und Grinser gehen nicht durch das grüne Licht.',
    'bag.d.officeKey': 'Walts Büroschlüssel, aus der Registrierkasse. Das Messing ist glattgegriffen.',
    'bag.d.token': 'Eine Starlight-Spielmarke mit einem ausgestanzten Stern. Nur für Automat Nr. 7.',
    'bag.n.fuse': 'Sicherungen',
    'bag.d.fuse': 'Schwere Keramiksicherungen für den alten Kasten der Mühle.',
    'bag.n.fuel': 'Dieselkanister',
    'bag.d.fuel': 'Diesel für die Generatoren. Er schwappt laut. Geh langsam.',
    'bag.d.keycard': 'Eine Sicherheitskarte mit Magnetstreifen. Jemandes Foto wurde abgekratzt.',
    'bag.d.key': 'Ein Schlüssel an einem Papieranhänger. Er öffnet hier etwas.',
    'help.pause': 'Pause',
    'help.touch': 'Touch',
    'help.touchText': 'Bewegungsstick unten links, auf der rechten Bildschirmseite ziehen, um sich umzusehen. Die Tasten rechts: benutzen, Taschenlampe, rennen, ducken, Karte.',
    'help.survive': 'Am Leben bleiben',
    'help.tip1': '<b>Der Fresser</b> ist auf geraden Gängen schneller als du und in Kurven langsam. Nimm die Ecken.',
    'help.tip2': 'Wenn die Leuchtstoffröhren zu flackern beginnen, <b>ist er nah</b>.',
    'help.tip3': 'Nimm eine <b>Laterne</b>, und für ein paar Sekunden flieht alles vor dir.',
    'help.tip4': '<b>Rot</b> hört nie auf. <b>Violett</b> schneidet dir den Weg ab. <b>Türkis</b> hört Wasser und springt von Ort zu Ort. <b>Bernstein</b> erstarrt, solange du hinsiehst.',
    'help.tip5': 'Du kannst dich unter Tischen und in Spinden <b>verstecken</b>. Wenn sie dich nicht hineingehen sahen, finden sie dich nicht.',
    'help.tip6': '<b>Kassettenrekorder</b> speichern das Spiel. Automatisch gespeichert wird bei Zielen, wenn du in Sicherheit bist.',
    'help.tip7': 'Bring jedem Spuk sein Andenken <b>zu seinem Schrein</b>. Davon hängt das Ende ab.',

    'pause.title': 'Pause',
    'pause.resume': 'Weiter',
    'pause.map': 'Karte',
    'pause.journal': 'Tagebuch',
    'pause.archive': 'Archiv',
    'pause.settings': 'Einstellungen',
    'pause.help': 'Anleitung',
    'pause.load': 'Letzten Stand laden',
    'pause.menu': 'Hauptmenü',

    'note.close': 'Schließen',
    'note.closeKey': 'Schließen (E)',

    'map.close': 'Schließen',
    'map.closeKey': 'Schließen (M)',
    'map.objective': 'Ziel',
    'map.tape': 'Kassette',
    'map.doc': 'Dokument',
    'map.shrine': 'Schrein',
    'map.supply': 'Vorräte',
    'map.locked': 'Verschlossene Tür',

    'kp.label': 'SICHERHEIT',
    'kp.clear': 'ENTF',
    'kp.enter': 'OK',
    'kp.open': 'OFFEN',
    'kp.error': 'FEHLER',
    'kp.close': 'Abbrechen (Esc)',

    'cab.help': 'Pfeiltasten oder WASD · Enter zum Starten · P für Pause ·',
    'cab.exit': 'Automat verlassen (Esc)',

    'choice.back': 'Zurücktreten',
    'card.skip': 'Klicken oder E drücken, um fortzufahren',

    'death.retry': 'Ab letztem Speicherstand weiter',
    'death.menu': 'Hauptmenü',

    'end.menu': 'Hauptmenü',
    'end.skip': 'Überspringen',
    'end.time': 'Spielzeit',
    'end.deaths': 'Tode',
    'end.docs': 'Dokumente',
    'end.freed': 'Spuke befreit',
    'end.drawings': 'Zeichnungen gefunden',

    'hud.objective': 'ZIEL',
    'hud.rec': 'REC',
    'hud.stamina': 'ATEM',
    'hud.battery': 'LICHT',
    'hud.power': 'STROM {t}',
    'hud.fps': '{n} FPS',

    'touch.pause': 'Pause',
    'touch.bag': 'TASCHE',
    'touch.map': 'KARTE',
    'touch.drink': 'TRINKEN',
    'touch.throw': 'WERFEN',
    'touch.crouch': 'DUCKEN',
    'touch.sprint': 'RENNEN',
    'touch.flash': 'LICHT',
    'touch.tap': 'TIPPEN',

    'inv.battery': 'BATTERIE ×{n}',
    'inv.almond': 'STAR POP ×{n}',
    'inv.glow': 'KNICKLICHT ×{n}',
    'inv.officeKey': 'BÜROSCHLÜSSEL',
    'inv.token': 'GOLDMARKE',
    'inv.fuses': 'SICHERUNG ×{n}',
    'inv.fuel': 'DIESEL ×{n}',
    'inv.keycard': 'SICHERHEITSKARTE',
    'inv.pellets': 'LATERNE ×{n}',

    'n.added': 'Ins Archiv aufgenommen: {title}',
    'n.saved': 'Spiel gespeichert',
    'n.batteryIn': 'Neue Batterie in der Taschenlampe',
    'n.batterySpare': 'Ersatzbatterie',
    'n.noSpare': 'Keine Ersatzbatterien.',
    'n.batteryFull': 'Die Batterie ist noch voll.',
    'hint.reload': 'R: Batterien der Taschenlampe wechseln',
    'touch.reload': 'BATT',
    'help.reload': 'Batterien der Taschenlampe wechseln',
    'help.lookBack': 'Beim Rennen hinter dich sehen (halten)',
    'n.batterySwap': 'Du hast eine Ersatzbatterie eingesetzt',
    'n.almond': 'Star Pop (Q zum Trinken)',
    'n.glow': 'Knicklicht (G zum Werfen)',
    'n.found': 'Gefunden: {name}',
    'n.drank': 'Du trinkst den Star Pop. Dein Atem wird ruhiger.',
    'n.noAlmond': 'Du hast keinen Star Pop.',
    'n.noGlow': 'Du hast keine Knicklichter.',
    'n.slow': 'Das Spiel läuft langsam. Unter Pause › Einstellungen › Grafik kannst du die Qualität senken.',
    'n.lockFail': 'Der Mauszeiger ließ sich nicht fangen. Halte die linke Taste gedrückt und ziehe, um dich umzusehen.',
    'n.flashDead': 'Deine Taschenlampe ist aus.',
    'n.holdBreath': 'Etwas ist nah. Halte Shift gedrückt, um den Atem anzuhalten.',
    'n.heardBreath': 'Es hat dich atmen gehört.',
    'n.noFlash': 'Du hast keine Taschenlampe.',
    'n.noBattery': 'Die Batterie ist leer. Such eine Ersatzbatterie.',
    'n.grace': 'Das war knapp! (Leicht: einmal pro Kapitel)',
    'n.freed': '{name} ist frei',
    'n.ghostBack': '{name} hat sich zurückgezogen',
    'n.cabinetHi': 'Deine Initialen stehen in der Bestenliste: SAM',
    'n.perfect': 'Du hast jeden Stern gegessen. Perfektes Spiel.',
    'n.fruit': 'Vor dem Haus ist ein Preis erschienen',
    'n.diesel': 'Dieselkanister',
    'n.drawing': 'Lilys Zeichnung ({n}/8)',

    'pr.read': 'Lesen: {title}',
    'pr.readWall': 'Die Schrift lesen',
    'pr.screen': 'Auf den Bildschirm sehen',
    'pr.tape': 'Kassette abspielen (speichert das Spiel)',
    'pr.battery': 'Batterie nehmen',
    'pr.almond': 'Star Pop nehmen',
    'pr.glow': 'Knicklicht nehmen',
    'pr.flashlight': 'Taschenlampe nehmen',
    'pr.token': 'Spielmarke nehmen',
    'pr.fuse': 'Sicherung nehmen',
    'pr.fuel': 'Dieselkanister nehmen',
    'pr.keycard': 'Sicherheitskarte nehmen',
    'pr.take': 'Nehmen: {name}',
    'pr.pellet': 'Laterne nehmen',
    'pr.phoneRing': 'Ans Telefon gehen',
    'pr.phone': 'Den Hörer abnehmen',
    'pr.cabinetFree': 'Am Automaten spielen (FREE PLAY)',
    'pr.doorLocked': '{name} (verschlossen)',
    'pr.doorOpen': 'Tür öffnen',
    'pr.doorClose': 'Tür schließen',
    'pr.drawerOpen': 'Schublade öffnen',
    'pr.drawerClose': 'Schublade schließen',
    'pr.safeOpen': 'Tresor öffnen',
    'pr.safeClose': 'Tresor schließen',
    'pr.safeLocked': 'Tresor (Kombination eingeben)',
    'pr.hide': 'Darunter verstecken',
    'pr.hideLocker': 'Im Spind verstecken',
    'pr.unhide': 'Herauskommen',
    'pr.shrineLook': 'Den Schrein ansehen',
    'pr.shrinePlace': 'Das Andenken am Schrein lassen',
    'pr.drawing': 'Lilys Zeichnung nehmen',

    'door.default': 'Tür',
    'door.office': 'Bürotür',
    'door.storage': 'Lagerraum',
    'door.wc': 'Toilette',
    'door.front': 'Eingangstür',
    'door.elevator': 'Lastenaufzug',
    'door.security': 'Sicherheitsraum',
    'door.stair': 'Nottreppe',
    'door.house': 'Das Haus der Spuke',
    'door.service': 'Personalaufzug',
    'lock.service': 'Der Aufzug ist tot. Alle drei Generatoren müssen laufen.',
    'door.exit': 'EXIT',
    'door.room': 'Zimmer {n}',
    'door.jammed': 'Tür',
    'lock.jammed': 'Verklemmt. Die Klinke lässt sich drücken, aber etwas hält die Tür von der anderen Seite fest.',
    'lock.exit': 'Der EXIT ist verschlossen. Noch nicht.',
    'door.pressure': 'Drucktür',
    'lock.pressure': 'Die Drucktür rührt sich nicht. Dahinter zischt Dampf.',
    'door.janitor': 'Hausmeister',
    'lock.janitor': 'Ein Zahlenschloss. Drei Ziffern.',
    'door.fireExit': 'Notausgang',
    'lock.fireExit': 'Eine schwere Kette und ein Vorhängeschloss. Der Hausmeister hat die Schlüssel.',
    'lock.fireExitMotel': 'Die Stange lässt sich nicht drücken. Jemand hat sie von draußen verkeilt.',
    'door.gym': 'Turnhalle',
    'door.mallExit': 'Türen des Einkaufszentrums',
    'lock.mallExit': 'Für die Nacht verschlossen. In der Ferne summt der Fotoautomat.',
    'door.room12': 'Zimmer 12',
    'lock.room12': 'Verschlossen. Das Nummernschild ist blank poliert, als würde es jemand jeden Tag berühren.',
    'door.room207': 'Zimmer 207',
    'lock.room207': 'Verschlossen. Ein Papierschild: BITTE RUHE. Darauf eine Sonne aus Wachsmalstift.',
    'door.elevatorH': 'Aufzug',
    'lock.elevatorH': 'Der Aufzug wartet mit geschlossenen Türen. Er wartet auf etwas.',
    'door.samHouse': 'Dein Haus',
    'door.tobyHouse': 'Tobys Haus',
    'door.neighbor': 'Haustür',
    'lock.neighbor': 'Verschlossen. Die Vorhänge bewegen sich, wenn du wegsiehst.',
    'door.alley': 'Hintertür zur Gasse',
    'lock.alley': 'Verschlossen. Erst, wenn du an der Ecke gestanden hast.',
    'door.kernel': 'Stahltür',
    'lock.kernel': 'Stahl, und verschlossen. Ein Messingschild: KERNEL — NUR W.',
    'lock.default': 'Verschlossen.',
    'lock.office': 'Verschlossen. Ein Messingschild an der Tür: „W. — GESCHÄFTSFÜHRER“.',
    'lock.front': 'Von außen mit einem Vorhängeschloss gesichert. Die Möbelpacker haben den Schlüssel.',
    'lock.elevator': 'Der Aufzug hat keinen Strom. Der Rufknopf ist tot.',
    'lock.security': 'Das Tastenfeld will einen vierstelligen Code.',
    'lock.stair': 'Das Licht am Kartenleser ist rot. Er braucht eine Sicherheitskarte.',
    'lock.house': 'Ein violetter Vorhang aus Licht. Vier Laternen halten ihn geschlossen.',

    'cap.front': 'vorn',
    'cap.back': 'hinten',
    'cap.left': 'links',
    'cap.right': 'rechts',
    'cap.phone': '[ein Telefon klingelt]',
    'cap.drag': '[schlurfende Schritte in der Nähe]',
    'cap.moan': '[ein Stöhnen]',
    'cap.farSteps': '[Schritte irgendwo anders im Gebäude]',
    'cap.thud': '[weit weg fällt etwas um]',
    'cap.buzz': '[eine Leuchtstoffröhre knistert]',
    'cap.whisper': '[Flüstern]',
    'cap.giggle': '[Kichern im Dunkeln]',
    'cap.radio': '[Funkrauschen]',
    'cap.thunder': '[Donner]',
    'cap.hiss': '[ein nasses Zischen, das sich entfernt]',
    'cap.skitter': '[Krabbeln auf Backstein]',
    'cap.whistle': '[eine Pfeife schrillt]',
    'cap.plastic': '[Plastik knarrt]',
    'cap.bite': '[Zähne schlagen in der Nähe zusammen]',
    'cap.biteFar': '[fernes Kauen]',
    'cap.callName': '[jemand ruft deinen Namen mit Tobys Stimme]',
    'cap.heavySteps': '[schwere Schritte, ein Gummiquietschen]',
    'cap.pipe': '[irgendwo in den Tunneln klingt ein Rohr]',
    'cap.locker': '[den Gang hinunter knallt ein Spind zu]',
    'cap.knock': '[drei Klopfer, irgendwo den Gang hinunter]',
    'cap.beep': '[ein Monitor piept in einem leeren Zimmer]',
    'cap.arc': '[hinter der Stahltür knallt Strom]',
    'cap.pop': '[eine Leuchtröhre platzt]',
    'cap.slam': '[hinter dir knallt eine Tür zu]',
    'cap.run': '[jemand rennt, außer Sicht]',
    'cap.callJune': '[eine Frauenstimme den Flur hinunter: „Eddie? Eddie, bist du das?“]',
    'cap.car': '[ein Auto zischt über die nasse Straße]',
    'cap.door': '[irgendwo eine Tür]',
    'cap.drip': '[Tropfen]',
    'cap.hum': '[Brummen der Leuchtstoffröhren]',
    'tab.access': 'Barrierefreiheit',
    'tab.perf': 'Leistung',
    'set.perfOverlay': 'Leistungsanzeige',
    'set.perfOverlay.help': 'Zeigt, wie das Spiel läuft. Nur FPS; Einfach zeigt zusätzlich Bildzeit, CPU- und GPU-Zeit pro Bild und wie ausgelastet beide sind; Detailliert ergänzt einen Bildzeitgraphen, Draw Calls, Dreiecke, Speicher, Renderauflösung und deine Grafikkarte. Die GPU-Zeit braucht einen Browser, der GPU-Timer-Abfragen erlaubt (die Desktop-Version tut das immer).',
    'set.perfCorner': 'Position der Anzeige',
    'set.perfCorner.help': 'In welcher Bildschirmecke die Leistungsanzeige sitzt.',
    'opt.perfFps': 'Nur FPS',
    'opt.perfBasic': 'Einfach',
    'opt.perfDetailed': 'Detailliert',
    'opt.cornerTR': 'Oben rechts',
    'opt.cornerTL': 'Oben links',
    'opt.cornerBR': 'Unten rechts',
    'opt.cornerBL': 'Unten links',
    'preset.ultraplus': 'Ultra+',
    'opt.ultraplus': 'Ultra+',
    'opt.shadow4': 'Ultra+ (8192)',
    'set.modelDetail': 'Modelldetail',
    'set.modelDetail.help': 'Wie fein die Kreaturen, Hände und anderen modellierten Figuren gebaut werden. Höher sieht aus der Nähe glatter aus und verlängert das Laden eines Kapitels. Ultra+ ist für die schnellsten Prozessoren.',
    'set.clutter': 'Detailobjekte',
    'set.clutter.help': 'Wie viele kleine Dinge die Räume füllen: Gemälde, Fotos, Kalender, Kisten, Papiere, Flaschen. Mehr lässt jeden Raum bewohnt wirken; weniger schont ältere Rechner.',
    'set.dof': 'Tiefenunschärfe',
    'set.dof.help': 'Verwischt, was weit von deinem Blickpunkt entfernt ist, wie ein Kameraobjektiv. Der Fokus folgt der Bildmitte. Höhere Stufen nehmen mehr Proben für eine weichere, sauberere Unschärfe.',
    'set.textureRes.help': 'Schärfe der Oberflächen: Wände, Böden, Holz, Stoff. Höher braucht mehr Grafikspeicher.',
    'set.shadows.help': 'Schatten deiner Taschenlampe und der Lampen draußen. Höher ist schärfer. Ultra+ nutzt eine 8192er-Schattenkarte und braucht viel Grafikspeicher.',
    'set.antialias.help': 'Glättet gezackte Kanten. MSAA ist am saubersten; FXAA ist günstig und macht das ganze Bild etwas weicher; beides zusammen ist am glattesten.',
    'set.dynLights.help': 'Wie viele Lampen in deiner Nähe gleichzeitig bewegte Dinge und Kreaturen beleuchten können.',
    'set.bloom.help': 'Das weiche Leuchten um helle Lichter und Bildschirme.',
    'set.bloomStrength.help': 'Wie stark dieses Leuchten ist.',
    'set.motionBlur.help': 'Verwischt das Bild bei schnellen Drehungen. Deine Hände und was du hältst bleiben scharf.',
    'set.particles.help': 'Staub in der Luft, Regen, Funken und Tropfen.',
    'set.viewDist.help': 'Wie weit entfernt Dinge gezeichnet werden und wie weit dich der Nebel sehen lässt.',
    'set.anisotropy.help': 'Hält Böden und Wände scharf, wenn du sie flach ansiehst. Kostet sehr wenig.',
    'set.contrast.help': 'Unterschied zwischen den dunklen und hellen Teilen des Bildes.',
    'set.saturation.help': 'Wie kräftig die Farben sind. Weniger wirkt wie ein altes Foto.',
    'set.fov.help': 'Wie breit du siehst. Breiter zeigt mehr, lässt aber alles weiter entfernt wirken.',
    'set.headBob.help': 'Wie stark die Sicht bei deinen Schritten schwankt. Verringere es, wenn dir davon übel wird.',
    'set.shake.help': 'Kamerawackeln bei Schrecken, Stößen und beim Rennen.',
    'set.grain.help': 'Filmkorn über dem Bild.',
    'set.chromatic.help': 'Farbsäume an den Bildrändern, wie bei einer billigen Linse.',
    'set.vignette.help': 'Abdunkelung zu den Bildschirmecken hin.',
    'set.crosshair.help': 'Ein kleiner Punkt in der Bildmitte, der beim Anvisieren von Gegenständen hilft.',
    'set.subtitles.help': 'Zeigt, was gesagt wird: Funksprüche, Kassetten, Gedanken.',
    'set.subtitleSize.help': 'Größe von Untertiteln und Geräuschuntertiteln.',
    'set.master.help': 'Lautstärke insgesamt.',
    'set.music.help': 'Lautstärke der Musik.',
    'set.sfx.help': 'Schritte, Türen, Gegenstände und alles, was du tust.',
    'set.ambience.help': 'Räume, Regen, Brummen und die Geräusche des Gebäudes.',
    'set.entities.help': 'Kreaturen: ihre Schritte, ihr Atem, ihre Stimmen.',
    'set.voice.help': 'Funkgerät, Kassetten und Gedanken.',
    'set.hrtf.help': 'Setzt Geräusche dreidimensional um dich herum. Am besten mit Kopfhörern; für Lautsprecher ausschalten.',
    'set.mouseSens.help': 'Wie schnell sich die Sicht mit der Maus dreht.',
    'set.invertY.help': 'Maus nach oben bewegen sieht nach unten.',
    'set.touchSens.help': 'Wie schnell sich die Sicht dreht, wenn du auf einem Touchscreen ziehst.',
    'set.toggleCrouch.help': 'Einmal drücken zum Ducken, noch einmal zum Aufstehen, statt die Taste zu halten.',
    'set.toggleSprint.help': 'Einmal drücken zum Rennen, noch einmal zum Gehen, statt die Taste zu halten.',
    'set.lang.help': 'Sprache der Menüs, der Untertitel und aller Dokumente im Spiel.',
    'set.jumpscare.help': 'Reduziert behält jeden Schrecken, macht die grellsten Blitze und lautesten Geräusche aber sanfter.',
    'set.hints.help': 'Kurze Tipps, wenn etwas Neues passiert.',
    'perf.frame': 'Bild',
    'perf.low1': '1 % Tief',
    'perf.cpu': 'CPU',
    'perf.cpuUse': 'CPU-Last',
    'perf.gpu': 'GPU',
    'perf.gpuUse': 'GPU-Last',
    'perf.na': 'k. A.',
    'perf.draws': 'Draw Calls',
    'perf.tris': 'Dreiecke',
    'perf.textures': 'Texturen',
    'perf.programs': 'Shader',
    'perf.res': 'Render',
    'perf.heap': 'JS-Speicher',
    'perf.sysCpu': 'System-CPU',
    'perf.appCpu': 'Spiel-CPU',
    'perf.procMem': 'Spielspeicher',
    'perf.card': 'Grafikkarte',
    'settings.revert': 'Rückgängig',
    'settings.keys': '↑↓ wählen · ←→ ändern · Q/E Reiter · Rücktaste rückgängig · Esc zurück',
    'settings.impact': 'Leistungskosten',
    'impact.0': 'Keine',
    'impact.1': 'Gering',
    'impact.2': 'Mittel',
    'impact.3': 'Hoch',
    'impact.4': 'Sehr hoch',
    'impact.5': 'Extrem',
    'settings.gpuLoad': 'Geschätzte GPU-Last',
    'settings.vram': 'Geschätzter Grafikspeicher',
    'settings.reloadBadge': 'Gilt, sobald das nächste Kapitel lädt',
    'settings.restartBadge': 'Gilt nach einem Neustart des Spiels',
    'settings.restartNow': 'Jetzt neu starten',
  });
})(typeof window !== 'undefined' ? window : globalThis);
