/* Deutsche Oberfläche für die Geschichte von Ada Lind: ersetzt, was zur alten Geschichte gehörte, und ergänzt,
   was die neun Regale brauchen (Türen, Treppen, Dokumentarten, Untertitel). Wird nach ui.js geladen. */
(function (root) {
  'use strict';
  root.PB.I18N.register('de', 'ui', {
    'game.subtitle': 'FUNDSACHEN',
    'menu.credit': 'Halvard · 13. Januar 1998 · 02:56',
    'diff.time': 'Geschätzte Spielzeit: 5–7 Stunden für alle, die jedes Dokument lesen und alle acht Zeichnungen finden.',
    'set.vhs.help': 'Zeigt das Spiel wie durch eine alte Heimvideokamera.',
    'help.drink': 'Ein Gerstenzucker lutschen',
    'bag.stats': 'Dokumente {a} / {b}   ·   Wrens Zeichnungen {c} / {d}',
    'bag.d.flashlight': 'Eine schwere Gummitaschenlampe von unter dem Schalter von Depot 9. Batterie: {n} %. Sie wird schwächer, bevor sie ausgeht.',
    'bag.n.almond': 'Gerstenzucker',
    'bag.d.almond': 'Eine Stange Gerstenzucker aus der Dose unter dem Schalter, aufgehoben für schlimme Nächte. Der Zucker beruhigt die Hände. Mit Q lutschen.',
    'bag.d.officeKey': 'Ein kleiner Messingschlüssel, glatt gegriffen.',
    'bag.d.token': 'Eine Messingmarke.',
    'help.padText': 'Linker Stick: gehen. Rechter Stick: schauen. A: interagieren. B: ducken. X: Batterie wechseln. Y: Taschenlampe. LB / RB: lehnen. RT oder linken Stick drücken: rennen. LT: Leuchtstab. Rechten Stick drücken: zurückschauen. Steuerkreuz: ↑ Tagebuch, ↓ Gerstenzucker, → Gegenstände. Ansicht: Karte. Menü: Pause. In Menüs bewegt das Steuerkreuz, A wählt und B geht zurück.',
    'help.tip7': 'Auf dem Grund jedes Ortes liegt eine Lüge. <b>Bring das Verlorene dorthin zurück, wo es hingehört</b>, und der Weg öffnet sich.',
    'map.shrine': 'Anspruch',
    'end.freed': 'Eingelöste Regale',
    'end.claimed': 'Eingelöste Regale',
    'inv.almond': 'GERSTENZUCKER ×{n}',
    'inv.token': 'MARKE',
    'n.almond': 'Gerstenzucker (Q zum Lutschen)',
    'n.drank': 'Du lutschst den Gerstenzucker. Dein Atem beruhigt sich.',
    'n.noAlmond': 'Du hast keinen Gerstenzucker.',
    'n.drawing': 'Wrens Zeichnung ({n}/8)',
    'pr.almond': 'Gerstenzucker nehmen',
    'pr.drawing': 'Wrens Zeichnung nehmen',
    'door.house': 'Das Haus',
    'touch.drink': 'ZUCKER',
    'inv.pellets': 'VERLORENE LICHTER ×{n}',
    'pr.pellet': 'Das verlorene Licht nehmen',
    'lock.house': 'Ein Vorhang aus Licht. Vier verlorene Lichter halten ihn geschlossen.',
    'help.tip1': '<b>Hör hin, bevor du hinsiehst.</b> Jedes Wesen hat seine eigene Regel: manche hören, manche sehen nur Licht, manche bewegen sich nur, solange niemand hinsieht. Die Dokumente verraten, welche.',
    'help.tip2': 'Wenn das Licht zu stottern beginnt oder der Ton aus der Welt weicht, <b>ist etwas nah</b>.',
    'help.tip3': 'Im Darunter: nimm ein <b>verlorenes Licht</b>, und der Fresser hält sich ein paar Sekunden von dir fern.',
    'help.tip4': 'Jedes Regal hat <b>seine eigenen Wesen</b>: einen Schaffner, der Fahrkarten prüft, Pferde, die nur laufen, solange die Orgel spielt, Kiefern, die sich nur bewegen, während du dich bewegst. Lerne die Regel jedes einzelnen.',
    'help.tip5': 'Du kannst dich unter Betten, Pritschen und Tischen und in Spinden <b>verstecken</b>. Hat dich nichts hineingehen sehen, sucht auch nichts.',
    'help.tip6': 'Das Spiel <b>speichert selbst</b> bei jedem Ziel, wenn du in Sicherheit bist.',
    'set.subtitles.help': 'Zeigt, was gesagt wird: Kanal neun, Kassetten, Gedanken.',
    'set.voice.help': 'Kanal neun, Kassetten und Gedanken.',
    // Türen und Durchgänge auf den neun Regalen
    'pr.unlock': 'Aufschließen',
    'pr.stairs': 'Die Treppe nehmen',
    'pr.stairsDown': 'Die Treppe hinuntergehen',
    'pr.stairsUp': 'Die Treppe hinaufgehen',
    'pr.ladderDown': 'Die Leiter hinunterklettern',
    'pr.ladderUp': 'Die Leiter hinaufklettern',
    'door.otto': 'Otto Brandts Büro',
    'lock.otto': 'Seit 1964 verschlossen. Der Schlüssel muss irgendwo im Archiv sein.',
    'door.concourse': 'Die Bahnhofshalle',
    'lock.concourse': 'Von der anderen Seite verschlossen.',
    'door.bridge': 'Die Brücke',
    'lock.bridge': 'Verschlossen. Der Kapitän hat den Schlüssel.',
    'door.cage': 'Der Förderkorb',
    'lock.cage': 'Das Korbgitter. Ohne Strom bewegt sich nichts.',
    'door.fire': 'Die Brandschutztür',
    'lock.fire': 'Verkeilt. Von dieser Seite.',
    'door.signe': 'Stuegata 4',
    'lock.signe': 'Verschlossen. Drinnen brennt eine Lampe.',
    'door.ghost': 'Die Geisterbahn',
    // Dokumentarten
    'kind.telegram': 'Telegramm',
    'kind.transcript': 'Mitschrift',
    'kind.clipping': 'Zeitung',
    // Untertitel für Geräusche
    'hint.flash': 'F schaltet die Taschenlampe ein und aus.',
    'cap.chute': '[ein Paket fällt die Rutsche herunter]',
    'cap.tube': '[die Rohrpost poltert]',
    'cap.bellFar': '[eine Glocke, draußen im Nebel]',
    'cap.doorShut': '[irgendwo fällt eine Tür zu]',
    'cap.stepsFar': '[Schritte, weit weg]',
    'cap.organ': '[eine Jahrmarktsorgel beginnt von selbst zu spielen]',
    'cap.organStop': '[die Orgel läuft aus und verstummt]',
    'cap.choir': '[ein Chor singt]',
    'cap.knocks': '[sieben Schläge, auf Stahl]',
    'cap.ice': '[das Eis knackt, weit draußen]',
    'cap.brake': '[kreischende Bremsen]',
    'cap.laugh': '[Lachen]',
    'cap.toll': '[eine Glocke schlägt]',
    'cap.breath': '[Atem, direkt hinter dir]',
    'cap.train': '[der Zug, mit voller Fahrt]',
    'cap.pa': '[ein Gong; der Lautsprecher knistert]',
  });
})(typeof window !== 'undefined' ? window : globalThis);
